### ISSUE TITLE
archive https://github.com/nodejs/promises?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#103]
Seems like there was a desire to form a working group but it didn't happen. Dormant now as far as I can tell.

@nodejs/tsc @nodejs/community-committee @chrisdickinson @benjamingr

**Comment by benjamingr** [comment]
@Trott go right ahead, at the current form it just disorganizes discussion I should have probably done this a while ago. Thanks for taking care of it!

(There was no desire to form a chartered WG for what it's worth - just a place to organize the efforts)

**Comment by Trott** [comment]
Archived. Thanks.
