### ISSUE TITLE
Accepting YouTube manager invitations

### ISSUE THREAD

**Issue by dshaw** [nodejs/admin#108]
It's taken quite some time and the help of multiple people to get setup with YouTube to be able to publish meetings from Zoom to Youtube. (Thank you, @mhdawson and @zibbykeaton for your patience.)

I finally found the magic link to accept YouTube invites:
https://myaccount.google.com/brandaccounts

At the time of writing this, the first link on the page will take you to your Pending Invitations.

🎉

If this is no longer viable, here's the path down rabbit hole I followed to get here:
* https://www.youtube.com/watch?v=BUakHgrNnd4 (It was wondrous validation to discover that I wasn't the only one dealing with YouTube invitation insanity.)
* https://productforums.google.com/forum/#!topic/youtube/DDuwFM1W3oA

**Comment by maddhruv** [comment]
Take me up for it!
dhruvjainpenny@gmail.com

**Comment by codeekage** [comment]
could support if need any assistance on that

**Comment by Trott** [comment]
This seems informational rather than actionable so I'm going to close. Feel free to re-open with a comment if I'm totally wrong about that. Just doing some general tidying, not acting on a strong principle or anything.

**Comment by ZibbyKeaton** [comment]
Bookmarked this @dshaw in case anyone else experiences issues with this.
