### ISSUE TITLE
Request to Extend Travel fund to CommComm Observers during transition

### ISSUE THREAD

**Issue by dshaw** [nodejs/admin#111]
The CommComm is actively working on modifying the process of becoming a CommComm Member. In the interim, there are some active CommComm observers who would like the opportunity to receive travel assistance to attend Collab Summit in Berlin.

I, personally, think it would be a reasonable exception to extend this to currently active CommComm Observers to further grow the CommComm, our initiatives and teams, and our representation throughout the world.

What do folks think?

**Comment by dshaw** [comment]
One such individual is @codeekage, an active CommComm Observer. Agiri has been an active participant in CommComm meetings and CommComm governance evolution work, he is active with both the Mentorship and the User Feedback team and is spearheading the effort to form local chapters.

**Comment by Trott** [comment]
I'm not opposed to this, but some things to consider:

* Any of the 559 people who are members of the @nodejs GitHub org can apply for travel funds. If a CommComm observer is not currently a member of a team in the GitHub org, perhaps before considering this exception to existing policy, we might consider seeing if they might want to participate in a WG or a team. Some of the teams are very easy/fast to join, such as most of the internationalization teams and the Website WG.

* These funds came from the board. A change in who they are available to may require board approval. I'm guessing you (@dshaw) would know the answer to that better than I would.

**Comment by mhdawson** [comment]
I like the idea as I believe the Observers identified would already have been made "Community Collaborators" based on the process being developer making them eligible for individual foundation membership and travel support.  

If we can find an existing team as a home, that might be the easiest way forward, or we might be able to form a team which is something like "active commcomm observers" if it is as simple as having to be in a team.  I believe they would still have to get an individual membership though.

**Comment by dshaw** [comment]
I think the chicken and egg problem might be that you need to be a Node.js team member to get the discounted Individual Membership.

I love the idea of finding an easy to join team. Brilliant.

**Comment by dshaw** [comment]
Thank everyone for the help and constructive feedback.

The @nodejs/mentorship team is happy to welcome @codeekage as a Member where Agiri will be helping coordinate new Mentees in our Slack channel. (ref: https://github.com/nodejs/mentorship/pull/28). Agiri will also be working with the Website Redesign team, where he has been accepted as a member, but processing is still in flight. (ref: https://github.com/nodejs/website-redesign/pull/33).

**Comment by dshaw** [comment]
At this point, I'm comfortable with this issue getting close. However, I suggest leaving it open to allow us to assist any other individuals who may need assistance.

**Comment by codeekage** [comment]
Closing #111

**Comment by codeekage** [comment]
Closing #111 since we no longer have observership in the Project.
