### ISSUE TITLE
Labeling `good-first-issues` in @nodejs/repos.

### ISSUE THREAD

**Issue by codeekage** [nodejs/admin#127]
@nodejs/community-committee CommComm meeting, we agreed on taking up the task of adding `good-first-issue` labels on every issue in @nodejs/repos that requires the label to help folks coming into the Node.js Project get started with regular/frequent contributions. From this [#38](https://github.com/nodejs/mentorship/issues/38).

WG Champions and Committee Chairs should please help with ~~opening an issue~~ in their various repos with the list of issues to be labeled `good-first-issue`. 

I could help with adding the label to help folks get started, so, you don't have extra homework of opening issues👍

**Comment by detrohutt** [comment]
> WG Champions and Committee Chairs should please help with opening an issue in their various repos with the list of issues to be labeled good-first-issue.

@codeekage Thanks for taking on this task. One nit though.. my understanding was that we (the people working on the new initiative) would be responsible for opening these issues (based on what @mhdawson said at [36:30 of the stream](https://youtu.be/qodESjBb62I?t=36m30s) and recommending/offering potential candidate issues for the `good-first-issue` label. @dshaw also recommended asking if WGs were able to help as opposed to expecting them to.

If this was further addressed in the private portion of the meeting, my apologies. Just trying to make sure there wasn't a miscommunication.

Also, I'm not sure this is directly related to https://github.com/nodejs/mentorship/issues/38. Or more specifically, as that issue stands right now, it doesn't mention `good-first-issue`. So maybe a better reference point would be [33:36-37:02 of the stream](https://youtu.be/qodESjBb62I?t=33m36s)?

**Comment by Tiriel** [comment]
@detrohutt You are indeed correct, this was also my understanding.

We should not put more work onto WG/Initiatives as they generally already have more than their full of it. The initiative of helping label issues with the `good-first-issue` label is a great one to help reroute newcomers where they are most needed and where they can enter our awesome ecosystem. But as I understand it, the people willing to help should be the ones opening the issues, not the WG/Initiatives champions.

**Comment by codeekage** [comment]
@Tiriel more like, existing issues that could be labeled `good-first-issue` to help newcomers get started. 

Sorry, if I wasn't clear.

**Comment by Tiriel** [comment]
@codeekage No problem, it's me that wasn't clear, I was talking about this phrase:

> WG Champions and Committee Chairs should please help with opening an issue in their various repos with the list of issues to be labeled good-first-issue.

We shouldn't be asking WG/Initiative champions to make all the tedious work and open themselves an issue. The point of all this is to help newcomers know where to go, and then indirectly, to help the WG/Initiative get all the people they require. Not give them extra-homework but requiring the open a new issue to list good first issues. I think that's more like our job. But I may have misunderstood what was said in yesterday's meeting.

**Comment by Trott** [comment]
Closing stuff that has been inactive for more than a year in this repo, but if someone plans on picking this up, just go ahead and re-open! No strong opinions from me. Just tidying.
