### ISSUE TITLE
Enable Travis CI webhook org-wide?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#148]
We've disallowed this for a long time because of concerns about the security repos, but they've been moved out. Is it acceptable to enable the Travis CI webhook org-wide so that people don't have to transfer the repo out of the org, add the Travis CI webhook, transfer the repo back into the org, and enable the GitHub bot to make Travis CI work?

@nodejs/tsc @nodejs/build @nodejs/automation

**Comment by joyeecheung** [comment]
+1

**Comment by phillipj** [comment]
As one who have worked closely with the work arounds related to Travis CI and the @nodejs-github-bot, I can safely confirm it is both time consuming an error prone in several aspects.

I for sure respect the reasons why we haven't wanted to enable the org-wide webhooks with private access before, but if those reason don't apply anymore, using Travis CI directly as one "normally would" would be beneficial to everyone in my opinion.

**Comment by maclover7** [comment]
🙌

**Comment by targos** [comment]
Another option is to use the Travis GitHub app and enable it only for repos that need Travis integration.

**Comment by obensource** [comment]
@Trott does this need a consensus period? If so can we consider that to have begun with the creation of this issue? @zeke and I are tracking this and are hoping the webhook might become available to us soon while we're at the collaborator's summit & JSConf EU and working synchronously. Would save us time and hassle.

**Comment by zeke** [comment]
@obensource if we follow the steps in https://github.com/nodejs/admin/issues/149 we will not have to wait for a decision to be made here.

**Comment by Trott** [comment]
> Another option is to use the Travis GitHub app and enable it only for repos that need Travis integration.

@targos OMG this totally worked! I was able to enable Travis-CI for just the i18n repository. Now @addaleax and I are talking about adding it to nodejs/node so that people can get immediate feedback on their PRs.

This can be closed if the GitHub App works for everyone. I'll close, but re-open if we still need webhooks or anything.

**Comment by joyeecheung** [comment]
Nice! We should probably disable the Travis CI polling in the github bot now that we can use the GitHub App!

**Comment by zeke** [comment]
Thanks everyone for making this happen 💛

**Comment by phillipj** [comment]
I just opened a github-bot PR to delete our Travis CI polling code: https://github.com/nodejs/github-bot/pull/183. As soon as we've transitioned all the repos to using the GitHub app instead, that PR can land.
