### ISSUE TITLE
Request to enable Travis CI for nodejs/i18n repo

### ISSUE THREAD

**Issue by zeke** [nodejs/admin#149]
We want to enable Travis CI on the nodejs/i18n repo.

Based on discussions with @joyeecheung, @Trott, and @mcollina, the recommended process is the following:

1. move the nodejs/i18n repo temporarily to my personal @zeke account
2. enable Travis CI
3. move the repo back to @nodejs
4. Land https://github.com/nodejs/github-bot/pull/171 in order to whitelist the i18n repo

I already have admin privileges on the i18n repo, so I am unblocked for 1,2,3. Step 4 will require help from someone else who has permission to merge PRs on the github-bot repo.

Is all this okay?

Related:

- https://github.com/nodejs/i18n/issues/58
- https://github.com/nodejs/build/issues/1221
- https://github.com/nodejs/github-bot/pull/171

cc @obensource

**Comment by Trott** [comment]
Ref: https://github.com/nodejs/admin/issues/148

**Comment by obensource** [comment]
@zeke @Trott 👍👍👍

**Comment by Trott** [comment]
Done.
