### ISSUE TITLE
Move `make-node-meeting` into Node.js GitHub org.

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#15]
There's a tool created by @rvagg that is used by some top-level committees and some WGs to create meeting issues. I'd like to propose that we move this into the Node.js org. I know that Rod and Bryan had previously discussed Bryan moving it in (https://github.com/rvagg/make-node-meeting/pull/19#issuecomment-323120647), and I'd like to push this through to completion.

I've created this issue in nodejs/admin because the tool is used by the TSC and CommComm, and I assume there will need to be some governance discussion.

**Comment by bnb** [comment]
A link to the repo would be useful 😅 

https://github.com/rvagg/make-node-meeting

**Comment by rvagg** [comment]
Happy to let this one go. I don't use it anymore and a few members of the org have commit & npm access to this already. I'm sure if it were under nodejs/ that it could be vastly improved upon to be more broadly useful.

**Comment by bnb** [comment]
@nodejs/tsc @nodejs/community-committee Would very much appreciate feedback on this 🙏

**Comment by joyeecheung** [comment]
SGTM

**Comment by mcollina** [comment]
sgtm

**Comment by targos** [comment]
+1

**Comment by MylesBorins** [comment]
sgtm

**Comment by addaleax** [comment]
+1

**Comment by mhdawson** [comment]
+1 from me.

**Comment by cjihrig** [comment]
+1

**Comment by Trott** [comment]
+1 +1 +1 +1

**Comment by jasnell** [comment]
+1

**Comment by evanlucas** [comment]
+1

**Comment by rvagg** [comment]
https://github.com/nodejs/make-node-meeting

**Comment by rvagg** [comment]
& https://github.com/nodejs/node-meeting-agenda which is the heart of the tool
