### ISSUE TITLE
Request to enable Travis CI for nodejs/security-wg repo

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/admin#150]
Similarly to https://github.com/nodejs/admin/issues/149, I would like to enable travis-ci on the security WG repo.

I suggest we see how it goes for i18n and follow the same procedure.

Does that make sense?

**Comment by Trott** [comment]
Done. It's possible that PRs will now automatically launch Travis, which will show the CI as failing if you don't have a travis.yml file or whatever, so you probably want to add one soon. (And if that's *not* the case, let me know because that's pretty useful information.)

**Comment by vdeturckheim** [comment]
@Trott Thanks a lot. We used to have one, I'll restore it.
