### ISSUE TITLE
The focus area of Admin is Process

### ISSUE THREAD

**Issue by dshaw** [nodejs/admin#151]
We had a great discussion at the Collaborator Summit around governance. In general, folks are happy  with the Technical Steering Committee (TSC) focused on ensuring the ongoing needs are fulfilled of the collaborators working on Node.js and its affiliated tools and services. The Community Committee (CommComm) compliments the efforts of the technical project supporting and empowering the Node.js community and ecosystem.

I propose that we invest more in our Admin function with space to focus on process to serve our growing project.

**Comment by Trott** [comment]
> I propose that we invest more in our Admin function with space to focus on process to serve our growing project.

Can you be more specific? What concrete action are you proposing?

**Comment by dshaw** [comment]
@Trott I'm proposing that we begin to evolve what we are doing in Admin from simply a holding place for shared TSC and CommComm interests to more formal participation and active organization amongst members who wish to work on the Node.js project by creating process which serves the needs of our members.

Today we have:
1) The Technical Steering Committee chartered and responsible for Node.js and the technical project
2) The Community Committee chartered and responsible for Community activities and sustaining Node.js Community Members

Admin is already a intersection of our teams and I think we would benefit by encouraging those who wish to server our project through process building, budget management and cross-project coordination to do so in shared space which we support.

Since the creation, maintenance and upkeep of said processes will require a fair amount of context, I believe that Members of the Admin team who choose (or our chosen) to work in this area, be bootstrapped by members of the TSC and CommComm.

I don't think anyone in the project is interested in creating a hierarchy. I explicitly would vote against such a thing. However, I've heard repeatedly that folks in the technical project want to focus on the technical project. CommComm folks are saturated with the vast needs of our community. I think we have now evolved to a point where we have sufficient administrative needs that require regular attention and we will all benefit by formally investing in growing this capacity.

**Comment by Trott** [comment]
@dshaw So this is a proposal to create a separate Admin team? (I'm not for or against yet; just genuinely trying to understand!)

I personally don't find the admin burden particularly high, but I'm also probably not a typical participant in a lot of ways and my experience may not be that of others. So I'm certainly *open* to the idea that something like that might be necessary.

**Comment by Trott** [comment]
Closing stuff that has been inactive for more than a year in this repo, but if someone plans on picking this up, just go ahead and re-open! No strong opinions from me. Just tidying.
