### ISSUE TITLE
commit-queue repository

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#152]
In accordance with our GitHub management policy, I'm opening an issue here to request a commit-queue repository so that folks working on a commit-queue prototype can organize and others can comment on relevant issues, etc.

If there are no objections from TSC or CommComm after 72 hours, I'll create the repo.

Thanks!

**Comment by Tiriel** [comment]
LGTM!

**Comment by tniessen** [comment]
Absolutely on it! (Before there was NCU, I actually started a very simple prototype for a CQ, will try to find it...)

**Comment by mhdawson** [comment]
SGTM

**Comment by Trott** [comment]
https://github.com/nodejs/commit-queue
