### ISSUE TITLE
Tickets for JS Interactive

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#158]
Two requests did come through for tickets to JS Interactive, one from @nodejs/tsc member and one from a @nodejs/community-committee (#156 #157) member. Can any of the members apply for a ticket here? Or is it just "top level committees"?

I think we should do a sanity check if it is _ok_ to expense that through the travel fund, $350 * 100 (# expected collaborators at JS Interactive) is 35000, which is a significant amount of our travel budget.

From a purely accounting perspective, I would prefer if we had a "free ticket" from the foundation given to the the top-level committees members. There will be a lot less effort and money paid in wire transfer fees and taxes.

cc @ladyleet @mrhinkle

**Comment by Tiriel** [comment]
I tend to think we should not allow appliance for tickets in the travel fund. Because then we would have to chose which tickets we allow, which confs, and we would anyway end up giving away every single cent of the fund. But I'm not sure it has to be anyone or no one.

My personal reasoning is that it's a travel fund, not an attending fund. If we had some kind of partnership with confs, or a diversity fund (and I wish we had), it would be great. But this is not the point of this fund, and as pointed, if we go that way, we may well end-up funding an awful lot of tickets for confs and not having anything left for travel.

So either we rethink the fund and rename it, or we stick to travel only. (And a quick remark: this doesn't please me much, since I can't buy conf tickets on my own and would greatly need a fund like this, so, all in all, I'd really much like it if we were to have a diversity fund or conf-attending fund)

**Comment by joyeecheung** [comment]
Based on the description of the `MEMBER_TRAVEL_FUND.md` I always thought that it is possible to apply for funds to attend conference, just that we will look at the requests based on the considerations listed in that documentation (impact, cost, equity, .etc)

I agree that we should set some kind of restriction on the conferences that we sponsor attendance for, but the conferences hosted by the foundation are a bit special in that we would want people active in the project to come and join the conversations happening in the conference.

If we do want to sponsor tickets, maybe it would be easier to manage if we:

- Set a number of tickets that we would sponsor in advance, and a deadline of applications
- Use something like Google Forms to receive the travel fund requests, like how the foundation manage the requests from speakers
- Review the applications based on the considerations that we list in the README and announce the people who will receive them, say, about 2-3 months before the conference?

**Comment by mcollina** [comment]
> I agree that we should set some kind of restriction on the conferences that we sponsor attendance for, but the conferences hosted by the foundation are a bit special in that we would want people active in the project to come and join the conversations happening in the conference.

If that's the case, I'd prefer to have a # of tickets to be set aside for the project by the organizers, and not to go through the travel fund itself. I think it would be a bad use of money to have it go through the travel fund.

**Comment by mcollina** [comment]
I agree with you @joyeecheung! I'd love to know if that would be possible from the organizers of JS Interactive.

**Comment by ladyleet** [comment]
Checking! Will get back shortly. // @annmarietonog

**Comment by Trott** [comment]
FWIW, I've withdrawn my request. I believe I will not need travel fund money for this event (although if it turns out I'm wrong, I'll certainly open up a new request).

**Comment by dshaw** [comment]
CC @JemBijoux

**Comment by JemBijoux** [comment]
I think @joyeecheung said it very well...

> Based on the description of the MEMBER_TRAVEL_FUND.md I always thought that it is possible to apply for funds to attend conference, just that we will look at the requests based on the considerations listed in that documentation (impact, > cost, equity, .etc)

> **the conferences hosted by the foundation are a bit special in that we would want people active in the project to come and join the conversations happening**

If the question is whether or not we should fund tickets for members, I don't see why not (but within reason). If it helps bring good people together then I think it's worth considering.  And on that front, we've identified a process for this sort of thing already:

> Review the applications based on the considerations that we list in the MEMBER_TRAVEL_FUND.md and announce the people who will receive them, say, about 2-3 months before the conference? The reviewers can be TSC and CommComm members since they are responsible for reviewing the requests in the repo as well.

There is a difference though if we're talking opening this up for all members.  We'd have to become a little more critical of newer requests, and there are still some open questions about limits, deadlines, specific events, etc.

Would be good to know to what extent the Foundation is open to sponsoring members. Let's confirm for sure whether or not "tickets for member attendees" is within the scope of "travel funds". If it is, then I say we approve within reason (with strong preference going to collaborators). If not, then I'm happy to add some clarification to the text outlining the restriction and we can provide feedback on the PR's.

**Comment by Trott** [comment]
Worth noting: If I'm not mistaken, one does not need to register for JS Interactive to attend the Collaborator Summit. (Correct me if I'm wrong.) Not saying we shouldn't encourage and even fund attendance anyway. But if we decide not to or do not have the funds to do so, it shouldn't hamper people's ability to attend Collaborator Summit.

**Comment by ryzokuken** [comment]
Any updates on this?

**Comment by ryzokuken** [comment]
No updates on this yet? Ping @ladyleet.

**Comment by AnnMarieTonog** [comment]
hi, @ryzokuken ! @ladyleet & I have been working with @joyeecheung on figuring this out. I will be discussing with the JS Interactive events team later this week, and give everyone an update then!

**Comment by ryzokuken** [comment]
@AnnMarieTonog great! Looking forward to it.

**Comment by joyeecheung** [comment]
Survey for the attendance of the JS Interactive/collab summit is out https://github.com/nodejs/summit/issues/99

**Comment by joyeecheung** [comment]
Hi all, the number of tickets requested in the survey (https://github.com/nodejs/summit/issues/99) has been approved, please submit a pull request for the funding - if you have already submitted a row without the cost of JSI, please submit a request updating your row, thanks!

**Comment by joyeecheung** [comment]
By the way, if you have not participated in the survey or did not indicate that you need a ticket in the survey, please open a new issue or discuss here, but it's probably going to take some more time to review additional requests and it may not be approved.
