### ISSUE TITLE
move `branch-diff` and `changelog-maker` into foundation

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#16]
These tools are active parts of our release pipeline, perhaps it would make sense for them to live in here.

/cc @rvagg

**Comment by gibfahn** [comment]
SGTM

**Comment by rvagg** [comment]
Fine by me, along with make-node-meeting pls

**Comment by mhdawson** [comment]
+1 from me.

**Comment by bnb** [comment]
+1 😄

**Comment by joyeecheung** [comment]
I think if there are not objections within 14 days, we can just move things forward and ask @rvagg to [transfer the repository](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) now?

**Comment by jasnell** [comment]
+1

**Comment by rvagg** [comment]
done, commit-stream is integral to both of these, any objections to moving that too?

**Comment by MylesBorins** [comment]
+1

**Comment by joyeecheung** [comment]
@rvagg Yes please! (If no one objects, which I don't think there will be)

**Comment by rvagg** [comment]
moved commit-stream too

I hope others actually take up the task of maintenance and improvement and it's not just me continuing my work in a different org on all of these tools that I've moved in

**Comment by joyeecheung** [comment]
@rvagg That's the goal. Also we are talking about putting these tools in a monorepo (https://github.com/nodejs/automation/issues/1 & https://github.com/nodejs/automation/pull/9) so hopefully that increases visibility as well.
