### ISSUE TITLE
archive nodejs/node-eps repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#160]
We don't use it anymore. Archiving it will leave it as readable but will prevent people from opening issues and pull requests, and will also signal clearly that it's legacy. Archive it?

@nodejs/tsc @nodejs/community-committee

**Comment by TimothyGu** [comment]
+1 for archiving.

**Comment by joyeecheung** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
Done.
