### ISSUE TITLE
Node.js Africa Launch - Node.js Nigeria Conf 2018

### ISSUE THREAD

**Issue by codeekage** [nodejs/admin#170]
The Node.js Africa Team will love to invite the @nodejs/collaborators to join us officially launch Node in Africa. 

Venue: ...
Date: 8th September, 2018.
Time: 11AM

Sponsor/ Attend/ Speak here: https://github.com/nodejsafrica/events/blob/master/node-ng-conf-2018/attendance.md

Hope to see some collaborators here in Nigeria. Thank you 🙏

**Comment by benjamingr** [comment]
Hey, is this an official Node.js Foundation event?

September 8th 2018 is pretty close already and I would not be able to attend due to prior obligations. 

Other than that - great initiative and I would love to attend a Node.js Africa event in the future.

**Comment by watson** [comment]
Great initiative. I know almost nothing about how big the Node.js usage is in Nigeria or even across Africa. It might be fun to get some fresh numbers from npm and the Node.js foundation to present at the event.

What's the process of submitting talks?

**Comment by ladyleet** [comment]
Congrats @codeekage on launching this!

**Comment by codehakase** [comment]
Congrats @codeekage and everyone involved!!!

**Comment by jalasem** [comment]
Great initiative 
What are modalities for submitting talks?

**Comment by IsraelGboluwaga** [comment]
Great one @codeekage. Can't wait. 

@watson you'd be shocked at how many people use node js around here.

**Comment by benjamingr** [comment]
I'm really confused at this issue.

 - Is this an official Node.js event? Is it related to the Node.js foundation?

I am very pro advocating and evangalizing Node.js in Africa but this is really confusing. It's not clear to me how to help or what's being done.

**Comment by ladyleet** [comment]
@benjamingr this is not an official Node.js Foundation event. :) @codeekage it would be great to let the community know how specifically we can help with community support as we do all other events!

**Comment by benjamingr** [comment]
@ladyleet then I do not understand why it's a topic at @nodejs/admin with a collaborator ping?

There are a lot of conferences involving Node.js and they don't ping nodejs/collaborators asking for help in the admin repo.

I would have expected the following instead:
 - If a code and learn is planned, a post to https://github.com/nodejs/code-and-learn 
 - If a summit is planned (I don't think one is), a post to https://github.com/nodejs/summit/issues
 - If anything administrative is required from the foundation - a post explaining that
 - If anything from the community committee is required, a post to https://github.com/nodejs/community-committee/


Otherwise, since this is not a Node.js foundation event - this feels like I got pinged into a private event. When @codeekage said:

> The Node.js Africa Team

It is unclear if we actually have a nodejs/africa team in the foundation that is tasked with promoting the project in Africa or if that's a private initiative. 

So in general:
 - I think the topic is important and would be willing to help
 - I don't think the post is appropriate given there are a lot of conferences but we haven't had any posts here from them (likely a good thing).

I don't want this sort of thing to be a trend.

**Comment by ladyleet** [comment]
@benjamingr this was submitted from the community as an issue on this repo. administrators can feel free to close or provide suggestions for what types of issues should be posted. :) i'm sure @codeekage appreciates your thoughts.

**Comment by hashseed** [comment]
I'm a bit irritated as well that all collaborators were pinged. This should not become a trend. I'm certain most collaborators cannot make any meaningful contribution here and for me this just adds noise.

**Comment by ladyleet** [comment]
k - well let's be nice - feel free to close the issue and suggest other ways @codeekage and others can engage in the future. :)

**Comment by benjamingr** [comment]
@ladyleet - @codeekage is a member of CommComm which oversees this repository - my assumption is that they are more informed than I am regarding the appropriateness of posting this here.

I don't have a very strong feeling about it (but generally agree with Yang) and I am bringing up a concern I've had regarding this issue. This isn't an adversarial thing - I want to understand better what our policy on this is.

I do not think @codeekage meant any ill intent with this - I just want to understand our policy better and understand what the appropriate channels for this are.

**Comment by ladyleet** [comment]
@benjamingr 👍

**Comment by ryzokuken** [comment]
I think @codeekage meant this more as an announcement, but I do agree on @benjamingr and @hashseed that:

1. It seems completely out of scope of nodejs/admin.
2. I believe most of the people who got pinged with the collaborators ping either aren't interested or won't be able to make it there.

Personally, I'd have liked it better if there wasn't a ping on the collaborators team because that seemed entirely unnecessary, and if @codeekage or one of the organizers of the event had provided an actionable list of stuff that interested individuals could use to help out.

**Comment by bnb** [comment]
Appreciate the initiative @codeekage, but generally events like this haven't been involved in the Node.js project - they've been very community driven. This isn't to say that having something more focused on events isn't wanted, but this repository isn't the appropriate venue for promoting events.

I'm going to close this for now. @codeekage if you would like to discuss a space for discussing events and creating a path for all kinds of community events to be promoted, I highly suggest creating an issue in the CommComm repository to discuss it. We will need to assess it and our ability to execute successfully on it (we've made a few attempts at this in the past without gaining much traction) and be able to decide if we can follow through effectively based on that discussion.

**Comment by hackygolucky** [comment]
@codeekage @benjamingr @ladyleet  My recommendation is to move this to a CommComm repo. This is out of scope for this repo(as its purpose is for joint administration efforts as related to the top-level committees of the project) but I think we may be able to chalk this up to folks not knowing expected practices in the Node.js project repos. As folks have said, we have to be respectful of not pinging everyone unless it it relevant to do so, so we try not to @-a large group of people in the project unless it is incredibly poignant and time-sensitive.

A few repos appropriate for us to help share the good word!:
- https://github.com/nodejs/community-committee/issues
- https://github.com/nodejs/evangelism

**Comment by bnb** [comment]
Going to close this for now.

@codeekage if you'd like to further discuss, please open an issue in a CommComm repo per @hackygolucky's suggestion 👍

**Comment by codeekage** [comment]
Had issues accessing github for some days. Sorry I’ve not been able to take questions and sort out this issue. :pray:

**Comment by codeekage** [comment]
Correction noted. Sorry to all @nodejs/collaborator for stepping out of line with this issue hope it gets sorted out in better manner. 

The aim was formerly inform all collaborators on what we intend to do in some few months and also get help from more experienced folks who have hosted tons of event and would love drop some interesting recommendation to make it a successful event. 

The only action item was assisting in best possible ways. 

Thank you for closing and fixing up my mistakes. Lesson learn :smile:

**Comment by codeekage** [comment]
Can I ping you on Twitter @benjamingr let’s draft a formal document for the CommComm and Code-And-Learn?

**Comment by benjamingr** [comment]
@codeekage I don't use twitter as I don't consider it a very conductive platform for constructive communication. You can shoot me an email to the email listed under my name in https://github.com/nodejs/node and I would love to see how I can help with this.

**Comment by maddhruv** [comment]
![screenshot_2018-07-02-17-44-15](https://user-images.githubusercontent.com/18121502/42163296-94241a46-7e1f-11e8-80c6-d803c3113e5e.jpg)

Is it?
:thinking: :confused: 
/cc @codeekage

**Comment by benjamingr** [comment]
@maddhruv It's also in the logo by the way:

![image](https://user-images.githubusercontent.com/1315533/42164408-9c66203e-7e0e-11e8-9a12-424804622785.png)

Not really sure what's up with that.

**Comment by maddhruv** [comment]
I actually was posting the heading cover but it had more colors so, 😋
Rather I choose to share the description.

BTW the more framed question is
"Is the conference/summit sponsored by NF?"

**Comment by benjamingr** [comment]
@maddhruv as far as I understand it is not but given that link I'd assume either:

 - It is foundation sponsored and that decision happened in CommComm
 - It is not foundation sponsored and there was confusion
 - There are talks about foundation sponsorship but nothing actionable.

Pinging @nodejs/community-committee to understand where we stand about this.

**Comment by codeekage** [comment]
@benjamingr I was specifically asked by @zibby from Node.js Foundation to include sponsored or supported by Node.js Foundation and you still dwelling on this doesn't look nice at all or tell well on my image as a collaborator.

Node.js Foundation has always sponsored SWAGs for the events we've held in the past and even for this very event, the SWAGs have been covered by the Foundation.

@maddhruv That doesn't look like a logo and That's a web banner for the event.

It will be nice if you could always ping me to confirm things you don't understand and get clarification.

This issue has been closed and should remain closed.

Thank you.

**Comment by maddhruv** [comment]
> That doesn't look like a logo

@codeekage when did I referred it a logo???
Neither of my two comments say _logo_

Sorry if the comments above are offending! 🙏🙏

I will delete them if you really wish

**Comment by codeekage** [comment]
@maddhruv I'm not offended just clearing out the point of @benjamingr calling it a logo with many colors.

**Comment by benjamingr** [comment]
So just to clarify: the answer to the question we've had about the conference is that the Node.js foundation is sponsoring SWAG and other things for the event so the quote is accurate.

Is my understanding correct @codeekage ?

**Comment by codeekage** [comment]
Yes, @benjamingr. Thank you for your clarification.

**Comment by codeekage** [comment]
Please, anything regarding this event can be addressed to me via the email address listed here https://github.com/nodejs/community-committee 

Thank you.

**Comment by codeekage** [comment]
I think it is best to push this to the CommComm  repo if they should be any further discussion on this issue has being clarified that the foundation sponsors swags for event. 

The foundation and most member of the node.js was aware before the formation of the node.js Africa org. 

The neccessity of going over this again is best addressed through me and the

**Comment by codeekage** [comment]
@Bamieh I don’t think this issue should be addressed in this repo anymore. 

The organization (node.js Africa) is moderated by me and I’m a member of the node.js org. Even before the formation of the mentioned org the foundation and most members of the org were aware. 

I hurriedly rushes into making announcements here which was completely wrong and corrections have made. 

Informations about the event and the org can be found in @nodejsafrica repos. 

I only mentioned communicating with me freely which is a matter of choice. 

This repo has been abused by me and I wouldn’t someone else making this same mistake. 

I will be closing this issue with this comment and please any further questioning or discussion should be done here: @nodejsafrica/admin or done in the CommComm repo. 

Thank you :pray:
