### ISSUE TITLE
Pings on nodejs/help

### ISSUE THREAD

**Issue by benjamingr** [nodejs/admin#177]
Hey,

Sometimes people ping teams (like /collaborators or /some-subsystem) in the https://github.com/nodejs/help/issues repo.

Some people feel like this is helpful in presenting a welcoming environment to new community members.

Some people feel like this is noisy and is creating churn and noise for collaborators.

Should we have a policy (or preference) on this?

(If you do not want to comment, feel free to react with 👍 for encouraging pings and 👎 for discouraging them)

**Comment by WaleedAshraf** [comment]
As far as I know, pinging **/collaborators** should be done only when someone is absolute about it because it has most members than any other team.

I think a general guide about when/how to ping teams would be great.

**Comment by ljharb** [comment]
I always want to be notified for anything related to the teams I’m on, but it’s not practical to follow every issue on every repo.

**Comment by Bamieh** [comment]
I feel that we should not be addressing this in a policy unless there are serious spams going on. IMO let us just keep this flexible for newcommers and let them use their best judgement on the pings.

Note that this based on me personally not minding getting pinged on issues.

**Comment by addaleax** [comment]
Fwiw, it’s pretty easy to set notifications for individual repositories to “ignore” – does that work for people who don’t like this?

**Comment by bnb** [comment]
@Bamieh FWIW you can't use an @org/team mention unless you're a member of the GitHub org, so as far as I know only other members could actually use this 🤔

**Comment by Bamieh** [comment]
@bnb true, I meant by new comers as people who recently joined the organization.

**Comment by benjamingr** [comment]
Looks like we have not reached consensus on whether or not this is a good idea and discussion has exhausted itself so I don't think we should have an official policy for now.

If anyone feels strongly about this issue feel free to reopen.
