### ISSUE TITLE
deleting a comment in https://github.com/nodejs/node/pull/21654

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#191]
Probably not malicious, but deleting this non-Collaborator comment in https://github.com/nodejs/node/pull/21654.

<img width="805" alt="screen shot 2018-07-23 at 8 36 02 pm" src="https://user-images.githubusercontent.com/718899/43115448-c5f4659a-8eb8-11e8-9a6f-70729f23f982.png">

**Comment by Trott** [comment]
Seems like nothing else to do here probably, so closing.

**Comment by ryzokuken** [comment]
@Trott GitHub now makes edits public, so it's relatively easy for people to see the text. I have not dealt with full redactions before, but can you somehow make this readable only for collaborators (kinda like locking the conversation, I guess).

**Comment by targos** [comment]
It's possible to delete the original message from revision history:
- click the `edited` drop down
- click on the message to delete
- click "Options"
- click "Delete revision from history"

**Comment by Bamieh** [comment]
@Trott I hope you don't mind that I removed it from history myself.

**Comment by ryzokuken** [comment]
Thanks, @targos. Glad we could take care of this super quickly.

**Comment by Trott** [comment]
FWIW, I'm pretty sure the history is only visible to people with commit privs to this repo. But better safe than sorry, so thanks for fully redacting everyone!

**Comment by brodybits** [comment]
FYI I was able to see the original content by @Trott in the drop-down edited history before it was explicitly deleted. Thanks @targos for the instructions, I didn't know it before.

**Comment by Trott** [comment]
> FYI I was able to see the original content by @Trott in the drop-down edited history before it was explicitly deleted. Thanks @targos for the instructions, I didn't know it before.

Oh well, there goes my theory! Thanks for the correction. And doubly thanks to folks for fixing it.
