### ISSUE TITLE
A Discussion on Scope

### ISSUE THREAD

**Issue by snostorm** [nodejs/admin#2]
As discussed in #1 and nodejs/summit#12 , this team's scope should be clarified by the wider community to ensure it will actually fill a need. Many people will be bringing many ideas on what the possible scopes _could_ be.

Let's collect them for future discussion and debate. Instead of too much yes/no debate in this thread, let's stick to idea collection and cover that later with our first round of Kickoff discussions. That said, if there are points or examples able to expand or clarify an existing idea, or concise con's worth including in an agenda, please add them.

The section below will summarize any ideas added later in the thread, linking to specific comments if the idea isn't concise (for space purposes.)

---
### Act as a "switchboard" for connecting groups.

Helping to connecting individuals and/or groups together within Node.js. Somebody might not know the right repo/WG to turn to for what could be a build or website issue.
### Acting as a hub for the collection and dissemination of best practices among WGs.

This could both be proactive research on how various WGs are operating and also a general dumping ground for ideas when members see things are working well within their groups. _Brief case studies, best practice documents, a WG "getting started" guide, etc._
### Networking

Meetings and forums to allow members of otherwise disconnected projects under the Node.js umbrella to have a reason to say "hi." The idea is reps from any interested WGs (ideally all WGs) would occasionally met and/or async. discuss what has been working well (or not so well) for them
### Workflow Tooling

To help identify shared needs among groups to try and reduce overlapping efforts. Relevant successful tooling could be shared; new tooling could be built in coordination with other groups like Website, Build, etc.
#### Specific Ideas
- The "schedule a meeting" button to automate all of the steps each WG maintainer has to go through in order to actually organize.
### WG Inventory

Maintain a centralized list of all Working Groups, their scopes, main organizers, etc. 
### Provide a WG Web Presence

Helping to provide a one-stop-shop on the Node.js Website for groups to easily publish information on their scope, activities, meeting minutes, meeting times, core membership, channels of communication, etc.  _Ideally much of this information could get vacuumed up from the individual WG repos to keep it all automated and decentralized._
### Provide a Home for Connecting Related Groups

The Evangelism, Documentation, Website and Internationalization Working Groups all have overlapping responsibilities with the 30+ language-based groups inside the project. This initiative acts as a hub for them to organize around common issues without also having to spin up a "Pan-Internationalization of Marketing and Online Content" group.

**Comment by snostorm** [comment]
From @jasnell in https://github.com/nodejs/summit/issues/12#issuecomment-129261660

> The scope of the WG needs to be carefully planned out. The role of this new WG would be to facilitate communication between the various WGs and to ensure that they have access to the resources needed to complete their goals. This may involve things like working with the TSC and the Foundation board to ensure that the necessary resources are even available, ensure that communications channels are open, and ensure that issues are being dealt with. The role is similar to those found in other organizations such as the W3C Team Liaison's that participate in W3C Working Groups. To be certain, the liaison does not have the authority to speak on behalf of either the TSC or Foundation board but do enable collaboration.

**Comment by mhdawson** [comment]
The concept of putting in place a common set of  tools/process for running a WG (scheduling meetings, sending out invites etc, best practices and howtos) sounds good to me.
