### ISSUE TITLE
Adding `Good First Issue` to all public repos in the Node.js Org.

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#20]
I'd like to suggest that, as the TSC and CommComm, we add the `Good First Issue` label to public repos in the GitHub organization.

I'd like to suggest this for a few reasons:
- Consistency: nodejs/node uses it, but (to the best of my knowledge) most other repos in the org use `Good First Contribution`.
- Ease of use: Having this on public repos will enable maintainers to quickly add it, and those looking to contribute to find issues more easily.
- Buy-in: It seems like GitHub itself has endorsed this specific method of "good for beginners" labeling with a recent update. Not sure if there's actual functionality around this, but it's better overall to use the same systems those new to the project may see elsewhere.
- Getting Started: This is also a VERY good resource for the nodejs/getting-started repo. I've been asked about two dozen times how to get started with contributing, and depending on the individual's interests I can _sometimes_ point them to issues labeled accordingly.

One barrier here may be, as mentioned, that most repos that have something like this in place use `Good First Contribution`. Changing the label is a possibility, though we'd of course want to respect the wishes of WG members if they were -1 on this change.

**Comment by Qard** [comment]
👍 for consistency.

**Comment by gibfahn** [comment]
>Consistency: nodejs/node uses it,

FWIW I assume someone renamed `Good First Contribution` -> `Good First Issue` since Github started including this notice:

<img width="501" alt="image" src="https://user-images.githubusercontent.com/15943089/31588172-37d2b4d8-b1e6-11e7-9e3c-335fe1ad0574.png">

+1 to using this if it's what Github considers a standard.

**Comment by mhdawson** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by hackygolucky** [comment]
Awesome. Can someone with owner access do this? cc @mhdawson and @MylesBorins because I don't know the full list of folks who currently have owner access.

**Comment by bnb** [comment]
I have added to all the CommComm repos 👍

**Comment by Trott** [comment]
If someone wants to do this, please do! But otherwise, this has been pretty quiet for almost five months, so I'm going to close it. Feel free to comment or re-open if you plan on working on this.
