### ISSUE TITLE
Input needed: Member Travel Fund (reconciliation & improvements)

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#205]
Hey all! :) This is concerning a PR and processes I'd like to make with regards to the travel fund.

Starting an issue here since there are too many threads going on about this and tagging who have previously expressed interest @JemBijoux @mhdawson @joyeecheung @bnb @williamkapke @dshaw @mcollina @MylesBorins 

**Problem:** Currently, there is very little visibility when looking at the MEMBER_TRAVEL_FUND.md as to how much has been paid out and submitted for reimbursement.

**Solution:** Provide more transparency to the travel fund of:
1. What's been approved and total dollar amount (Community)
2. What's been submitted for reimbursement and total dollar amount (Node Foundation)
3. What's been paid out and total dollar amount (Node Foundation)

**Currently:**
Been working on getting all the info for this for a few weeks and finally we have a spreadsheet that outlines a few things [here](https://docs.google.com/spreadsheets/d/1IzQ4KW0J1L6hRjSOi-ShkJs1QHfTzM-7uSTDRpKP32A/edit#gid=0) - view only.

I would like to **delete** this spreadsheet asap and only work in github for this so we consolidate where information is being disbursed. I also am in favor of have one source of truth.

**Summary of spreadsheet**
1. Added all rows on MEMBER_TRAVEL_FUND.md (might be a few days out of date)
2. Added what has been submitted and reimbursed as of up to June 30
3. Highlighted the three important columns and added totals to the bottom of the spreadsheet.

**Suggested PR & Process Moving Forward:**
1. I would like to add a few new columns to the MEMBER_TRAVEL_FUND.md that reflect this spreadsheet.
2. @mhdawson suggested we put the total numbers someplace visible -  but perhaps this solves that problem?
3. Whenever there is a request that comes in for reimbursement a new PR will be submitted to update the totals.
4. Whenever there is a disbursement from bill.com OR every month when the financials come out, a new PR will be submitted to update the totals.

**Questions? Comments?**
Let me know your thoughts! Did I miss anything that we need to cover? Good idea? Bad idea? Suggestions?

I would like to submit this PR asap because this spreadsheet will get out of date very soon and it'll be confusing for all. 😄 

If all are good to move forward I can start with an initial PR and ask for feedback there. 🎊

**Comment by mcollina** [comment]
I'm totally +1 on the proposed approach, send the PR.

**Comment by ladyleet** [comment]
@mcollina lightning fast! :) thanks for the input!

**Comment by ladyleet** [comment]
@joyeecheung that is a good idea. or perhaps after the year closes we should move them to a different .md file? i could see us doing this for 2017.

**Comment by joyeecheung** [comment]
@ladyleet SGTM

**Comment by mhdawson** [comment]
+1 for having a different file for each year.  We had discussed that earlier, just needed somebody to do it :)

I'm also +1 to adding the columns.  My only additional suggestion might be to somehow flag the rows that have been included in the current total so that its easy to tell which ones you should add to the total to get the up to date amount.

**Comment by WaleedAshraf** [comment]
SGTM 👍 
We can automate updating totals later on. That will save creating a separate PR for updating total.

**Comment by ladyleet** [comment]
@mhawson sorry if this seems like a silly question but how do you suggest we do "My only additional suggestion might be to somehow flag the rows that have been included in the current total so that its easy to tell which ones you should add to the total to get the up to date amount."

**Comment by ladyleet** [comment]
@WaleedAshraf yes @bnb brought up i think it was manhattanjs that does this well. but i'm all for just getting this done asap and then making improvements.

**Comment by mhdawson** [comment]
@ladyleet it could be a column that indicates if they are included or not, or possibly bolding non-bolding or some other type of formatting?

We might even change the format, so that we have an upper section with the requests that have been included in the total, with a lower section that people PRs new requests info.  When the totals are updated the entries in the lower section could then be moved into the upper section.  Just a few ideas off the top of my head.

**Comment by ladyleet** [comment]
@mhdawson okay I'll play around with it for sure to take these things into consideration. Sounds like most are 💯 should I green light?

**Comment by mhdawson** [comment]
I'd say generate the PR for your suggested changes :)

**Comment by JemBijoux** [comment]
Hey @ladyleet can I follow up with you around this and see if there's anything I can do to help?

**Comment by ladyleet** [comment]
@JemBijoux not yet! :) needed to figure a few things out and update to the latest #s. soon. :)

**Comment by chowdhurian** [comment]
Closing this as it looks to me like this was addressed in #226! Please feel free to reopen when necessary! 💛
