### ISSUE TITLE
Update GitHub Organization URL and Verify it

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#207]
GitHub just launched a feature that enables [verification of domains](https://help.github.com/articles/verifying-your-organization-s-domain/) on org profiles.

I went to the Node.js org profile, and noticed it still links to nodejs.org/foundation. Presently, that redirects to https://foundation.nodejs.org/

I'm not 100% sure for the reasoning behind linking to the Foundation site originally, but at this point with the verification feature GitHub has shipped I think it makes more sense to just link directly to nodejs.org – which links to the Foundation page for interested individuals.

**Comment by TimothyGu** [comment]
> I'm not 100% sure for the reasoning behind linking to the Foundation site originally

I think that's because the org is for the entire Foundation, rather than just for the Node.js project.

**Comment by bnb** [comment]
Express (and libuv?) is theoretically under the Node.js Foundation as far as I know, yet is in an entirely different organization that links to the express website, not the foundation site. The same should be applicable here.

**Comment by bnb** [comment]
@Trott @mhdawson @MylesBorins @rvagg any possibility on this? Not sure what's needed on the website end at present 😬

**Comment by Trott** [comment]
I'm for linking to nodejs.org but wouldn't want to do that unilaterally so I'll wait for a few others to weigh in for sure....

**Comment by rvagg** [comment]
well, there's 3 of us with a +1 so how about I just do it eh? https://nodejs.org/foundation/ is kind of a weird link to have, I wonder who did it in the first place?

**Comment by rvagg** [comment]
<img width="329" alt="verified" src="https://user-images.githubusercontent.com/495647/44374609-75512480-a532-11e8-8958-aee430123e17.PNG">
