### ISSUE TITLE
Moderation Team at Collab Summit(JS Interactive 2018)

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/admin#208]
As noted in https://github.com/nodejs/summit/issues/100, and discussed in a Moderation Team meeting on Aug. 8, for getting more folks into moderating in general as collaborators and interest in the Moderation Team or considering self-nominating for the Moderation Team, we'd love to chat. 

Agenda TBD

**Comment by Trott** [comment]
The event is passed, so I'm going to close this.
