### ISSUE TITLE
Creation of a new repository: security-advisories

### ISSUE THREAD

**Issue by vdeturckheim** [nodejs/admin#210]
Hello, 

As of [current policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories), I would like to request the authorization to create a new repository name nodes/security-advisories.
It will contain the current content of the 'vuln' directory of the Security WG current repository (https://github.com/nodejs/security-wg/tree/master/vuln). This repository would be managed by the Security Working Group.

Having a separate repository for these data has been requested by several third parties and WG members in order to a cleaner and more efficient management of this dataset.

Thanks a lot,
Vlad

cc @nodejs/security-wg

**Comment by sam-github** [comment]
Sounds very reasonable to me. +1

**Comment by vdeturckheim** [comment]
Closing as nobody objected. I will create the repo now.

**Comment by vdeturckheim** [comment]
https://github.com/nodejs/security-advisories
