### ISSUE TITLE
JS Interactive & Node Community Corner - Questions?

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#211]
In order to create more transparency within what is going on with the new JS Interactive, including the Node Community Corner (we are organizing agenda on issue https://github.com/nodejs/summit/issues/103), myself and a few others will be coming to the TSC & CommComm this week and next to help answer any questions and get everyone more involved.

Please feel free to use this issue to post questions here so we can have some time to get ready for answers. We'll of course have open discussion as well during those meeting times.

We'll also be providing regular updates every 2 weeks so that any questions can be addressed in a timely fashion!

**Comment by ladyleet** [comment]
@bnb @jasnell @mhdawson how do i cc agenda issue so this gets added every 2 weeks? thx in advance for help. :)

**Comment by bnb** [comment]
cc @nodejs/community-committee 👍

**Comment by ladyleet** [comment]
ah cool thanks @bnb. i'm assuming tsc has their own label, etc so i'll wait for help with that.

**Comment by bnb** [comment]
I got your back, @ladyleet 😜

**Comment by ladyleet** [comment]
@bnb haha magic! thanks! 🥇

**Comment by ladyleet** [comment]
just a reminder that please post any questions here for today's TSC! :)

**Comment by Trott** [comment]
(Removed `tsc-agenda` label because we've got this slated for a private meeting today. If that's the wrong thing to do, feel free to add the label back. I'm just trying to make sure it doesn't mistakenly appear on next week's public agenda.)

**Comment by mhdawson** [comment]
@ladyleet when you think its a good time for an update in the public section please re-add tsc-agenda.

**Comment by ladyleet** [comment]
@mhdawson pretty sure i can't add labels - but can you add this back to tsc-agenda for next week?

**Comment by ladyleet** [comment]
@Trott can you please add tsc-agenda label for this week's TSC meeting? 🥇

**Comment by mhdawson** [comment]
@ladyleet its too late for it to be auto-added to this week's meeting. If we add it now it will be added to next week's meeting, is that ok?

**Comment by Trott** [comment]
> @ladyleet its too late for it to be auto-added to this week's meeting. If we add it now it will be added to next week's meeting, is that ok?

@mhdawson Why not just add it to this week's agenda right now?

@ladyleet Anyone can add anything to the agenda. Just leave a comment in the meeting issue, which for this week is https://github.com/nodejs/TSC/issues/597.

> @Trott may be worth leaving the label on until the event is over 😉

@bnb 👎  We should never leave things on the agenda if there is not something to say/do about them. That is hugely disrespectful to people who use the agenda to figure out whether or not they need to make an extra effort to attend. For many people, these meetings are early in the morning or late at night. For others, they need to move around work meetings so they can attend. Not everyone on the TSC is paid to work on Node.js. 

This is one reason why I consider the standing items on the TSC agenda to be abominations and I wish we would explicitly forbid standing items.

**Comment by Trott** [comment]
> @ladyleet Anyone can add anything to the agenda. Just leave a comment in the meeting issue, which for this week is nodejs/TSC#597.

(Went ahead and did it.)

**Comment by ladyleet** [comment]
Okay thank you for both your help @trott and @mhdawson I'll go ahead and comment tsc issues for future meetings! :) See y'all tomorrow!

**Comment by mhdawson** [comment]
@Trott I was just asking if it needed to be on this week versus next.  In any case its on the agenda now so all is good.

**Comment by mhdawson** [comment]
If possible it would be good to vote on @gabrielschulhof's nomination in the meeting.  

 @gabrielschulhof are you going to be able to make it?

**Comment by mhdawson** [comment]
Removed from agenda, until there is another update.

**Comment by amiller-gh** [comment]
Closing this because the event is now in the past and we ROCKED it! 🎉
