### ISSUE TITLE
creation of new repository: open-standards

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#213]
see: https://github.com/nodejs/TSC/issues/583

please lmk if you want a different name

**Comment by mcollina** [comment]
+1
Il giorno gio 16 ago 2018 alle 06:39 Myles Borins <notifications@github.com>
ha scritto:

**Comment by TimothyGu** [comment]
Sounds fine to me, though I'd slightly prefer just "web-standards".

**Comment by MylesBorins** [comment]
@TimothyGu I've updated the issue title, happy to go with shorter name

**Comment by joyeecheung** [comment]
+1

**Comment by MylesBorins** [comment]
Quick question before I make the repo

EMOJI VOTE for the name

open-standard 🎉
web-standards ❤️

**Comment by mhdawson** [comment]
+1

**Comment by boneskull** [comment]
somebody make the repo already 😝

**Comment by MylesBorins** [comment]
I've been on vacation this week. Current blocker on repo is getting a
readme and stuff together... If someone else from the org wants to kick it
off please go for it

**Comment by MylesBorins** [comment]
It is done
