### ISSUE TITLE
Node Community Corner at Node + JS Interactive - Agenda Committee 8/31

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#219]
Over the past few weeks we have collected topics folks are interested in covering in the Node Community Corner (issue https://github.com/nodejs/summit/issues/103).

We are now looking for a few folks to represent TSC & CommComm who are interested in helping lead the final agenda.

In order to accommodate both time zones - I've scheduled this for Friday Aug 31 at 8am PT / 3pm GMT.

If you'd like to volunteer please comment in this thread with your email address and I'll add you to the invite.

Here have been the submissions so far. You can view the [raw spreadsheet](https://docs.google.com/spreadsheets/d/19gNAJJ7AiZ1k0qhXDGo4wwmDmlG8Sd9zlAnGWIFMYmc/edit#gid=1319532678) if you like.

- Effectively leverage nodejs/help repo
- Node Todo: You Can Do This!
- Redesigning Nodejs.org
- What's new in Streams!
- Building Open Source Communities
- Building Foundations of the Node.js Community

We encourage working groups to submit sessions as well, so please reach out to folks in those working groups or submit yourself!

**Comment by mcollina** [comment]
I'm in to do the work, however I've also sent a submission.

What topics are we missing that are not covered by the main tracks of the conference?

Here are some ideas:

* error handling (I've often seen this done wrong)
* promises and async await (@nodejs/promises-debugging)
* how the Node.js event loop works (this is still not clear)
* operating a large-scale Jenkins installation
* responsible disclosure of vulnerabilities (@nodejs/security-wg)
* diagnostics? (@nodejs/diagnostics)

@nodejs/user-feedback maybe you might want to recommend a few topics.

**Comment by ladyleet** [comment]
@mcollina cool addd you to the invite thanks!

**Comment by bnb** [comment]
Happy to help out 👍

**Comment by codeekage** [comment]
Happy to help out too :tada:

**Comment by WaleedAshraf** [comment]
Will be available for any kind of help. 👍

**Comment by ladyleet** [comment]
Thank you @codeekage @WaleedAshraf - I have added you both to the calendar invitation.

**Comment by joesepi** [comment]
I'm happy to help and starting next week, I will have more time to do so!

**Comment by ladyleet** [comment]
Cool! Would love a few more TSC folks to come participate. @joesepi I added you to the calendar invitation.

**Comment by JemBijoux** [comment]
@ladyleet I should have noted also, but I'm down as well!

**Comment by ladyleet** [comment]
@JemBijoux Great! Added you!

**Comment by mhdawson** [comment]
I won't be able to make the first meeting as I'm away on Friday but will try to catch up afterwards.

**Comment by joyeecheung** [comment]
I am interested in helping out! (See my profile for the email address)

**Comment by ladyleet** [comment]
@joyeecheung added you!

**Comment by dshaw** [comment]
@ladyleet The @nodejs/user-feedback would love to share what we've been doing and let folks know how we can help. Here's a quick overview of what I'd like to share:

## Bringing User Feedback to Node.js

"Over the past year a team of individuals have been working with the Node.js Community Committee to provide better opportunities to the Node.js community to connect with the Node.js project and provide feedback. The groups started by supporting the needs of the Benchmarking WG, helping create a formal survey and sharing the results. Now there are several focus areas and area leaders covering general user scenarios, tooling developers, and the enterprise use case. We are preparing another major survey for community feedback around Promises. We'll share what's worked and what has not and how you can get involved."

**Comment by ladyleet** [comment]
@ryzokuken you can feel free to propose for sure!

**Comment by davisjam** [comment]
@ladyleet I'm available to help out. Not sure if [this talk proposal](https://github.com/nodejs/summit/issues/100#issuecomment-411818696) will make it into the Node.js Summit but I would be happy to give some sketch of it here. Or simply attend office hours. Etc.

**Comment by ak239** [comment]
I know that I am a bit late but I would like to give a talk about my current [ndb](https://github.com/GoogleChromeLabs/ndb) effort.
I would like to demo this tool, highlight what challenges I had on my way and describe how this effort might affect Node tooling ecosystem.
Is it any slot that I can use? :pray:

**Comment by mcollina** [comment]
@ak239 can you prepare a title and abstract? There is space and we'll get you in!

**Comment by ak239** [comment]
It sounds awesome. Thanks a lot. Draft of title and abstract is below, I will massage it during weekends.

ndb - improved node tools
> In July I silently launched new experiment - ndb - an improved debugging experience for Node.js enabled by Chrome DevTools. ndb has some powerful features exclusively for Node.js: child processes are detected and attached to, breakpoints can be placed before the modules are required, files are editable within the UI and many others, easy-to-run profiler is included, e.t.c.
> I would like to demo ndb, tell what difficulties I encountered and share my vision how ndb might affect future of Node.js tooling.
