### ISSUE TITLE
Should we remove duplicates of the moderation doc across org?

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#22]
Seems like we still have a copy in the TSC repo, and the main Nodejs repo is still pointing to it

**Comment by williamkapke** [comment]
I'd like to see 1 source of truth

+1

**Comment by mhdawson** [comment]
+1.  There should be a single copy.

**Comment by MylesBorins** [comment]
I'll take the action item of reviewing stuff across the repo.

**Comment by MylesBorins** [comment]
I've started work on this

fix casing of md in admin repo: https://github.com/nodejs/admin/pull/25
update copy in TSC repo: https://github.com/nodejs/TSC/pull/395
update copy in core: https://github.com/nodejs/node/pull/16423

Will likely need to be updated in almost every repo in the org... will start going through

**Comment by hackygolucky** [comment]
@MylesBorins Is there more work to be done on this or can it be closed? It looks like the PRs you've linked were closed or merged, but I'm not sure about the 

> Will likely need to be updated in almost every repo in the org... will start going through

**Comment by MylesBorins** [comment]
I think this is mostly done
