### ISSUE TITLE
new repo and/or team request: tools

### ISSUE THREAD

**Issue by boneskull** [nodejs/admin#220]
@bcoe, @bengl and myself (and anyone else who is interested--let me know!) are working to improve the experience for those writing tools in Node.js.  This effort arose out of the [User Feedback Initiative](/nodejs/user-feedback).

Currently, we have some initiatives written up [in the User Feedback Initiative repo](https://github.com/nodejs/user-feedback/tree/master/groups/tooling).  One of these intiatives, ("`mkdir -p`") was recently merged (nodejs/node#21875).  Ideas have been gathered in nodejs/user-feedback#59, but the user feedback repo isn't an appropriate venue for more focused discussions.

So...

- We would like a public repo for discussion and definition of initatives scoped to this effort.
- We plan on meeting regularly (though we have yet to create a schedule) as a nascent, unofficial working group, and would like to broadcast meetings from the official Node.js account on YouTube Live.
- We would like a team to which "@" notifications can be sent.

* * *

cc @iarna and @evocateur who have expressed interest in helping  
cc @mcollina because he likes the initiatives :smile:  
cc @mhdawson because I asked him about this yesterday

**Comment by refack** [comment]
I would be happy to join.

IMHO if the repo is targeted around discussion, maybe a more specific name might be better suited (downstream-tools / userland-tools / tools-discus / tools-feedback).

P.S. We have several tools who dogfood under @nodejs/automation, @nodejs/build and @nodejs/documentation

**Comment by evocateur** [comment]
Happy to join as well.

**Comment by boneskull** [comment]
Regarding the name...

@refack To me, `downstream-tools` or `userland-tools` sound like somebody else's problem. :wink:  `-discuss` or `-feedback` imposes more limits on the scope than I think are necessary at this point.

`tools` or `tooling` would be ideal.  `tooling-group` or `tools-group` would also work, though both are verbose.

**Comment by mcollina** [comment]
I'm happy to help!

@boneskull I think we need a way to differentiate between the tools that Node.js core uses and the ones that could be built on top of Node.

@nodejs/tsc I can act as a champion in our strategic initiatives (see https://github.com/nodejs/TSC/blob/master/Strategic-Initiatives.md).

**Comment by boneskull** [comment]
@mcollina The differentiation could come in the form of a repo description and/or `README`.  It's not always clear--maybe even *rarely* clear--the purpose of any given repo by its name alone.  I'm not too terribly bothered by seemingly-similar repo names.  In isolation, most of the repo names in the `nodejs` org don't give too many hints about their purpose!

(If anything is to be done here, let's adopt a repo naming convention for both working groups and actual tools the project uses. Or throw all the tools in a monorepo 😝! In some ways this is actually a GitHub problem, since we can't subdivide the org...)

...ahem..


What I'm trying to avoid is presenting this as something "other than" or "apart from" Node.js core.  It's not about building userland tools--it's about building a better Node core for those who choose to build userland tools.

Maybe it sounds like splitting hairs... but really, I'm cool with any name  that is consistent with this idea.

**Comment by Trott** [comment]
I'm fine with the name as is. We can always change it later if someone comes up with a better name. (There's certainly precedence for that. My `node.git` directory on my computer is named `io.js` because the repo used to be named something else. 😄 )

**Comment by Trott** [comment]
(Just in case it's not clear: +1 from me.)

**Comment by refack** [comment]
> tooling

I like `tooling`. It succinct, and and to me does not imply there's a bunch of tools inside.

In anyway I'm +1, and leave the final work WRT the name bikeshedding to the OP.

**Comment by refack** [comment]
Maybe what I'm missing as well is a slightly more focused definition of what "tools" are. I'm assuming CLI apps, but maybe that's too narrow...

**Comment by bnb** [comment]
I would ❤️ to participate in this.

**Comment by obensource** [comment]
I'd love to help–count me in! 👋

**Comment by Bamieh** [comment]
I would love to help as well

**Comment by bnb** [comment]
>Maybe what I'm missing as well is a slightly more focused definition of what "tools" are. I'm assuming CLI apps, but maybe that's too narrow... 

@refack I'd assume CLI tools for sure are a part of this, but one of the referenced things is `mkdirp` which is a dead-simple module. I think the definition is probably much more broad. For example, I'd personally consider both [Probot](https://probot.github.io/) and [Package Phobia](https://packagephobia.now.sh/) "tools for Node.js". Probot is a module to interface with GitHub Apps directly, while Package Phobia teeters on the edge of useful for end-users/useful for developers – but I'd still consider it a tool for Node.js.

Of course @boneskull's, @bcoe's, and @bengl's definitions may vary 😄

**Comment by mcollina** [comment]
I'm tagging this tsc-agenda, I think we can move forward.

**Comment by boneskull** [comment]
@bnb Yeah, that's fair.  CLI apps are the major driver though. 

The `mkdirp` PR came from the need for CLI apps to do this sort of thing quite often (think scaffolding tools).  The initiatives won't necessarily be CLI-specific, but I imagine some will be much less useful for deployed services, cloud functions, etc.

**Comment by watson** [comment]
I'm interested in helping out as well

**Comment by mhdawson** [comment]
+1 its great to see this happen.  Also my 2cents.  A bit verbose but maybe "tools-for-nodejs" as the repo name ?

**Comment by mhdawson** [comment]
@nodejs/tsc @nodejs/community-committee ping as I believe the process for a new repo is:

```md
Provided there are no objections from any TSC or CommComm members raised in the issue, such requests are approved automatically after 72 hours. If any objection is made, the request may be moved to a vote in each of the Technical Steering and Community Committees. If either the TSC or CommComm rejects the request, then the request is denied.

In certain cases, Node.js Foundation Board of Directors approval may also be required.
```

So unless there are objections to the creation of the new repo can simply move forward.  I suggest we just wait 72hrs from this ping ( I don't believe this falls into the case were we need to involve the board)

**Comment by mhdawson** [comment]
One more suggestion for the name 'tooling-support-wg'

**Comment by richardlau** [comment]
> One more suggestion for the name 'tooling-support-wg'

I wouldn't want to name something `-wg` unless it actually is, or is likely to become, an actual working group. Maybe this will become one, but at the moment it's proposed as "new repo and/or team".

**Comment by mhdawson** [comment]
@richardlau true, but we do have the security-wg which was only chartered after quite a while.

**Comment by boneskull** [comment]
`tool-aid` :wink:

**Comment by boneskull** [comment]
@mhdawson @richardlau we can be clear about being *non*-chartered in the `README`, if that's helpful. 

That said, this effort may or may not become a chartered WG at some point. The future is hazy...

I would like to avoid `support` in the name (no tool support!! use SO!!), or `userland`, `downstream`, or `ecosystem` for reasons I've mentioned above.

Names, in order of my preference:

1. `tooling`
2. `tooling-wg`
3. `tooling-group`
4. `tool-aid` 😎 

If anyone objects to `tooling`, please move to next one. 72h after no objections, then sounds like we can create it.  Thank you everyone!

**Comment by Trott** [comment]
I'm not going to stand in the way of it or anything, but I'd avoid `-wg` in the name as it will inevitably cause confusion about chartered vs not-chartered. We have enough of that confusion already and we should take steps to reduce that.

Also, `wg` is an abbreviation that is clear to us but not necessarily to people unfamiliar with the project. Another reason to avoid it.

**Comment by Bamieh** [comment]
I'd vote for `tooling` mainly because it is the most generic yet clearly reflects the intent of the group.

**Comment by mhdawson** [comment]
This can proceed.

**Comment by mcollina** [comment]
Repo created, https://github.com/nodejs/tooling! It's an empty scaffold :).
I've added @boneskull, @bcoe, @bengl, @bnb and @evocateur.
