### ISSUE TITLE
Badges for N-API add-ons

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/admin#221]
Over in @nodejs/n-api we've been discussing the idea of producing badges which add-on maintainers can add to their README.md to indicate that their add-on is N-API-based, and which version of N-API it uses. We wanted to discuss this more widely before starting to release documentation to the effect.

The badge would look something like this:

![n-api-badge](https://user-images.githubusercontent.com/976081/44600581-aede9580-a7a7-11e8-8fbb-c94a7cca125a.png)

I don't know why github makes it appear larger than it really is.

**Comment by bnb** [comment]
+1 to this, especially given the interesting research that @ashertrockman and a few others did on the usage of badges in npm ([ref](https://cmustrudel.github.io/projects/badges/), [ref](https://cmustrudel.github.io/papers/icse18badges.pdf)).

**Comment by bnb** [comment]
That said, `3` is a bit ambiguous. My first thought before reading the issue was that there were 3 modules using N-API in the entire application. Would `v3` or some other variant be equally acceptable?

**Comment by gabrielschulhof** [comment]
@bnb "v3" is probably better than just "3".

**Comment by digitalinfinity** [comment]
cc @seldo who suggested this idea at Node-Summit

**Comment by seldo** [comment]
Nice to see this getting action. Also, woah, @bnb, I had no idea people were doing academic research on this!

**Comment by mhdawson** [comment]
@nodejs/TSC @nodejs/community-committee please chime in if you have any concerns.  I think its a good idea and will help evangelise N-API but want to make sure there are not concerns/issues we've not thought of.

**Comment by amiller-gh** [comment]
No concerns from me – I love this idea.

**Comment by Bamieh** [comment]
I am +1 on this

**Comment by mhdawson** [comment]
Since there are no objections we'll move forward. Closing.
