### ISSUE TITLE
Summit Topic: Joint Foundation Governance Breakout Session

### ISSUE THREAD

**Issue by amiller-gh** [nodejs/admin#228]
> Stub ticket for tracking, will be filled out soon.

## Motivation
To have a substantive discussion about project governance.

## Agenda
TBD

**Comment by mcollina** [comment]
Who is going to lead this sessions? @MylesBorins @hackygolucky?

**Comment by amiller-gh** [comment]
Happy to take point on organizing / leading, but will *gladly* collab with @MylesBorins or @hackygolucky  👍

**Comment by yoshuawuyts** [comment]
A thing I feel might be worth touching on during this meeting is an RFC process for Node.

**Comment by Trott** [comment]
Is there an agenda? This is a broad topic and it would be helpful to know what aspects are planned for discussion during the limited time we have.

**Comment by amiller-gh** [comment]
Thats because so much has been in flight that I didn't have a concrete idea of exactly what format this would take until quite literally yesterday! Theres been some great conversations this week. Updating with a rough agenda now 👍

**Comment by amiller-gh** [comment]
Closing because this happened! Please check out nodejs/bootstrap for all future joint Foundation governance work, and https://github.com/nodejs/bootstrap/issues/11 for a synthesis of takeaways from the session 🎉
