### ISSUE TITLE
Un-archive node-addon-examples repo

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/admin#229]
Could we please un-archive this repo? We would like to add examples showing N-API used directly and via node-addon-api.

cc: @nodejs/n-api

**Comment by Trott** [comment]
@gabrielschulhof Is it safe to assume that @nodejs/n-api will take over maintenance of the repository? (Basically: Keeping it up to date.) If so, great, we'll make that team the Collaborators team for the repository. If not, any idea who?

**Comment by Trott** [comment]
OK. Is this time-sensitive? Unless someone objects, this request can be considered automatically approved in a about 53 hours from now. 

Pinging people that might have opinions: @rvagg @eljefedelrodeodeljefe

**Comment by mhdawson** [comment]
Not time sensitive. +1 from me.

**Comment by mcollina** [comment]
+1
Il giorno ven 7 set 2018 alle 22:30 Michael Dawson <notifications@github.com>
ha scritto:

**Comment by mhdawson** [comment]
@gabrielschulhof its been 72 hours so I think we should be good to go.

**Comment by gabrielschulhof** [comment]
@mhdawson I don't quite understand. I still cannot push to the repo because it remains archived. Somebody with the appropriate access needs to unarchive the repo so we can start making PRs against it and then land those PRs.

**Comment by Trott** [comment]
And I just updated the collaborators to be @nodejs/n-api. Closing.
