### ISSUE TITLE
Removing org members who are on 0 teams

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#230]
Barring objections from @nodejs/tsc or @nodejs/community-committee, I'm going to remove members from the org who are on 0 teams. (I've done this once or twice before.) This usually happens when someone is on some teams, and then leaves the teams or the teams get removed due to inactivity or whatever. It is trivial to add someone back if there's a good reason to do so, so this is a low risk move.

I'll email the four people who are on zero teams to let them know so they aren't surprised when they get the GitHub email saying they've been removed. It will also give them the opportunity to say "Oh, I should be on the `fhqwhgads` translation team!" or whatever in case being on zero teams is a mistake or something.

**Comment by Trott** [comment]
(I'll do this after 72 hours.)

**Comment by refack** [comment]
Just a general reminder, membership in the github org, has 3 privileges:
1. Access to the moderation repo.
2. Free individual membership to the NF.
3. The Node.js badge on the user's github page.

IMHO it is reasonable that all of those should be based on active contribution to the project. Maybe with exception of emeriti, so maybe have an emeriti team?

**Comment by ljharb** [comment]
Such a team could be deprived access to the moderation repo, and not included in “members”, so that it would allow folks to retain the badge forever if they wished.

**Comment by addaleax** [comment]
Just to clarify, access to the nodejs/moderation and nodejs/members repositories is only granted to the nodejs/members team only applies to `nodejs/members`, not by membership in the github org itself.

**Comment by jakeNiemiec** [comment]
@Trott While you are seeking to clean up inactive members, you should also consider removing any members match the criteria for "automatic removal" per the end of Section 4 of both charters:

>In the case where an individual CommComm/TSC member -- within any three month period -- attends fewer than 25% of the regularly scheduled meetings, does not participate in CommComm/TSC discussions, and does not participate in CommComm/TSC votes, the member shall be automatically removed from the CommComm/TSC.

**Comment by Trott** [comment]
@jakeNiemiec Those criteria for removal have never been met by anyone since being adopted, at least not on the TSC side. I'm not a member of CommComm so I can't speak to that. I definitely watch out for this stuff on the TSC.  All current members of the TSC, except for the member who was only added this week, participated in https://github.com/nodejs/TSC/pull/569, so there's nobody on the TSC who qualifies for automatic removal at this time.

**Comment by Trott** [comment]
All done! Thanks!
