### ISSUE TITLE
Request to create repo napi-test-suite

### ISSUE THREAD

**Issue by gabrielschulhof** [nodejs/admin#236]
In https://github.com/nodejs/abi-stable-node/issues/334 we discussed making the N-API test suite (test/addons-napi) available as a separate npm package: napi-test-suite (or nts), so that other implementations of N-API such as [ShadowNode](https://github.com/Rokid/ShadowNode/) – which is forked from [IoT.js](https://github.com/Samsung/iotjs) might run it.

May we (@nodejs/n-api) please have a repo named `napi-test-suite`? It would initially include an unmodified copy of test/addons-napi, but might at a later time include scripts to build and run the tests.

**Comment by mhdawson** [comment]
+1 from me (but really I'm part of the team requesting :))

**Comment by richardlau** [comment]
> It would initially include an unmodified copy of test/addons-napi,

It will probably also need a copy of `test/common` if `test/addons-napi` is unmodified.

**Comment by gabrielschulhof** [comment]
@richardlau https://github.com/Rokid/ShadowNode/blob/master/test/common/index.js includes parts of what the Node.js version has, the parts that are used by the N-API suite.

**Comment by gabrielschulhof** [comment]
Ping! Any chance this may go ahead?

**Comment by Trott** [comment]
@gabrielschulhof I think the GitHub governance doc in this repo says you can go forward after 72 hours with no objections, so go for it.

**Comment by mhdawson** [comment]
We should be good to go.

**Comment by yorkie** [comment]
@mhdawson @gabrielschulhof Good to see that really happened, may I join this nodejs n-api team, either?

**Comment by mhdawson** [comment]
@yorkie do you mean be a member who can land changes in the nodejs/napi-test-suite or to joing the core N-API team as documented in nodejs/abit-stable-node.

In either case probably best to open an issue on one of those 2 repos with the request.

Closing this issue since the repo has been created.

**Comment by yorkie** [comment]
Yea, @mhdawson I'm interested in joining N-API and contribute to those :)
