### ISSUE TITLE
Moderation Discussion @ Node+JS Interactive 

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#242]
Issue to log the discussion of Moderation at Node+JS Interactive

**Comment by hackygolucky** [comment]
Notes! https://docs.google.com/document/d/1qDr-d4Ib76mtNKKIFGTQik8A7HrEqR3G7mDVkI6K28I/edit?usp=sharing

**Comment by Trott** [comment]
The event is passed, so I'm going to close this.
