### ISSUE TITLE
Split `delivery-channels` team into subteams

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#244]
Right now, @nodejs/delivery-channels has one subteam (@nodejs/version-management for folks who run project like `n`, `nvm`, etc.). I think it should have two other subteams: @nodejs/embedders and @nodejs/distros or something like that. That should cover all the people currently on the team, and so the team itself can just be comprised of the subteams. That will enable us to @-ping subteams as needed without spamming everyone else, but also allow us to notify all of them easily when that is something we need to do.

Sound OK to folks?

**Comment by mhdawson** [comment]
I'm ok with doing that, although I'm not sure its been a big problem.

**Comment by Trott** [comment]
> I'm ok with doing that, although I'm not sure its been a big problem.

I should have said so in the original post, but this is in direct response to someone who is in @nodejs/delivery-channels and wants a separate @nodejs/embedders subteam. Yes, it probably hasn't been a big problem. But, like I suspect you are, I am inclined to defer to team members on this sort of stuff.

**Comment by Trott** [comment]
Hello, folks! Which team(s) best described you? Are you an embedder, a distro, a version manager, or none of the above? Let me know...

	@alexeykuzmin	Alexey Kuzmin  alexeykuzmin
	@danbev	Daniel Bevenius  danbev Maintainer
	@deepak1556	Robo  deepak1556
	@Elexy	Alex Knol  Elexy
	@felixrieseberg	Felix Rieseberg  felixrieseberg
	@GnorTech	Kevin Fan  GnorTech
	@groundwater	Jacob Groundwater  groundwater
	@jkleinsc	John Kleinschmidt  jkleinsc
	@kapouer	Jérémy Lal  kapouer
	@lance	Lance Ball  lance
	@MarshallOfSound	Samuel Attard  MarshallOfSound
	@mhdawson	Michael Dawson  mhdawson Maintainer
	@nitsakh	Nitish Sakhawalkar  nitsakh
	@rogerwang	Roger Wang  rogerwang
	@vanessayuenn	Vanessa Yuen  vanessayuenn
	@zcbenz	Cheng Zhao  zcbenz
	@zeke	Zeke Sikelianos  zeke

**Comment by codebytere** [comment]
```
@alexeykuzmin	Alexey Kuzmin alexeykuzmin
@deepak1556	Robo deepak1556
@felixrieseberg	Felix Rieseberg felixrieseberg
@groundwater	Jacob Groundwater groundwater
@jkleinsc	John Kleinschmidt jkleinsc
@MarshallOfSound	Samuel Attard MarshallOfSound
@nitsakh	Nitish Sakhawalkar nitsakh
@vanessayuenn	Vanessa Yuen vanessayuenn
@zcbenz	Cheng Zhao zcbenz
@zeke	Zeke Sikelianos zeke
```
are all electron-adjacent and would be embedders :)

**Comment by rogerwang** [comment]
@rogerwang and @GnorTech are embedders.

**Comment by Trott** [comment]
Since @danbev and @lance are Red Hat folks, I'm guessing they should be in @nodejs/distros (which I will create as soon as I have someone to add)?

I think @kapouer is also a package maintainer for a Linux distro?

**Comment by danbev** [comment]
> Since @danbev and @lance are Red Hat folks, I'm guessing they should be in @nodejs/distros

Yep that is correct. Sorry, I only edited https://github.com/nodejs/admin/issues/244#issuecomment-430753091 which was not obvious.

**Comment by mhdawson** [comment]
I'd like to get messages sent to all 3.  I'm not of the above but interested in what problems/issues all 3 might be having.

**Comment by Trott** [comment]
This was done a long time ago but I forgot to close the issue.
