### ISSUE TITLE
Proposed merger poll

### ISSUE THREAD

**Issue by jasnell** [nodejs/admin#246]
@nodejs/tsc and @nodejs/community-committee members... As the discussion around the proposed Node.js + JS Foundation merger continues, I'd like to solicit some feedback from as many of you as possible to determine whether we have a good level of alignment around the goals and timeline.

**May I ask each of you to please respond to the following poll. You may respond privately via email or via a google form here: https://goo.gl/forms/UmUVLvQS6zWbJ6Bq1**

I will collect and report the results one week from today (or sooner if I get responses from everyone sooner than that)

The poll is simple, for each statement, indicate your level of agreement (or disagreement) on a scale of 1 to 5.

1 (strongly disagree)
2 (somewhat disagree)
3 (neither agree or disagree)
4 (somewhat agree)
5 (strongly agree)

1. I understand the goals of the proposed Foundation merger.

2. I believe the proposed Foundation merger will benefit Node.js.

3. I believe the proposed Foundation merger will benefit JS Foundation projects.

4. I understand the motivation for the timeline proposed by the Foundation board for the proposed merger.

5. I believe the Node.js board has adequately considered the interests of the Node.js project while evaluating the proposed merger.

6. The proposed merger will solve existing problems in the Node.js project.

7. The Node.js project must have representation on the Foundation board.

8. I believe the proposed merger should proceed on the proposed timeline.

9. The proposed merger will be good for Node.js Foundation gold and silver member companies.

10. The proposed merger will make it easier for the Foundation to provide resources to the Node.js project.

11. I don't have an opinion about the proposed merger.

12. Concerns about the proposed merger have been adequately discussed and addressed.

**Comment by MylesBorins** [comment]
Would this be easier to administer via google forms? we could allow for anonymous reports while enforcing only one response per email address. We could then easily visualize the responses.

Happy to help administer. That being said it would be interesting to hear how this data is planning to be used, why it is being limited to TLC rather than all members and the JSF.

**Comment by MylesBorins** [comment]
Also, would it make sense to move this over to nodejs/bootstrap?

**Comment by jasnell** [comment]
It's a simple poll. Administering it won't be difficult. The purpose is to take the temperature of the room on things as we proceed, specifically within Node.js top level committees. The discussion in the bootstrap repo is focused on answering a different set of questions.

**Comment by ChALkeR** [comment]
Perhaps it would be easier to collect the data using google forms than email replies?

**Comment by jasnell** [comment]
Email replies are just as easy for me really.

**Comment by MylesBorins** [comment]
@jasnell I don't find email replies to be particularly productive for sharing the results

**Comment by jasnell** [comment]
I've added a google form for those who wish to respond that way: https://goo.gl/forms/UmUVLvQS6zWbJ6Bq1

Email responses are also acceptable for me (thank you to those who have already taken the time to respond, I've recorded your answers)

**Comment by mhdawson** [comment]
Can we get the data?  I saw some of it being used in one of the discussions but I think the full data should be available at least to those who participated.

**Comment by jasnell** [comment]
@nodejs/tsc @nodejs/community-committee ... there are a couple of TSC members and a handful of community-committee members who have not yet weighed in (we have 24 out of 34 responses). I'm going to keep the poll open through the rest of today then post the full results to the bootstrap repository in a separate issue tomorrow.

**Comment by Trott** [comment]
Given the merger has happened, it seems like this can be closed. Obviously, re-open if I'm wrong.
