### ISSUE TITLE
request to move the refack/GYP repo to the org

### ISSUE THREAD

**Issue by refack** [nodejs/admin#247]
It seems the remaining support Google was providing for GYP has ended (CI doesn't work anymore, and the last contributor is not responding), so I request to move a forked repo to the org.
This will facilitate current efforts to make GYP python3 compatible (https://github.com/nodejs/node-gyp/pull/1335, https://github.com/nodejs/node-gyp/pull/1150, https://github.com/nodejs/node/pull/23669, [gyp-developer/ivg8pfDSrr0](https://groups.google.com/forum/#!topic/gyp-developer/ivg8pfDSrr0)), as well as bug fixes and adaptation to new toolchain versions. Most importantly I want to revive GYP's CI test suite so we could have decent coverage of our current and future floating patches.

My assumption is that first and foremost this will help alleviate `node-gyp` pain points. Following that I have several ideas for improvements:
1. automating GYP-GN cross-compatibility
2. static analysis and debugging tools to `.gyp` files (make it easier to maintain)
3. build time optimizations (such as whole library caching, since only tools at this level have knowledge of all the inputs and variables used when building a library as a whole)
4. adapting to new features in existing toolchains.

IMHO coordinating such efforts requires the umbrella of an organization such ours, since bootstrapping a personal fork (especially one that is diverging from Google, and not explicitly affiliated with Node.js) is very challenging.

/CC @nodejs/gyp @node-gyp @nodejs/build @nodejs/build-files @nodejs/python

**Comment by joaocgreis** [comment]
Link: https://github.com/refack/GYP

This sounds good to me. Ideally, I'd like to see node-gyp move to gyp.js, thus not requiring Python at all. I realize that this will require some more work, so for now being able to easily fix issues in gyp would be great.

**Comment by joyeecheung** [comment]
SGTM. Until we make a decision on the build system we want to switch to (or even if we want to switch to a new one), the current status is that we will have to maintain a fork of GYP anyways.

Also, thanks for all the work you put into maintaining the GYP stuff!

**Comment by jasnell** [comment]
Sgtm

**Comment by mcollina** [comment]
sgtm

Il giorno ven 19 ott 2018 alle ore 15:00 James M Snell <
notifications@github.com> ha scritto:

**Comment by targos** [comment]
Sgtm

**Comment by mhdawson** [comment]
Sgtm

**Comment by richardlau** [comment]
This can go ahead. as per https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories

> * Transferring a repository into or out of the organization
>
> Provided there are no objections from any TSC or CommComm members raised in the issue, such requests are approved automatically after 72 hours.

**Comment by refack** [comment]
Thanks, I'm setting things up, and will try to follow up in the next few days.

**Comment by Croydon** [comment]
What happened to this? 🤔

**Comment by 391861737** [comment]
What happened? +1
