### ISSUE TITLE
Requesting calendar admin privleges

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#252]
Oh Hey,

I seem to be updating the calendar a bunch and it would likely be a good idea for me to not have to ask people to do it all the time. Can someone add me as an admin to it?

**Comment by williamkapke** [comment]
Please see: https://github.com/nodejs/admin#nodejs-foundation-calendar

**Comment by mhdawson** [comment]
+1, PR yourself into the page @williamkapke mentioned above, once landed I can add you.

**Comment by bnb** [comment]
+1
