### ISSUE TITLE
use GitHub's Organisation description field to mention governance

### ISSUE THREAD

**Issue by refack** [nodejs/admin#257]
In GitHub's Organization Settings page there's a description field:
![image](https://user-images.githubusercontent.com/96947/47798988-bd917d80-dcff-11e8-9b8f-30c108914cbb.png)
As far as I can tell, at the moment it is empty:
![image](https://user-images.githubusercontent.com/96947/47799213-31cc2100-dd00-11e8-93b6-48ee3ff8ebec.png)

We could use it to add a few words about the org’s CoC and governance model. IMHO this will help reduce uncertainty WRT to repos that don’t have those explicitly mentioned.

**Comment by keywordnew** [comment]
Thread ping, for comments.

**Comment by ljharb** [comment]
Now that the code of conduct file can be in an org-wide repo and apply to all repos, perhaps using that would be more effective?

**Comment by mhdawson** [comment]
@ljharb if you mean adding a link to the org-wide CoC file -> https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md as part of the description that makes sense to me.

**Comment by ljharb** [comment]
@mhdawson i meant that since that file exists, the OP's concern about reducing uncertainty no longer applies, since all new repos have the CoC by default.
