### ISSUE TITLE
Joint TSC + CommComm meetings

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#26]
Hey All,

it seems like there are likely agenda items that involve discussion and sign off from both groups. Would it make sense for us to create a monthly joint meeting of the two committees?

**Comment by mhdawson** [comment]
I'm generally in favor or in person meetings, but I'm not sure what we'd have on the agenda so far.  Do you have some example of where the meeting would have accelerated closing where sign off was required ?

I'm only hesitating as some people really want to avoid additional meetings.

**Comment by bnb** [comment]
Additional meetings are okay with me, but I know I'm able to generally be more flexible than most people 😬

cc @nodejs/community-committee

**Comment by jasnell** [comment]
If there are enough *current* agenda items to warrant *a single* joint meeting now, then that is fine. I would hold off on setting up a recurring meeting schedule until after we see if enough joint concern issues come up over time to justify it.

**Comment by rachelnicole** [comment]
Maybe bi-monthly?

**Comment by bnb** [comment]
@MylesBorins is this something we're still interested in?

**Comment by MylesBorins** [comment]
@bnb I am interested in this. I think it might be in line with Todd Moore's proposal, so I want to see how that pans out

**Comment by jasnell** [comment]
Is there a next step here?

**Comment by Trott** [comment]
Closing for now. Feel free to re-open if this should still be an active conversation.
