### ISSUE TITLE
Transferring ownership of node-vscode-config

### ISSUE THREAD

**Issue by trivikr** [nodejs/admin#260]
Hi,

Earlier discussions in https://github.com/orgs/nodejs/teams/collaborators/discussions/58

The repo is already moved to nodejs as I followed the steps in [documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/), and wasn't blocked. I wasn't aware of the [policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories) which @Trott shared and following it now.

**History:**
* I've been contributing to Node.js core for more than a year now, and have been using VSCode editor.
* I'd created a [node-vscode-config](https://github.com/trivikr/node-vscode-config) repo with VSCode launch config 7 months ago, and shared it with contributors in mini Code+Learn events. The devs whom I'd interacted with found it useful.

**Proposal:**
* I would like to share this config with all the collaborators by moving it under nodejs organization.
* Since Node.js core doesn't allow editor specific configs, the repo will continue to exist independently and we'll link it from Node core documentation. Collaborators can add VSCode specific configs later, or create other editor specific repos or rename this repo to include configs of other editors.

Regards,
Trivikram

**Comment by trivikr** [comment]
The repo is already moved under nodejs org, and I don't see an option to transfer it back to myself.
If you're an owner and would want the ownership to lie with me till the decision is taken on this issue, then please follow the [documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-organization/#transferring-to-your-personal-user-account) to initiate the transfer of [node-vscode-config](https://github.com/nodejs/node-vscode-config) back to me.

**Comment by devsnek** [comment]
can multiple editor configs be held in one repo? a repo just for vscode seems a bit extreme.

**Comment by Trott** [comment]
The repo needs a LICENSE file and a Code of Conduct.

**Comment by trivikr** [comment]
@devsnek Yeah, we can rename the repo (to **node-editor-config** for example) and create a folder for each editor where configs can be stored?

**Comment by Trott** [comment]
@trivikr Looks like the PR with that information has not yet landed. However, maybe https://github.com/nodejs/admin/pull/68/files will be helpful? It doesn't say what LICENSE is acceptable, but the main repo uses MIT license, so I imagine that would be an easy 👍.

**Comment by trivikr** [comment]
Added MIT License in https://github.com/nodejs/node-vscode-config/pull/3

**Comment by refack** [comment]
A tad bit of name bikeshedding: I suggest `node-code-ide-configs` just to have it clear about its intended purpose.

**Comment by Trott** [comment]
It seems like perhaps this should be closed. Feel free to re-open (or leave a comment requesting that it be re-opened) if you disagree. I'm just tidying up and not acting on a super-strong opinion or anything like that.

**Comment by trivikr** [comment]
The repo was renamed to `node-code-ide-configs` and now lies in nodejs org at https://github.com/nodejs/node-code-ide-configs
