### ISSUE TITLE
Deselect "Allow members to create repositories for this organization"?

### ISSUE THREAD

**Issue by trivikr** [nodejs/admin#261]
Hi,

**Issue:**
* I'd created a discussion at https://github.com/orgs/nodejs/teams/collaborators/discussions/58 about transferring the ownership of node-vscode-config and wasn't aware of the [policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories)
* I initiated the transfer of [node-vscode-config](https://github.com/trivikr/node-vscode-config) by following [github documentation](https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/) and it was successful.
* When the policy was shared with me, I created issue #260

**Suggestion:**
Deselect "Allow members to create repositories for this organization" so that this doesn't happen again ([documentation](https://help.github.com/articles/repository-permission-levels-for-an-organization/#creating-repositories))?

Regards,
Trivikram

**Comment by Trott** [comment]
I agree that it should be de-selected. This was discussed at some point in the past and we decided to be permissive/empowering about stuff, but I don't think this was the right move for this particular privilege.

**Comment by joyeecheung** [comment]
We can try deselecting first and see how it works out, but since we already have a process of proposing to create/transfer repos, it probably doesn't really matter who gets to push the button - in any case pinging the TSC or say something on the IRC would should that done fairly quickly.

**Comment by joyeecheung** [comment]
> since we already have a process of proposing to create/transfer repos

uh, OK, probably not entirely accurate until https://github.com/nodejs/admin/pull/68 is merged (my bad :( whoever wants to pick that up feel free to push there or start a new PR)

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee Any objections to making this change? I'm +1-ish on it. Sounds like @joyeecheung is too.

**Comment by MylesBorins** [comment]
I don't think we need this. It has not generally been a problem and the few times someone has slipped up it has been quickly rectified

**Comment by Trott** [comment]
OK, if there's not consensus, I'm not going to push for it, as I don't feel strongly. Closing. Feel free to re-open if I'm acting too hastily.
