### ISSUE TITLE
Data repository

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#267]
In Node.js we have a _lot_ of data spread out across various repositories. This data can be hard to consume for the average user who may not even know it exists in what is – to them – an obscure repository.

In the past few weeks I've talked with @amiller-gh about this and how we may be able to consume this data for the benefit of the website redesign... we have so much but hardly surface any of it in a way that's known or useful to those outside of the contributor base.

I've been working on some tools like [node-release-lines](https://github.com/nw/node-release-lines) and even [good-first-issue](https://github.com/bnb/good-first-issue) that consume data that's contained with the Node.js GitHub org, but it's not necessarily the easiest.

As such, I'd like to discuss the possibility of having a central `nodejs/data` repository in which data that we create from various parts of the project can be housed and consumed more reliably without putting the effort of doing so on the end-user.

Here's a quick list of data sources I'd ❤️ to see centralized:

- Changelogs: https://github.com/nodejs/node/blob/master/CHANGELOG.md
- Security Vulnerabilities: https://github.com/nodejs/security-wg
- Node.js release data: [json](https://nodejs.org/dist/index.json), [tab](https://nodejs.org/dist/index.tab)	
- Node.js download metrics: https://nodejs.org/metrics/
- Benchmarking data: https://benchmarking.nodejs.org/
- Code coverage (as JSON): https://coverage.nodejs.org/

As a note, I'm 100% sure this isn't close to all the data that we have about Node.js... and that's part of the idea here. Provide a central location for both end-users and Node.js contributors to know they can rely on for their data.

I will say: a goal of this should not be to take over the data of WGs and initiatives, or to move that data outside of their domain. If WGs or initiatives would want to only have their data in a `nodejs/data` repository, that would be totally fine. However, I know that's probably not going to happen across the board... tooling to pull together data and make it consumable would need to be within the scope of this group (I've already played with some tooling like this, it shouldn't be a barrier).

I mostly wanted to create this discussion to see if there are comments, objections, or concerns to this kind of repository before I go ahead and create it. Additionally, if people are _also_ interested in working on this it would be great to hear that support and have you join the effort if we do indeed launch it 😄

**Comment by vdeturckheim** [comment]
Side note, we are moving the data out of the Security WG repo to https://github.com/nodejs/security-advisories

**Comment by mcollina** [comment]
I'm +1 on the initiative, and -1 to have a centralized repo. It would _highly complicate_ write access.
I prefer if that repo uses a set of scripts to update the data on a regularly basis.

**Comment by fhemberger** [comment]
Also:

Release schedule: [json](https://github.com/nodejs/Release/blob/master/schedule.json), [png](https://github.com/nodejs/Release/blob/master/schedule.png)

Website publication webhook: https://nodejs.org/github-webhook.log

**Comment by bnb** [comment]
@mcollina I'm not opposed to that. The only concern I do have is the shape of data breaking based on WG decisions without giving feedback to the data repository/team and extra work being triggered because of that.

Is this a valid concern? 🤔

**Comment by mcollina** [comment]
@bnb it is valid. However I tend to think that the WGs could change format as they see fit, as they are responsible of the data. This will create more work, but I would prefer to not add any burden to WGs.

**Comment by bnb** [comment]
I'm going to close this for now since there's been no forward movement in over a year. While I think it would still be a nice thing to have, I don't think other folks are as on-board with it as I am. More than happy to be wrong - please feel free to re-open if I am 👍
