### ISSUE TITLE
transfer https://github.com/watilde/remark-preset-lint-node/ into nodejs org

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#273]
Would seem to make sense to transfer https://github.com/watilde/remark-preset-lint-node/ into the nodejs org. (It was @watilde's idea: https://twitter.com/watilde/status/1062189105679716352. Good idea.)

Before it is transferred, it needs a code of conduct and a CONTRIBUTING.md file. Other than that, I think it's ready to go.

This is the remark-lint plugin with all of our settings for markdown linting.

@nodejs/tsc @nodejs/community-committee

**Comment by richardlau** [comment]
Relevant Node.js GitHub Organization Management Policy: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories

Code of conduct and CONTRIBUTING.md file would be good, but it's not currently called out as a requirement. https://github.com/nodejs/admin/pull/68 (which has not yet landed) includes them in a list of files that the repository should "ideally" contain, but again not a requirement.

**Comment by Trott** [comment]
@watilde Whenever you like, you can initiate the transfer under Settings in the repo. (See https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/.)

**Comment by watilde** [comment]
@Trott Sure! We also want to make sure about team access to transfer. Is that ok to make a team who manages release process?

**Comment by watilde** [comment]
No team + Add bots would also work fine probably!
https://github.com/nodejs/admin/blob/7f8317babb35cfd507ae895b119dc039b714a3f7/enable-travis-under-nodejs.md#step-2-add-the-bot-to-your-team

**Comment by Trott** [comment]
The team that owns `core-validate-commit` repo is the `@nodejs/automation`.

We could add you to the `linting` team and make `linting` the owner of the repo.

Or we can create a new team as you suggest.

Or we can add you and me and whoever else as individual owners.

(All that with or without bots is fine by me too.)

I'm technically not on TSC at the moment, so if someone else on @nodejs/tsc could handle setting up all the admin elements for the repo, that would be great.

**Comment by watilde** [comment]
Done 🎉
+ https://github.com/nodejs/remark-preset-lint-node

We can close this issue as resolved, thank you all :)

Following up:
+ I assigned @nodejs/linting as committer. Could I join the team?
+ I'm working on meta info update.

**Comment by Trott** [comment]
> I assigned @nodejs/linting as committer. Could I join the team?

@nodejs/tsc Can someone please add @watilde to `@nodejs/linting`?

**Comment by Trott** [comment]
I think this can be closed now, but if I'm wrong, re-open.

**Comment by watilde** [comment]
@apapirovski Could you make me Maintainer? I need to add `@nodejs/bots` to the repo and enable CI after that.
