### ISSUE TITLE
A few ToDo to finish transfer of remark-preset-lint-node

### ISSUE THREAD

**Issue by watilde** [nodejs/admin#279]
ToDo:
- [ ] I added `@nodejs-foundation` as maintainers on [npm](https://www.npmjs.com/package/remark-preset-lint-node). To finish this transfer, it needs to get approve.
- [ ] I need to add `@nodejs/bots` to the [repo](https://github.com/nodejs/remark-preset-lint-node) and enable CI. Could someone make me Maintainer for `@nodejs/linting` or do that?

Refs:
+ Original issue: [nodejs/admin#273
](https://github.com/nodejs/admin/issues/273)
+ Tracker: https://github.com/nodejs/remark-preset-lint-node/issues/10
+ Guide: [nodejs/admin#68](https://github.com/nodejs/admin/pull/68)

🐈

**Comment by watilde** [comment]
Could someone from @nodejs/tsc who may have a permission help me to finish the tasks?

**Comment by targos** [comment]
@watilde I cannot help on the first point as I don't have access to the `@nodejs-foundation` account.
Why do you need to add `@nodejs/bots`? What kind of CI should be enabled? I don't see any particular CI configuration such as a `.travis.yml` in the repo.

**Comment by watilde** [comment]
@targos Once `@nodejs/bots` is ready, I was planning to run `npm test` on CI every time PR is created and master is updated.

Do you know any idea around a is managing `@nodejs-foundation` account? Then I'll add about it to the WIP guide.

**Comment by targos** [comment]
> Once @nodejs/bots is ready, I was planning to run npm test on CI every time PR is created and master is updated.

Sounds like something that can be done in Travis CI? It would be easier to setup and maintain than a new Jenkins job.

**Comment by richardlau** [comment]
> Do you know any idea around a is managing `@nodejs-foundation` account? Then I'll add about it to the WIP guide.

[`nodejs-foundation`](https://www.npmjs.com/~nodejs-foundation) is owned by the Build WG: https://github.com/nodejs/build/blob/master/doc/access.md#npm-management

**Comment by Trott** [comment]
The repo was transferred so I think this can be closed.
