### ISSUE TITLE
Node.js core values initiative

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/admin#28]
> At it’s core, Node.js is a collection of people working towards a shared goal. Improving people’s lives. This can be done through making software faster, it can be done by making empathetic APIs. This can be done by making a reliable platform, it can be done by being kind to each other. We work to improve the lives of the many individuals on this planet who rely on Node.js. We work to improve the lives of the many individuals on this planet who help make Node.js possible. — Myles Borins, TSC Director

We've kicked off the Core Values Initiative via the October 2017 Collaborators' summit. You can read my wrap-up and instructions for running a session [here](https://medium.com/@hackygolucky/node-js-core-values-ab5387c4fd49).

Q: Would it be appropriate to track the raw data from each event as a file in this repo or in CommComm? I'm happy to upload that so we have a folder of them as we get more turned in from future sessions. I'm sure someone could have fun with that data. 

**For this initiative, we want as many perspectives from a representative group of the Node.js global community as we can muster.** At Collaborators’ Summit October 2017, most of the participants were existing collaborators, Board Directors, project leadership, and excited-to-contribute community members. 

If you have a large meetup or are helping at a Node.js event internationally, please use the slides and the practice guide to perform the value exercise. Share it with the Community Committee by [filing an issue](https://github.com/nodejs/community-committee/issues) with your report, so we can build our core values and create a plan for progress that is truly representative of the global Node.js community.

We'll be project tracking this initiative over the next six months [here](https://trello.com/b/fVAT5Zun/nodejs-core-values-initiative).

**Comment by mhdawson** [comment]
I'd be happy to have this tracked in the Community committee repo since I think that team will be leading the effort.

**Comment by joyeecheung** [comment]
Just curious: why do we track this with trello instead of a Github project? I think we only need columns and cars?

**Comment by joyeecheung** [comment]
Also: there will be a D2 conference (D2=Design&Dev) hosted in Hangzhou, China in December, if our team attend as usual I can plan to do an session there. Would be interesting to see how Chinese devs (mostly frontend/fullstack devs) think about the core values of Node.js. It's organized by Alibaba so I can try to find to seek help from the organizers.

**Comment by jasnell** [comment]
@dshaw ... can you update on where things are at with this initiative?

**Comment by Trott** [comment]
Dormant for over a year. I'm going to close this, but if that's not the right thing to do, by all means, use that "re-open" button!
