### ISSUE TITLE
Move llhttp and llparse to Foundation

### ISSUE THREAD

**Issue by indutny** [nodejs/admin#280]
See: https://github.com/nodejs/node/issues/24730 and others.

Does @nodejs/tsc think that [llhttp](https://github.com/indutny/llhttp) and [llparse](https://github.com/indutny/llparse) repos should be moved to Node.js foundation?

**Comment by mcollina** [comment]
Big +1 from me.

**Comment by danbev** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by jasnell** [comment]
Sgtm

**Comment by indutny** [comment]
_Unrelated pros of having them in NF: two more repos starting with `ll` :wink:_

**Comment by cjihrig** [comment]
+1

**Comment by indutny** [comment]
I just realized that `llparse-test-fixture` has to be moved here too.

**Comment by indutny** [comment]
Moving now.

**Comment by indutny** [comment]
https://github.com/nodejs/llhttp
https://github.com/nodejs/llparse
https://github.com/nodejs/llparse-test-fixture

Voila!

Thank you everyone.
