### ISSUE TITLE
Require travel fund recipients to submit travel reports after the events

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#281]
To better manage the travel fund I propose we require every recipient of the funding to submit a travel report after the trip. The content may include:

1. What their goals are for this travel
2. Sessions/talks they attended/gave, and a brief summary of takeaways
3. Conversations e.g. hallway tracks, that they think are appropriate to document in a public space
4. What they have achieved in the events (e.g. if they have done work in the events, like actually writing code)
5. What they will bring back for future work: actionable items, etc.

For posterity the documents may be stored in this repo and submitted via PRs.

The purpose of this proposal is to give the administrators more confidence when they approve a travel fund request from an individual who may not be very active in the organization and whose work they might not be familiar with.

**Comment by joyeecheung** [comment]
cc @nodejs/community-committee @nodejs/tsc

**Comment by mcollina** [comment]
Definitely +1.

**Comment by thefourtheye** [comment]
A template would be nice to have when we file reports.

**Comment by WaleedAshraf** [comment]
+1

**Comment by antsmartian** [comment]
Definitely +1. It would definitely help in the process.

**Comment by Trott** [comment]
Travel fund is now a CPC thing, so I think this can be closed here?
