### ISSUE TITLE
Node + JS Interactive 2019 - Please comment before 1/15

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#286]
Hey team,

The LF events staff are evaluating options for the 2019 Node + JS Interactive conference and wanted to see if you had a strong preference for any of the below options. 

Bear in mind that these are subject to change (some may be cost prohibitive, not have quite the amount of space we need, or become unavailable, etc) - but your input is valued!

*  Denver, CO - November 5-8
* Montreal - December 10-13
* New Orleans, LA - December 10-13
* Vancouver - September 8-11
* Seattle, WA - September 10-13 or December 10-13
* Toronto - December 10-13

They are also interested in making sure we don't schedule this over other big events/conferences, so if you're aware of any major conflicts with the dates above let me know. They want to whittle this list down to a couple of preferred options, get a better understanding of the financial implications, and then take it to the board(s) for a final decision.

Please provide input in the next 72 hours as we need to have the dates ready for the board meeting where this will be discussed further.

Tracy

**Comment by jasnell** [comment]
Location wise, none of the options are great given the dates. The only ones that definitely will not work for me is Vancouver, September 8-11 and Seattle September 10-13 as those overlap and conflict with NearForm's company retreat. Given these choices, New Orleans is likely best but having the conference within the US is currently not an ideal choice in my opinion.

**Comment by mhdawson** [comment]
I don't have strong feelings from a personal standpoint, but I think that for people in Europe one of the locations in the East versus West would be good for a change.

**Comment by cjihrig** [comment]
+1 to New Orleans if we settle on a December date (nicer weather than Canada that time of year).

**Comment by MylesBorins** [comment]
I have a slight bias for Toronto, my hometown. I know there is a strong local community we can build on top as well (they have a number of local meet ups and I’ve attended node events there before). I’m unsure if New Orleans has the local community we can build on top of

**Comment by apapirovski** [comment]
I don’t have a personal preference but from a visa perspective, I would strongly recommend choosing Canada over the US. Neither is necessarily easy but Canada is definitely easier given enough time and the right paperwork. (Speaking from past experience.)

—Anatoli

**Comment by Qard** [comment]
Definite preference to Canada from me, though I may be biased. ;)

Also, agreed on comments about east coast being easier for people in Europe. Personally though, I wouldn't want to be in Eastern Canada in winter. 😅

**Comment by chowdhurian** [comment]
The demographics for last year's conf was 45% US, 45% Canada, 10% rest of the world. We can do better. An accessible east coast city (I'd think in Canada, but I'm seeing YMMV experience earlier in this thread) could contribute towards improving the 10%.

**Comment by WaleedAshraf** [comment]
Canda because for the little edge in VISA process. But I know last time, people had problems even with Canadian VISA. So, no high expectations.
So, I'll go for Toronto or New Orleans.

**Comment by ryzokuken** [comment]
> I don’t have a personal preference but from a visa perspective, I would strongly recommend choosing Canada over the US. Neither is necessarily easy but Canada is definitely easier given enough time and the right paperwork. (Speaking from past experience.)

As a person who got rejected a Canadian visa, please this. Shifting it to the US will make it substantially worse for everyone to get visas IMO.

**Comment by apapirovski** [comment]
The timing is certainly less than ideal. On the flipside September and early October are the perfect time to visit Toronto and Montreal. But I assume there is no venue available at the appropriate price to make that happen.

**Comment by Fishrock123** [comment]
Exactly what @apapirovski said. I would guess a good few of us would feel more secure about it being in a Canadian city. Politics in the US seems pretty unstable and it's hard to know how things might look visa / foreigner wise by next fall.

**Comment by ljharb** [comment]
There are issues with entry to Canada as well that the US does not have.

**Comment by codeekage** [comment]
Everywhere now it’s difficult to secure a visa from Nigeria. Europe comes easy but US and Canada. Phew... last year was extremely difficult. However, US will be preferable if someone is ready to be a guarantor for folks coming from Africa or other part of the world. An invitation will not get it done 100%. Going through travel agency usually attract more cost. 

2019 will be a great year to see things change.

**Comment by jphblais** [comment]
I'm from Montreal and I don't recommend it in December, but in September would be nice.  If I can help to find a place to do the event LMK.  Any other place where the weather is warm I will be in!

**Comment by ryzokuken** [comment]
> There are issues with entry to Canada as well that the US does not have.

I agree. I've been reading up on Canadian Immigration Laws a lot lately and to say that they're kinda weird would be an understatement.

> TPAC 2019 will be 16-20 September 2019 in Fukuoka, Japan.

Could the foundation explore the possibilities of this one? It should be a fun change as compared to the usual, and Japan has a more laid back immigration policy than either the US or Canada. Apart from that, EU always has it easier for people than NA.

**Comment by richardlau** [comment]
Given the deadline for comments has long passed, should this be closed?

**Comment by martindsouza** [comment]
Vancouver.

**Comment by Trott** [comment]
> Given the deadline for comments has long passed, should this be closed?

I think so. Obviously, re-open if I'm wrong about that.

**Comment by DarylThayil** [comment]
Did a decision get reached?

**Comment by lmshaffe** [comment]
Looks like Montreal, Dec. 10-12 according to the site: https://events.linuxfoundation.org/events/nodejs-interactive-2019/

**Comment by DarylThayil** [comment]
Thanks!

**Comment by DennisRichi** [comment]
[DoxyPEP](https://ikwilvanmijnsoaaf.nl/products/behandeling-doxypep) should only be used according to advice from a qualified healthcare professional. The right timing and dose can depend on a person's health, medications, and STI risk. Using antibiotics incorrectly can cause side effects and may contribute to antibiotic resistance, so people should not start DoxyPEP without medical guidance.
