### ISSUE TITLE
Creating a nodejs/quic repository

### ISSUE THREAD

**Issue by jasnell** [nodejs/admin#287]
I am beginning work on a QUIC implementation for Node.js core. The work would proceed within a separate fork of nodejs/node master, just like we did with http/2. The intent would be to add QUIC directly to core and not as a separate native addon.

If there are no objections to creating the nodejs/quic repository, I will do so by the end of this week.

**Comment by benjamingr** [comment]
Hey @KromDaniel has expressed interest in helping out with this. I told him to ping you on IRC - I hope that's ok 😄

**Comment by jasnell** [comment]
Repository created! https://github.com/nodejs/quic/issues/1

**Comment by jasnell** [comment]
@nodejs/quic team created!

**Comment by KromDaniel** [comment]
Thanks you for the introduction Benji :)

**Comment by Trott** [comment]
With the repo and team created, seems like this can be closed. Obviously, re-open if I'm wrong.
