### ISSUE TITLE
Adding cc-review labels to Node.js org repos

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#29]
As a part of helping include and onboard CommComm members, the CommComm has created the "observer" group. 

As per the normal workflow of GitHub, the @nodejs/community-committee group has been mentioned when opinions and review from members of the CommComm are needed. Something I've been frustrated about is how this reduces visibility for CommComm observers, effectively only enabling them to have eyes on things that happen in the CommComm repo and those that it oversees.

I recently brought up the idea of creating a broader team (ref: https://github.com/nodejs/community-committee/issues/166), but there are a few issues with this. The way the CommComm membership flow is set up, it would effectively give Org membership (regardless of to anyone who came into the CommComm repo and requested to be an observer. This would also effectively provide a way to get around paying for Individual Membership with no contribution to the project - not that there's a _reason_ people would want to at this point, but it does provide such a loophole.

We discussed this in yesterday's CommComm meeting, and the option we landed on was creating a way for such discussions to be monitored by observers. I know the TSC repo has the [cc-review label](https://github.com/nodejs/TSC/labels/cc-review), so it was suggested that we use that as a method for CommComm Observers to be able to have a bit more insight into the work we're doing in repos that aren't necessarily obvious.

I believe the only places that it would currently need to be added is nodejs/admin, nodejs/node, nodejs/code-and-learn (maybe?), nodejs/summit, and nodejs/nodejs.org. I can add it to nodejs/admin and nodejs/nodejs.org, but I also wanted to be sure we created this issue to get feedback and get approval if necessary 👍

**Comment by mhdawson** [comment]
Makes sense to me.

**Comment by jasnell** [comment]
Is there a next step here? Has this been done?

**Comment by bnb** [comment]
It hasn't been entirely completed, but can be addressed on an as-needed basis since @rachelnicole and I (and any future CommComm Chairpeople) are org owners. 👍
