### ISSUE TITLE
Google Summer of Code 2019

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#291]
Deadline to apply is Feb 6th

--> https://opensource.googleblog.com/2019/01/seeking-projects-for-gsoc-2019.html

Would we like to do this? One of my first internships in technology was through this program, would be interested in giving back as a mentor.

**Comment by mcollina** [comment]
I mentored before in GSoC, and it has had a very positive impact on my student career.

  +1.

**Comment by gabrielschulhof** [comment]
I've also been a mentor before. +1.

**Comment by mbj36** [comment]
I have been a student twice and mentored once both in my past and i can definitely say GSoC has huge impact in my career.

**Comment by mhdawson** [comment]
@MylesBorins sounds like you are volunteering to be the mentor and in that case sounds good to me:)

**Comment by ryzokuken** [comment]
I've been both a student and mentor, +1.

**Comment by codeekage** [comment]
@MylesBorins is there any progress on this?

**Comment by MylesBorins** [comment]
Hey All,

Sorry to be the bearer of bad news but I didn't get all the things together in time for the application this round. My sincerest apologies. Perhaps we should kick off a thread (maybe in mentorship?) about potential projects so we are ready to go when the next round starts.
