### ISSUE TITLE
2018 travel funds page has formatting issues

### ISSUE THREAD

**Issue by yoshuawuyts** [nodejs/admin#292]
![2019-01-16-134937_3840x2160](https://user-images.githubusercontent.com/2467194/51250049-8e50eb00-1995-11e9-9aef-564d091dba39.png)

- https://github.com/nodejs/admin/blob/master/TravelFunds/2018.md

**Comment by SofiEstevez** [comment]
Hi @yoshuawuyts ! I was editing things and I think I copy-pasted something by mistake. Just opened a PR to correct this before seeing you opened this, sorry :)

**Comment by yoshuawuyts** [comment]
@SofiEstevez All good; thanks for the swift handling!

**Comment by codeekage** [comment]
Closing this since it’s been fixed.
