### ISSUE TITLE
A Who's Who of nodejs/collaboration

### ISSUE THREAD

**Issue by snostorm** [nodejs/admin#3]
Hi everyone! I thought it might be nice to know who's joined and find out what Groups and regions are represented. Here's a list I'll keep evolving until it is worth making in to markdown. Please feel free to edit directly (or comment in a reply any corrections.)

Want to join the efforts? Just [request membership](https://github.com/orgs/nodejs/teams/collaboration) and then say hello in the comments below. Try to include what you've seen listed for other members.

@jasnell, James M Snell (IBM), USA - TSC, Collaborators, Internationalization, Convergence, LTS
@snostorm, Sean Ouimet, Canada/France - Website, French i18n, Documentation
@srl295, Steven R. Loomis (IBM), USA - TSC, LTS, Internationalization
@thefourtheye, _anonymous?_, India - Collaborators, Smoke Test

_The best structure and possible team/repo cross-linking of this list is TBD. Alphabetical list by GitHub handle._

**Comment by srl295** [comment]
@snostorm count me in!
