### ISSUE TITLE
Ask the Foundation to buy & send a yubikey to any collaborator that wants one

### ISSUE THREAD

**Issue by rvagg** [nodejs/admin#30]
"collaborator" in the sense of anyone with org access. We're trying to lock down 2fa for the org but have some troubles with people in countries where that's difficult for whatever reason. This could also be a nice bonus for folks becoming active contributors. 

I don't know how this would work exactly or who would administer it so that would need to be sorted out before we could go ahead with this.

**Comment by gibfahn** [comment]
>We're trying to lock down 2fa for the org but have some troubles with people in countries where that's difficult for whatever reason. This could also be a nice bonus for folks becoming active contributors.

+1 on this in general, but what issues with standard 2FA are we having? Seems like it'd be useful to try to deal with them as well.

**Comment by joyeecheung** [comment]
I am living in "countries where that's difficult for whatever reason", but I think there are already enough mobile apps for enabling 2fa? I use Google Authenticator and have heard that Authy is pretty nice as well, and they are both free. There are also many local/international apps that supports TOTP.

Also...I think people living in countries having difficulties getting SMS messages from Github might also have difficulties receiving yubikey shipments?

**Comment by mhdawson** [comment]
@Trott could you reply to the initial email about not being able to use SMS messages to ask why one of the phone based apps is not an option ?

**Comment by Trott** [comment]
@mhdawson Sure, will do.

**Comment by Trott** [comment]
@mhdawson Got a positive reaction about using something like Google Authenticator.

**Comment by mhdawson** [comment]
@Trott sounds good.

**Comment by jasnell** [comment]
Is there a next step here? I assume this needs to go to the board?

/cc @MylesBorins @williamkapke

**Comment by Trott** [comment]
I *think* this can be closed. We've enabled 2FA for the org and there wasn't much fallout.
