### ISSUE TITLE
Archive/delete enterprise-advisory-group repo

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#302]
We should archive and/or delete this repo.  See

https://github.com/nodejs/user-feedback/issues/129

for more details.  Current activity is being handled under the user-feedback repo.

**Comment by Trott** [comment]
SGTM

**Comment by ChALkeR** [comment]
+1 to what @Trott said: archiving seems good to me.

**Comment by mhdawson** [comment]
Repo archived.
