### ISSUE TITLE
Travel Fund for Collab Summit JSConfEU Travel

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#304]
Hey all! We were chatting in CommComm the other day about this.

Collab Summit JSConfEU is coming up. Last year in October, I worked closely with @joyeecheung @JemBijoux and others on getting an "average" of # of people who would be going and cost.

Do we need to do this for the next Collab Summit, or only when we feel like we are running out of $ (for October's next, for example).

Let us know how to proceed. // @bnb @thekaeway @jorydotcom @keywordnew

**Comment by mcollina** [comment]
For october, we issued a statement that we needed to have all travel approved by September 1st, if I recall correctly.

**Comment by keywordnew** [comment]
Totally! Airfare fluctuates more closer to the travel date so an early deadline means less revised travel PRs (and more accurate cost projections) from people finding that their ticket has jumped in price.

**Comment by joyeecheung** [comment]
Note that the travel is tied to visa applications, is it possible for us to provide visa letters this time if we are renting a venue? For attendees who need a visa there is a chance that they may not be able to travel in the end if they don’t have their visa approved (that has happened several times before), but the airfare is usually not refundable.

**Comment by jorydotcom** [comment]
@joyeecheung I've written several visa letters before, I would be happy to assist with this assuming Node + JSF are ok with it (I would need to use official letterhead)

**Comment by MylesBorins** [comment]
Fwiw the board had approved a travel fund of the same amount as last year. I've talked to Brian and we will get a recommendation of how to approach spending for may and eligibility with regards to merge

**Comment by ladyleet** [comment]
Thanks @MylesBorins!

In terms of visa letters I'm pretty sure we cannot write them because this is not a Foundation hosted event, but will double check 100% again. // @jorydotcom

**Comment by MylesBorins** [comment]
@ladyleet re: visa letters... this was the number one reason for sponsoring the event ourselves. I've followed up with @brianwarner to look into how we can get foundation support for this

**Comment by brianwarner** [comment]
I'm on it!

**Comment by ladyleet** [comment]
@MylesBorins oh good! :) that bit of critical info was totes not in my brain - working with @brianwarner as well as we message in all these things. so glad that we can solve this issue! 🎉

**Comment by ladyleet** [comment]
@MylesBorins - @brianwarner and I talked yesterday and he's going to personally do the visa invitations for this event 🎉 .

That being said, it's not going to follow the traditional process of how we typically do invitation letters. Give us a week or two to get things set up.

This is probably a separate issue, however, than this specific thread on whether we should do anything about getting a rough idea of how much will be requested this time around for the summit.

If all think this is a none issue so early in the year, I'll close this issue!

**Comment by WaleedAshraf** [comment]
We can get a rough estimate from the last year? @ladyleet

**Comment by ahmadawais** [comment]
@ladyleet this is awesome news. Excited about this event. My wife @maedahbatool and I are planning to apply for JSConf EU and Collab Summit travel scholarship. This would be a first-time attendance so I was just looking into how to get around getting a VISA invitation. Subscribed to this issue for updates. Let me know if I need to look/apply somewhere else.

Peace! ✌️

**Comment by ladyleet** [comment]
@WaleedAshraf we used about half the travel fund at the last JSConfEU. :)

**Comment by ladyleet** [comment]
@ahmadawais make sure to apply soon! :) in terms of the visa invitation, if you have yet to do so, email visainfo@nodejs.org
