### ISSUE TITLE
Charging for Collab Summit at JSConfEU?

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#305]
Hi all! At the last CommComm we talked about way to get a better headcount of the Collab Summit since we are paying for each head with food, etc.

One way would be to charge $5pp and use this $ to buy swag and/or feed it back into the travel fund budget for the next Collab Summit just so we decrease the # of people who RSVP who are not sure.

Thoughts? 

Ccing @bnb @thekaeway @jorydotcom @keywordnew for visibility.

PLEASE ONLY COMMENT YES/NO IN RESPONSES UNLESS YOU HAVE AN ISSUE WITH THE CONCEPT

**Comment by mcollina** [comment]
I'm -1 on using $ to buy swag. I'm +1 in using 5$ for paying for food.
In other terms, I think the swag needs to come from a different pot of money.

**Comment by MylesBorins** [comment]
If we want to collect money and use it for something we should check with foundation legal to ensure that it is ok to do so, and that we won't be introducing any sort of weird tax implications or issues with of 501c6 status.

I'd personally prefer all proceeds be donated to charity if we do something like this.

Do we have numbers for past summits? What was the no show rate like?

**Comment by ladyleet** [comment]
@MylesBorins we would collect $ on behalf of the foundation and of course donate it back. I will double check about the donating back and any implications.

We are trying to avoid the 50% no show rate but maybe @mcollina can comment on this.

**Comment by mcollina** [comment]
There was never a 50% no-show at a previous collab summit. Last year we had all names of all the attendees, and they more or less showed up.

**Comment by Trott** [comment]
Is this supposed to be about Code & Learn rather than Collab Summit maybe?

**Comment by ladyleet** [comment]
i guess the main goal we are trying to get at is accomplish the % show rate and also solve the problem of people suggesting topics and not showing up to lead it @mcollina! :) 

@Trott no this is for collab summit but maybe this is where my "50%" dropoff recollection was serving me wrong. :)

**Comment by MylesBorins** [comment]
If I recall we introduced a $50 no show fee for code and learn to help with
attendance.

If what Matteo is correct and we haven't had an issue with no shoes for
collab summit would it perhaps make sense to not move forward with this
fee?

**Comment by joyeecheung** [comment]
I cannot recall there was a summit where there were a significant number of people signing up without showing up. In fact I think we usually have a good number of people showing up without signing up. And if we pick a venue with enough food options nearby, should the catering be not enough for our attendees we could just go out for lunch. I remember we did not have catering and went out for food in Berlin 2017 and it was fine.

**Comment by ladyleet** [comment]
@MylesBorins since this is not done with the LF events team and not a foundation hosted event and still a collaborator's event, we aren't using the same system and employing the same guidelines as we did for the conference. 

I'll let @keywordnew and @jorydotcom chime in as they have been in all the meetings where we discussed this! :) and this was also mainly to address @mcollina's issue with no shows.

**Comment by ladyleet** [comment]
Perhaps this is more of a question since there is a lot more $ being spent on food, etc (much like when it's done at the Node+JS Interactive conference vs other JSConfEU events where everything was sponsored prior. Now we are paying for a certain # of people (for food at the hotel venue) for people whether they show up or not based on RSVPs! :)

**Comment by jorydotcom** [comment]
Right, I was thinking that the no-show rate was much higher (for the collab summit) and that some kind of financial incentive might be used to offset that. But if the data show that isn't an issue, then perhaps we don't need it at all. 

It also might be nice to include a donation option, and let people select some amount they may be comfortable with, and donate that to Black Girls Code for example.

**Comment by ladyleet** [comment]
Okay - I like @jorydotcom's idea. If anyone sees any issue with this let me know.

**Comment by mcollina** [comment]
I'm -1 to a no-show rate as high as the one at the Collab Summit. We never had the no-show problem at the Collab Summit and I'm not understanding why we are optimizing for this.
(Code&Learn in Vancouver is a different story).

In Berlin we usually have the issue of people showing up without being registered.

I would prefer that every donation went to a Berlin-based group (or at least EU).

**Comment by joyeecheung** [comment]
I wonder if it’s necessary to provide catering for attendees though. An important part of the summit is about having informal conversations during breaks, it does not seem to matter a lot whether the conversations happen on the way out looking for food or in the hallway when people are having lunch. I am personally fine with no catering at all, some recommendations about food options near the venue would be nice though, though I certainly can’t speak for everyone.

**Comment by ladyleet** [comment]
Conclusion is that we will not be charging for Collab Summit. @joyeecheung catering is required as the venue has a food minimum we have to meet. :) So, all in all, we actually kind of get the food "for free" since it fits within our original budget for venue only no food. :)
