### ISSUE TITLE
Google Season of Docs 2019

### ISSUE THREAD

**Issue by codeekage** [nodejs/admin#310]
Hello All - 

Google launched a new programme to attract technical writers to open source projects. Season of Docs brings technical writers and open source projects together for a few months to work on open source documentation. 2019 is the first time they're running this exciting new program and would love if we could take part in the programme.

Registration opens April 2 - 24 April. : https://opensource.googleblog.com/

 cc: @nodejs/mentorship @MylesBorins

**Comment by mbj36** [comment]
It would be awesome if we participate. Open to all the help needed in this.

**Comment by Trott** [comment]
@nodejs/documentation

**Comment by Trott** [comment]
Aside from the nodejs docs, the nodejs.dev repo/site could use a lot of love/work in terms of editing and expansion.

**Comment by mhdawson** [comment]
+1 any help we can get with the docs would be great.  I'm sure we can find some good areas to focus on from those that already exist as mentioned by @Trott to some we are just trying to pull together (ex diagnostics best practices)

**Comment by codeekage** [comment]
Awesome! 

Next action item will be setting up a team and picking a date to start planning facilitation processes for the programme. Knowing the area of focus and engaging collaborators across the project that will be willing to work with technical writers for the few months. 

Interested folks should please +1 below. 🙏

**Comment by MylesBorins** [comment]
@brianwarner @mkdolan what are the next steps for us to kick this off? Can someone from the project sign us up or does that need to be handled by a foundation rep? I believe it will require "signing off" on something to register

**Comment by mkdolan** [comment]
We can't register until April 2, but we can get everything ready now. 

Looks like we need the following:

- List of project ideas for a technical writer to help on
- 2+ organization administrators (@brianwarner or I could, but it would be good to have someone directly involved from the community)
- 2+ open source mentors

**Comment by codeekage** [comment]
I’m happy to champion it. 👍🏻

**Comment by mbj36** [comment]
@codeekage I am happy to lead this.

**Comment by codeekage** [comment]
@mkdolan with about a some few days to org registration for Google Season Docs are they any action items we need to put in place before then? 

I'm available to chair meeting regardless.

**Comment by mkdolan** [comment]
I think the key thing is to collect the project ideas that a technical writer can help with. It looks like @codeekage and @mbj36 are signing up to be mentors, but they're going to want specific project proposals that they would ask someone to work on. Google provides guidance on this here:

https://developers.google.com/season-of-docs/docs/project-ideas

**Comment by codeekage** [comment]
> 2+ organization administrators (@brianwarner or I could, but it would be good to have someone directly involved from the community)

I could do this as a CommComm member if need be. I've also gone ahead to draft project-ideas that we can iterate on and develop too. 

https://docs.google.com/document/d/1KmSJLymZMoC4JcozHNkYntoD0G9fgiPHuzofMkKrzIg/edit?usp=sharing

**Comment by MylesBorins** [comment]
I'd like to volunteer to be one of the admins... as a googler I will be in a good position to help with this

**Comment by keywordnew** [comment]
@codeekage love the idea of an ongoing nodejs/content initiative

**Comment by mbj36** [comment]
Just a heads up guys - https://opensource.googleblog.com/2019/04/season-of-docs-org-apps.html

Season of Docs is now accepting applications!

**Comment by codeekage** [comment]
Cc @mkdolan and @MylesBorins.

**Comment by brianwarner** [comment]
I'm looking at the doc that @codeekage put together (thanks Agiri).  I'm happy to do the application.  Are there any other things we'd like to include in the list of project ideas?

Here's @codeekage's link again:
https://docs.google.com/document/d/1KmSJLymZMoC4JcozHNkYntoD0G9fgiPHuzofMkKrzIg/edit#heading=h.tulakvg73ths

**Comment by brianwarner** [comment]
All, with the application due tomorrow, is the content in the linked document ready to go?  If so, I'll finish the submission.

**Comment by brianwarner** [comment]
All: The submission is in.  I'll keep you updated via this issue.

I created a static copy of @codeekage's items for the purposes of the submission.  Please let me know if you have suggestions for changes.  This is what will be used when the GSoD team evaluates our submission: https://docs.google.com/document/d/1DLFu-BZiAshjKp546MaImDeceL_3yBGzf-aQ4BywER4/edit#

Thank you to everyone who was involved!

**Comment by codeekage** [comment]
Registration for Orgs closes today, do we have any input so far?

**Comment by brianwarner** [comment]
@codeekage, @mbj36, @Trott, @mhdawson, @keywordnew:

Who will be the mentors, if we are accepted?  Please have them fill out this form: https://forms.gle/a1x26WQGzURLerv66

cc/ @MylesBorins

**Comment by codeekage** [comment]
I’d love to mentor. 👍🏻

**Comment by mbj36** [comment]
I would love to. I registered through link provided by Brian!

**Comment by brianwarner** [comment]
We heard back from GSoD, and unfortunately we were not selected as one of the pilot organizations.  Here is the message:

> Thank you for your interest and enthusiasm for Season of Docs.
> 
> We’re sorry to say that your organization’s application for Season of Docs was not successful this year. Because 2019 is the program’s pilot year, we were only able to accept 50 organizations out of the almost 200 applications submitted. There were many high quality applications, so the selection of organizations was not easy.
> 
> Please do stay in touch with the progress of Season of Docs, and let us know if you have any questions or feedback by emailing  season-of-docs-support@googlegroups.com. We are hoping to grow the program's capacity in subsequent years, so please apply again next year.
> 
> Sincerely,
> The Season of Docs team

**Comment by mkdolan** [comment]
If anyone is interested we could try setting up a documentation mentoring program through our mentorship system. Looks like you already have interested mentors and some topics we could load into the system and do a push to see who might have interest. Shuah Khan (Linux kernel guru) leads the mentorship program creation and could probably help us organize an info session if you have interest.

**Comment by codeekage** [comment]
@mkdolan can start discussions on this:
> https://github.com/nodejs/admin/issues/310#issuecomment-488341383


I could move forward with an issue in the comm-comm to start up discussions.

**Comment by Trott** [comment]
Seems like this could/should be closed and any conversation about a mentoring initiative to take its place this year can refer to this conversation. (If I'm wrong about that and this should remain open, just go ahead and reopen it, of course. Or leave a comment if GitHub doesn't allow you to reopen it.)

**Comment by ovflowd** [comment]
I hope I'm not "necro-posting" here, is there any progress regarding the mentoring initiative?

I agree that Node.js as an org would benefit from being part of GSoD. I would love to take place here to mentor, as I've done that for GSoC for the last 3 years.

Even more, since Nodejs.dev could really get some help for the Docs part of it.
