### ISSUE TITLE
Exploration of who is interested in being Node CPC representatives

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#314]
In the TSC meeting this week the suggestion was that before we decide on the process we should ask who is interested in being our CPC representatives.

Unless there are objections that sounds like a good idea.  @nodejs/tsc, @nodejs/community-committee.

What I suggest is that we wait until Friday for people to raise any objections to that approach and if there are no objections before Friday at 5 EST, then people comment if they would be interested/have time.

As Myles mentioned there is an expectation on the level of involvement for the voting members (which the project representatives will be) as outlined in: https://github.com/nodejs/bootstrap/blob/master/proposals/stage-2/CPC_CHARTER/CPC-CHARTER.md#voting-members

If you have any questions on that front please reach out to any of the TSC/CommComm (or other Node.js members who were more actively involved in the bootstrap committee (including @chowdhurian @amiller-gh @mcollina @joesepi @obensource @hackygolucky @MylesBorins @mhdawson  (apologies for anybody I might have missed)

**Comment by mhdawson** [comment]
Ok, I guess I'll be the first.  I'm interested in being one of the Node.js CPC representatives.

**Comment by mcollina** [comment]
I’m interested as well.

**Comment by MylesBorins** [comment]
I plan to continue to participate in the CPC, open to everyone!

Very happy for folks other than me to be the voting members 😇.

**Comment by amiller-gh** [comment]
I also plan to continue participating as the CPC spins up, but given my bandwidth the past couple months I don't think I can commit to being a voting member right now 🙏

**Comment by codeekage** [comment]
I’m also interested. If my absence to the bootstrap sessions piror to now won’t be a blocking. 😅

**Comment by bnb** [comment]
Also interested in participating in the CPC both as an attendee and as a voting member.

**Comment by joesepi** [comment]
I am interested in being a part of the CPC; if not a voting member, I will be an observing member.

**Comment by ahmadawais** [comment]
I also plan to participate and interested as a CPC regular member. 💯

**Comment by LaRuaNa** [comment]
I'm also quite excited to participate in the CPC as regular member :]

**Comment by MaedahBatool** [comment]
I am interested in becoming a regular CPC member.✊

**Comment by keywordnew** [comment]
Currently I don't have the cycles to commit to the responsibilities of being a CPC voting member.

I do intend, as a regular member, to serve as a link (together with anyone else who self-nominates) between Node.js and OpenJS Foundation's CPC. 👩🏽‍💻

**Comment by mhdawson** [comment]
This was to see if we had enough interest to need elections/voting.  Since we do discussion has moved to: https://github.com/nodejs/admin/issues/316.  Closing.
