### ISSUE TITLE
Process for selecting CPC members representing Node.js project

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#316]
This issue was opened to gather information on who/how many people might be interested in being the Node.js voting representatives: https://github.com/nodejs/admin/issues/314).  This came out of a discussion in a TSC meeting with the thought that we should understand how many people might want to run for those positions before figuring out the election process.

Note that this only applies to the "voting" members that will represent Node.js.  "regular" membership is available to member of the Node.js project (and the other OpenJS projects as well).  See (https://github.com/openjs-foundation/bootstrap/blob/master/proposals/stage-2/CPC_CHARTER/CPC-CHARTER.md#regular-members)

It was tagged for discussion in the Community Committee and on review of those self-nominating it was suggested we should proceed to discuss a selection process.  I took the action to open an issue to get that started.

Some of the questions (please add more as you think of them) that we need to answer.

* Who is eligible to run for each of the 2 positions, TSC members, CommComm members, 
  other?
* Who can cast votes, TSC members, CommComm members, any Node.js project member, 
   other?
* What voting process should be used.

As a point of reference, the closest equivalent was the board representation under the previous Node.js foundation were we had 2 representatives.  For one position,  eligible candidates are members of the community committee and the candidates are voted on by community committee members.  For the second, eligible candidates are members of the TSC and the candidates are voted on by TSC members.

**Comment by mhdawson** [comment]
@nodejs/community-committee @nodejs/tsc

**Comment by MylesBorins** [comment]
I think we should move forward with the exact same process we had for directors.

1 for TSC, 1 for commcomm

TSC votes for their rep, CommComm for theirs

**Comment by Trott** [comment]
> I think we should move forward with the exact same process we had for directors.
> 
> 1 for TSC, 1 for commcomm
> 
> TSC votes for their rep, CommComm for theirs

I do like the simplicity of this.

**Comment by mcollina** [comment]
+1

**Comment by keywordnew** [comment]
I'm currently +1 for the same process for directorship.

Surfacing some discussion around this from the last CommComm session. There was also suggestion that CommComm and TSC members be able to vote for the overall pool of applicants, while still being able to place exactly one voting member per leadership committee.

**Comment by mhdawson** [comment]
I'm +1 for the same process we had for directors.

**Comment by Trott** [comment]
/ping @nodejs/tsc Would be great to get decisive consensus on this on the TSC side.

**Comment by gabrielschulhof** [comment]
The existing process sounds good. +1

**Comment by cjihrig** [comment]
+1 to using the existing process.

**Comment by gireeshpunathil** [comment]
if the capacity of the voting members in CPC and scope of subject being voted by the voting members are same / equal between the 2 voting members, then I would imagine the 2 members be voted by both the teams, rather than in isolation.

So an alternate proposal is:
 - nominate at least one from both TSC  and commcomm.
 - elect representatives by the combined team.

**Comment by thefourtheye** [comment]
> As a point of reference, the closest equivalent was the board representation under the previous Node.js foundation were we had 2 representatives. For one position, eligible candidates are members of the community committee and the candidates are voted on by community committee members. For the second, eligible candidates are members of the TSC and the candidates are voted on by TSC members.

This sounds good. +1

**Comment by danbev** [comment]
+1 to using the existing process.

**Comment by WaleedAshraf** [comment]
+1 for existing process

**Comment by apapirovski** [comment]
+1 to existing process

**Comment by Trott** [comment]
> if the capacity of the voting members in CPC and scope of subject being voted by the voting members are same / equal between the 2 voting members, then I would imagine the 2 members be voted by both the teams, rather than in isolation.

This can introduce certain complexities that I'm not sure we want to try to deal with this first time around (but maybe if we want to modify the process next year). For example, if TSC has 20 members and CommComm has 12, does that mean CommComm's opinions will be under-represented in the vote result? Additionally, it complicates the vote procedure. Does each person get to vote for just one candidate and the top two win? Or does each person get two votes? Or is there a ranked-choice system of some kind?

For these reasons, I'm inclined to favor the simplicity of Myles's proposal this first time around. We can adjust later if it is warranted.

**Comment by ChALkeR** [comment]
The existing process looks good, +1.

**Comment by gireeshpunathil** [comment]
@Trott - I agree that the election process may be more complex with my suggestion. However, my view is that definition of `representation` takes front seat than the means to implement that. To me, I see two issues with the first(popular) approach:

 - It mkes two teams (TSC and CommComm) look isolated teams with perhaps split priorities
 - Personally, it makes me feel awkward that I am represented by someone whose selection process I have not taken part of.

Having said that, these (split priorities and awakward feelings) are hypothetical at the moment, and may prove to be a NOOP.

**Comment by mhdawson** [comment]
The majority of the comments seems to suggest we should stick to the existing process (for board members) and potentially consider changes for next year mostly due to the complexities around how voting might work.  I think that would be good so that we don't delay identifying who the Node.js representatives will be.

@nodejs/tsc, @nodejs/community-committee any objections to following the existing process which would be:

1 CPC rep elected by TSC members
1 CPC rep elected by commcomm members

using processes that are similar to what was done to elect the board representatives?

**Comment by bnb** [comment]
No objection.

**Comment by ahmadawais** [comment]
Definitely +1 on the current process.

**Comment by sagirk** [comment]
No objection.

**Comment by mhdawson** [comment]
Ok, I see only agreement with the last suggestion that we proceed with 1 rep for the TSC and one for commcomm as suggested above.

**Comment by Trott** [comment]
Seems like this can be closed, but if I'm wrong, re-open, of course!
