### ISSUE TITLE
Who has access to the node.js Youtube channel?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#317]
It would be great if [these recordings from the recent Node.js diagnostics summit](https://github.com/nodejs/diagnostics/issues/203#issuecomment-472534669) can be uploaded there.

**Comment by mcollina** [comment]
It's not that easy @joyeecheung. Those videos will need to be edited and cut out to be uploaded individually.

I have access, but I won't have time to do the video editing piece.

**Comment by keywordnew** [comment]
Looks to me like a good first issue also.

**Comment by joyeecheung** [comment]
I think we actually have been uploading these recordings in entirety first and then upload edited clips separately?  e.g. https://www.youtube.com/watch?v=ZRVjWhBEwB0

**Comment by ladyleet** [comment]
If someone sends it to me I'll upload. :P ladyleet@nodejs.org

**Comment by joyeecheung** [comment]
@ladyleet The recordings are up in the [Google drive](https://drive.google.com/drive/folders/1YLrO8XwAdWPaFNmyZZRqPAsSIDGo_RXw) I think we can just upload them as-is without editing. We did that for a VM summit before as well IIRC.

**Comment by bnb** [comment]
@joyeecheung did those ever get uploaded? If not, do they still need to be? I'd be happy to do so if needed.

**Comment by joyeecheung** [comment]
@bnb From a quick search in our YouTube account, I don’t think they have been uploaded. Would be great if they are, thanks!

**Comment by Ericexchanger** [comment]
Purpose?

**Comment by Trott** [comment]
Given that this issue has been dormant for over 4 years, can we close it? I don't imagine anyone making an effort to edit and upload 5+ year old videos at this point (but if I'm wrong, then great).

**Comment by joyeecheung** [comment]
I am not sure if the videos were ever uploaded, but it seems a bit weird to upload now anyway, so closing.
