### ISSUE TITLE
Duplication in reimbursement instructions

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#319]
https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#reimbursement seems to have the reimbursement instructions listed twice, but in slightly different wording/format. Can someone who is very familiar with the process make it a single simple set of instructions? I can take a try at it, but I imagine it's best if someone on the Foundation end of things does it?

**Comment by WaleedAshraf** [comment]
I'll mark it as the good first issue and maybe @SofiEstevez can help which one to take.

**Comment by Trott** [comment]
(Removed the good-first-issue label because there's now an open PR addressing this.)
