### ISSUE TITLE
adding coveralls to nodejs.dev

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#327]
we already use this for citgm

any objections?

**Comment by joyeecheung** [comment]
Did you mean Coveralls? I think you do not need organization-wise permissions if you just enable their app for a repo? (no objections either way)

**Comment by MylesBorins** [comment]
@joyeecheung I did indeed mean coveralls. If there is no need for permission as the app is already installed I'll go ahead and flip the bit EOD tomorrow. Just wanted to make sure there was documentation of this.

**Comment by targos** [comment]
The Codecov app is installed, not Coveralls.

**Comment by targos** [comment]
And Codecov is what we have in CITGM: https://github.com/nodejs/citgm/pull/653#issuecomment-447555556

**Comment by MylesBorins** [comment]
@targos thanks for the clarification. I've asked the nodejs.dev team if they are willing to use that tool instead

**Comment by LaRuaNa** [comment]
PR landed https://github.com/nodejs/nodejs.dev/pull/211 we went for codecov
