### ISSUE TITLE
Request: Create nodejs/perfetto

### ISSUE THREAD

**Issue by kjin** [nodejs/admin#330]
Hi all,

As some may know I am working on [Perfetto](https://perfetto.dev/) integration in Node, which would replace our trace_events implementation to make tracing more robust. To make this process more transparent and easier to collaborate on I'd like to request that a nodejs/perfetto (or similar name) repo be created. In the mold of nodejs/http2 and others, it would be the central location for issues, milestone tracking, questions, etc.

Thanks!

**Comment by mhdawson** [comment]
+1 I can help set up the repo once the required time for the issue being open elapses (see https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories for more details)

**Comment by kjin** [comment]
Looking at the policy re: Teams -- I think a child team of `@nodejs/diagnostics` (like `@nodejs/diagnostics/perfetto`) for broadcasts would be great.

**Comment by mhdawson** [comment]
Ok we'll take this as a request to create 

1) Repo called nodes/perfetto-nodejs-wip  (added wip to make it clear its not a fork of perfetto and is temporary)
2) a team called @nodejs/diagnostics/perfetto or something similar (I'm not that familiar with how the sub teams work so we'll have to see what is possible).

**Comment by mhdawson** [comment]
@nodejs/TSC @nodejs/community-committee FYI.

**Comment by joyeecheung** [comment]
@mhdawson I don't think you can nest the team with slashes..so it's supposed to be `@nodejs/perfetto` but as a subteam under `@nodejs/diagnostics`

**Comment by Trott** [comment]
(Getting into the weeds here a bit but unless you want everyone in the perfetto team to get all the access/permissions of people in the diagnostics team, probably best to make it its own separate team rather than a subteam. Generally, I'd say teams should either consist entirely of subteams or else they should have no subteams at all.)

**Comment by mhdawson** [comment]
@joyeecheung thanks for the clarification. Based on @Trott comment I think a separate team is probably the way to go.

**Comment by kjin** [comment]
That sounds good and would be consistent with the repo naming as well!

**Comment by joyeecheung** [comment]
Maybe it makes more sense to put the team under nodejs/core which is supposed to include people working on core (but not all of them are collaborators so the team does not grant write access to the upstream)

**Comment by mhdawson** [comment]
I'll start by creating `nodes/perfetto-nodejs-wip` unless I hear any objections by tomorrow.

At the same time I'll look at the existing teams to better understand @joyeecheung suggestion and post low I'd like to create the teamname/ hierarchy

**Comment by kjin** [comment]
Thanks!

**Comment by Bamieh** [comment]
Updated the link website as it was resolving to this repo.

**Comment by mhdawson** [comment]
Repository created here: https://github.com/nodejs/perfetto-nodejs-wip

**Comment by mhdawson** [comment]
Making a subteam of core makes sense to me.  Teams like platform-axi and platform-windows are indirectly a subteam of core so it seems consistent with that.

**Comment by mhdawson** [comment]
I've created the team as perfetto and made it a subteam of core.  I've made Kelvin a maintainer of that team so he can add people.

**Comment by mhdawson** [comment]
@kjin I'll let you check things out before I close this.  

The first thing to do would be to update the README.md to make it clear what the repo contains as opposed to the one that came from the node repo.

**Comment by kjin** [comment]
@mhdawson It seems that I don't have write access to the repo yet. I can see that the team has been created, so I guess it would make sense to have that team have write access?

**Comment by mhdawson** [comment]
oops, I create the team but I forgot to add the team as those who can access.  Doing that now

**Comment by mhdawson** [comment]
Should be fixed now.

**Comment by kjin** [comment]
@mhdawson Thanks! One final request -- could you make `perfetto` the main branch on the repo?

**Comment by mhdawson** [comment]
@kjin done.

**Comment by kjin** [comment]
Thanks!
