### ISSUE TITLE
nodejs-ru and other very-out-of-date translation repos

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#334]
Hey, @nodejs/community-committee or whoever would be responsible! What do we do with translation repos that are very out of date? I'd like to archive them and we can unarchive them if there is ever a reason to have them. For example, https://github.com/nodejs/nodejs-ru/ has not had any significant content since before the io.js merger. It's been effectively dormant for about 4 years. Tooling needs to be updated, etc., but I think it's safe to say that this repo is unlikely to be useful to anyone. It seems like if anyone wanted to add relevant translations for Russian, they could/would do it by adding an `ru` directory at https://github.com/nodejs/nodejs.org/tree/master/locale.

/cc @nodejs/node-ru @nodejs/website @nodejs/documentation  in case any of my assumptions above are incorrect.

**Comment by zeke** [comment]
>  archive them and we can unarchive them if there is ever a reason to have them

👍

**Comment by zeke** [comment]
> if anyone wanted to add relevant translations for Russian

or, https://crowdin.com/project/nodejs/ru

**Comment by ChALkeR** [comment]
Yes, "just archive it" was also what I thought when I saw the notifications, I didn't propose it simply because I was not sure that nothing else is going on elsewhere.

+1 to archiving nodejs-ru and all outdated localization repos that were not touched (including issues/prs) in a year.

**Comment by Trott** [comment]
Repository archived.

**Comment by ChALkeR** [comment]
@Trott There are a lot of other unarchived inactive localization repos, what about those?
E.g. see https://github.com/nodejs?page=6

**Comment by Trott** [comment]
> @Trott Only one of them? There are a lot of other unarchived inactive localization repos, what about those?
> E.g. see https://github.com/nodejs?page=6

I'm +1 on archiving localization repos that haven't been updated in a year or more. I was being lazy...uh, i mean, uh, efficient here and just doing the one that was giving me notifications about outdated dependencies. If you or anyone else wants to archive other repos, I will gladly +1 an issue proposing it!
