### ISSUE TITLE
About the nodejs-foundation npm account and collaborator access

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#34]
Hi, I am wondering

1. Who has access to the Node.js foundation npm account (https://www.npmjs.com/~nodejs-foundation)?
2. How do we manage the npm collaborator access of the npm modules transferred to the foundation? If someone wants to request being added as a collaborator, what's the process? Should they open an issue in the project's repo and seek consensus, or somewhere like this for better visibility?
3. If a new npm collaborator is going to be added, whose consensus are needed? The project's Github collaborator? TSC? Members of the related Github team/WG?

**Comment by joyeecheung** [comment]
BTW I want to be added as a collaborator of https://www.npmjs.com/package/llnode but I am not sure where to ask.

**Comment by gibfahn** [comment]
>Who has access to the Node.js foundation npm account (https://www.npmjs.com/~nodejs-foundation)?

The build WG have access. Lots of history in https://github.com/nodejs/TSC/issues/211.

However, if you read through that thread, the agreement was to keep the nodejs-foundation account as a backup, and to have individual collaborators who push updates for each module.

So the way to progress would be to raise an issue in llnode asking to be given npm publish access. 

I think @rnchamberlain and @richardlau have npm publish access for llnode.

**Comment by gibfahn** [comment]
Found the node build doc for it: https://github.com/nodejs/build/blob/master/doc/process/npm_management.md

**Comment by richardlau** [comment]
AFAIK I have npm publish for node-report but not llnode.

**Comment by rnchamberlain** [comment]
@joyeecheung yes, as @gibfahn says, suggest raise an issue on https://github.com/nodejs/llnode for this. I don't think there is a formal process, but any existing npm collaborator can add you to the npm list. So for llnode thats @hhellyer, @indutny or me. 

Probably worth checking with @hhellyer about the npm release process/steps for llnode when you come to do that, I think he's done them all up to now.

**Comment by joyeecheung** [comment]
For posterity:

1. The build working group has access to the Node.js foundation npm account
2. The projects under the foundation manage the npm collaborator access on their own. 
3. To gain the npm collaborator access, open an issue in the project repo. It's up to the collaborators of that project whether the request should be accepted.
