### ISSUE TITLE
Move https://github.com/Eomm/package-compliant to node.js org

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#343]
This tool has been developed as part of the package-maintenance team's work. https://github.com/Eomm/package-compliant.  We'd like to move it to the node.js org so that we can have "team" ownership.

For more discussion see: https://github.com/nodejs/package-maintenance/issues/161 and https://github.com/nodejs/package-maintenance/blob/master/docs/drafts/Baseline%20practice%20-%20Document%20support%20levels.md

Any objections?

**Comment by Trott** [comment]
The policy for transferring is outlined in https://github.com/nodejs/admin/blob/0f2af76492b9efff8bafedbf650bb0a3c4f76e44/transfer-repo-into-the-org.md. I have no objection, but it would be preferable if the recommendations there could be implemented: a Code of Conduct (usually just a link to the org one), a minimal CONTRIBUTING.md, and anything else missing.

**Comment by mhdawson** [comment]
@Trott thanks was going to make sure we did that in advance but thanks for pointing out.

**Comment by Eomm** [comment]
I have added the missing documents to the project we are requesting to move

**Comment by Eomm** [comment]
I think that the policies of step 1 for transferring the repository are respected now.

So I'm adding cc @nodejs/community-committee and @nodejs/tsc in order to follow all the step 2 👍

**Comment by keywordnew** [comment]
For folks who try clicking on "Node.js GitHub Organization Management Policy" in Step 2, the link is broken. There's already PR open to fix that: #355. Thanks, @Eomm!

Until it's merged, here's [the link](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANGEMENT_POLICY.md#repositories).

**Comment by mhdawson** [comment]
@Eomm I think you need to do the transfer.  Some info is here: https://github.com/nodejs/admin/blob/master/transfer-repo-into-the-org.md. If you have any questions or need help just let me know.

**Comment by keywordnew** [comment]
This repo was moved as agreed and is now found at https://github.com/nodejs/package-compliant

Closing the issue as it has been resolved.
