### ISSUE TITLE
Move `node-ment` repo into the Node.js Org

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#35]
@bamieh has done a TON of work on a repo around Mentorship as a part of the discussion around mentorship in the CommComm (ref: https://github.com/nodejs/community-committee/issues/172).

As per our last CommComm meeting (ref: https://github.com/nodejs/community-committee/pull/199) we've agreed to begin the process of pulling the repo that @bamieh has worked on into the Node.js Org - and begin co-ordinating work around it as necessary.

Here's the repo: [Bamieh/node-ment](https://github.com/Bamieh/node-ment)

cc @nodejs/community-committee @nodejs/tsc

**Comment by mcollina** [comment]
SGTM

**Comment by Trott** [comment]
No objections, either way, but if possible, it would be great if it could be named more descriptively. `nodejs/mentor-program` or something like that?

**Comment by Bamieh** [comment]
@Trott  how about `mentorship`? Should I transfer it now?

**Comment by joyeecheung** [comment]
`nodejs/mentorship` SGTM. (I had no idea what `node-ment` was from the first glance..)

**Comment by Bamieh** [comment]
I thought its a cool name (node-ment) lol. Anyways I renamed the repo to mentorship. I attempted to do a transfer but i got this message:

![image](https://user-images.githubusercontent.com/6191849/34410563-d7ce9d62-ebd9-11e7-878a-0aefec2dd7dc.png)

So i guess someone has to create a repo from nodejs side so i can transfer it or something..

**Comment by Trott** [comment]
> So i guess someone has to create a repo from nodejs side so i can transfer it or something..

I imagine there's no rush on this. This issue has been open for 12 hours. It would be good to give people more time than that to express opinions, especially at a time when a lot of people are away from their computers. I don't expect any objections to this but ¯\\_(ツ)_/¯.

Assuming nothing too exciting happens in this issue, if no one's created the repo by end of UTC day January 2, post here or send me an email and I'll create it.

(And if someone feels differently and creates the repo 5 minutes after I've posted this, I'm OK with that too. I just don't want to be the person who does that myself.)

**Comment by mhdawson** [comment]
SGTM

**Comment by Bamieh** [comment]
@Trott it's january 3rd already 😄

**Comment by Trott** [comment]
Hi, @Bamieh! Would you be willing to give me admin privileges on https://github.com/Bamieh/mentorship so I can transfer it into the nodejs org?

**Comment by Bamieh** [comment]
invitation sent

**Comment by Trott** [comment]
> invitation sent

Cool. I'm a member now.  I think you need to change my role to Owner for me to be able to transfer it to the nodejs org.

**Comment by Bamieh** [comment]
@Trott this is what i thought i'd have to do. But this is what i got instead:

![image](https://user-images.githubusercontent.com/6191849/34602644-388c50b0-f209-11e7-8121-aec960661368.png)

After reading about it on github:

> There is only one owner of a repository owned by a user account; this permission cannot be shared with another user account. To transfer ownership of a repository to another user, see "How to transfer a repository."

so i do not believe this is possible. Maybe we have to do something else?

- Transfer ownership to you then you transfer ownership
- Create a repo on nodejs and i will submit the initial commit to the repo
- Create the mentorship repo and give me admin access on it so i can transfer ownership to it

@bnb I believe this should be addressed in the `STRATEGIC-INITIATIVES`?

**Comment by ljharb** [comment]
@Trott @Bamieh the only way to do this is to do one of the following:
1) temporarily grant @Bamieh the ability to create repos in the nodejs org, by making them an owner.
2) @bamieh, you would transfer your repo to another person who *is* an owner in the nodejs org, like @trott - who would then bounce it into the nodejs org. Repo redirects will work forever (until @trott, aka the bouncer, creates a repo with the same name, or forks the repo).
3) Create a new "nodejs-transfer" org. Make all nodejs org owners, owners in that org. Allow all nodejs-transfer org members to transfer repos into it. Make @bamieh a nodejs-transfer org member. @bamieh moves the repo into the transfer org, and then a nodejs org owner bounces it into the nodejs org.

Sadly github doesn't have any better choices than this.

**Comment by Bamieh** [comment]
@ljharb **# 3** seems the most scalable (for future initiative transfers as well) and protects from the issue addressed in **# 2**. Maybe we do not have to have _ALL_ nodejs owners in that org, rather than just a few owners assigned the responsibility for transfers.

Although i am not completely against **# 1** as a temp solution, but i highly discourage doing this hack (for me or for others in the future) as it's risky for both parties.


I also thought this option is also possible, any ideas?

> Create the mentorship repo and give me admin access on it so i can transfer ownership to it

**Comment by ljharb** [comment]
No, that's not possible, since personal repos can only ever have that one admin.

You're right that the third option is the most scalable; the first option is likely untenable due to the risk in giving out that much access to the nodejs org; the second option is the most convenient but requires more coordination.

**Comment by bnb** [comment]
I am happy to help execute on any of this - please let me know how I can help!

**Comment by Trott** [comment]
I'm not sure who we'd have to involve create a new org like `nodejs-transfer` or whatever. Worst case, I put this on the agenda for the TSC meeting and hopefully can figure stuff out there. But a solution sooner would be nice.

**Comment by Fishrock123** [comment]
If owner permissions are required, I already have a "testing" org set up that could be used to do a transfer were we don't need to give owner rights to the nodejs org.

I/We can give folks owner rights to https://github.com/TestOrgPleaseIgnore and then it can be moved there first, and then myself or someone else could move it here.

GitHub **will** handle redirects for this correctly, AFAIK.

**Comment by targos** [comment]
Any member of the org has the right to create repositories, not only owners. We should just add @Bamieh to a team.

**Comment by Bamieh** [comment]
The mentorship program is now under nodejs 🎉 https://github.com/nodejs/mentorship

**Comment by Trott** [comment]
Thanks, whoever made it happen!  :-D

**Comment by Bamieh** [comment]
haha thanks @Trott for making it happen!

**Comment by Trott** [comment]
> haha thanks @Trott for making it happen!

Wasn't me! I just brought it to the TSC meeting and kinda threw up my hands. I assumed it was either @Fishrock123 or @targos...

**Comment by Bamieh** [comment]
I transferred the repo from my account, but you were the one that invited me over.
