### ISSUE TITLE
Standardize Travel Fund reporting currency using ISO 4217

### ISSUE THREAD

**Issue by keywordnew** [nodejs/admin#358]
[ISO 4217](https://en.wikipedia.org/wiki/ISO_4217) is a way to refer to currency amounts using a 3-letter code like USD for US Dollars, JPY for Japanese Yen, and PHP for Philippine Peso. 

Benefits:
* easier to parse these records if we decide we need that in future to make it easier to manage by Foundation folks. If the travel fund scales to the larger OpenJS, that's more likely.
* easier to read and follow if we're being visually consistent. Seeing `USD 440`, `1221 €`, and `$955 USD` all in the same list is fixable.

**Comment by WaleedAshraf** [comment]
+1

**Comment by joyeecheung** [comment]
+1, and I think it would be better if we just use one currency (USD? because the foundation is registered in the US) for the estimate and the final amount that are written in the table. The breakdown in the PR can list the expenses in other currencies and convert them to USD in the end.

**Comment by keywordnew** [comment]
Checklist (so far), add guidelines to [travel fund](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md) doc:

- [ ] about the breakdown being ok in different currencies
- [ ] about the total needing to be in USD (include a helpful link to convert)
- [ ] about how to format the currency display

**Comment by tniessen** [comment]
That probably depends on what the policy is for when currency conversion should happen. Personally, I feel like it makes sense to convert either at the time of booking or at the time of the expense report, which would both be later than the travel fund requests. This most likely won't make much of a difference, but the foundation should have clear guidelines.

**Comment by mcollina** [comment]
Credit cards and banks charge some fees for converting between currencies. Note that to get money back it’s possible to have around 4% loss in fees. As an example, for an event in Canada: EUR -> CAD for the hotel, EUR -> USD for reimbursement.

I’ve never used the Travel Fund, so I don’t know: do you need to file your expenses in USD?

**Comment by WaleedAshraf** [comment]
I think in PR/Booking currency should be in which booking was made, and should be converted at the time of expenses by the foundation to USD.

i.e, Pakistan currency always keeps going up/down w.r.t USD. So, if someone booked in PKR, they should get the same PKR amount reimbursed. No matter what is the current rate.

In short, the foundation would take any profit/loss due to rate changes.

**Comment by Trott** [comment]
Travel fund is now a CPC thing so I think this can be closed here?
