### ISSUE TITLE
archive repos/remove teams for nodejs-ms and nodejs-mk

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#359]
I'd like to archive https://github.com/nodejs/nodejs-ms and https://github.com/nodejs/nodejs-mk. Both have no significant content and have not had any commits in 4 years or so. Additionally, the @nodejs/nodejs-ms and @nodejs/nodejs-mk teams both have 0 members. I'd like to additionally remove those teams once the corresponding repositories are archived.

@nodejs/community-committee @nodejs/tsc

**Comment by keywordnew** [comment]
+1

**Comment by ChALkeR** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by mcollina** [comment]
+1

Il giorno gio 9 mag 2019 alle ore 13:46 Waleed Ashraf <
notifications@github.com> ha scritto:

**Comment by Trott** [comment]
All done.
