### ISSUE TITLE
Proposal to archive nodejs/testing

### ISSUE THREAD

**Issue by keywordnew** [nodejs/admin#362]
The description of [the repo](https://github.com/nodejs/testing) says it's inactive.

**Comment by keywordnew** [comment]
Pinging @nodejs/community-committee @nodejs/tsc to see if there's any feedback.

**Comment by cjihrig** [comment]
SGTM

**Comment by mcollina** [comment]
SGTM

**Comment by WaleedAshraf** [comment]
SGTM

**Comment by Trott** [comment]
+1

**Comment by BridgeAR** [comment]
+1

**Comment by keywordnew** [comment]
To be clear, my handle doesn't have the permissions to archive nodejs/testing and so resolve this issue. For anyone who does, this issue has been open for 6 days, has gathered no objections and several explicit thumbsups.

**Comment by Trott** [comment]
Done.
