### ISSUE TITLE
OpenJS Community Corner at Node + JS Interactive

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#365]
Curious if y'all want to do this again or if you've had any private discussions around this? 

Just planning for Node + JS Interactive! :) 

Please comment!

**Comment by mhdawson** [comment]
I think it was well received last year :)

**Comment by keywordnew** [comment]
+1

Had feedback from multiple people that the Community Corner was a great forum for the project!

**Comment by WaleedAshraf** [comment]
+1
It was great last time.

**Comment by mcollina** [comment]
+1!

Il giorno dom 26 mag 2019 alle 04:10 Waleed Ashraf <notifications@github.com>
ha scritto:
