### ISSUE TITLE
request for a new github repo for exploration of a WebCrypto API implementation

### ISSUE THREAD

**Issue by sam-github** [nodejs/admin#366]
I've been talking with @tniessen and @mhdawson about implementing https://www.w3.org/TR/WebCryptoAPI/ (more readable docs at https://developer.mozilla.org/en-US/docs/Web/API/SubtleCrypto). This is the standard Web crypto API implemented in (most or all) modern browsers.

We'll start by implementing it as a standalone package, and would like a https://github.com/nodejs/ repo to work in, so we can request CI and also invite collaborators who are interested to get involved.

Can we do this? We suggest a repo name of `webcrypto`. It can get the same access permissions of github.com/nodejs/node (all node core collaborators), or if that causes too much work/will deluge them with messages about a new repo, just adding @tniessen and myself would be fine.

**Comment by Trott** [comment]
For reference:

> Provided there are no objections from any TSC or CommComm members raised in the issue, such requests are approved automatically after 72 hours.

SGTM.

**Comment by mhdawson** [comment]
LGTM

**Comment by targos** [comment]
LGTM

**Comment by ChALkeR** [comment]
LGTM

**Comment by codeekage** [comment]
LGTM

**Comment by MylesBorins** [comment]
LGTM

**Comment by mhdawson** [comment]
@sam-github I think you can go ahead and create the new repo...

**Comment by sam-github** [comment]
I created https://github.com/nodejs/webcrypto

It's completely empty, @tniessen or I will add some of the README, etc, boilerplate soonish. I gave all node core collaborators access, I hope that was reasonable. Please tell me if there is some convention on this.
