### ISSUE TITLE
Summit Code of Conduct enforcement responsibility

### ISSUE THREAD

**Issue by benjamingr** [nodejs/admin#367]
It is currently unclear who is supposed to enforce the Code of Conduct in OpenJS summits. 

The moderation team is not empowered to enforce the CoC in summits. When we receive reports to report@nodejs.org in the summit we work with summit organizers to resolve the issue. 

I think so far this has been working on a "good faith" basis where project members and summit organizers feel strongly about providing a collaborative environment and volunteer to help resolve issues.

I think there is value in an official policy and clarification for summits since they are an official foundation event.

 - At what capacity does project leadership expect the moderation team to be involved in resolution of reports in summits? 
 - Should there be a different report email that reaches summit organizers directly for these issues?

Note that at the moment in both summits I've participated in there were multiple moderation team members but in theory there could be a summit without any moderation team attendance. 

Personally I don't have strong feelings about it.

@nodejs/moderation @nodejs/community-committee

**Comment by mcollina** [comment]
I think enforcing the CoC is a responsibility of the Summit team. @jorydotcom, @keywordnew and my email were listed during the initial slide deck. I think these was not easily accessible. We should provide this as part of the summit repo docs.

**Comment by jasnell** [comment]
I agree that it's the Summit team's responsibility but the process does need to be formalized. For all events such as this, there should be a single responsible lead for ensuring these are handled.

**Comment by benjamingr** [comment]
I think we have consensus and agree. Going to go ahead and close this with the usual "If anyone feels strongly - reopen"
