### ISSUE TITLE
Please submit - CFP closing for Node + JS Interactive in 11 days (6/14)!

### ISSUE THREAD

**Issue by ladyleet** [nodejs/admin#368]
FYI CFP closes in 11 days for Node + JS Interactive!

Please please submit soon :) https://linuxfoundation.smapply.io/prog/nodejs_interactive_2019/

Conference is December 11 & 12 in Montreal, QC.

@mcollina @keywordnew can y'all bring this up in TSC/CommComm as a reminder?

**Comment by WaleedAshraf** [comment]
thanks for the reminder @ladyleet. Will communicate in next meeting.
Do we have some content to share/tweet on social media about this?

**Comment by joesepi** [comment]
CFP was extended but has now passed. Closing issue. Thanks!
