### ISSUE TITLE
CoC report information is inaccurate

### ISSUE THREAD

**Issue by pup** [nodejs/admin#37]
the coc states that the report@nodejs.org alias redirects to members of the TSC, which isn't accurate anymore, as it now redirects to the moderation team. this should be changed

**Comment by addaleax** [comment]
is there a public list of @nodejs/moderation team members that we could link to? It feels like there should be, for transparency

**Comment by Trott** [comment]
AFAIK, there is no public list of @nodejs/moderation and that should change (or if there is a list, let's publicize it more).

Furthermore, the list that the email goes to (which *is* publicly available at https://github.com/nodejs/email/blob/c2126c9cdf6f8abcecc50d9e4f2ac2043797c560/iojs.org/aliases.json#L55-L64 but obviously we can make that more user-friendly) does not match the membership of @nodejs/moderation. (It appears to be missing @thefourtheye.) So a PR to fix that is also in order.

**Comment by benjamingr** [comment]
The public list of @nodejs/moderation is literally @nodejs/moderation https://github.com/orgs/nodejs/teams/moderation shows a list of members.

**Comment by gibfahn** [comment]
>The public list of @nodejs/moderation is literally @nodejs/moderation github.com/orgs/nodejs/teams/moderation shows a list of members.

That's not public, it's only accessible to members of the org.

**Comment by ryanmurakami** [comment]
Fixing the email alias here: https://github.com/nodejs/email/pull/82
And fixing the coc here: #40

**Comment by bnb** [comment]
Closing - https://github.com/nodejs/admin/pull/40 has been merged 👍
