### ISSUE TITLE
Transfer https://github.com/trott/node.js.org into the org

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#370]
I'd like to transfer https://github.com/trott/node.js.org into the org. @nodejs/tsc @nodejs/community-committee

**Comment by Trott** [comment]
Refs: https://github.com/js-org/js.org/pull/3115#issuecomment-500611565

**Comment by mcollina** [comment]
SGTM

**Comment by mhdawson** [comment]
+1 on transferring but a few questions:

* How does this get deployed?
* Who owns the node.js.org?

**Comment by MattIPv4** [comment]
@mhdawson Trott is using a GitHub pages site, so it is automatically deployed whenever a new commit is pushed to the branch configured to serve GH pages within the repo, `master` or `gh-pages`.

With regards to node.js.org, it is part of the free subdomain service that I help @indus to maintain. You can find out more on [our website](https://js.org) or on [our GitHub repo](https://github.com/js-org/js.org)

Hope that helps :)

**Comment by mhdawson** [comment]
@MattIPv4 thanks, that clarifies a lot for me.

**Comment by cjihrig** [comment]
SGTM

**Comment by WaleedAshraf** [comment]
SGTM

**Comment by codeekage** [comment]
SGTM

**Comment by MattIPv4** [comment]
@Trott what's the latest on this? :)

**Comment by Trott** [comment]
Done! https://github.com/nodejs/node.js.org
