### ISSUE TITLE
Q&A with James Snell – OpenJS Board election

### ISSUE THREAD

**Issue by joesepi** [nodejs/admin#375]
Per https://github.com/nodejs/admin/issues/364, we are opening up the election for the Node.js project board seat on the OpenJS Board of Directors.

Welcome to the Q&A session for nominee James Snell @jasnell!

@nodejs/tsc and @nodejs/community-committee please ask your questions of this nominee in this issue. You will find a link to the CIVS election poll in your email inbox.

CANDIDATE STATEMENT:
>My primary interest in representing the project on the Board at this time is to ensure that the overall direction that the Foundation is taking represents the best interests of the project as a whole. There are several initiatives, just as the long awaited Certification, the Interactive event, and travel fund, as well as ecosystem wide concerns such as package maintenance and sustainability that require champions on the Board. The more we have, the better.

**Comment by gireeshpunathil** [comment]
- from what source(s), and through what methodology(ies), will you gather needs of Node.js project?
 - it is rare to have unanimous opinion among members on project's issues or topics. how will you drive convergence?
 - you may be `owning` and driving one or more initiatives in the project. how will you position Node.js' collective priority on top of yours?
 - how will you pursue node's interest with board?
 - how will you assess implications of board's direction / decision to Node.js project?
 - how will you tackle situations wherein Node.js' interest is orthogonal to that of the larger JS ecosystem?
 - what will you define as success criteria of your role in the board representing Node.js?
 - what, in your opinion, are the top n advantages of Openjs foundation to the Node + JS ecosystem?
 - what, in your opinion, are the top n priorities of the Node.js project at the moment?

**Comment by jasnell** [comment]
Hey all, just a heads up, I've been traveling for NodeConfCo and just back home early this morning. I'll get answers here later today or tomorrow! Thank you!

**Comment by jasnell** [comment]
My apologies for taking a bit longer to respond.

> from what source(s), and through what methodology(ies), will you gather needs of Node.js project?

Nothing beats active daily involvement and talking to individuals.

> it is rare to have unanimous opinion among members on project's issues or topics. how will you drive convergence?

Not only is it rare, it nearly impossible. Node.js has excelled when we actively and deliberately avoid asking if everyone agree and instead ask if there are any objections. Flipping that bit fundamentally changes the dynamic of the conversation and allows us to make progress easier.

> you may be owning and driving one or more initiatives in the project. how will you position Node.js' collective priority on top of yours?

My priority is on the health and vitality of the ecosystem.

> how will you pursue node's interest with board?

My interest in the board is to ensure accountability to the projects. The Foundation and the board are useless constructs if they do not actively serve the needs of the projects.

> how will you assess implications of board's direction / decision to Node.js project?

There is a fairly simple rubric: does the decision hinder the goals of the project or do they help? Does the decision advance health and vitality of the ecosystem or does it hurt?

> how will you tackle situations wherein Node.js' interest is orthogonal to that of the larger JS ecosystem?

I disagree with the premise that Node.js' interests *are* orthoginal to that of the larger JS ecosystem.

> what will you define as success criteria of your role in the board representing Node.js?

That the Foundation and Board remain accountable and transparent to the projects they serve.

> what, in your opinion, are the top n advantages of Openjs foundation to the Node + JS ecosystem?

Executed properly, the Foundation drives awareness, support, and contribution to the projects they serve.

> what, in your opinion, are the top n priorities of the Node.js project at the moment?

Continued focus on open governance, alignment with the larger JS ecosystem, and continued focus on improving overall developer experience.

**Comment by mhdawson** [comment]
Election complete, closing.
