### ISSUE TITLE
Update the logistics of being reimbursed after travel is complete

### ISSUE THREAD

**Issue by brianwarner** [nodejs/admin#379]
I'd like to propose an update to the guidance we provide to travel fund recipients when they're ready to be paid.  Having been through this cycle a few times now, I think we can streamline the reimbursement part of the process.

Currently, travel fund recipients are asked to fill out a spreadsheet and send in photos of their receipts.  This is cumbersome, time-consuming, and error-prone.  Further, it takes a good deal of verification on my side to ensure that the amounts are correct, that currencies are correctly converted, and that all receipts are correctly attached.

I'd like to propose adding a second process based upon how we do it at The Linux Foundation.  I recommend that travel fund recipients use Expensify to capture photos of their receipts during/after travel, and document expenses in the local language on the receipt.  They would then submit the Expensify report in lieu of the spreadsheet and a zip file of receipt photos.  A free Expensify account is sufficient, and I've created some guidelines on how to configure it.  There are also phone apps available, so that expenses can be captured on the fly.

My hope is that this will decrease the amount of time it takes for recipients to submit their requests (in theory, they can hit send as soon as they add their last expense), and decrease the amount of time it takes for me to verify and submit the requests for payment.

I have drafted up some changes to the [process document](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md), which I'll submit as a pull request once this issue has been discussed.  I've also created a [PDF guide](https://github.com/nodejs/admin/files/3346976/reimbursement_process.pdf) on how to configure Expensify and submit an expense report which I'll include in the same PR (but also attached here so you can see it).

The current manual process can certainly stick around if someone prefers it, but I think this would be a major improvement.

Thoughts?

**Comment by MylesBorins** [comment]
+1 on introducing the new process. Thanks for doing the heavy lifting brian

**Comment by brianwarner** [comment]
Per an email with @Trott, I've opened #381 with my specific proposed updates.  I'll close this issue so that we can move any discussion over there.  Thanks for the feedback so far!
