### ISSUE TITLE
retire bootstrap team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#382]
Since the foundation merger is complete, I imagine that @nodejs/bootstrap has been supplanted by the @openjs-foundation/bootstrap team. If I'm not wrong about that, then I propose that we remove @nodejs/bootstrap.

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by mcollina** [comment]
SGTM

**Comment by bnb** [comment]
For clarity, I believe @nodejs/bootstrap has been replaced by @openjs-foundation/cpc, not @openjs-foundation/bootstrap.

SGTM 👍

**Comment by codeekage** [comment]
SGTM

**Comment by codeekage** [comment]
Sorry! For closing this, it was a mistake

**Comment by mhdawson** [comment]
SGTM, the bootstrap repo was already migrated to the openjs-foundation org so makes sense to retire the team as well.

**Comment by keywordnew** [comment]
SGTM.

**Comment by Trott** [comment]
I deleted the team. There were a bunch of folks on the team who are not on any other teams in the @nodejs org. I will remove them from the org. Nothing personal, of course! And if there's some other team they should be added to, happy to do it. It does seem like many of these folks may be more properly in the @openjs-foundation org (where they presumably already are!).

@aupdegrove
@brianleroux
@christian-bromann
@gibson042
@jorydotcom
@justmoon
@ryanblock
@StevenAyr
@torgo
