### ISSUE TITLE
Remove members on zero teams

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#383]
The following folks are currently on no @nodjes org teams and have write access to no @nodejs org repositories. I'd like to remove them or get them added to an appropriate team.

I'd like to be biased towards action on this, as adding someone to a team is easy. So barring opposition from anyone on @nodejs/tsc or @nodejs/community-committee, I'll remove anyone below after 72 hours unless there's indication of a team they should be added to and (if they weren't the ones suggesting the team) they specifically agree to be added to that team. Again, being removed is no big deal because we can always add someone to the right team later. So I'd rather not have this stay open for four months. 😀

Also, if it's been more than 72 hours and I haven't yet done this, feel absolutely free to beat me to it.

* ~@Andersos~
* @balupton
* @fhemberger (left the website team very recently--still watches the repo and comments here and there but that's something anyone can do--don't need to be a team member for that--obviously, they'd be re-added in a heartbeat if they wanted back on the Website WG)
* @jbajwa
* @justinbeckwith
* @jxm262
* @rnchamberlain

**Comment by MylesBorins** [comment]
+1

**Comment by Trott** [comment]
Since @JustinBeckwith is a Google Cloud person, it might make sense for them to be on the delivery-channels team, if they want. Cloud doesn't cleanly fit into any of the existing three subteams (version-management, distros, embedders), so we'd either have to create a fourth subteam or else consider cloud to be one of distros or embedders. I would propose a fourth subteam. It would be cool to have a place where AWS Lambda, Google Cloud, Microsoft Azure, etc. folks were. I can imagine a future where that will be more and more useful/necessary.

**Comment by Andersos** [comment]
I thought I was part of the nodejs/i18n team

**Comment by Trott** [comment]
> I thought I was part of the nodejs/i18n team

It appears not, but let's get that rectified if appropriate! /ping @amiller-gh @bnb @obensource @richardlitt @zeke

**Comment by codeekage** [comment]
1+

**Comment by RichardLitt** [comment]
@Andersos 	Added. :)

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
All done with the list above, but I'm not closing the issue because I did another pass and found the following with 0 teams:

* @s3ththompson They removed themselves from the website team 4 days ago. They are on no other teams. Any objection to removing them from the org? (@s3ththompson Feel free to jump in and say that there's a team you want to/should be on if that's the case!)

**Comment by s3ththompson** [comment]
Please feel free to remove me! I removed myself from the website team given that I haven't worked on Node stuff for a while. :wave:

**Comment by Trott** [comment]
All done!
