### ISSUE TITLE
Remove foundation and board teams?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#384]
The @nodejs/foundation and @nodejs/board teams are infrequently used and I *think* Foundation has stale membership. 

Moreover, they seem like they should be supplanted by teams in the @openjs-foundation org. IIUC, there isn't really a Node.js Foundation or a Node.js Foundation Board anymore. It's all OpenJS Foundation at this point.

**Comment by brianwarner** [comment]
I can't speak for the others, but as for myself, I'm not using these teams.  

And that's correct, the the OpenJS Foundation/Board supersedes the Node.js Foundation/Board.

**Comment by mkdolan** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by Trott** [comment]
Aside: I originally wrote something (since edited) that made it clear that I had no idea who the CommComm rep on the Node.js board was. (It was @hackygolucky.) I’m terribly sorry. While I don't pay close attention to board happenings, I certainly should have enough awareness to avoid rendering committee representatives on the board invisible. I'll try to do better.

**Comment by mhdawson** [comment]
I think this repo would also be archived: https://github.com/nodejs/board. It's long out of date and if it should exit it should now be in the OpenJS Foundation org.

**Comment by mhdawson** [comment]
I'm +1 on removing the foundation and board members teams as well.  The foundation one will no longer apply and the board one would be down to a single board member for the Node.js project  so I  don't think we need a team for that anymore.

**Comment by Trott** [comment]
* `@nodejs/foundation` team removed
* Removed members from the org whose only team was `@nodejs/foundation`
* Removed `@nodejs/board`
* Archived the https://github.com/nodejs/board repository after closing the one open pull request and two open issues (all inactive for many months or longer)

Follow up with any concerns, or requests for people to be instated on to other teams or whatever. Thanks!
