### ISSUE TITLE
Goal-setting for the Node.js remote AMAs are kicking off

### ISSUE THREAD

**Issue by keywordnew** [nodejs/admin#388]
Node.js collaborators had an AMA for core subsystems at the last Collab Summit in Berlin https://github.com/nodejs/summit/issues/154

There is a plan to continue AMAs for Node.js, and it's important that input into the content and target audience be open/broad.

The next meeting is on [Thursday, 25th July, at 8:30 PST](https://meet.google.com/eck-odbc-dqq).

**Comment by bnb** [comment]
@keywordnew is this resolved at this point? If so, can it be closed? If not, what are necessary next steps?

**Comment by keywordnew** [comment]
This initiative continued for a few months, at least till an an AMA for CommComm in November 2019. Rachel and Eva from This Dot were championing this, I believe. 

I'll close this issue for now, as goal-setting had been completed. As for the continuity of the AMAs, that's an open-ended question :)
