### ISSUE TITLE
Request for Travel Funds

### ISSUE THREAD

**Issue by codeekage** [nodejs/admin#390]
Hey All - 

As part of the outreach initiative, I'd be attending and facilitating an event in Lagos, Nigeria [OSCA](https://opencollective.com/osca/events/osca-port-harcourt-31395ev) as I previously did in Port Harcourt, Nigeria 6th July 2019. 

The event was an opening to collaboration and open source, and a window for Node.js. Please, I'd love to know if it's okay to open a PR for Travel Fund for the event in Lagos, Nigeria 3rd August 2019.

Thank you  🙌

**Comment by codeekage** [comment]
cc: @ladyleet @nodejs/community-committee @nodejs/tsc

**Comment by gireeshpunathil** [comment]
I don't know whether the travel fund policy bylaw allows this or not, but I absolutely support this!

**Comment by Trott** [comment]
> I'd love to know if it's okay to open a PR for Travel Fund for the event in Lagos, Nigeria 3rd August 2019.

Given the short time frame, I think you should open a pull request immediately.

**Comment by Trott** [comment]
> > I'd love to know if it's okay to open a PR for Travel Fund for the event in Lagos, Nigeria 3rd August 2019.
> 
> Given the short time frame, I think you should open a pull request immediately.

(The pull request takes 72 hours minimum to approve. It can't be pre-approved in this issue or anything. You have to open the pull request and then TSC and CommComm evaluate it, either approving it or not.)

**Comment by Trott** [comment]
I don't think there's any reason to have this issue open. But if I'm wrong, feel free to re-open. (And people can still comment on a closed issue.) Again, I think the thing to do is open a pull request.
