### ISSUE TITLE
Visa Request & Fund for Node + JS Interactive

### ISSUE THREAD

**Issue by codeekage** [nodejs/admin#391]
Hello All - 

It's about 6 months to the event and preparations are yet to be made, and I really do want to be part of 2019's Node + JS Interactive. In the spirit of:

> For all events, 3rd party or hosted Foundation events, it is recommended to apply for a visa at least 6 months prior to an event.

Is it okay to send in Travel Funds PRs for Node + JS Interactive? 

Thank you 🙌

**Comment by keywordnew** [comment]
Feel free to make a travel fund PR as soon as you have the estimated costs. 👍🏽
