### ISSUE TITLE
The Slack GitHub app is requesting more permissions

### ISSUE THREAD

**Issue by targos** [nodejs/admin#392]
See https://github.com/organizations/nodejs/settings/installations/130191

![image](https://user-images.githubusercontent.com/2352663/61577720-b7406d00-aaeb-11e9-8e3a-8f3256f6bd55.png)

It's currently only installed for the `nodejs/moderation` repo:
![image](https://user-images.githubusercontent.com/2352663/61577735-d17a4b00-aaeb-11e9-9fe1-094a0f6466d2.png)

Should we accept the request? Is the app still in use?

/cc @nodejs/moderation

**Comment by benjamingr** [comment]
We do use this in the moderation team slack. Thank you for keeping a close watch. We basically use this for an alert when there is new issues in the repo so we have a faster response time for those.

**Comment by bnb** [comment]
Going to close this since it seems resolved (and @benjamingr's comments still hold true to this day). If needed, please feel free to reopen 👍
