### ISSUE TITLE
Add @christian-bromann and @jorydotcom to the org

### ISSUE THREAD

**Issue by keywordnew** [nodejs/admin#393]
Per #382, a few folks were removed from the org as part of routine clean maintenance.

As partial reversal, could we get @christian-bromann and @jorydotcom in the org? At least temporarily while /summit remains in the org, they'll need access so that they can help manage issues and PRs in the nodejs/summit repo in which they're both actively involved.

**Comment by Trott** [comment]
Probably easiest to add them as external collaborators to that repository and/or move that repository to the openjs-foundation org.

**Comment by Trott** [comment]
I've added them both as collaborators with write access to the summit repo. Feel free to close this if that's all that's needed.

**Comment by jorydotcom** [comment]
Thanks @Trott & @keywordnew!!

**Comment by Trott** [comment]
(Re-open if there's still an issue here, of course!)
