### ISSUE TITLE
Archive https://github.com/nodejs/nodejs-ar?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#397]
As I understand it, all (or at least most) of the https://github.com/nodejs/nodejs-XX (where XX is a language code) repositories are not serving much of a purpose. They are mostly (or entirely) inactive. Translations are now happening in the main repo for the website (https://github.com/nodejs/nodejs.org) and on CrowdIn. I don't *think* these repositories come into play.

So I'd like to start archiving them, one or two at a time.

/ping @nodejs/i18n @nodejs/nodejs-ar in case I'm wrong about any of the above.

@nodejs/tsc @nodejs/community-committee

**Comment by maddhruv** [comment]
> Translations are now happening in the main repo for the website (nodejs/nodejs.org) and on CrowdIn. 

100%

you can archive these repositories unless we need them for language-specific discussions or helps(issues), which are even mostly happened at the 18n repo

**Comment by Trott** [comment]
One member of @nodejs/nodejs-ar asked that the repo be left open for a while for it to get in order. I'm not 100% sure what that means, but I think it's fine to wait at least until the README is pointing people to the right current places to do i18n work (the nodejs.org repo for website stuff, except for API docs which are in CrowdIn). I'm going to close this, but if anyone feels strongly that it should be archived sooner rather than later, please comment, re-open, whatever.

**Comment by maddhruv** [comment]
Will try to put the redirection note on all of these repos
and will ping you or anyone to archive them one by one
