### ISSUE TITLE
How to onboard team members?

### ISSUE THREAD

**Issue by srl295** [nodejs/admin#4]
I renamed the team for the `Intl` WG to [Intl](https://github.com/orgs/nodejs/teams/intl). I'd like to onboard more team members as seen in https://github.com/nodejs/Intl/issues/5 - but they aren't current "nodejs collaborators". Is this a problem? What's the right process? I don't seem to have access to make changes, who would make them?

Posting here for purposes of shared memory.

**Comment by srl295** [comment]
@mikeal @rvagg any ideas? TSC item?

**Comment by Fishrock123** [comment]
> Is this a problem? 

Nope, you can add collaborators for a WG to just that WG's team.

> What's the right process? 

None in specific, whatever is best for the WG. Core (and maybe build) is the only one that is particularly regimented.

> I don't seem to have access to make changes, who would make them?

You're an owner, so you should. Just type their name into the "add a person" search box on this page: https://github.com/orgs/nodejs/teams/intl

**Comment by srl295** [comment]
@Fishrock123 I'm a "team maintainer" of Intl but not an [Owner](https://github.com/orgs/nodejs/people?utf8=✓&query=role%3Aowner+) of the nodejs org, so while I could add someone to *Intl* I can't add them to *nodejs* and thus *Intl* if they aren't already part of *nodejs*.

**Comment by kosamari** [comment]
@Fishrock123 @srl295 
Yes for the same reason I'm the only one adding each member to translation teams.
I feel like there should be central place to request/add collaborators...

**Comment by kosamari** [comment]
It would be great to sort out what happens after "request team access" (i.e click **join** button on teams page) How does the access get approved & who is watching the request notification.

(I get few request to join translation team every now and then)

**Comment by mikeal** [comment]
Can we automate this? In most cases there is a repository that exactly matches the team name. If you add someone to a repo that isn't in the org they show up here:

https://github.com/orgs/nodejs/outside-collaborators

It would be nice if a script just picked this up and invited these people to the org and added them to the team that matches the repo someone added them to. This way all the team admins would need to do is add them as a collaborator to the repo.

**Comment by kosamari** [comment]
@mikeal I assume we can create bot "Owner" account & use the account's API key to run watch script.
https://developer.github.com/v3/orgs/members/#add-or-update-organization-membership

**Comment by srl295** [comment]
> https://github.com/orgs/nodejs/outside-collaborators

404 - is it an Owner-only page?

**Comment by srl295** [comment]
OK. I didn't realize I can give ownership to the `Intl` repo separately from the `Intl` team. I've now added some more 'outside collaborators' I suppose.
