### ISSUE TITLE
Request to create nodejs/wasi repo

### ISSUE THREAD

**Issue by cjihrig** [nodejs/admin#400]
I don't anticipate this being contentious, but wanted to open this issue for visibility and awareness. I'd like to create a `nodejs/wasi` repo containing a fork of `nodejs/node`. This repo would be for collaborating and iterating on https://github.com/nodejs/node/pull/27850 outside of a single core PR.

~~I'll wait the normal 48 hours before creating the repo just in case there are objections for some reason.~~ I see the policy here is 72 hours to wait before creating a repo.

cc: @devsnek @guybedford @nodejs/tsc

**Comment by Trott** [comment]
I don't expect any contentiousness here either, but just to make sure we're pinging 'em: @nodejs/community-committee

**Comment by keywordnew** [comment]
Go for it 🙌🏽

**Comment by MylesBorins** [comment]
+1

**Comment by cjihrig** [comment]
Thanks all. https://github.com/nodejs/wasi exists now.

**Comment by devsnek** [comment]
^ This might also need a WASI github team to delegate write access to the repo

**Comment by cjihrig** [comment]
I gave the Collaborators team access and created https://github.com/orgs/nodejs/teams/wasi/.
