### ISSUE TITLE
Proposal for openjs-foundation/summit

### ISSUE THREAD

**Issue by keywordnew** [nodejs/admin#403]
[#242](https://github.com/openjs-foundation/cross-project-council/issues/242) was opened in `openjs-foundation/cross-project-council` to create `openjs-foundation/summit`.

Two options have been proposed, of which one will be chosen:
* a new repo
* move the existing nodejs/summit repo to the openjs-foundation

Initial discussion has highlighted the benefits of keeping nodejs/summit history and context by moving it. This is the origin of the Summit and the community should be preserved.

Feel free to thumbs up, thumbs down, and/or discuss here or in the CPC mentioned earlier.

**Comment by mhdawson** [comment]
I'm +1 for moving to the existing repo unless somebody else has concerns.

**Comment by mcollina** [comment]
+1!

Il giorno mer 14 ago 2019 alle 19:55 Michael Dawson <
notifications@github.com> ha scritto:

**Comment by keywordnew** [comment]
Final comments from @nodejs/community-committee @nodejs/tsc ?

**Comment by WaleedAshraf** [comment]
+1 with moving existing repo. We will need to add all the members in `openjs-foundation/summit` repo.

**Comment by keywordnew** [comment]
Need the help of an org owner to transfer nodejs/summit, @mhdawson @amiller-gh :-)

**Comment by mhdawson** [comment]
I'm happy to do it. Will ping you to co-ordinate.

**Comment by mhdawson** [comment]
@keywordnew I moved the repo over but I'm not an org owner in the openjs-foundation so I can't update members/team.

@openjs-foundation/cpc-voting-members
 can one of the voting members help out with this?

**Comment by keywordnew** [comment]
Thanks @mhdawson! With which handles would members/team need to be updated?

**Comment by keywordnew** [comment]
- [x] Repo moved.
- [x] Team created.

I'm going to close this issue. Please feel free to reopen this issue if necessary, or open a new issue at the new location: https://github.com/openjs-foundation/summit

**Comment by WaleedAshraf** [comment]
can someone add me also? @keywordnew

**Comment by keywordnew** [comment]
@WaleedAshraf of course! Can you please join the openjs-foundation org so we can do that?

**Comment by WaleedAshraf** [comment]
@keywordnew I think someone with org access needs to do that. I'll open issue in openjs-foundation/summit repo.
