### ISSUE TITLE
Org description

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/admin#405]
Making this issue here since I didn't know of a better place to make it. I just realized we don't have an org description. We should probably have one, not for any specific reason, just because it doesn't hurt.

Maybe we could just reuse the description from the nodejs/node repository.

**Comment by keywordnew** [comment]
Related issue: #257

**Comment by keywordnew** [comment]
I'd suggest a modification of the description from nodejs/node:

> Repositories related to the Node.js JavaScript runtime ✨🐢🚀✨

**Comment by aduh95** [comment]
We now have an org description.
