### ISSUE TITLE
Archive nodejs/ffi repo and remove group?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#406]
The repo has been idle for over two years and the group seems inactive. Archiving is low-stakes--it's trivial to undo. Same for removing/adding groups.

/ping @nodejs/ffi in case I'm wrong about all of this.

(The repo has recent commits because I rebased against core master this morning to remove a bunch of vulnerability reports from GitHub. That's when I noticed that there are zero differences between that repo and master. It hadn't been updated since 2017 and it has no commits that aren't in master.)

@nodejs/tsc @nodejs/community-committee

**Comment by cjihrig** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by jasnell** [comment]
SGTM

**Comment by Trott** [comment]
Done.
