### ISSUE TITLE
Request to use netlify on nodejs-ko

### ISSUE THREAD

**Issue by outsideris** [nodejs/admin#411]
In @nodejs/nodejs-ko , we are using GitHub pages and actions for our blog for nodejs news.

We need to build a preview on PR because we missed broken markdown in code review. We will use netlify for the only preview because blog URL is hard to change.

Thanks. https://github.com/nodejs/nodejs-ko/issues/877

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment]
Privileges that need to be granted: https://www.netlify.com/docs/github-permissions/

I'd assume we would enable only for the single repository.

**Comment by nschonni** [comment]
Is the separate repo still needed outside https://github.com/nodejs/nodejs.org/tree/master/locale/ko

**Comment by Trott** [comment]
> Is the separate repo still needed outside https://github.com/nodejs/nodejs.org/tree/master/locale/ko

@nodejs/i18n Is the https://github.com/nodejs/nodejs-ko repo necessary? Or should everything be happening in https://github.com/nodejs/nodejs.org/tree/master/locale/ko and CrowdIn at this point?

**Comment by Trott** [comment]
> > Is the separate repo still needed outside https://github.com/nodejs/nodejs.org/tree/master/locale/ko
> 
> @nodejs/i18n Is the https://github.com/nodejs/nodejs-ko repo necessary? Or should everything be happening in https://github.com/nodejs/nodejs.org/tree/master/locale/ko and CrowdIn at this point?

There's a gh-pages branch on the  https://github.com/nodejs/nodejs-ko so it has a web presence that I imagine most of the other translation repos don't.

**Comment by yous** [comment]
Yes, @nodejs/nodejs-ko translate almost every release post on <https://github.com/nodejs/nodejs-ko>, which is served on separate website (<https://nodejs.github.io/nodejs-ko/>). Also there is a Twitter bot (https://twitter.com/nodejs_ko) for notifications.

**Comment by Trott** [comment]
This all got a year or more out of date and then the GitHub repo was archived in March. I'm going to close this issue.
