### ISSUE TITLE
Code&Learn: Call for session proposals

### ISSUE THREAD

**Issue by christian-bromann** [nodejs/admin#415]
Hey Node Community 👋 

as you might know we are planning a Code&Learn session again at this years Node+JS interactive. The format will be a little bit different. We want every project to participate by proposing collaboration sessions on different topics of the project. The idea is that attendees can either join a collab session proposed by core maintainer of the project or even propose their own session. Before the event we will then filter sessions that have enough participants and a facilitator to run the session. We want to have generally smaller groups of people contributing to a specific area or idea on the project. I already proposed [two sessions](https://github.com/openjs-foundation/code-and-learn/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3AWebdriverIO) for the WebdriverIO project. Sessions topics can be vary from super general like "Contribute a unit test" to super specific like "Node.js + LibUV".

This new format is not set in stone. We appreciate any feedback or suggestion to make this a successful event. So far it seems that it will be held similar as to last years Node+JS Interactive, the morning after the conference before the collab summit. It all depends on how many project members are interested to run a session and how many attendees want to participate.

Looking forward to your proposals and ideas. Cheers!

**Comment by mhdawson** [comment]
@nodejs/n-api I know we already have a workshop at Node+JS Interactive but any interest in proposing a session on building N-API addons?

**Comment by mhdawson** [comment]
@nodejs/n-api one though I had was may one on adding tests for node-addon-api?

**Comment by Trott** [comment]
I'm not the person to prepare such a session, but if there's someone who can prepare it, I'll be happy to help: A session specifically for Windows developers that want to contribute to Node.js. We need more Windows-centric devs in core.
