### ISSUE TITLE
Collaborator Summit - Montreal 2019

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#416]
Hi @nodejs/collaborators,

It's time to plan your trip to Montreal for the Collabor Summit on the 13th and 14th of December 2019 (together with [Node+JS Interactive](https://events.linuxfoundation.org/events/nodejs-interactive-2019/))! We are still putting out a registration link, but in the meantime it's important that you propose any sessions you'd like to present and propose using this [link](https://github.com/openjs-foundation/summit/issues/new?assignees=christian-bromann%2C+evahowe%2C+jorydotcom%2C+keywordnew&labels=Montreal+2019%2C+Collaborator+Summit%2C+Session+Proposal&template=summit-topic-proposal.md&title=Summit+Topic%3A+).

You can find Berlin 2019's agenda for inspiration at https://github.com/openjs-foundation/summit/blob/master/2019-05-Berlin/agenda.md.

**Comment by boneskull** [comment]
should relay this message to the ojsf mailing list(s)

**Comment by boneskull** [comment]
I have twittered it: https://twitter.com/b0neskull/status/1179457849367265281

**Comment by mhdawson** [comment]
One suggestion would be to add some detail on what selecting one of these implies:

- [] Collaborate
- [] Workshop
- [] Talk
