### ISSUE TITLE
Enable Travis for node-addon-api

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#417]
Similarly to #414 enable travis for node-addon-api

Unless there are objections I'll do this late next week.

@nodejs/tsc, @nodejs/community-committee

**Comment by mcollina** [comment]
SGTM

Il giorno ven 4 ott 2019 alle 20:18 Michael Dawson <notifications@github.com>
ha scritto:

**Comment by cjihrig** [comment]
+1 from me.

**Comment by mhdawson** [comment]
Enabled, closing.
