### ISSUE TITLE
Set up Netlify for Pull Request previews for nodejs.org repo

### ISSUE THREAD

**Issue by XhmikosR** [nodejs/admin#422]
Or something else that has the same effect.

Currently one has to pull down the changes locally to see them in action which is far from optimal.

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee @nodejs/website

**Comment by phillipj** [comment]
Couldn't agree more, would love to have previews rather than being forced to run locally and/or ask for screenshots.

SGTM

**Comment by XhmikosR** [comment]
Something to new since I made this issue. Netlify has changed their pricing. Not sure if it will affect us, just throwing it out there.

In theory, we should be OK, at least for starters.

**Comment by targos** [comment]
What are the permissions asked by Netlify?
Is it an OAuth or a GitHub app ?

**Comment by XhmikosR** [comment]
https://www.netlify.com/docs/github-permissions/

**Comment by targos** [comment]
LGTM

**Comment by targos** [comment]
I guess we need to setup a Netlify account for the org. Should it belong to the Build WG?

**Comment by richardlau** [comment]
https://github.com/nodejs/nodejs.dev has some sort of Google Cloud Build staging thing going on. Could that potentially be used? I think @MylesBorins set it up.

**Comment by MylesBorins** [comment]
@richardlau TBH the setup that we have on nodejs.dev is not neccessarily ideal for everyone and is a little bit more hands on then simply installing netlify.

**Comment by targos** [comment]
What about https://github.com/nodejs/admin/issues/422#issuecomment-539369086 ?

**Comment by gengjiawen** [comment]
> I guess we need to setup a Netlify account for the org. Should it belong to the Build WG?

I think it should be more general. since all our doc service may need it.

**Comment by mcollina** [comment]
The Build WG currently manages all Node secrets, so yes, I would say it's the build wg.

**Comment by Trott** [comment]
@nodejs/build

**Comment by joyeecheung** [comment]
I think sending a PR to https://github.com/nodejs-private/secrets to store the credentials would be enough, people who place their public keys in the corresponding folder there would just get the access

**Comment by bnb** [comment]
@joyeecheung I would be happy to send that PR if needed, pending getting the details from the Website WG.

**Comment by MylesBorins** [comment]
I just got previews setup on nodejs.dev using GitHub actions, the nodejs-infrastructure gcp account, and a free tier cloudflare cdn.

I could likely spin this up to do staging previews for .org rather painlessly if folks are interested. With that said it isn't a huge deal to use netlify

**Comment by ovflowd** [comment]
I think this can be closed as we adopted Vercel for previews...
