### ISSUE TITLE
Archive https://github.com/nodejs/nodejs-no

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#424]
As I understand it, all (or at least most) of the https://github.com/nodejs/nodejs-XX (where XX is a language code) repositories are not serving much of a purpose. They are mostly (or entirely) inactive. Translations are now happening in the main repo for the website (https://github.com/nodejs/nodejs.org) and on CrowdIn. I don't think these repositories come into play.

So I'd like to start archiving them, one or two at a time.

/ping @nodejs/i18n @nodejs/nodejs-no  in case I'm wrong about any of the above.

@nodejs/tsc @nodejs/community-committee

**Comment by Trott** [comment]
(No commits have landed in https://github.com/nodejs/nodejs-no for over four years.)

**Comment by gireeshpunathil** [comment]
+1 for archiving, assuming future translation requirements will be accepted / handled in the main repo.

**Comment by eiriksm** [comment]
+1 for archiving. The activity was mostly around "the iojs period", but that is not so relevant any more :)

**Comment by cjihrig** [comment]
+1 for archiving.

**Comment by bnb** [comment]
+1 for archiving all inactive repos. I believe nodejs/nodejs-ko is relatively active, though.

**Comment by Trott** [comment]
Done! Thanks!
