### ISSUE TITLE
Nodejs Interative & Collab Summit

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/admin#425]
I am about to open PR for travel fund request for Collab Summit. Should I mention the ticket cost of Nodejs Interactive in the travel funds or not?
Last time collaborators were given code to register for Nodejs Interactive and also mentioned ticket cost in the travel fund request.

I'm not sure what's the process this time.

@brianwarner @mcollina @keywordnew

**Comment by mcollina** [comment]
We usually do not cover the cost of attending the conference as part of the travel fund. If you are planning to participate in a panel/representing Node, you should seek a free ticket from the organization.

cc @nodejs/tsc @nodejs/community-committee

**Comment by Trott** [comment]
> Last time collaborators were given code to register for Nodejs Interactive and also mentioned ticket cost in the travel fund request.

To the best of my knowledge, there's no code for Collaborators and no need to mention ticket cost or any other cost other than costs for which you are seeking reimbursement.

**Comment by ladyleet** [comment]
Responding here - the foundation will cover tickets for collaborators for the conference. 

While I'm still coordinating internally and working with @keywordnew on rollout this week, feel free to just email me for the code if you are a collaborator ladyleet@nodejs.org.

I am trying to set up registration for Collab Summit this year as well - will let you know when we get that set up.

**Comment by Trott** [comment]
So if Collaborators are getting a code to use to get a ticket at no cost, I guess that means they shouldn't include the cost in their travel fund requests?

**Comment by WaleedAshraf** [comment]
@Trott I think yes. Tracy said the same in this comment: https://github.com/nodejs/admin/pull/437#issuecomment-551387447

**Comment by ladyleet** [comment]
> @Trott I think yes. Tracy said the same in this comment: [#437 (comment)](https://github.com/nodejs/admin/pull/437#issuecomment-551387447)

👍 happy to answer additional questions. im emailing you a code @Trott
