### ISSUE TITLE
enable dependabot

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#430]
I'd like enable dependabot for nodejs/nodejs.org so we can stop manually doing things like https://github.com/nodejs/nodejs.org/pull/2723. That would mean installing it for the org (like we have done for Travis and other things) but only enabling it on the nodejs.org repository (and other repositories where we deem it appropriate). 

Any objections?

Permissions required are:

> Write access to code
> Read access to checks, commit statuses, and metadata
> Read and write access to issues and pull requests

FWIW, dependabot was acquired by GitHub some time ago, in case that helps people's comfort level here.

@nodejs/tsc @nodejs/community-committee @XhmikosR

**Comment by targos** [comment]
SGTM

**Comment by gireeshpunathil** [comment]
+1

**Comment by Trott** [comment]
Installed dependabot for the org and enabled it for nodejs.org repo.

**Comment by ChALkeR** [comment]
SGTM
