### ISSUE TITLE
Where should I submit the Expensify report to?

### ISSUE THREAD

**Issue by starkwang** [nodejs/admin#435]
In our [travel fund documentation](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#reimbursement), it mentions that the member should submit the Expensify report with operations@openjsf.org **ON CC**:

> Once you have uploaded your receipts, please add them to a report and submit it with operations@openjsf.org **on cc**, and the Memo field set to "YOURNAME - TRIPNAME".

But where should I submit the report **TO**? 🤔

**Comment by Trott** [comment]
@brianwarner

**Comment by brianwarner** [comment]
It's fine if operations@openjsf.org is on To: or Cc:, just so long as it gets there somehow.  Thanks!
