### ISSUE TITLE
Space available at Index 2018 in San Francisco on Feb 20 for Node.js use.  

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#44]
Space is available at the [Index 2018 conference](https://developer.ibm.com/indexconf/) in San Francisco on Feb 20 for use by the Node.js community.  This would include  a room for up to ~200 people for either a morning or afternoon session. Space, chairs/tables, power strips, WiFi, AV, and catering will be provided.

While this is in the same venue as the Index 2018 conference it is open to all (ie you do NOT have to be registered at the conference) and there is no charge to attend this part of the event. 

I talked with Mark Hinkle (@mrhinkle) and we came up with this as a suggested agenda:

* Introduction to Node.js Initiatives, working groups and teams (including Community Committee and TSC initiatives) and how to get involved
* End user feedback session (as a way to bolster the work in https://github.com/nodejs/user-feedback)
* Community values working session

@nodejs/tsc, @nodejs/community-committee, @nodejs/user-feedback  how does that sound and would you be able to participate ?

Updated Agenda:

The Node.js community day session is a good opportunity to connect with the Node.js community, learn what is coming up on the technical and organizational side of things, as well as contributing back by providing feedback based on your experience with Node.js. The session will be structured in four parts:

* Introduction to Node.js and the Node.js foundation - led by Mark Hinkle executive director of the Node.js foundation.  **A great way to be introduced to Node.js and the foundation**.

* Introduction to Node.js initiatives, working groups and teams (including Community Committee and TSC initiatives) and how to get involved - led by Michael Dawson (TSC Chair ) and Tierney Cyren (Community Committee Co-Chair). **A great way to learn what's coming in the future for Node.js**.

* End-user feedback session. In person feedback session between Node.js end users and the Node.js end-user feedback team - led by Dan Shaw (user feedback team lead).  **A great way to get involved and contribute back by sharing your experience to make Node.js better**.

* Community values working session - led by Tierney Cyren (Community Committee Chair) and Joe Sepi (Community Committee member).  **A great way to learn and share the values that make Node.js successful**.

Whether you are a Java developer who wants to learn more about Node.js, a developer just starting with Node.js or a long time user, this is a good opportunity to talk and connect with community members.

**Comment by mrhinkle** [comment]
This is great Michael, thanks for securing the space. I'd be glad to help in whatever way is appropriate.

**Comment by jasnell** [comment]
Good to see. I, however, will be unable to participate as I will be in Europe that week.

**Comment by rachelnicole** [comment]
I talked with @bnb and we both really like the intro to initiatives, working groups and teams, and also the Community Values working session. 

What kind of attendees does the conference usually bring in? Would it be worth having a Code & Learn at all?

**Comment by bnb** [comment]
@mhdawson once a schedule is landed, we should make sure to publicize that the event will be happening and emphasize the Travel Fund as a means for collaborators and individual members to attend.

**Comment by joyeecheung** [comment]
I probably won't be able to make it because I have something planned with my family during that time (the Chinese New Year holidays).

**Comment by joesepi** [comment]
I will be there an will be happy to help in any way possible.

@rachelnicole and @bnb - this is a brand new conference, but the focus is developers. You can see more of the tracks they are cultivating here: https://developer.ibm.com/indexconf/sessions/

**Comment by mhdawson** [comment]
@joesepi thanks for jumping in with some additional detail.  One of the options I had discussed with Mark was a Code and learn but we were not sure if we could fit that in with the other suggested items and if we'd have volunteers available to help run it.

**Comment by mhdawson** [comment]
@bnb in terms of publicizing, absolutely.

**Comment by mhdawson** [comment]
@bnb @rachelnicole with one or both of you be able to attend to cover the part where we go through the CommComm initiatives ? 

@Myles you've done a number of the Community Values sessions, wondering if you are available to help with that part ?

**Comment by mhdawson** [comment]
@dshaw wondering if you'd be around to help with the user feedback session ?

**Comment by MylesBorins** [comment]
wrong myles 😄 

Unfortunately I'm going to be in the bay area both two weeks before, and two weeks after the event... which makes it hard for me to attend unfortunately (it will also be my birthday 🎉)

More than happy to discuss how values sessions have been run

**Comment by mhdawson** [comment]
@MylesBorins thanks will follow up with you to do knowledge transfer.

**Comment by mhdawson** [comment]
Issue in user-feedback repo for planning on user feedback session: https://github.com/nodejs/user-feedback/issues/29

**Comment by bnb** [comment]
@mhdawson I confirmed that I'll be able to attend 😃

**Comment by jcasman** [comment]
Asked @mhdawson to answer three Node community questions to help highlight the Node Community Day activities at Index. If you have a chance to push it out (professional contacts, social media, friends), much appreciated: [Three Exciting Node.js Community Topics in 2018](https://dzone.com/articles/three-exciting-nodejs-community-topics-in-2018)

**Comment by joesepi** [comment]
@mhdawson and @bnb: I will be there all 3 days and am happy to help in any way.
Also: talks/speakers are announced but schedule is being finalized.
https://developer.ibm.com/indexconf/sessions/

**Comment by vdeturckheim** [comment]
I'll be in SF on that date, would it make sense to do something regarding security?

**Comment by jchip** [comment]
I'd love to join this session with my team from @WalmartLabs.  Do we need to register for the conference?  Can we join just this part only?

**Comment by mhdawson** [comment]
@jchip the community day is open to all.

**Comment by mhdawson** [comment]
@vdeturckheim part of what we have on the proposed agenda is 

`Introduction to Node.js Initiatives, working groups and teams (including Community Committee and TSC initiatives) and how to get involved.`

If you would like to cover the part on the security WG that would be great.

**Comment by vdeturckheim** [comment]
@mhdawson awesome. I'll prepare something to present, what is the expected format for this?

**Comment by mhdawson** [comment]
@joesepi I'm thinking you might help/lead the session on values.  Let's get together to discuss with @bnb

**Comment by mhdawson** [comment]
@vdeturckheim still need to coordinate on the format.  So far I know that Tierney, Joe, Gibson (nominated as TSC), and myself will be there to cover the TSC and CommComm WGs and initiatives.  I'll arrange a time to discuss together so that we can agree how to best deliver the content.

@rachelnicole any chance you will be able to make it ?

**Comment by mhdawson** [comment]
I've been asked for an outline of the session that can be put up on the Index site and promoted.

This is my suggestion based on discussions so far:

The Node.js community day session is a good opportunity to connect with the Node.js community, learn what is coming up on the technical and organizational side of things, as well as contributing back by providing feedback based on your experience with Node.js. The session will be structured in four parts:

* Introduction to Node.js and the Node.js foundation - led by Mark Hinkle executive director of the Node.js foundation.  **A great way to be introduced to Node.js and the foundation**.

* Introduction to Node.js initiatives, working groups and teams (including Community Committee and TSC initiatives) and how to get involved - led by Michael Dawson (TSC Chair ) and Tierney Cyren (Community Committee Chair). **A great way to learn what's coming in the future for Node.js**.

* End-user feedback session. In person feedback session between Node.js end users and the Node.js end-user feedback team - led by Dan Shaw (user feedback team lead).  ** A great way to get involved and contribute back by sharing your experience to make Node.js better**.

* Community values working session - led by Tierney Cyren (Community Committee Chair) and Joe Sepi (Community Committee member).  **A great way to learn and share the values that make Node.js successful**.

Whether you are a Java developer who wants to learn more about Node.js, a developer just starting with Node.js or a long time user, this is a good opportunity to talk and connect with community members.




@rachelnicole if you can make it I'll update the 'led by' for the second part to include you
@nodejs/collaborators if anybody else is going to be in SF or at the conference and are available to participate/help out that would be great, just let me know.

**Comment by rachelnicole** [comment]
@mhdawson unfortunately I am unable to attend

**Comment by mhdawson** [comment]
@rachelnicole sorry to hear that, but thanks for confirming.

**Comment by mhdawson** [comment]
@jchip reading through supplemental information I found this:

`
•	Option 2 - Promotion Code: CD1NODEJS Register to attend our Community Day Meeting only. There’s no cost to attend, but you must register. 
`

So free to attend but use that promocode to register

**Comment by mhdawson** [comment]
Also just noted, that if people are planning to attend the conference there is a second promo code for the Node.js community being made available because we are taking part in the community day.  

`
•	Option 1 - Promotion Code*: IND18HALF2 Join our Community Meeting on Tuesday, February 20th and stay for Index Conference on Wednesday and Thursday. This code provides you, as our guest, a special 50% off rate of $175 for Index. 
*Please note: Promotion code valid through 11:59PM Pacific, February 9th. 
Code may not be applied retroactively to existing registrations. Government Owned Entities are not eligible for this discount.
`
The ask is that the code be used by our community members and not share on social media.

**Comment by mhdawson** [comment]
@vdeturckheim can you send me your email (through the email listed on my github profile) so that I can add you to the invite to discuss the WGs/initiatives section.

**Comment by vdeturckheim** [comment]
@mhdawson done :D

**Comment by WaleedAshraf** [comment]
I'll be there for all 3 days, actually for the whole week. Let me know if I can be of any help.

**Comment by mhdawson** [comment]
Forwarded on abstract since there were no comments.

**Comment by mhdawson** [comment]
@WaleedAshraf sounds good.  I'll talk to Tierney to see if there is anything specific beyond helping by being there as a CommComm representative and connecting with the attendees that you can help out with.

**Comment by Trott** [comment]
> Whether you are a Java developer who wants to learn more about Node.js, a developer just starting with Node.js

Is that supposed to say "JavaScript" instead of "Java"?

**Comment by mhdawson** [comment]
I meant Java as there will be a number of them at the conference. But maybe it should have been Java or Javascript developer.

**Comment by mhdawson** [comment]
Late breaking news.  I just received an even better promo code for the projects supporting the community day.  Am amazing 100% off !

Follow this link:  https://www.ibm.com/events/wwe/indexconf/indexconf18.nsf/Registration.xsp?open 
Select "Attendee" as your Registration Type 
Enter your Registration Promotion Code*: IND18FULL
*Restrictions: 
Promotion Code expires February 12th, 11:59PM Pacific 
GOE's not eligible
Code may not be applied retroactivity to existing reservations

**Comment by mhdawson** [comment]
@ZibbyKeaton I've not been forwarded any numbers.  I can ask if there is a way to get that info.

**Comment by ZibbyKeaton** [comment]
@mhdawson I've had a few folks ask me about when the community day starts and I'm not seeing it on the site or in my emails. Do you happen to know when it will start and roughly how long it will last?

**Comment by mhdawson** [comment]
Event was held, closing.
