### ISSUE TITLE
codecov for the GitHub org

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#441]
@bcoe has been working on getting Windows coverage included in coverage.nodejs.org. He's intending to use codecov to merge Linux results with Windows results. So there's an application request for that in the nodejs GitHub org right now. I'm inclined to approve it, but want to give @nodejs/tsc and @nodejs/community-committee an opportunity to weigh in.

**Comment by targos** [comment]
We already seem to have the Codecov GitHub app installed in the org:

![image](https://user-images.githubusercontent.com/2352663/68686999-ce104100-056c-11ea-9f2d-326185607071.png)

![image](https://user-images.githubusercontent.com/2352663/68687021-d799a900-056c-11ea-8652-212b77a4b14f.png)

Don't we just need to enable it for the repo that `coverage.nodejs.org` uses?

**Comment by Trott** [comment]
Guess someone authorized it some time between the four days ago when it was requested and today. :-D Might have even been me. OK, let's consider this an FYI then. I'll close. Thanks.
