### ISSUE TITLE
GitHawk

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#442]
A request for enabling GitHawk came from @AliSawari but I don't have any context and can't find anything searching the issue tracker. Leaving a note here in case they or anyone else want to make the case for GitHawk. In the meantime, I'm doing to use the "deny" button and another request can always be submitted if the org decides to enable it. Thanks!  

/ping @nodejs/tsc @nodejs/community-committee

**Comment by Trott** [comment]
Closing for now, but feel free to re-open (or request it be re-opened in a comment if the button is unavailable) if this is a conversation we should have at this time! Thanks!

**Comment by AliSawari** [comment]
hey there @Trott 
I submitted this Request because I wanted to comment on and review issues related to our translation team, @nodejs/nodejs-fa right away from my phone! because i spend a lot of time in the way to work LOL

Unfortunately, GitHub does not have an official client for smart phones
that is why Im using GitHawk. it is a free github client made for iOs

**Comment by richardlau** [comment]
> Unfortunately, GitHub does not have an official client for smart phones

They have one in beta:
https://github.blog/2019-11-13-universe-day-one/#mobile

**Comment by AliSawari** [comment]
@richardlau Thank you
I did search App Store for it before, didn't find that specified app
I will surely search again, thanks again for informing

**Comment by AliSawari** [comment]
Looks like we have to wait for it to come out... :neutral_face:

**Comment by bnb** [comment]
Y

**Comment by ljharb** [comment]
Until then, the web works fine on a phone, no?

**Comment by AliSawari** [comment]
yes it does, but most of the time I'd end up forced to switch to Desktop Version which again, you have to zoom in to click buttons

**Comment by ljharb** [comment]
For which features? GitHub recently updated the mobile view to have a lot of the desktop features that were previously missing. I think suggestions is the big one that's still not there tho.

**Comment by AliSawari** [comment]
I have reconsidered using GitHub Official website on my phone. thanks for noticing everyone!  :wave: 
@Trott @ljharb . you may close
