### ISSUE TITLE
Node.js Foundation Membership

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/admin#445]
Currently, if you try to renew "Node.js Foundation Membership", it shows this message. I think it's because of openjs-foundation merge. Putting it here so that it can be fixed later and also update in the [TRAVEL_FUNDS](https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#requirements) doc.

![image](https://user-images.githubusercontent.com/8335457/69328169-0f7cac80-0c4f-11ea-8da2-0c00437b7bdd.png)

**Comment by Trott** [comment]
I don't think Node.js Foundation membership is really a thing anymore. And the Travel Fund will be moving to the OpenJS CPC. So this will hopefully self-resolve in the next month or so.

**Comment by WaleedAshraf** [comment]
I'm okay with closing this issue. Would be good if we can add to some "things to do" list when we move travel fund to CPC. I'm not sure if there is an issue keeping such a list or something similar,

**Comment by bnb** [comment]
Going to close this since there's no such thing as the Node.js Foundation anymore, and the OpenJS Foundation membership work is done through the CPC.
