### ISSUE TITLE
Document member onboarding

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/admin#45]
Any training, logs, and documents that need to be supplied to Moderation team members should be in an easy to find place, and likely with a Real Human ™️ hosting a short meeting to make sure they are set up for success.

**Comment by Trott** [comment]
@nodejs/moderation Should this remain open? If so, can we get a checklist of tasks or something like that?

**Comment by ryanmurakami** [comment]
Looks like this is partially referenced in #97, but we probably want a document or directory in `moderation` with the resources required.

**Comment by Trott** [comment]
This *seems* to be resolved by https://github.com/nodejs/moderation/blob/master/ONBOARDING.md. But if I"m wrong, feel free to re-open (although this probably more appropriately belongs in the moderation repo at this point?).
