### ISSUE TITLE
archive nodejs/members respository

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#452]
Now that OpenJS Foundation is a thing, it seems like the https://github.com/nodejs/members repository is superfluous. I propose archiving it. We can always unarchive it if it turns out we need it after all. Archiving it will also help discourage people from trying to renew their Node.js Foundation membership, which I don't think they can actually do right now.

@nodejs/tsc @nodejs/community-committee

**Comment by cjihrig** [comment]
Unless someone has a reason to keep it, +1.

**Comment by mcollina** [comment]
+1
Il 18 dic 2019, 16:13 -0500, Colin Ihrig <notifications@github.com>, ha scritto:

**Comment by WaleedAshraf** [comment]
+1

**Comment by ahmadawais** [comment]
LGTM. +1

**Comment by Trott** [comment]
Archived. Thanks!

**Comment by ChALkeR** [comment]
Belated +1.
