### ISSUE TITLE
Create 2 new repositories for build wg - jenkins config

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#464]
The build WG would like to get the ok to add 2 new repositories that we'll use to keep a history of the configuration of the jobs within jenkins.

The repos we want to create are:

 * jenkins-config-test
 * jenkins-config-release

More details on the plans are in: https://github.com/nodejs/build/issues/2133

**Comment by Trott** [comment]
+1. FWIW, approval is not needed to create new repositories. 

What teams will have write or admin access?

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by sam-github** [comment]
Initially, they will be private repos.

They will be readable by nodejs/build, and writable by a jenkins backup cron job.

Intention is that when we validate that no sensitive information is in the build job XML, they become public, readable by all, but only writable by the jenkins backup cron job.

**Comment by sam-github** [comment]
+1

**Comment by bnb** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by bnb** [comment]
Been 6 days with no -1s or -0s. I’d like to assert that these can go ahead and be created.

**Comment by mhdawson** [comment]
@bnb agreed. Created the repositories.

@rvagg, @sam-github what teams should we give access to the repo? 

I'm thinking maybe build for jenkins-config-test and build-infra for jenkins-config-release as a start?

We also need to likely add some user so that the automation can push the updates.  What do we need to add for that?

**Comment by sam-github** [comment]
I added @nodejs/jenkins-admins to nodejs/jenkins-config-test and @nodejs/jenkins-release-admins to nodejs/jenkins-config-release. Those are the groups that can already see the respective jenkins config right now, so it doesn't expose anything new.

@rvagg is in both, so he can add any other groups he deems reasonable.
