### ISSUE TITLE
unblock translation process

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#469]
See https://github.com/nodejs/nodejs.org/issues/2906 by @alexandrtovmach:

> @nodejs/website @nodejs/i18n
> We need to unblock translation process here [nodejs/i18n#72](https://github.com/nodejs/i18n/issues/72). For that I need github **personal access token** generated under nodejs organization with next scopes:
> ![image](https://user-images.githubusercontent.com/28801003/72880957-8cd4a400-3d08-11ea-844c-399fcc579689.png)
> 
> Token will be used here:
> ![image](https://user-images.githubusercontent.com/28801003/72881337-43388900-3d09-11ea-84c7-243087b9474c.png)
> 
> Please help me with that

**Comment by targos** [comment]
In the screenshot, it says "set up integration via access token only if you have limited or no access to the GitHub repository".
What would be the other way to set it up?

**Comment by ljharb** [comment]
On behalf of someone else who has no access to manage integrations, perhaps

**Comment by bnb** [comment]
Theoretically an org owner should be able to do this?

Additionally, perhaps this merits @nodejs-github-bot being the "owner" of this integration so it's not tied to someone who may or may not be an org owner in the future?

**Comment by bnb** [comment]
ping @nodejs/i18n does that unblock you?

**Comment by alexandrtovmach** [comment]
Thanks everyone for help, I'm finally unblocked and this issue can be closed
