### ISSUE TITLE
Setup a bot account for Node.js org

### ISSUE THREAD

**Issue by gengjiawen** [nodejs/admin#471]
I am thinking add auto doc push for node-addon-api/ https://github.com/nodejs/node-addon-api/blob/cb498bbe7f8aa601e95c7946df3db6dedf15f709/package.json#L245 using https://github.com/JamesIves/github-pages-deploy-action. But this requires token https://github.com/JamesIves/github-pages-deploy-action#required-setup. Thoughts ?

**Comment by ryzokuken** [comment]
can't this be done via CI?

**Comment by nschonni** [comment]
There is one https://github.com/nodejs-github-bot but I believe it is only used for Docker-node right now

**Comment by gengjiawen** [comment]
> can't this be done via CI?

Not sure which you mean, I intend to make auto push doc using github CI. But it requires token to push to `gh-pages` branch.

**Comment by gengjiawen** [comment]
@Trott Can you push this a little forward.

**Comment by mmarchini** [comment]
@gengjiawen I don't think you need a bot token for this. Is this the workflow you're looking for?

1. Trigger Action when a commit is pushed to `master`
2. The action will run `npm run doc`
3. The result from above will be published to GitHub Pages

If that's the case, you can do it with `GITHUB_TOKEN` by pushing the result from `npm run doc` to https://github.com/nodejs/node-addon-api/tree/gh-pages.

**Comment by gengjiawen** [comment]
I don't want `GITHUB_TOKEN` bind to personal account, it may cause management or other security issues.

**Comment by mmarchini** [comment]
GITHUB_TOKEN is not binded (or bindable) to personal accounts. Is the idea to publish the docs _outside_ the nodejs org?

**Comment by gengjiawen** [comment]
> GITHUB_TOKEN is not binded (or bindable) to personal accounts. Is the idea to publish the docs _outside_ the nodejs org?

Not out the nodejs org. Looks `GITHUB_TOKEN` is a good solution. I will give it a  try.

**Comment by MylesBorins** [comment]
We can make an ssh key for the specific repo fwiw.

Here's an example action for deploying to gh_pages

https://github.com/tc39/proposal-module-attributes/blob/master/.github/workflows/publish.yml

In this case we setup a deploy key for the specific repo, generated with ssh-keygen

https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

**Comment by gengjiawen** [comment]
Finished: https://github.com/nodejs/node-addon-api/pull/691.

Any way I can live view the site. I know how to do this on gitlab. Not sure how it works on github.

**Comment by gengjiawen** [comment]
Ok, find a preview one: https://cdn.statically.io/gh/gengjiawen/node-addon-api/gh-pages/index.html

but the url looks not so official.

**Comment by nschonni** [comment]
You need to turn on the GitHub pages in the Settings for the repo. This might help https://pages.github.com/

**Comment by gengjiawen** [comment]
My looks like this, but it's (http://www.gengjiawen.com/node-addon-api/) a 404
![image](https://user-images.githubusercontent.com/3759816/77825720-2d4ea680-7146-11ea-87f3-ee0e64882253.png)

**Comment by gengjiawen** [comment]
I see, I have choose a theme.

**Comment by gengjiawen** [comment]
> Here's an example action for deploying to gh_pages
> 
> [tc39/proposal-module-attributes:.github/workflows/publish.yml@`master`](https://github.com/tc39/proposal-module-attributes/blob/master/.github/workflows/publish.yml) [](/tc39/proposal-module-attributes/blob/HEAD@{2020-03-20T00:56:14Z}/.github/workflows/publish.yml)
> 
> We used a deploy key and action secret to do auth. Generated a key with ssh-keygen. Public key is used for deploy key as documented here. The private key is an encrypted secret. I then deleted the key locally.
> 
> [developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys](https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys)
> 
> [help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets](https://help.github.com/en/actions/configuring-and-managing-workflows/creating-and-storing-encrypted-secrets)

You can try this way without generating any key, super easy.

Thanks all.
