### ISSUE TITLE
Election for the Voting Representative for the OpenJS Cross-Project-Council

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#472]
Hi fellow @nodejs/tsc and @nodejs/community-committee ,

It’s time we elect our new Cross-Project-Council voting representatives for next term which starts on April 1st 2020. The current ones are @joesepi and me.

I propose we follow the same pattern we did last year with the TSC electing a representative and the CommComm electing one (see https://github.com/nodejs/admin/issues/316).

We need to have elected our new representatives by the 31st of March, therefore I propose the following timeline:

March 9th Call for nominations for both CPC representatives
March 16th Close nominations and open balloting for CPC representative
March 23rd Close balloting and announce CPC representative
March 23rd- Handover
April 1st Transition complete

As chairs of each committee, I kindly ask @mhdawson and @bnb to coordinate the nominations and balloting for the TSC and CommComm.

Please note the expectations of the voting CPC representative:
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#voting-members

Also note: any member of the Node.js org can participate in the Cross Project Council as a regular member.
https://github.com/openjs-foundation/cross-project-council/blob/master/CPC-CHARTER.md#regular-members
Similar to the practices in Node.js, the CPC follows the consensus seeking model and there is little difference between a voting rep of a project and a regular member. Becoming a regular member could be a good way to get involved if one is unsure of running for a voting member.

**Comment by joesepi** [comment]
If anyone has any questions about what it's like to participate as a member of the CPC, please don't hesitate to reach out to any of us. My DMs are open and you can find me on Slacks.

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
+1. Also happy to facilitate the CommComm vote.

**Comment by mhdawson** [comment]
Unless I hear objections before then I'll open the call for nominations on the TSC side on Monday.

**Comment by joesepi** [comment]
I think it should also be made clear that if anyone is considering running for the role but the timing of the weekly meetings is an issue -- there is talk of reconsidering the meeting times as new people come on board. Don't let that be a blocker.

**Comment by mhdawson** [comment]
Issue opened in the TSC repo.

**Comment by mcollina** [comment]
As per https://github.com/nodejs/TSC/issues/835#issuecomment-602889188, I'll keep serving as Voting Representative for the @nodejs project for the next term.

**Comment by joesepi** [comment]
As per https://github.com/nodejs/community-committee/issues/586, I'll keep serving as the Voting Representative for the @nodejs project for the next term.

**Comment by joesepi** [comment]
Closing this issue as elections have concluded. Thanks all.
