### ISSUE TITLE
Archive commit-queue repository

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#473]
This should be super-duper uncontroversial given the conversation at the end of the only issue ever opened in that repository. I'm moving the conversation to the build repository.

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee @nodejs/commit-queue

**Comment by jasnell** [comment]
SGTM

**Comment by bnb** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by mmarchini** [comment]
+1

**Comment by Trott** [comment]
Done.
