### ISSUE TITLE
New repos for sample ci configs

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#477]
The package maintenance team would like 2 new repos to maintain sample CI configs for using Travis and Github actions.

See: https://github.com/nodejs/package-maintenance/issues/321

The team has made recommendations in terms of what Node.js versions to test on, and would like to provide ci configs which support those recommendations.

The repos we'd like are:

  * nodejs/ci-config-travis
  * nodejs/ci-config-github-actions

**Comment by mhdawson** [comment]
The discussion ended up with using a separate repo for each type of ci so that

* we could have different teams maintaining the repos
* some ci's only seem to allow an org/repo reference as opposed to a path within the repo.

**Comment by mhdawson** [comment]
@nodejs/tsc would be good to get some approvals on this.

**Comment by mhdawson** [comment]
@nodejs/community-committee ping as well.

**Comment by richardlau** [comment]
> 
> 
> @nodejs/tsc would be good to get some approvals on this.

It might be nice but technically you don't need any approvals -- just no objections in a 72 hour period: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
@richardlau I understand that, but would like a few +1's anyway.

**Comment by mmarchini** [comment]
+1

**Comment by nschonni** [comment]
Wouldn't it be better to just work with their docuementation teams to improve their official docs like https://github.com/travis-ci/docs-travis-ci-com/edit/master/user/languages/javascript-with-nodejs.md

**Comment by dominykas** [comment]
We've tried reaching out to see if the defaults can be changed, and we did get some traction in the right direction, but this is broader than just that, e.g. we want shareable and automatically updatad configs to run tests in all LTS versions since 8, or all versions that ever existed - depending on your support policy.

We also want to lower the burden on maintainers to not have to keep that up to date, esp. if they have a lot of repos.

I also think that the node community would probably be better in deciding and maintaining and advocating the options available, letting CI providers focus on what they do best.

**Comment by mhdawson** [comment]
Tagged for agenda as FYI, if no objections after meeting time will consider approved and move to create.

**Comment by bnb** [comment]
Huge +1. I am also happy to help maintain GitHub Actions CI templates since I’ve been working with them quite a bit lately ❤️

**Comment by mhdawson** [comment]
Should have taken this off the agenda as FYI complete

**Comment by mhdawson** [comment]
The repos have been created, closing.  The maintainers will be managed through the ci-config-travis-maintainers and ci-config-github-actions-maintainers teams.  Initially I've just added @dominykas to that list.  We have an action to document more governance for the package maintenance team and we'll include in that how the two maintainer teams will be managed.

**Comment by ljharb** [comment]
I’d like to be on the Travis list.
