### ISSUE TITLE
Disable dependabot on nodejs/node-v8

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#478]
Apparently dependabot is enabled by default on repositories now. Since the repository is a "mirror" of `nodejs/node` it makes no sense having the bot enabled there.

Ref: https://github.com/nodejs/node-v8/pull/151
cc @targos

**Comment by ljharb** [comment]
To disable it, go to https://github.com/nodejs/node-v8/network/alerts and uncheck "automated security updates".

**Comment by targos** [comment]
Done
