### ISSUE TITLE
Conflict management training for Moderation team and collaborators

### ISSUE THREAD

**Issue by hackygolucky** [nodejs/admin#48]
I've done quite a bit of research and I've whittled it down to two types of options to account for our global collaborator base:

1. [Self-paced online course in Udemy](https://www.udemy.com/conflict-management-in-the-workplace/)
    - pros: at your own pace, very text-focused so more likely to translate to other languages than an English-based video training
    - cons: Not as robust, not interactive with other Node.js collaborators to contextualize the learning
2. Distributed, online video training with a conflict management training team. Option for further advisement on specific conflicts(that are sort of a step below requiring arbitration but have been escalated)
    - pros: very robust, team of experts who will actively cater to our context
    - cons: likely much more $$

The plan would be to see which program feels effective but also reasonable for Moderation team members and collaborators to learn, and then build the proposal/budget request for the Node.js board to allocate funding.

**Comment by gibfahn** [comment]
Maybe this doesn't have to be an either-or decision. 

`1` sounds like a good starting point, we can try to have the online course as standard for all moderation team members, and look at `2` in parallel.

So these for goals/aims:
- Have the online course for Moderation team members as standard
- Look at the in-person training separately, maybe as a one-off

**Comment by Trott** [comment]
The board has conditionally approved conflict management training but @mrhinkle has to do some follow-up before we can move forward with it.

**Comment by refack** [comment]
האם זה יצא לפועל?
אם כן האם הצוות משתמש בידע בנ"ל לטובת האירגון?

**Comment by ryzokuken** [comment]
@refack I believe you planned to write this comment in English? 😄

**Comment by Trott** [comment]
This seems to have sort of run its course. If there's more to be done here, it will probably have to involve CPC or the OpenJS Foundation board at this time. If I'm wrong, feel totally free to re-open. Just trying to tidy up the issue tracker a little bit.
