### ISSUE TITLE
Call for Volunteers for the OpenJS Foundation Code of Conduct Panel

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#480]
Hey @nodejs/moderation,

We are looking for volunteers for the OpenJS Foundation Code of Conduct Panel (CoCP).
The focus of the CoCP is to coordinate cross-project CoC policies and enforcement, as well as providing an escalation path.  You can find a wider definition at https://github.com/openjs-foundation/cross-project-council/blob/master/FOUNDATION_CODE_OF_CONDUCT_REQUIREMENTS.md#escalation. 

Here is the original issue: https://github.com/openjs-foundation/cross-project-council/issues/469

It would be fantastic if @nodejs/moderation could elect/nominate/volunteer a member for that team!

Thanks!

**Comment by ljharb** [comment]
As a member of @nodejs/moderation and a CPC member, I'm happy to volunteer to be on that panel, if there's no objections from any stakeholders.

**Comment by benjamingr** [comment]
Hey I would also be happy to volunteer if it makes sense.

**Comment by mcollina** [comment]
We can provide one volunteer:

> each top-level project may optionally provide 1 member

How would you like to run the election? Can the moderation team coordinate an election like we elect our voting representative?

**Comment by ryanmurakami** [comment]
We can do the election internally on the moderation team slack. I'll bring this up there and then report back.

**Comment by benjamingr** [comment]
I'm fine with @ljharb taking this - was just trying to help. Plenty of other places that help can go where we miss volunteers.

I appreciate the will to have a vote and the fact you are taking this seriously and with respect.

**Comment by mcollina** [comment]
Are there any objection to nominate @ljharb for this position?

**Comment by mcollina** [comment]
No objection, @ljharb would be our representative for the this term.
