### ISSUE TITLE
Archive https://github.com/nodejs/perfetto-nodejs-wip?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#481]
I would like to archive https://github.com/nodejs/perfetto-nodejs-wip. It has not had a commit in about 10 months (until I rebased just now). If it ever becomes active again, we can unarchive it. @nodejs/tsc @nodejs/community-committee @kjin

**Comment by mmarchini** [comment]
cc @nodejs/diagnostics

**Comment by mhdawson** [comment]
Unless @kjin indicates otherwise +1. We can always un-archive if the effort is revived.

**Comment by jasnell** [comment]
No objection to archiving right now but I do hope to get back to this by the end of the year.

**Comment by bnb** [comment]
No objection. Also pre-emotive +1 to unarchive when @jasnell or anyone else starts working on it again.

**Comment by mcollina** [comment]
No objection

**Comment by Flarna** [comment]
No objection

**Comment by BridgeAR** [comment]
No objection

**Comment by Trott** [comment]
Archived!
