### ISSUE TITLE
Google Season of Docs

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#483]
The 2020 initiative has been started. I think we should get involved

https://groups.google.com/forum/#!topic/season-of-docs-announce/x04Gl7D4dm8

**Comment by codeekage** [comment]
Hello @MylesBorins, Please, ar you still following up on this? I'm happy to help where I can.

**Comment by MylesBorins** [comment]
Applications open April 13th and Close May 4th. I can work with @brianwarner on the initial bits of the application

**Comment by codeekage** [comment]
Hello @MylesBorins please, are there any updates on this?

**Comment by MylesBorins** [comment]
@brianwarner can you please fill out the form found at https://docs.google.com/forms/d/e/1FAIpQLSfW36sFci3s51hFtJSZ_V2FcaMXJ-uCig84ynnn9ezoe9H_MQ/viewform

ping me if you need answers to questions

**Comment by brianwarner** [comment]
I realized this is still open, and wanted to give the update that we are participating. The application is here: https://github.com/openjs-foundation/cross-project-council/tree/master/mentorship/2020/google-season-of-docs

This issue can probably be closed.
