### ISSUE TITLE
Remove automation teams and archive the automation repo

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#488]
As explained in https://github.com/nodejs/Release/issues/547#issuecomment-597098210

> Yes, so far I think most automation projects are maintained by individuals who have access and the commit access is not granted with teams - automation-collaborators is more like "TSC/TSC emeritus who also spend time on automation" (then they already have commit access to these repos anyway), rather than "automation team members who are given commit access to these repos".

> Also based on the activity of automation team, I think it probably makes more sense to disband it now in favor of smaller teams for individual projects. We don't have meetings over there, the gitter channel is not active, and a lot of the work done in the automation projects are by Node.js collaborators who are not in that team anyway.

The automation team was created so that we can ping a group of people for work/reviews/ideas about automation, but it is too big and rarely used at this point. Instead we tend to just open issues/PRs in https://github.com/nodejs/node-core-utils (which is somewhat like a mono repo now where new tools are being added) where the we talk about more concrete ideas and work on actual code.

I think it's time to remove the following teams

- @nodejs/automation 
- @nodejs/automation-admins 
- @nodejs/automation-collaborators 

And just assign collaborators to different projects when necessary - or when the team grows big enough, create teams for each project. So in addition I propose to create

- @nodejs/node-core-utils

To manage https://github.com/nodejs/node-core-utils 

In addition I think it's also time to archive https://github.com/nodejs/automation - it was good for what we tried to do back then but now most of the activities happen in node-core-utils.

cc @nodejs/tsc

**Comment by mmarchini** [comment]
+1 on deleting these teams and on creating a ncu team

**Comment by bnb** [comment]
+1

**Comment by codebytere** [comment]
+1

**Comment by Trott** [comment]
Should https://github.com/nodejs/node-auto-test be archived as well?

**Comment by richardlau** [comment]
> 
> 
> Should https://github.com/nodejs/node-auto-test be archived as well?

I think we should keep it. I believe @mmarchini has used it recently to try out some GitHub Actions related things and it would be the ideal place to trial any work towards a commit queue.

**Comment by mmarchini** [comment]
+1 on keeping node-auto-test

**Comment by joyeecheung** [comment]
nodejs/node-core-utils has been created a while back. I have archived the automation and deleted the automation teams.
