### ISSUE TITLE
archive ecmascript-modules fork?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#489]
Doesn't look like much is happening with https://github.com/nodejs/ecmascript-modules. Can we archive it?

I'm going to synch it up with the main repo now, mostly to silence GitHub warnings about minimist.

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by ljharb** [comment]
cc @nodejs/modules-active-members

**Comment by MylesBorins** [comment]
IMHO it can be archived

**Comment by ljharb** [comment]
Seems reasonable, now that ESM is unflagged in node 13. There's a few open PRs (@guybedford, @mathiasbynens) and some open issues (@coreyfarrell, @jkrems, @geoffreybooth, @smotaal), but presumably those could be closed, or transferred into nodejs/node?

**Comment by jkrems** [comment]
I’d be surprised if anything there is still relevant. +1 for archiving it.

**Comment by jkrems** [comment]
I’d be surprised if anything there is still relevant. +1 for archiving it.

**Comment by bnb** [comment]
+1 if modules folks thinks it's fine, which they seem to.

**Comment by GeoffreyBooth** [comment]
Fine by me. I think the issues should get migrated somewhere though, either the main Node repo or the modules repo? I guess the PRs could get migrated to the Node repo or just archived?

**Comment by mhdawson** [comment]
+1 based on modules team indicating its a good idea

**Comment by jkrems** [comment]
> I think the issues should get migrated somewhere though

I don't remember us ever looking at them and we're not deleting the repo or taking any other irreversible action. If somebody wants to actually continue any of the issues, they either (a) have already done it and the ecmascript-modules ones is an inactive dupe or (b) can always do it in the future.

**Comment by MylesBorins** [comment]
all issues and PRs are currently closed. I believe those get maintained
during archiving, which should be sufficient.

**Comment by Trott** [comment]
Archived.
