### ISSUE TITLE
Changing name of localization team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#491]
Per https://github.com/nodejs/i18n/issues/219#issuecomment-608949928 and subsequent comments, I'd like to remove the existing @nodejs/translators team (which I think was just created very recently, and change the name of @nodejs/localization to @nodejs/translators 

Someone please say something if this is a problem. Thanks!

@nodejs/community-committee @nodejs/tsc

**Comment by alexandrtovmach** [comment]
Yeah, sounds great!!! If it's possible could you also add me as admin for this team, so I can organize stuff?
@benjamingr any objections?

**Comment by alexandrtovmach** [comment]
We're already done with guidelines, and would like to make a few announcements for all teams, and resolving this issue will be very helpful 😉

**Comment by Trott** [comment]
* Moved nodejs-ko from existing translators to existing Localization
* Added write access for Localization team to i18n repo
* Deleted existing translators team
* Renamed Localization team to translators
* Made @alexandrtovmach a maintainer of the team. (The other maintainer is @benjamingr.)

One change is that the new translators team is not a subteam of i18n the way the old team was (because it's already a subteam of `@nodejs/coreworkinggroups` and I didn't want to change that. Hopefully that's not a problem? Or we could open another issue to move i18n to be a subteam of coreworkinggroups and then translators as a subteam of that.

**Comment by Trott** [comment]
> * Made @alexandrtovmach a maintainer of the team. (The other maintainer is @benjamingr.)

General note that I sometimes forget to share with new maintainers of parent teams like this, and might as well share more widely as a GitHub comment: Only maintainers are direct members. Everyone else gets their membership on the team by being a member of a subteam (which are the 30+ translation teams like `nodejs/nodejs-ko` and `nodejs/nodejs-ar`). As a general rule, please don't add members directly to translators. It makes things difficult later on when we're cleaning up members in the org. Exceptions for maintainers is fine (and usually necessary) and I imagine adding the crowdin bot or something might be necessary depending on what you're doing.

**Comment by alexandrtovmach** [comment]
@Trott Thank you so much
