### ISSUE TITLE
Install github dco app for use in ci-config-travis and ci-config-github-actions repos

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#492]
For the new ci-config repos requested by the Package-maintenance team I'd like to enable the DCO github app https://github.com/apps/dco to enforce sign offs for the commits.

**Comment by mcollina** [comment]
sgtm

**Comment by mhdawson** [comment]
Discussed in TSC meeting 16 April 2020 and agreed could proceed if no objections in 72 hours: https://github.com/nodejs/TSC/blob/master/meetings/2020-04-16.md#nodejsadmin

**Comment by mhdawson** [comment]
It requires these permissions:

Read access to code
Read access to members, metadata, and pull requests
Read and write access to checks

Will install for only the 2 specified repositories.

**Comment by joesepi** [comment]
SGTM

**Comment by BethGriggs** [comment]
+1

**Comment by mhdawson** [comment]
Installed for the 2 specific repositories.
