### ISSUE TITLE
archive nodejs/wishlist

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#495]
The https://github.com/nodejs/wishlist repo was never started in the direction it was intended to and the person who started it has confirmed they're not going to be able to prioritize that over other work.

**Comment by WaleedAshraf** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
This has been open for a week with no -1s. Archived.
