### ISSUE TITLE
create a "how to run a Node.js Working Group meeting" page

### ISSUE THREAD

**Issue by pmuellr** [nodejs/admin#5]
I've cat-herded a few Node.js working group meetings, figured I should write down how I do this, for other folks, and to fine-tune how we do these.

Not intended to be "the one and only way", more of a starter kit if you don't have another process that already works for your WG.

Examples here:
- previous API WG Meeting - https://github.com/nodejs/api/issues/9
- future API WG Meeting - https://github.com/nodejs/api/issues/11

Presumably this becomes a wiki page, or md file, in this repo.

**Comment by pmuellr** [comment]
Think I'll write this out as an md file in a branch, which we can decide what to do with when it's publishable.

**Comment by Qard** [comment]
:+1: Some guidance on this stuff would be much appreciated. You've been a big help with keeping the tracing working group on track, a glimpse into your process would be quite insightful. :smile_cat:

**Comment by pmuellr** [comment]
@nodejs/collaboration I just pointed someone to my PR https://github.com/nodejs/collaboration/pull/6 , for guidance on how to run a working group meeting.  Realized I never pushed to get this merged.

Can someone take a look?

Is this repo/group still alive, or has it moved somewhere else?
