### ISSUE TITLE
Self-nomination: Social Team

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#500]
I'd like to self-nominate myself as a member of the [social team](https://github.com/nodejs/admin/blob/master/social-team.md) ❤️

**Context:** I genuinely love working around open-source and communications, and the social team is a good way to do that for Node.js. Having the project drive the direction of our social accounts is something I've been keen on for years, and I'm incredibly excited to see it come to fruition. I'm eager help improve the state of content going out, helping to ensure that what's going out is helping the project, the community, and the ecosystem be more welcoming, equitable, and approachable.

**Time commitment:** I'll be able to commit as much time as is needed to this.

If this process seems unfamiliar, please see the membership section of the [social-team.md](https://github.com/nodejs/admin/blob/master/social-team.md#membership) doc ❤️

**Comment by bnb** [comment]
I suppose I should ping @nodejs/tsc and @nodejs/community-committee on this since it requires +1s with no -1s.

**Comment by addaleax** [comment]
+1

**Comment by targos** [comment]
+1

**Comment by jasnell** [comment]
+1

**Comment by ahmadawais** [comment]
+1

**Comment by cjihrig** [comment]
+1

**Comment by BridgeAR** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by bnb** [comment]
Opened this 7 days ago, but realized I didn't actually codify the social team mirroring the 7 day window policy that the Moderation Team has, so I've now opened up a PR for that: https://github.com/nodejs/admin/pull/504

I suppose that without further objection, I'd like to recommend this could be considered "approved" on Friday this week to add 4 additional days for objections since that policy was not yet in place.

**Comment by bnb** [comment]
It's currently End of Work on Friday. There's been no -1s and no -1s to my assertion about it ending today, so I'm going to say this is finalized. I'll work with the appropriate folks on Monday to get things set up and transferred into the Social Team's hands ❤️
