### ISSUE TITLE
Setting up 1Password for Teams for Node.js

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#509]
1Password kindly offers [free Teams plans](https://github.com/1Password/1password-teams-open-source) for Open Source projects.

One of the features that is offered through Teams plans is shared 2FA. Authorized users have access to a cycling 2FA code that's compatible with most/all MFA-enabled sites.

Given that we now have a Node.js Social Team that has password-based access to the @nodejs Twitter account, I'd like to ensure we've got 2FA turned on for the account while still enabling everyone who should have access to have access. 

Given that, I'd like to request that we go through the process of acquiring the 1Password for Teams for Open Source projects for Node.js. The Social Team is one current team that could use this, but having it be owned by the TSC, jointly with the TSC and CommComm, or by current project leadership (chairpeople and OpenJS representatives; perhaps the simplest solution) and enabling other uses would likely be ideal.

cc @nodejs/tsc @nodejs/community-committee

**Comment by bnb** [comment]
I opened this 23 days ago with no negative comments from @nodejs/tsc and @nodejs/community-committee. Given that, I'm going to take the time to apply for the 1Password Teams plan that's free for us, and will PR the documentation around it once it's approved.

**Comment by bnb** [comment]
This has been completed. PR up momentarily.

**Comment by mmarchini** [comment]
We also have a LasPass account, what is the guidance between using one or the other? Zoom credentials are on LastPass today, any chance we can have it on 1Password (either move to 1Password or have it on both)?

**Comment by bnb** [comment]
AFAIK LastPass is controlled by the Foundation, not the project. I've now stored CommComm's Zoom credentials in 1Password and have restricted that to a CommComm group within the 1Password.

**Comment by bnb** [comment]
I didn't answer your second question, sorry @mmarchini: more than happy to store them on 1Password and help set up the team infra for that to restrict it.

**Comment by mmarchini** [comment]
That would be amazing, thanks! Since the credentials for WG meetings is shared across many WGs + TSC (afaik), we should probably have a team specific for these credentials (instead of having a team with everyone from TSC + WGs)?
