### ISSUE TITLE
Pulling CommComm's i18n repo into nodejs/

### ISSUE THREAD

**Issue by obensource** [nodejs/admin#51]
The current [Node.js i18n initiative](https://medium.com/@obensource/internationalizing-node-js-fe7761798b0a) owned by CommComm is seeking to officially establish our working group. Our [MVP repo can be found here](https://github.com/obensource/i18n), and we'd like to pull it into [nodejs/](https://github.com/nodejs) to keep things moving. 🎉

I'm not sure what tasks are required in order to transfer this, your help is greatly appreciated! 🙌

**Comment by bnb** [comment]
Thanks for creating the MVP repo!

@Trott any ideas on what's involved in moving the repo? 😄

**Comment by Trott** [comment]
> @Trott any ideas on what's involved in moving the repo? 😄

@bnb Step one is to [wait at least 72 hours](https://github.com/nodejs/TSC/blob/master/GitHub-Org-Management-Policy.md#repositories):

> Any organization member may request the creation of a new repository within the Node.js Foundation GitHub Organization by opening an issue in the Node.js admin repository. Provided there are no objections from any TSC or CommComm members, such requests are approved automatically after 72 hours.

After that, I think [as long as the current owner is an org member, they can transfer it over](https://github.com/nodejs/admin/issues/35#issuecomment-356738056). Guess we'll find out in 72-ish hours and figure out what to do if that doesn't work.

**Comment by obensource** [comment]
@Trott sounds good! Thanks a bunch for the info! 🙌

**Comment by obensource** [comment]
@Trott @bnb it looks like this issue has passed the 72 hour consensus gathering period. I think I should be good to go for pulling it in if y'all wouldn't mind giving a 👍 :)

**Comment by bnb** [comment]
It does indeed. I believe the current owner of the repo needs to be an owner of the Node.js org. So myself, @Trott or someone could do it if the repo was transferred to us? Not 100% sure if I'm understanding that process correctly.

**Comment by obensource** [comment]
@bnb based on what @trott said, I was under the impression that any 'org memeber' can do it as long we observe the stipulations he outlined. No harm in me trying I guess. I'll give it a shot, and let you know if it doesn't work. :)

**Comment by bnb** [comment]
Ahh, I totally misread that! Thanks for clarifying. Let us know how it goes!

**Comment by obensource** [comment]
@bnb no worries! Having no trouble doing it right now, but I'm not sure about this and which teams I should give access to it? 

![screen shot 2018-01-23 at 8 23 42 pm](https://user-images.githubusercontent.com/1910457/35314500-7e946afe-007b-11e8-914c-81c83ca8ce3a.png)

I'll add the ones I think are relevant, and can always add more later–I guess I'm just most worried about people getting possible email/notification noise :P

**Comment by obensource** [comment]
@bnb sweet–should be live momentarily. I only gave access to the CommunityCommittee for now since this is a CommComm WG repo, if anyone from another team wants team access for it let me know! :D

Thanks all! 🎉🎉🎉

**Comment by obensource** [comment]
Woop woop! [We're live](https://github.com/nodejs/i18n)!💥

Closing this issue. 👍
