### ISSUE TITLE
request to add aixtools (Michael Felt) to the platform-aix team

### ISSUE THREAD

**Issue by sam-github** [nodejs/admin#511]
background: https://github.com/nodejs/build/issues/2328#issuecomment-634843571 

@aixtools is an AIX expert who has volunteered to receive notifications for when @nodejs/platform-aix is pinged in nodejs (build or node).

This kind of expertise is valuable, somewhat rare, and we could use more of it.

Adding @aixtools to https://github.com/orgs/nodejs/teams/platform-aix requires adding him to the org, but would not automatically make him a nodejs collaborator, and I don't think it comes with any access privileges. As a somewhat example, @AshCripps is on the build-wg so is an org member, but not a collaborator.

I've got the GH admin rights to do this, but I'm not sure exactly what the process is, so since its an admin issue, I am opening it here.

cc: @nodejs/build

**Comment by Trott** [comment]
@sam-github For @nodejs/platform-* teams, you can unilaterally add people. No one really "owns" any of those teams, and for platforms like AIX and SmartOS, it's hard to imagine turning down anyone willing to dive in on issues.

**Comment by aixtools** [comment]
Just thought I'd mention - when I try the link  https://github.com/orgs/nodejs/teams/platform-aix from above I get:
![image](https://user-images.githubusercontent.com/10852597/83748212-21112900-a662-11ea-9c40-43c0894f645b.png)

**Comment by richardlau** [comment]
I believe the way GitHub works is that the team pages are only visible to members of the organization the team belongs to.

**Comment by aixtools** [comment]
Sounds good. Then I'll know when I "am in" :)

**Comment by sam-github** [comment]
@aixtools I sent you the invite, thanks so much for the offer.

**Comment by aixtools** [comment]
I’m in. Thanks
