### ISSUE TITLE
ES modules repo/team cleanup

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#513]
I'd like to archive https://github.com/nodejs/dynamic-modules. It seems inactive.

I'd also like to remove the modules-observers team. It seems to have served its purpose. As modules becomes less and less of an isolated strategic initiative and more and more something in core, an observers team seems less necessary.

I'll leave this open for at least 72 hours (and probably longer) for comments before doing anything.

@nodejs/tsc @nodejs/community-committee @nodejs/modules-active-members @nodejs/modules-observers

**Comment by zackschuster** [comment]
i'm a member of modules-observers. would i be able to transfer to a different team? i'd like to stick around :)

**Comment by giltayar** [comment]
You can take out the modules observer group, but you won't be able to stop me observing you! 😃

Thank you for the time spent as a member and as an (official) observer (and especially for @MylesBorins for inviting me to join). I learned a lot, and hopefully contributed some, even if just a little.

And kudos for the great work in delivering ESM to Node.js!

And, as a parting gift, here's a talk about ESM I gave at Node.TLV, a few days before the Covid-19 quarantine: https://www.youtube.com/watch?v=kK_3OP0uJ0Y. I believe this talk and the insight it gave the audience about the reasons for the decisions the WG took, would not have been possible if I had not been an observer.

**Comment by coreyfarrell** [comment]
I don't have the bandwidth to enable notifications for the entire nodejs/node repository but membership in the modules-observers team gives me notifications I need.  Maybe I should request transfer to the modules-active-members team but I think the modules-observers team still has a valid purpose.

**Comment by benjamingr** [comment]
@giltayar knowing you: if you are interested and want to get involved in more areas including but not limited to:

 - Universal JavaScript (EventTarget/AbortController)
 - Streams and the (possible) new HTTP API
 - Promises UX
 - Docs
 - People engagement and CommComm

All those things could use help and of course - the modules team is still very much active and working on shipping ESM and I'm sure they'd love help. I am happy to help you get involved in any of these areas.

Of course, you are (probably) a busy person - so no pressure to get involved in any of these.

We are also always looking for more moderators for the moderation team :]

------

@coreyfarrell - just to make sure you realize, you are also a member of the tooling team so this change would likely have little impact org wise. In terms of modules-observers (as a member of that team) - what sort of notification would that be? IIRC that team just exists as a matter of governance (right?)

**Comment by coreyfarrell** [comment]
@benjamingr I'm aware of my membership in the tooling team.  As a member of modules-observers I receive notifications for any issue/PR tagged with `@nodejs/modules`.

**Comment by guybedford** [comment]
Sounds good, thanks @Trott for the cleanup here.

Typically we only cc @nodejs/modules-active-members when writing a PR or modules issue. How are observers still getting notified for these? Or is this a special rule for labels?

**Comment by Trott** [comment]
I archived the dynamic-modules repo. Still have to figure out what to do with the team.

**Comment by zackschuster** [comment]
@guybedford we're auto-subscribed to a bunch of places, like moderation.

**Comment by Trott** [comment]
OK, someone else may make a different decision, but I'm going to leave the team, but remove folks who don't chime in about wanting to stay so that we don't have a long tail of inactive folks with access to the moderation repo, etc. If you haven't said anything in this thread and I've removed you and you want to get re-added, leave a comment in the next week or so.

**Comment by Trott** [comment]
(I'll also leave folks who are active on other teams.)

**Comment by Trott** [comment]
OK, all done! Closing but will repeat this bit:

> If you haven't said anything in this thread and I've removed you and you want to get re-added, leave a comment in the next week or so.

**Comment by WebReflection** [comment]
So, I woke up with:

> You’ve been removed from the modules-observers team on the Node.js organization.

and

> You have been removed from the @Node.js organization

... were both necessary?

**Comment by Trott** [comment]
> were both necessary?

Thanks for the feedback. Can you elaborate a bit?  Is it that the email notifications arrived without an email explanation that this was happening? In other words, there was little context and it was impersonal. Or is it something else?

(Related: Did you want to be added back to the team?)

**Comment by benjamingr** [comment]
@WebReflection feel free to ping me on Facebook (or via email) if you want to find other teams to get involved in. I think the project could benefit a lot from your contributions. Additionally if you are already involved with the work of another team you can be ask to be added back.

This was just a standard team clean-up, if you get removed from the last team you are a member of in GitHub it removes you from the org (I think so).

**Comment by Trott** [comment]
> This was just a standard team clean-up, if you get removed from the last team you are a member of in GitHub it removes you from the org (I think so).

For that matter, modules-observers still exists and you're welcome to be added back to it. We're doing audits on a few teams right now. (Specifically, I'm doing one on platform-windows and there are other ones for jenkins-admins and various other builds groups.) There are a few reasons for pruning the group memberships. (The big one for me is access to private repos.)

> This was just a standard team clean-up, if you get removed from the last team you are a member of in GitHub it removes you from the org (I think so).

It's not automatic (although you are far from alone in expecting that behavior!). That second step happens manually. I go through every few weeks or so and remove people who are on 0 teams from the org. At this point, it's a thing I've been doing for so long that I don't even think about why I do it anymore, and maybe I should re-evaluate that practice.

**Comment by bmacnaughton** [comment]
i'd like to be added-back/kept on the module-observers team. figuring out how to make our APM auto-instrumentation work with ES modules is my current focus. 

our specific implementation monkey-patches the objects returned by the require function. i'm just starting to read months of backlog but is there any particular area where i can find a focus on that specific use case? issue https://github.com/nodejs/modules/issues/339 is the closest i've found but there's a lot to look at. i'm probably missing others.

**Comment by bizob2828** [comment]
I’d also like to be added back to module observers.

**Comment by WebReflection** [comment]
@Trott @benjamingr thank you both, I didn't realize myself I was just module observer, hence my "_reference counting_" went down to zero after that. I know I haven't been too active recently but ... well, work / life happens, but I assure you I'm reading pretty much everything going on in there so ... thanks for adding me back, I'll try to contribute more in the near future 👋

**Comment by sendilkumarn** [comment]
Hi @Trott & @benjamingr same here I was removed from the org but I would like to continue being part of the org and contribute.

If there is a possibility I would like to contribute toward the following teams 

- Streams and the (possible) new HTTP API
- People engagement and CommComm

Thanks in advanceadvance🙂

**Comment by giltayar** [comment]
I’d also like to be added back to module observers.

**Comment by manekinekko** [comment]
Hi @Trott & @benjamingr I was also removed from the org but I would like to continue being part of it. I have been away because of parent leave. Would love to keep contributing to the Node community, if you folk still need help please let me know. Cheers.

**Comment by Trott** [comment]
I've re-added everyone who has commented. 

@bmacnaughton Your invitation is still pending, which I think means you haven't accepted it in the GitHub interface? (The invitation for @manekinekko is pending too, but I just added it now.)
