### ISSUE TITLE
archive https://github.com/nodejs/open-standards

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#514]
Work has moved to https://github.com/openjs-foundation/standards

**Comment by Trott** [comment]
Should we also remove the @nodejs/open-standards team or does that still serve a purpose?

**Comment by MylesBorins** [comment]
I think we can also remove that team

**Comment by bnb** [comment]
+!

**Comment by MylesBorins** [comment]
Done

**Comment by Trott** [comment]
Re-opening pending removal of the team as well. Self-assigning so I'm not creating work for anyone else. :-D

**Comment by Trott** [comment]
Deleted the team.
