### ISSUE TITLE
Audit platform teams

### ISSUE THREAD

**Issue by AshCripps** [nodejs/admin#518]
Out of the ci stability session came the proposal that we audit the various platform teams we have in node to ensure that everyone is still active and willing, then allowing us to drive for more people to join them to help the fight to improve our CI stability.

The teams:
@nodejs/platform-aix
@nodejs/platform-arm 
@nodejs/platform-macos 
@nodejs/platform-ibmi 
@nodejs/platform-freebsd 
@nodejs/platform-ppc 
@nodejs/platform-s390 
@nodejs/platform-smartos 
@nodejs/platform-windows 
@nodejs/platforms

**Comment by AshCripps** [comment]
cc @Trott

**Comment by aixtools** [comment]
Is a reply sufficient for this audit?

**Comment by AshCripps** [comment]
@aixtools this issue is more calling for said audit that is being handled in other repos, That being said as a new member we know you are active :)

**Comment by ThePrez** [comment]
Are we supposed to be using this issue as a "roll call" to verify our presence for the audit, or is this issue simply to track a TODO that will be accomplished by some other means?

**Comment by Trott** [comment]
> Are we supposed to be using this issue as a "roll call" to verify our presence for the audit, or is this issue simply to track a TODO that will be accomplished by some other means?

It's a tracking issue. So far, I've only started the Windows team checks. Speaking of which, I should probably finish that up....

**Comment by AshCripps** [comment]
On the IBM specific platforms front I'm not 100% sure we need a full audit we do aim to keep on top of it and I believe all members are IBMers or IBM affiliated but will need to double check

**Comment by mhdawson** [comment]
@AshCripps I suggest you just propose the list for the IBM specific platforms. Except for people who were on the lists but were not IBMers.

@cjihrig you might do the same for smartos

**Comment by Trott** [comment]
The @nodejs/platform-windows team audit is complete. The team went from 10 members to 5. https://github.com/nodejs/build/issues/2389
