### ISSUE TITLE
Use zulip rather than IRC

### ISSUE THREAD

**Issue by yjoyos** [nodejs/admin#52]
Hey, guys i am new to node and just wanted you guys to try out zulip. I send bunch of invitation for node tsc members. Althugh i mean to do it for all team members it very hard so please sign your self up to node-test org on zulip just for you guys to test. After that if you guys like it you can create node or nodejs realm on zulipchat.com. https://node-test.zulipchat.com/

I created basic streams up there private stream for tsc, collabarators, You guys can go ahead and set up private streams for who you want. Start a group PM and much more...

You guys can also set up zulip on your own server ie `nodejs.org`. It can be upgraded by git repo and zulip is open source ie Apache 2.0 so fell free to think on 

Lastly, i want to say i am not affilated with zulip in any way, so you should consider asking them question related to zulip ie at `chat.zulip.com`.

**Comment by MylesBorins** [comment]
@yjoyos thanks for submitting this and taking the time. At the moment I'm not sure that we would be likely to adopt a new chat platform that doesn't have general traction from the team. We should keep this issue open while the discussion around best communication medium is still happening and I'll make sure that we consider zulip when we have the discussion

**Comment by jasnell** [comment]
Closing as there does not appear to be anything further here.
