### ISSUE TITLE
Request to join @nodejs/automation-admins

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#520]
@nodejs/automation-admins is the only team with admin access to https://github.com/nodejs/node-auto-test. That repository is useful to test automation tools, but sometimes changing the repository settings is needed to enable automation (so we know the requirements before moving any automation to nodejs/node). I have access to the Settings tab since I'm on TSC, but don't want to abuse the access, so I'm explicitly requesting to join the `automation-admins` team.

(alternatively, since it is mostly a throw-away repository, we might consider adding admins privilege to that repository for a wider group such as `@nodejs/automation`, but I understand if folks are reluctant to do so)

**Comment by gireeshpunathil** [comment]
+1 to grant access to Matheus

**Comment by mmarchini** [comment]
Pinging @nodejs/tsc and @nodejs/community-committee just in case 

(I don't think we have a defined process to request to join a more privileged team?)

**Comment by mhdawson** [comment]
+1

**Comment by mmarchini** [comment]
We don't have a clear policy on joining teams, but since there has been no objections and a few approvals from TSC and CommComm, I'll go ahead and add myself to the team tomorrow.

I also opened a PR with a suggested policy to request to join a team: https://github.com/nodejs/admin/pull/525

**Comment by mmarchini** [comment]
Added myself to the team.
