### ISSUE TITLE
Request to create new oauth app for grafana authentication

### ISSUE THREAD

**Issue by jbergstroem** [nodejs/admin#522]
I seek the approval for creating a new oauth2 application in the nodejs org that helps provide access levels to grafana, similarly to how jenkins authenticates the different teams.

Since each oauth app has its own callback url, I cannot reuse the one from jenkins.

Context and background here: https://github.com/nodejs/build/issues/2370

cc: @mmarchini @MylesBorins

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by mmarchini** [comment]
+1 from me

**Comment by jbergstroem** [comment]
> Do you have a link to the GitHub app we'd be adding?

Someone with correct permissons would visit [this page](https://github.com/organizations/nodejs/settings/applications) and create this application for me. I would retrieve a client id and secret and provide a callback url [`https://grafana.nodejs.org/login/github`] to the person creating it. 

More info about [how to create an oauth app in github](https://developer.github.com/apps/building-oauth-apps/creating-an-oauth-app/) should it be needed. Also, here's the [page from grafana](https://grafana.com/docs/grafana/latest/auth/github/) that explains what I will be doing from the other end.

**Comment by mhdawson** [comment]
+1 from me as well. I can help create the app once we have enough approvals. The are mandatory:  "Application Name", "Homepage URL" and "Authorization callback URL". A description is optional

**Comment by mhdawson** [comment]
@jbergstroem what scopes need to be authorized for graphana?

**Comment by jbergstroem** [comment]
@mhdawson i should really try this with another org but the documentation says `scopes = user:email,read:org`. Perhaps check if jenkins asks for something similar.

**Comment by bnb** [comment]
No objection.

**Comment by WaleedAshraf** [comment]
No objection

**Comment by mmarchini** [comment]
7 days have passed and no objections, although our [policy](https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#github-apps) requires two approvals from each committee (so at least four approvals) to add a GitHub App to a repository or to the org (in this case, the app is org wide IIUC). @bnb @WaleedAshraf should we consider your comments as approvals, or only as not objecting?

If those are approvals we can move forward and I can help setup the GitHub App on the org in the next couple of days (or over the weekend).

**Comment by jbergstroem** [comment]
I can be available with some heads up to help out.

**Comment by mhdawson** [comment]
I'm on holiday now until Monday but if help is still needed at that point I can try to catch up with @jbergstroem

**Comment by bnb** [comment]
@mmarchini consider mine an approval.

**Comment by targos** [comment]
@jbergstroem Can you please provide the values for each field of the form?

![image](https://user-images.githubusercontent.com/2352663/87241668-b5229d00-c425-11ea-9cd9-cf3db60f9abc.png)

**Comment by jbergstroem** [comment]
> @targos said: Can you please provide the values for each field of the form?
- application name: grafana acl (improvement to naming suggested)
- homepage url: https://grafana.nodejs.org
- application description: This application allows grafana to read the nodejs organization github groups and emails that allows us to implement fine-grained authorization in grafana
- callback url: https://grafana.nodejs.org/login/github

**Comment by targos** [comment]
@jbergstroem I created the application. How can I give you the client ID and secret?

**Comment by jbergstroem** [comment]
> @jbergstroem I created the application. How can I give you the client ID and secret?

I emailed you my gpg pubkey.

**Comment by targos** [comment]
I answered your email with the encrypted secrets.

**Comment by jbergstroem** [comment]
> I answered your email with the encrypted secrets.

Received. Will test the integration tonight.

**Comment by jbergstroem** [comment]
Update: looks like it works, I just need to sort out some issues on receiving the request. Bare with me and hopefully we can call it at that.

**Comment by mmarchini** [comment]
@jbergstroem did it work? Does this issue need to remain open?

**Comment by jbergstroem** [comment]
@mmarchini will close this since the oauth app works. Thanks for the help, everyone. I will share more updates once we get the dashboard into general availability.
