### ISSUE TITLE
Request permission to create personal and Jenkins tokens for `github-bot` add Secrets to `nodejs/reliability` and `nodejs/node`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#523]
I noticed we don't have a policy to create tokens for `github-bot` nor do we have a policy to add Secrets (which are used by Actions) to repositories, so I'll assume the same requirements we have for creating GitHub Apps (because functionally creating token + adding secrets is similar to creating an App). This issue bundles a few requests:

### For `nodejs/reliability`

- Create a Jenkins token for `@nodejs-github-bot`
- Create a personal GitHub token for `@nodejs-github-bot` with `repo.public_repo` and `user.read:user` scopes
- Add those secrets to the `nodejs/reliability` repository: `JENKINS_TOKEN` (with the Jenkins token generated above), `USER_TOKEN` (with the personal access token generated above) and `USER_NAME` (with `nodejs-github-bot`)

These tokens will be used by the `nodejs/reliability` Actions to generate daily reports of all failures in our CI. The reports are generated via [`ncu-ci`](https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-ci.md).

Ref: https://github.com/nodejs/reliability/pull/24 and https://github.com/nodejs/reliability/issues/25

### For `nodejs/node`

- Create a Jenkins token for `@nodejs-github-bot`
- Create a personal GitHub token for `@nodejs-github-bot` with `repo.public_repo` and `user.read:user` scopes
- Add those secrets to the `nodejs/reliability` repository: `JENKINS_TOKEN` (with the Jenkins token generated above), `GH_USER_TOKEN` (with the personal access token generated above) and `GH_USER_NAME` (with `nodejs-github-bot`)

These tokens will be available for any Actions running on `nodejs/node`, **except for Actions running on the scope of Pull Requests from forks** (so a PR with a malicious actions **does not** have access to those tokens). Initially, these tokens are intended to be used on `Commit Queue` and `Start CI via Label` Actions, but it will be available for other Actions as well.

Ref: [Commit Queue](https://github.com/nodejs/node/pull/34112) and [Start CI via Label](https://github.com/nodejs/node/pull/34089) (both PRs are blocked until the Secrets are added to the repository).

cc @nodejs/tsc @nodejs/community-committee

**Comment by gireeshpunathil** [comment]
+1

**Comment by mmarchini** [comment]
In theory this requires two approvals from TSC and CommComm (per https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#github-apps-bot-personal-tokens-and-repository-secrets), although until yesterday the policy for adding secrets was unspecified. So ping @nodejs/tsc @nodejs/community-committee.

**Comment by mhdawson** [comment]
+1

**Comment by mmarchini** [comment]
Sorry for the constant pings, but this still needs two other approvals per our policy. @nodejs/tsc @nodejs/community-committee

**Comment by bnb** [comment]
+1

**Comment by addaleax** [comment]
+1

**Comment by ahmadawais** [comment]
+1

**Comment by mmarchini** [comment]
Thanks! I started to add the secrets, but apparently github-bot doesn't have all the permissions it needs on Jenkins (https://github.com/nodejs/reliability/issues/26). I'll wait until we add those permissions to it before finishing this task.

**Comment by mmarchini** [comment]
All secrets were added.
