### ISSUE TITLE
cleanup chakracore teams and vm repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#526]
I think we can probably eliminate @nodejs/ChakraCore, @nodejs/node-chakracore, and @nodejs/node-chakracore-admins. Am I wrong? Happy to keep around anything that makes sense, but at this point, I think all work has stopped on node-chakracore?

Additionally, it seems that we can archive https://github.com/nodejs/vm which stemmed from the effort to make things JavaScript engine-neutral. We can always start something new or unarchive it if efforts along those lines resume in the future.

@nodejs/tsc @nodejs/community-committee

**Comment by mmarchini** [comment]
I'm fine with it (kinda sad though, was hoping to see time travel debugging on Node.js some day).

**Comment by Trott** [comment]
> was hoping to see time travel debugging on Node.js some day

Still might happen? https://developers.google.com/web/updates/2020/03/chromium-chronicle

**Comment by gireeshpunathil** [comment]
may be a good idea to wait for an opinion from the pinged team members themselves? IIUC lot of effort were spent on chakra, so may be they can assert what their long term plan with it is.

**Comment by jasnell** [comment]
At this point all work on the node-chakracore stuff is halted. The repo has been archived and, afaik, the team has shifted focus to v8 and chromium. It's safe to disable/delete these.

**Comment by Trott** [comment]
I plan to wait at least 3 days and, given the long holiday weekend in the U.S., probably more like 5 days before acting.

**Comment by bnb** [comment]
I am +1. 

With my project hat on (i.e. not representing Microsoft - I am not sure what official statuses are): my understanding as an ecosystem member is that ChakraCore is still under development but as @gireeshpunathil there is a larger focus on V8 now that Edge has moved to Chromium.

Speaking with my Microsoft hat on: if it's needed/wanted, I'd be happy to figure out who the correct people are to ping for context or connect folks to.

**Comment by joaocgreis** [comment]
I believe the teams can be removed. I just removed the Jenkins jobs, so they are no longer necessary there. They should be easy to bring back if the effort on Node-ChakraCore is to resume.

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
Seems like we have consensus. I'd say go for it @Trott.

**Comment by ChALkeR** [comment]
+1

**Comment by Trott** [comment]
All done.
