### ISSUE TITLE
Self-nomination: Social Team

### ISSUE THREAD

**Issue by joesepi** [nodejs/admin#527]
I'd like to self-nominate myself as a member of the [social team](https://github.com/nodejs/admin/blob/master/social-team.md) 🙌

**Context:** I am a believer in the Node.js project managing its own social media and I want to work towards having a vibrant and engaged presence. I'm interested in tooling and processes to allow people within our community to help add to that presence. I'm also happy and eager to help promote content that is important to the platform. And to borrow a quote from Tierney's (@bnb) application, as this is also very important to me and is well said in their nomination:
>I'm eager [to] help improve the state of content going out, helping to ensure that [content] is helping the project, the community, and the ecosystem be more welcoming, equitable, and approachable.

**Time commitment:** I'll be able to commit as much time as is needed to this.

If this process seems unfamiliar, please see the membership section of the [social-team.md](https://github.com/nodejs/admin/blob/master/social-team.md#membership) doc

/cc @nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment]
+1 from me.

**Comment by ahmadawais** [comment]
+1 from me as well.

**Comment by mmarchini** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by bnb** [comment]
It has now been 7 days, and there have been zero objections from the TSC and CommComm. As per the social-team doc (linked in Joe's post), this is now accepted.

Going to merge https://github.com/nodejs/admin/pull/528. Welcome to the Social Team, Joe.
