### ISSUE TITLE
Create repository `nodejs/tweet` under the Social Team

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#529]
As part of my [initial recommendation](https://github.com/nodejs/admin/issues/454) around creating the social team was to create a repository and use [Twitter Together](https://github.com/gr2m/twitter-together) by @gr2m (a former CommComm member ❤️ ) to enable us to provide more broad control of the Twitter account for project members outside of just Social Team members.

As a social team member, I've now gone through and requested API access from Twitter for the @nodejs account and have been approved.

I'd like to go ahead and create this repository now, with the following goals:

- Set up Twitter Together.
- Define what is and is not acceptable usage of the account through the repository.
- Make clear that this is a way for the Social Team to expand reach but is not the only path we'll engage on the platform.

This also opens up the possibility for some level of automation for the social team to enhance the content we're putting out - think along the lines of a weekly calendar roundup that balances signal vs. noise.

**Comment by bnb** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment]
+1

**Comment by ahmadawais** [comment]
+1

**Comment by mmarchini** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1. A clear definition of what type of content qualifies (or a best practice around that) would be great to set upfront, IMO.

**Comment by WaleedAshraf** [comment]
+1

**Comment by bnb** [comment]
Plenty of +1s. No -1s. Been open for  > 3 days. Going to go ahead and kick this off here soon.

**Comment by bnb** [comment]
This is now completed
