### ISSUE TITLE
HELP NEEDED - Crypto compliance review

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#530]
In order to follow - https://github.com/nodejs/admin/blob/master/us-export-control.md

We need to:

* Review the licenses in the existing repositories to confirm they are all OSI approved.
* Create tooling to crawl through the GitHub repositories and Node.js to look for binaries.
* Review the list of binaries and identify if they contain source code.
  ( For binaries that include cryptography, validate that the corresponding source code is also provided. If 
  it is not, either add the source code or remove the binaries.
* Put a process in place that scans on a regular basis for new binaries so that they can be reviewed.

I'm opening this issue to ask for volunteers.

**Comment by mhdawson** [comment]
Current status is that we are talking with the Foundation to see how they can help get this part completed

**Comment by nschonni** [comment]
Maybe use an existing tool like https://github.com/fossology/fossology

**Comment by bnb** [comment]
closing since this is relatively resolved AFAIK
