### ISSUE TITLE
New Repo Request: http-next

### ISSUE THREAD

**Issue by Ethan-Arrowood** [nodejs/admin#531]
The NodeJS Web Server Framework Working Group requests a new repo in the NodeJS org titled **http-next**. We will be using this repo to develop a ground-up rewrite of the http core modules. This plan was discussed during the OpenJS World collaboration summit and continued during our routine working group meetings.

Here are some relevant issues for more information:
- [Future of http Organization Plan](https://github.com/nodejs/web-server-frameworks/issues/54)
- [Future of http Technical Plan](https://github.com/nodejs/web-server-frameworks/issues/55)

Reminder: requests like this are automatically approved after 72 hours. If you object to this new repo or would like to propose a different name please do so promptly so we can discuss. Thank you!

**Comment by mhdawson** [comment]
+1

**Comment by mcollina** [comment]
LGTM.

Is this going to be a node core fork?

**Comment by Ethan-Arrowood** [comment]
Great question @mcollina 

@jasnell do you think a fork would be best or would you like to built it in another way?

**Comment by wesleytodd** [comment]
I don't think this will be a node core fork.  My understanding was that this would house the mid and top tier apis, and @jasnell was working on the lowest level apis in node core now.  So, this repo would house the http1/2/3 apis and whatever abstraction we build on top of that to make the compatibility story better.

If anyone from the @nodejs/web-server-frameworks team disagrees with my understanding please chime in.

**Comment by Trott** [comment]
According to https://github.com/nodejs/admin/blob/1ac8f19c14c22683c8f8271ca8f205a6580b3be6/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories, this is effectively approved. Looking at the web-server-frameworks folks, I see at least four people that should be able to add the repo (Matteo, James, Michael, and Gireesh). Happy to do it if they'd prefer that for any reason, but probably best for one of them to just set it up.

**Comment by mhdawson** [comment]
Repo created, https://github.com/nodejs/http-next.  @Ethan-Arrowood can you push, licence, readme.md and code of conduct files before anything else goes in?

**Comment by Ethan-Arrowood** [comment]
Pushed! Let me know if anything needs to be changed

**Comment by Trott** [comment]
I think this can be closed now? Re-open if I'm wrong, of course.
