### ISSUE TITLE
New repo nodejs-next-10

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#534]
In our initial meeting on strategy for the next 10 years of Node.js we agreed we should have a new repo to keep minutes, generating meeting issues etc.

My proposal for the repo name is 

nodejs-next-10

See https://github.com/nodejs/node/issues/34260

**Comment by mhdawson** [comment]
Would also like to ask at the same time for a new team called next10 that is used to manage access to the repo

**Comment by mmarchini** [comment]
+1

**Comment by bnb** [comment]
since `nodejs` is already in the slug for the org, perhaps `next-10` or `next-ten` would be a slightly nicer naming structure? I'm always put off by `nodejs/nodejs-{x}`.

Regardless, +1 for creating a repo for this.

**Comment by mhdawson** [comment]
I'm going with `next-10`, will plan to use that.

**Comment by mhdawson** [comment]
will also make team name 'next-10'

**Comment by bnb** [comment]
that SGTM, +1

**Comment by mhdawson** [comment]
No objections in 72 hours as per: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories so will go ahead and create the repo and team.

**Comment by mhdawson** [comment]
Repo and team created, closing
