### ISSUE TITLE
Add `@nodejs-github-bot` to `@nodejs/collaborators`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#536]
As per https://github.com/nodejs/reliability/issues/26, our bot doesn't have the necessary permission to interact with Jenkins via `node-core-utils`, which prevents it from generating CI failure reports and later will prevent it from [starting CI](https://github.com/nodejs/node/pull/34089). @richardlau [suggested](https://github.com/nodejs/build/issues/2394) we add the bot to `@nodejs/collaborators` because Jenkins doesn't have a good UI experience for the lockdown during security releases. The bot already has the same write permissions as the collaborators team to to nodejs/node, so there should be no concerns there. It will get extra write permissions to `nodejs/node-auto-test`, which IMO is a good thing. Not sure if it would give more permissions and I can't find an easy way to check it via GitHub interface.

This is not a collaborator nomination, so I believe this is the appropriate repository to discuss/request permission. cc @nodejs/tsc @nodejs/community-committee @nodejs/jenkins-admins

**Comment by mmarchini** [comment]
@richardlau do you know if making the `@nodejs/bots` team a subteam of collaborators would work? for Jenkins permissions?

**Comment by richardlau** [comment]
I’m not sure. https://issues.jenkins-ci.org/browse/JENKINS-44920 suggests it should work, https://issues.jenkins-ci.org/browse/JENKINS-63051 claims it does not.

**Comment by richardlau** [comment]
The user page in Jenkins shows the groups the user is in as far as Jenkins is concerned, e.g. https://ci.nodejs.org/user/nodejs-github-bot/

**Comment by mmarchini** [comment]
Guess we can try it, and if adding as subteam doesn't work we can add the bot to collaborators directly

**Comment by mhdawson** [comment]
Adding it to the sub-team makes sense to me unless we'd want to remove access for collaborators when doing as security release but still have the bots work.

**Comment by jbergstroem** [comment]
(fwiw, brought up in the build team wg meeting and no one had objections to testing it out)

**Comment by mmarchini** [comment]
I'll go ahead and add the bots team as a subteam of collaborators to test if that's enough. If it doesn't work I'll add github-bot as a collaborator and try again. Will keep this open until next Monday in case anyone has any objections.

**Comment by mmarchini** [comment]
List of repositories the bot will gain write access when added to the collaborators team:

- nodejs/wasi
- nodejs/gyp-next
- nodejs/webcrypto
- nodejs/promises-debugging
- nodejs/reliability
- nodejs/promise-use-cases
- nodejs/node-auto-test
- nodejs/node-v8
- nodejs/vm
- nodejs/node-chakracore
- nodejs/moderation
- nodejs/help
- nodejs/code-and-learn
- nodejs/node-convergence-archive
- nodejs/node
- nodejs/node-v0.x-archive

GitHub lists all repositories not only the ones the bot will be given new access (for example, it already have write permission on nodejs/node), so I'm not sure which of these teams we'll be granting new access.

**Comment by mmarchini** [comment]
I added the bot as both a subteam and a direct member of collaborators, and it still doesn't have permission to start CI:

![image](https://user-images.githubusercontent.com/4048656/88851705-ffd04300-d1a1-11ea-89e3-0595f441a00e.png)

I'm also getting 403 when trying via API calls.

FWIW the issue we found on reliability was different and increasing permissions for the bot was not necessary to fix it (needed to use the github user name instead of the bot email to authenticate to jenkins via API call with token). But we still need to increase bot permissions to start CI if we want to move forward with https://github.com/nodejs/node/pull/34089.

**Comment by Trott** [comment]
@nodejs/build Any idea on the CI problem above?

**Comment by mhdawson** [comment]
@mmarchini as an experiment have you tried adding the the permissions in the matrix for the GitHub bot user to see if that works  or not? That would clarify whether it is an issue with the permissions or how they are being assigned to the GitHub bot.

**Comment by mmarchini** [comment]
I'm not a Jenkins admin so I can't do that, I'm happy to check if someone can make the changes in the matrix

**Comment by mmarchini** [comment]
Did someone add the bot to the matrix? it seems to be working now

**Comment by mmarchini** [comment]
Ok, the bot seems able to start CI when the `@nodejs/Bots` team is a subteam of `@nodejs/collaborators` (good, because I'm not sure we can remove a team from the subteams list of another team).

**Comment by mmarchini** [comment]
Just so others don't try to do it, when I tried to remove the `@nodejs/Bots` team from being a subteam of `@nodejs/collaborators`, I got these messages:

![image (1)](https://user-images.githubusercontent.com/4048656/88870428-328e3180-d1ca-11ea-966e-b44348f33838.png)

![image (2)](https://user-images.githubusercontent.com/4048656/88870425-315d0480-d1ca-11ea-9603-0b90ba12338c.png)

I thought it was just bad naming on the buttons, but to be sure I tested it on another org with a test team first, and the buttons are right: trying to remove a team from being a subteam of another team will result in the first team being deleted :/

@Trott mentioned he would prefer for the bot user to be added directly to collaborators since in the past we had other bots on the `@nodejs/bots` team, but unfortunately that won't be possible.

**Comment by Trott** [comment]
> @Trott mentioned he would prefer for the bot user to be added directly to collaborators since in the past we had other bots on the `@nodejs/bots` team, but unfortunately that won't be possible.

So you tried it after bots was removed but github-bot was added as a to the collaborators team? I'm astonished that wouldn't work. That doesn't make sense to me at all. Why would someone on a subteam have *more* permissions than someone directly on the team? So strange....

**Comment by Trott** [comment]
The answer to the "Why can't I disassociate the subteam rather than deleting it?!" question: Go the subteam's settings and there's a pull down for Parent Team. Select "Clear selected value" and that should make it not have a parent team anymore.

**Comment by mmarchini** [comment]
Disassociate the subteam and addded the bot account directly to Collaborators :)

**Comment by mmarchini** [comment]
This was done and the world didn't end, so closing
