### ISSUE TITLE
Travis CI on nodejs/ci-config-travis

### ISSUE THREAD

**Issue by dominykas** [nodejs/admin#539]
It seems Travis does not have access to https://github.com/nodejs/ci-config-travis and therefore all the configs there cannot be imported.

There is no `.travis.yml` at the root, but I don't think it's necessary - it seems https://github.com/hapijs/ci-config-travis works just fine without it, so I assume it is some permission at the organization level that prevents this.

Can someone please turn that on?

Thanks!

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by mmarchini** [comment]
Since Travis is used on the Org already (https://github.com/nodejs/nan/runs/954394147), we can fast track. Please leave a :+1: on this comment if you agree this should be fast-tracked.

**Comment by mmarchini** [comment]
Btw, +1 on the request

**Comment by Trott** [comment]
> Btw, +1 on the request

Same.

**Comment by bnb** [comment]
+1 on the request and fast-track.

**Comment by ahmadawais** [comment]
+1

**Comment by mmarchini** [comment]
Done! @dominykas can you confirm if it is working now??

**Comment by dominykas** [comment]
Yes, it does - thanks!
