### ISSUE TITLE
move undici to the nodejs org

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#541]
A long time ago, I started developing https://github.com/mcollina/undici which is a replacement for Node.js core `http.request` and `http.Agent`. I think it has a reached a point of maturity where it would benefit to be in the Node.js organization instead. 

wdyt?

cc https://github.com/mcollina/undici/issues/312

**Comment by mmarchini** [comment]
cc @nodejs/community-committee @nodejs/tsc

**Comment by bnb** [comment]
SGTM :shipit:

**Comment by mcollina** [comment]
Done.

I've also created a team with @ronag and myself in it with `Maintain` access to the undici repo.
