### ISSUE TITLE
Change "default branch for new repos" setting for nodejs/pkgjs orgs

### ISSUE THREAD

**Issue by ljharb** [nodejs/admin#543]
i requested to enable the "default branch name for new repos" beta for the nodejs and pkgjs github orgs.

If we decide we want to change that for new repos, we can set https://github.com/organizations/nodejs/settings/repository-defaults to "main" right now (it will change to "main" automatically later this year; so this would just be opting in to the new default explicitly).

Concretely, I'd like to change the default for both orgs to "main"; thoughts?

(see also: https://github.com/nodejs/node/issues/33864)

To clarify further: Github Pages now works flawlessly regardless of what your default branch is set to, and anything that needs a hardcoded string can use "HEAD", so there should be no technical barriers to new repositories using any default branch name.

**Comment by bnb** [comment]
+1. 

cc @nodejs/community-committee @nodejs/tsc

**Comment by ahmadawais** [comment]
+1

**Comment by rachelnicole** [comment]
+1

**Comment by targos** [comment]
I think the default was changed to `main` automatically by GitHub, so this can be closed?

**Comment by ljharb** [comment]
The setting is now "main", whether Github set it or someone else did, so yes, closing.
