### ISSUE TITLE
Create new repository for "future of build toolchain" strategic initiative

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#544]
I'd like to create a repository for this strategic initiative so we can better organize discussions around known issues, possible solutions and user feedback. I don't have any name preference for the repository, could be `build-tools-next`, `build-tools-revamp`, `build-tools-future`, `after-gyp`, or anything else.

If having a repository for this is too much and it flops, we can always archive it :)

cc @nodejs/tsc @nodejs/community-committee

**Comment by bnb** [comment]
I particularly like `after-gyp` :)

**Comment by mmarchini** [comment]
Repository created: https://github.com/nodejs/build-toolchain-next
