### ISSUE TITLE
Request to create new repository `node-cq-archive`

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#547]
One suggestion for the `commit-queue` is to make landed PRs purple instead of closing them. Since it requires force-pushing to the PR head branch, if something goes wrong we're overriding the original commits. To ensure recoverability in case of failures, I suggest creating a repository that will essentially be a fork of `nodejs/node` for the Commit Queue to push a backup of any PR it tries to land (in case something goes wrong). The repository will have Actions disabled, limited commit access and issues/PRs disabled.

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by bnb** [comment]
If this moves us toward all purple merges, huge mega ultra +1.

**Comment by mmarchini** [comment]
@bnb we can only hope

**Comment by ljharb** [comment]
Git itself already retains that backup - the PR will show a timeline entry with the old sha and the new one, and the old sha will be accessible until github GCs it, which I've never discovered it to do. Are you sure a backup repo is even needed?

**Comment by mmarchini** [comment]
@ljharb good point, in this case a backup repo might not be necessary. We could implement this and if we have an incident where a PR gets completely messed up and unrecoverably lost because of the commit queue we can rethink the backup repository.
