### ISSUE TITLE
Experiment with mmarchini-oss/npm-otp-publish to publish org npm packages

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#548]
I've been working on [this Action](https://github.com/mmarchini-oss/npm-otp-publish) to make it possible to publish npm packages via Actions for projects that require 2FA. Since publishing org npm packages requires 2FA, we could try this Action on some projects. We could start with node-core-utils and maybe llnode, and I'm happy to help setup it on other projects that would be interested.

To use that Action we'll need to create one or more bot accounts on npm (depending how granular we want access to be) and add the npm token from those accounts to the appropriate repositories.

Thoughts?

cc @nodejs/tsc @nodejs/community-committee

**Comment by mcollina** [comment]
@ronag do you think we could experiment this with undici?

**Comment by ronag** [comment]
@mcollina Yes, that was my intention with the original suggestion 👍

**Comment by targos** [comment]
+1.

We could use the foundation's 1Password account to share the OTP secret (1Password supports it in a nice way and generates the codes like an authenticator app)

**Comment by bnb** [comment]
+1. Happy to help get the 1Password set up if you would like, @mmarchini.

**Comment by mmarchini** [comment]
With Automation tokens on npm this is not necessary anymore
