### ISSUE TITLE
Add SLACK_WEBHOOK secret to nodejs/node

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#551]
Add `SLACK_WEBHOOK` secret which is a webhook URL to the OpenJS Foundation #nodejs-dev Slack channel. This allows us to send selective notifications to the channel via Actions, such as [notifying folks when someone force pushes](https://github.com/nodejs/node/pull/35131).

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee reminder we need two +1s from each committee

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
+1

**Comment by mmarchini** [comment]
Need one more from @nodejs/community-committee

**Comment by mmarchini** [comment]
@nodejs/community-committee need one more +1

**Comment by Trott** [comment]
I forget where, but I believe we documented that for people who are on both committees, their vote can count for one committee or the other. Did we change that and now Michael Dawson has the double-value vote? I mean, not that we need to raise the obstacles to approval higher....

**Comment by Trott** [comment]
> I forget where, but I believe we documented that for people who are on both committees, their vote can count for one committee or the other. Did we change that and now Michael Dawson has the double-value vote? I mean, not that we need to raise the obstacles to approval higher....

I can't find it anywhere, so I think we should go with what you (@mmarchini) have been going with. If someone wants to make it harder to approve things, they an open a pull request to change the GitHub policy doc in this repo. I don't think anyone is going to advocate for that. Certainly not me.

**Comment by mmarchini** [comment]
I've been counting each persons vote as one vote, so if they are on two committees they vote counts towards the committee with least votes so far. It doesn't change the fact that we have three TSC votes (you, Shelley and Michaël) and one CommComm vote (Michael). We still need one more from CommComm.

**Comment by mmarchini** [comment]
(we don't require 4 votes, we require two from each committee)

**Comment by mmarchini** [comment]
added to commcomm agenda for awareness

**Comment by Trott** [comment]
Ah, I didn't realize that we count the GitHub reactions too.

If nothing else, our current process could use some clarifying, at least for me.

**Comment by mmarchini** [comment]
If we don't, I've passed some apps and secrets without proper approvals 😅

**Comment by bnb** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by mmarchini** [comment]
Secret added and PR landed.
