### ISSUE TITLE
Add SLACK_WEBHOOK secret to nodejs/node-v8

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#553]
Slack webhook in the OpenJS Foundation slack (channel #nodejs-v8-canary) for important notifications on the nodejs/node-v8 repository.

Ref: https://github.com/nodejs/node-v8/pull/171#issuecomment-691640335

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment]
I should probably know the answer but @mmarchini does this mean that additional people who have access to nodejs/node-v8 will now have access to the secret?

**Comment by mmarchini** [comment]
No, the secret is only visible while I'm setting, after that GitHub will mask it on logs (and when editing users can only enter new values, the old value won't show up).

**Comment by mmarchini** [comment]
Cc @nodejs/community-committee need one more +1

**Comment by Trott** [comment]
+1 (but I'm not on CommComm....)

**Comment by bnb** [comment]
+1

**Comment by mmarchini** [comment]
Done
