### ISSUE TITLE
GitHub Secret for nodejs/docker-node

### ISSUE THREAD

**Issue by nschonni** [nodejs/admin#556]
We had the token setup awhile ago for the creation of PRs from Travis-CI https://github.com/nodejs/docker-node/issues/670
We're migrating over to GitHub Actions https://github.com/nodejs/docker-node/pull/1337, so we need to have the secret `GITHUB_API_TOKEN` created. If the old token is stored in the nodejs/secrets repo from the original request it can be reused.

Otherwise I believe only `repo:public_repo` permission should be needed for a new token. The bot currently has an existing fork of the docker-library/official-images to push to it's own fork, then create a PR to the upstream.

I'd request a fast-track on this one because we're holding of landing the 14.12.0 release and non-amd64 Alpine patches because of a minor complaint (bad PR titles) about the current PR setup from the official-images maintainers

/cc @nodejs/docker

**Comment by mmarchini** [comment]
cc @nodejs/tsc @nodejs/community-committee 

We already have secrets for GitHub tokens, which means we can fast-track this (needs two folks from either committee approving the fast track). If we fast-track, this will only need one approval and wait 72h from the time the committees were notified.

**Comment by mmarchini** [comment]
I'm +1 for adding this, but I want to understand why the GITHUB_TOKEN provided by GitHub doesn't work for this use case first. @nschonni have you tried it?

**Comment by nschonni** [comment]
This particular setup in the PR no, but I have tried similar things where this doesn't work because:
- It's pushing to a repo that isn't the one that triggered the action
- It's creating an PR through the API to a separate repo

I've got a separate action were we're looking to generate PRs for the docker-node repo, where the built-in one will work fine

**Comment by mmarchini** [comment]
I thought that was the case, just wanted to make sure someone tried first :)

(again, I'm +1, I can't approve my fast track request though, and either way we need to wait 72h before setting up secrets on nodejs/docker _if folks approve the fast tracking_)

**Comment by mhdawson** [comment]
+1 to fast track

**Comment by joesepi** [comment]
+1 to fast track

**Comment by nschonni** [comment]
Just looping back the details here https://github.com/nodejs/docker-node/pull/1337#issuecomment-698668672
> docker_node_github_api_token.md is in build/github-bot in the secrets repo already, I assume that's what you're asking for?

So a new token won't be required, and we'll be able to re-use this one after approval

**Comment by nschonni** [comment]
Did this hit the "fast-track" threshold, or is it still missing votes?

**Comment by mmarchini** [comment]
Yeah, it's approved. As soon as someone has the time to add the secret to the repo it will be done. I'll try tomorrow but if anyone can do it first go ahead

**Comment by nschonni** [comment]
@mmarchini awesome! Whenever the Secret is added, I'll land the outstanding PRs when I see this issue is closed

**Comment by nschonni** [comment]
Friendly ping, we'd like to get out the backlogged 4.12 and 4.13 tags

**Comment by bnb** [comment]
@nschonni if you tell me what needs to be copied where, happy to help. If I'm not instantly responsive here, feel free to DM me on Twitter or the OpenJS Slack.

**Comment by nschonni** [comment]
Thanks @bnb! I think this is what we need:
- Copy the existing PAT in the secrets repo: docker_node_github_api_token.md is in build/github-bot 
- On https://github.com/nodejs/docker-node/settings/secrets add the value as a new "Repository secret" called `GITHUB_API_TOKEN`

**Comment by mmarchini** [comment]
Created. I had to change the name to `GH_API_TOKEN`, apparently github doesn't let us create secrets starting with GITHUB_ (or it just doesn't let the specific GITHUB_API_TOKEN name). So remember to change that in the PR as well. Feel free to close this issue once the Action is working :)

**Comment by nschonni** [comment]
Awesome @mmarchini I'll add that code suggestion on the PR for the name change

**Comment by nschonni** [comment]
Secret is working! Thanks @mmarchini
