### ISSUE TITLE
Proposal to transfer "cjs-module-lexer" repo into Node.js organization

### ISSUE THREAD

**Issue by guybedford** [nodejs/admin#557]
Once the PR at https://github.com/nodejs/node/pull/35249 lands, Node.js will have a dependency on the external project https://github.com/guybedford/cjs-module-lexer, which was created and will be maintained explicitly for this PR feature.

I expect to maintain this project for at least a few years, but that maintenance would be done always based on upstreaming. In addition there would be no plans to add features that would not be included in the Node.js implementation.

To enable all Node.js collaborators to be able to equally contribute to this repo I would like to propose transferring the repo into the Node.js organization. I would continue to be the primary developer on that project, but it would be a clearer distinction than it being some arbitrary third party project without any direct involvement.

The primary roadmap I see for the project is:
* General maintenance.
* Improve any detection cases that come up.
* Upstream the C implementation at some point (instead of the JS implementation) for a minor perf improvement.
* Upstream any bug fixes from es-module-lexer (the project this was forked from in the first place).

It would be great to hear what others think of this or if there are other suggestions for handling the process between these projects.

//cc @targos

**Comment by targos** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by mmarchini** [comment]
This is approved. @guybedford can you make sure the repository have the following files?

- CODE_OF_CONDUCT.md: it can be a reference to the Node.js Code of Conduct.
- CONTRIBUTING.md: if there isn't one already, the contributing guide of Node.js core could be a good example. Consider including the Developer's Certificate of Origin section in the document to avoid potential copyright conflicts.
- LICENSE, or other kind of documents that describe the license of the project.
- README.md

If any of those files are missing, feel free to open a PR to add them and ping me to double check. We can transfer the repository afterwards.

**Comment by guybedford** [comment]
Sure will do. Just give me a few days to prepare the repo for the transfer.

**Comment by guybedford** [comment]
I hate to admit I still haven't got around to this work.

Basically if someone would like to offer to do this repo setup for the transfer I would be glad to assist, but in the end I also don't feel like there's anything wrong with maintaining the repo locally for the time being too.

Feel free to prod me anytime though on it.

**Comment by guybedford** [comment]
I've finally gone ahead and transferred the cjs-module-lexer project into the Node.js organization having completed the setup steps here. I've also added the Node.js foundation to the npm access for the package.
