### ISSUE TITLE
Broad Node.js Survey

### ISSUE THREAD

**Issue by RRomoff** [nodejs/admin#560]
Hi All:

The Foundation would like to get the broad Node.js User Survey back off the ground. Last year, we made a bunch of progress in getting community feedback (https://github.com/nodejs/admin/issues/380 ) but needed to pause due to other priorities.

We also had some legal feedback pertaining to how extensive and in-depth our data set was regarding GDPR protected data / Personal Identifying Information, and it's been advised we remove it. These would be questions 6,7 and 10-15. We are opting to keep question 5 as it would be helpful for developer outreach.
 
Several of our questions ask about gender identity, ethnic origin, and even health. Later questions invite a recipient to share their identity. Even without volunteering that data, the data set is so extensive that it's possible that some individuals could be identified algorithmically if someone were able to get access to the database.

Collecting and storing that data could present risk to the Foundation that we are not comfortable with (potential liability that could lead to significant mitigation costs if the data is ever compromised).

We do have a goal of serving underrepresented communities, so we recommend adding a general question around this. For example, our Events team asks in registrations, "do you identify with underrepresented communities?”

RE surveys moving forward, the recommendation from the Foundation is that after this big survey, we will be moving more toward smaller, more focused surveys that will provide specific insights to individual projects (The Unhandled Promises Survey from the Node.js TSC is an example of how we will try surveys in the future.)
 
Here's the survey in a google doc:https://docs.google.com/document/d/1DcRB6M7snS-7qJD0kB1RGl9DE2whVNNjM-ubftbsSo0/edit?usp=sharing 

I’ll keep this open for a week for discussion and then I’d like to move forward to setting up and administering the survey. Thanks all!

**Comment by RRomoff** [comment]
I'll be closing this down Weds and starting on next steps. Please let me know if there are any questions!

**Comment by mhdawson** [comment]
@RRomoff can you give us a rundown on the next steps and timeline for them?

**Comment by RRomoff** [comment]
**Next steps and timeline**
- update the survey w/o Oct 19
- re-engage with external survey resource, week of Oct 26
- format survey into surveymonkey, week of Oct 26
- Open Survey - week of Nov 2
- Collect responses ~ 4 weeks
- Close Survey, Week of Dec 7/14
- Analyse results (timing TBD on external expert)
- Publish Results (timing TBD, but early 2021)

**Comment by mhdawson** [comment]
@RRomoff thanks! Great to have that level of insight :)

**Comment by RRomoff** [comment]
Hi All-
With a busier than expected end of year, the survey was pushed. I'm glad to say that it's loaded into the survey tool and ready to be shipped. Here's the link I wanted to share in case anyone would like a final review. My plan is to get this out next week. 
Thank you!
https://www.surveymonkey.com/r/D6HXXPP

**Comment by mhdawson** [comment]
@RRomoff thanks for the update.

**Comment by bnb** [comment]
Happy to help with socials as it opens. I can work with @joesepi on some copy and schedule tweets / other posts.

**Comment by bnb** [comment]
Going to close this 👍🏻
