### ISSUE TITLE
Admin access to https://github.com/nodejs-github-bot/official-images for nodesj/docker team

### ISSUE THREAD

**Issue by nschonni** [nodejs/admin#562]
This repo/fork is used to create pull requests to the docker/offical-images repo. Requesting access for the team so we can prune stale branches and fix the auto-pr branch if something goes wrong in the auto-pr process.

Not really sure how this should get documented

/cc @nodejs/docker

**Comment by nschonni** [comment]
Alternate would be to create a fork in the nodes org and grant permissions there. We'd then just need to adjust the auto-pr job to use that

**Comment by mmarchini** [comment]
Why can't the repository live in the org instead?

**Comment by nschonni** [comment]
@mmarchini it could, that was my follow on comment 😄 , but maybe it did show up before you responded

**Comment by mmarchini** [comment]
ah, guess I got confused with "create a fork". I meant transfer the whole repo and have the main repo in the org.

**Comment by nschonni** [comment]
No worries, maybe this is a better statement:

Option 1:
- Give Admin or maintainer access to https://github.com/nodejs-github-bot/official-images nodejs/docker

Option 2:
- Create a new fork of https://github.com/docker-library/official-images into the nodejs org
- Grant Admin access to nodejs/docker to new repo
- Grant Write access to nodejs-github-bot to new repo
- Update nodejs/docker-node auto PR flow to use new repo
- Delete/archive https://github.com/nodejs-github-bot/official-images 

Option 3:
- Transfer existing fork https://github.com/nodejs-github-bot/official-images into nodejs org
- Grant Admin access to nodejs/docker to new repo
- Update nodejs/docker-node auto PR flow to use transferred fork

I do kind of like the second option, but it doesn't look like there is much president for forks in the org https://github.com/nodejs?q=&type=fork&language=

**Comment by mmarchini** [comment]
I'm more inclined to option 3. I always thought it was weird that we had that repository on the bot account. I don't understand why Admin access is needed though.

**Comment by mmarchini** [comment]
Also, since Option 2 deletes the original repo and keeps only the fork, there's essentially no difference between options two and three.

**Comment by mhdawson** [comment]
+1 on option 3

**Comment by nschonni** [comment]
> Also, since Option 2 deletes the original repo and keeps only the fork, there's essentially no difference between options two and three.

Option 2 allows up to update and test with the new repo before the old one is removed. Option 3 assumes that we can co-ordinate timing and that there are no snags in updating all the CI workflows as a "big bang".

> I don't understand why Admin access is needed though.

Sorry, missed the comment. I guess full Admin might not be needed, maintainer might be enough to be able to prune and possibly force-push to fix PR branches if there are issues with the automation. Goes back to the original purpose of the issue, before it veered off into moving the repo

**Comment by ljharb** [comment]
Option 2 deletes all issues and PRs, unrecoverably.

**Comment by nschonni** [comment]
There are no issues because it's a fork of an upstream repo already. There are a few old testing PRs https://github.com/nodejs-github-bot/official-images/pulls?q=is%3Apr+is%3Aclosed but I think it could be Archived rather than deleted at the end if you think there is anything to keep

**Comment by Trott** [comment]
There seems to be agreement that this should happen, although I guess it's not unanimous about whether it should be option 3 or option 2. But I guess there's consensus?

What's the next step? Somebody with the bot login credentials needs to initiate the transfer?

**Comment by nschonni** [comment]
Since the auto-PR is blocked on #574, this might be a good time to do this with Option 3 since it's not functioning anyway

**Comment by mmarchini** [comment]
@nschonni I can do it. No need to coordinate with anyone then?

**Comment by nschonni** [comment]
yup, go ahead, we need to keep doing manual PRs for now anyway

**Comment by mmarchini** [comment]
Repository transfered to https://github.com/nodejs/official-images, @nodejs/docker has been added with ["Maintain" role](https://docs.github.com/en/free-pro-team@latest/github/setting-up-and-managing-organizations-and-teams/repository-permission-levels-for-an-organization#repository-access-for-each-permission-level).

**Comment by mmarchini** [comment]
@nschonni you might need to update the repo name on nodejs/docker-node actions, although GitHub might do the redirect properly as well.

**Comment by nschonni** [comment]
🎆 thanks @mmarchini!

**Comment by PeterDaveHello** [comment]
Thanks @mmarchini! 🎉
