### ISSUE TITLE
Archive nodejs/webcrypto

### ISSUE THREAD

**Issue by tniessen** [nodejs/admin#565]
I wasn't aware of @jasnell's efforts to add WebCrypto to Node.js core until a few days before the PR was opened. At this point, it probably doesn't make sense to continue my own efforts in https://github.com/nodejs/webcrypto. I didn't have much time during the last couple of months, and apart from Sam and @panva, there has been little to no help and/or engagement in that repository. And while a lot of time and effort went into it on my side, it still hasn't reached a point at which it could be considered a complete implementation, partially due to the lack of certain features in Node.js core.

Therefore, I would like to archive the repository. I am not aware of any particular process for that (correct me if I'm wrong), so unless someone objects within the next week or so, I will archive the repository.

Refs: https://github.com/nodejs/admin/issues/366

**Comment by tniessen** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
Done.

**Comment by tniessen** [comment]
Unarchived and re-archived to change the repository description to something meaningful.
