### ISSUE TITLE
Adding ttshivers to nodejs/docker team

### ISSUE THREAD

**Issue by nschonni** [nodejs/admin#566]
We have a new member we'd like to add to the team, but it looks like because they're not in the nodejs org currently, we can't directly add them to the team https://github.com/nodejs/docker-node/issues/1366

/cc @ttshivers @nodejs/docker

**Comment by Trott** [comment]
I've sent them an invitation.

@nodejs/tsc @nodejs/community-committee @nodejs/docker Any objection to making @nschonni a Maintainer for @nodejs/docker?

**Comment by ttshivers** [comment]
Thank you. Got the invite and accepted.

**Comment by Starefossen** [comment]
> I've sent them an invitation.
> 
> 
> 
> @nodejs/tsc @nodejs/community-committee @nodejs/docker Any objection to making @nschonni a Maintainer for @nodejs/docker?

No objections here!

**Comment by Trott** [comment]
Made @nschonni a Maintainer of `@nodejs/docker`. Closing this.
