### ISSUE TITLE
Move `node` Snap management repo into nodejs org

### ISSUE THREAD

**Issue by rvagg** [nodejs/admin#567]
I'd like to move primary maintenance of the Node.js Snap package `node` into this org, and I think I need to open an issue here to formalise it. I've discussed this with @nodejs/build-infra and have got a :thumbsup: from @mhdawson at least (and no disagreement from the others). I haven't yet mentioned this to @nodejs/build so this should serve as that and I would like @nodejs/build to be the "owner" of the new repo.

The primary action I'd like to take is to transfer https://github.com/rvagg/node-snap/ into this org, with the repo name `snap`.

This repository is responsible for triggering builds for the Node.js Snap that gets published to the Snap store as `node`: https://snapcraft.io/node

Previously all of this was handled privately on a server in my house from a simple cron job. It now runs from that repo using GitHub Actions as cron. The repo is responsible for:

* Documentation about the Snap, it gets linked from the Snap store and when you type `snap info node`.
* Defining how the Snap is built, per release line, via the snapcraft.yml descriptor file.
* Watching nodejs.org/downloads for new releases on a 15 minute interval, when there are new releases for the monitored release lines, it updates itself (a branch per release line) and pushes a copy of the repo to https://launchpad.net/node-snap - Launchpad takes over from there, building the Snaps and publishing them to the store.
* Receiving feedback about the Snap - which primarily takes the form of "A new release line of Node.js is out, why haven't you published it yet?" and "Why is the latest Snap so out of date?" (there have been bugs and there's an auth limit of 2 years between Launchpad and Snapcraft which gets in the way too).

Along with this, I'll be:

* Putting the credentials for the `openjs` Canonical (Launchpad & Snapcraft) account into nodejs-private/secrets/build/infra, including an SSH key used for the https://launchpad.net/node-snap repo.
* Asking Canonical to transfer ownership of the `node` Snap to the user `openjs` from my own private account. The `openjs` account currently has access, but I'm the owner and I'd like that switched.

What are the next steps to getting the repo transferred these days? I don't have org admin access these days obviously so someone will have to receive it when I transfer it.

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
@rvagg the review process is described here: https://github.com/nodejs/admin/blob/master/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories

After 72 hours if there are no objections it can be transferred over and I should be able to help with that.

**Comment by mhdawson** [comment]
@rvagg can you add a code of conduct file which references https://github.com/nodejs/admin/blob/master/CODE_OF_CONDUCT.md

**Comment by mhdawson** [comment]
You can probably just copy this one: https://github.com/nodejs/node-addon-api/blob/master/CODE_OF_CONDUCT.md

**Comment by rvagg** [comment]
@nodejs/tsc I'm now transferring the `rvagg/node-snap` into this org. Could the person who receives the transfer please rename it to `nodejs/snap`, give @nodejs/build-infra admin access to it and @nodejs/build write access to it.

**Comment by rvagg** [comment]
OK, I didn't need it to be accepted, I guess because I'm a member of the org. https://github.com/nodejs/node-snap is there now, I got to select the two teams but I think that only gives write access. Could I please get it renamed to `snap` and the build-infra team elevated to Admin so they can edit the settings & secrets and such.

**Comment by targos** [comment]
I renamed it to `snap` and `build-infra` is now Admin.

**Comment by rvagg** [comment]
perfect, thanks @targos. relevant secrets also added @ https://github.com/nodejs-private/secrets/pull/143
