### ISSUE TITLE
Happy Calendar Maintainers review day!

### ISSUE THREAD

**Issue by williamkapke** [nodejs/admin#57]
Per the defined process:
> This list should be reviewed and pruned annually (at minimum). The calendar has a yearly recurring event on Jan 31st for this. An issue should be opened asking the calendar maintainers for their continued volunteering efforts (directly @-mention all members). After 1 week, this list should be PRed removing members that did not respond.

... it's time! So...

@gibfahn - Gibson Fahnestock
@hackygolucky - Tracy Hinds
@jasnell - James Snell
@joshgav - Josh Gavant
@mcollina - Matteo Collina
@mhdawson - Michael Dawson
@nebrius - Bryan Hughes
@ryanmurakami - Ryan Lewis
@sam-github - Sam Roberts
@trott - Rich Trott
@williamkapke - William Kapke
@bnb - Tierney Cyren

Please reply to this thread with a `+1`... or 👍 reaction... or whatever you want to give a positive indication that you're still available to help maintain the Calendar. It's that simple.

<sup>If you were recently added and it seems silly that you'd want to be removed - please just play along anyway 😆- this only happens annually</sup>

 I'll be back in 7 days to tally up the replies and adjust the list.

On vacation? Missed this issue? Don't worry- it's super easy to get added back! (just open a PR)

Thanks for helping out!

**Comment by ryanmurakami** [comment]
+1

**Comment by sam-github** [comment]
Remove me if you'd like. I'm not maintaining any calendars right now, probably will be again in 6 months, but I can be added back then.

**Comment by mhdawson** [comment]
+1

**Comment by hackygolucky** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by nebrius** [comment]
You can remove me, thanks.
