### ISSUE TITLE
Add `workflow` scope to github-bot token used on nodejs/node

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#572]
### Why

The Commit Queue can't land changes to `.github/workflows` (see https://github.com/nodejs/node/issues/34770#issuecomment-730558824). That's because the Personal Access Token we use for Commit Queue doesn't have the `workflow` scope.

### Request

Add `workflow` scope to the Personal Access Token we use on `nodejs/node`

### Potential risk

It shouldn't be more risky than using the Commit Queue without that scope. With that being said, someone should do an extra evaluation of risk before enabling this scope for the PAT.

**Comment by nschonni** [comment]
We've run into this for the docker-node PAT as well recently because they added GitHub Actions to their repo it creates PRs for. Can we piggy back this to make it a general "Add `workflow` scope to github-bot", or is it better to spin up a new issue?

**Comment by mmarchini** [comment]
@nschonni create a new issue, since re-using this issue would require re-approval from folks who already approved.

**Comment by mmarchini** [comment]
cc @nodejs/community-committee one more to go :)

**Comment by bnb** [comment]
+1

**Comment by Trott** [comment]
@mmarchini Did this happen and can be closed? Or should this remain open?

**Comment by mmarchini** [comment]
Done
