### ISSUE TITLE
Create private repo for inadvertent disclosures

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#573]
Would like to create new private repo called `premature-disclosures` for inadvertent disclosure handling as outlined in: https://github.com/nodejs/node/pull/36155

If approved I'll rename/cleanup https://github.com/nodejs/node-temp which was created adhoc during the last inadvertent disclosure.

**Comment by gireeshpunathil** [comment]
I approve

**Comment by mcollina** [comment]
I approve

**Comment by targos** [comment]
I approve the creation of `premature-disclosures` but I don't think it should be a copy of `nodejs/node`. Let's make it an empty repo with a README that explains what it is about.

**Comment by mhdawson** [comment]
@targos that is what had created. Myles had pushed the node content when we thought there was still a possibility of moving a PR. Given that we can't removing all of that is what I had in mind as part of the "cleanup"

**Comment by mhdawson** [comment]
Repo repurposed and cleanup. Maybe not in the best way but should do.

**Comment by mmarchini** [comment]
Is the assumption that CommComm and Moderation can have access to this repository, even though they wouldn't receive a disclosure through the proper channels? Since both teams are admins on the org they have access to any private repos.
