### ISSUE TITLE
Create repo node-api-headers

### ISSUE THREAD

**Issue by NickNaso** [nodejs/admin#576]
I would like to create new public repo called  `node-api-headers`. The N-API team discussed about that in the last meeting happened today 18th December 2020. The reference issue is https://github.com/nodejs/node-addon-api/issues/855.
The purpose of the repo is to provide the N-API headers file and the symbols exported by N-API. 
@nodejs/n-api

**Comment by mhdawson** [comment]
+1 from me.

**Comment by Trott** [comment]
Regarding repository creation our [docs](https://github.com/nodejs/admin/blob/f2d17d0102c0edbe21b367f732e8b3d1a549da5e/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories) say

> Provided there are no objections from any TSC or CommComm members raised in the issue, such requests are approved automatically after 72 hours.

So someone can create the repository and then close this issue. Maybe @mhdawson or @gabrielschulhof as they are both TSC members and members of the n-api team?

**Comment by mhdawson** [comment]
I've created the repo and given access to the n-api team.

@NickNaso could you add a README.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md ?

**Comment by oshunter** [comment]
> I've created the repo and given access to the n-api team.
> 
> @NickNaso could you add a README.md, CODE_OF_CONDUCT.md and CONTRIBUTING.md ?

Hi，mhdawson

When the n-api repo can be accessed?

**Comment by mhdawson** [comment]
@oshunter its here: https://github.com/nodejs/node-api-headers but not yet populated with content.
