### ISSUE TITLE
Create @nodejs/platform-zos team

### ISSUE THREAD

**Issue by richardlau** [nodejs/admin#579]
The IBM z/OS team have begun the process of upstreaming their changes to build Node.js on z/OS, starting with libuv: https://github.com/libuv/libuv/pull/3060.

I've been making changes on the CI (https://github.com/nodejs/build/issues/2491) and it would be very helpful to have a team containing the members for pings/notifications. Would it be possible to create a @nodejs/platform-zos team, initially including:
- @zsw007
- @IgorTodorovskiIBM
- @alexcfyung

in a similar fashion to the existing nodejs/platform-s390, nodejs/platform-ibmi teams? Ideally we'd have the same members also in libuv/zos.

https://github.com/nodejs/nodejs.org/pull/3635 is an example of where such a team would be pinged.

@nodejs/tsc @nodejs/community-committee @nodejs/libuv

**Comment by gireeshpunathil** [comment]
+1

**Comment by zsw007** [comment]
@alexcfyung is also working with me and Igor to upstream changes to build Node.js on z/OS. He is currently looking at changes on the Node.js side, so it may be beneficial to include him in the @nodejs/platform-zos team as well.

**Comment by mmarchini** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by richardlau** [comment]
Since there have not been any objections please could someone with permissions create and populate nodejs/platform-zos? And maybe @cjihrig could you update the libuv/zos team to include the additional members?

**Comment by targos** [comment]
Created @nodejs/platform-zos and invited 3 people:
![image](https://user-images.githubusercontent.com/2352663/108068067-eae5cf00-7061-11eb-981e-7c0be80aae76.png)

**Comment by cjihrig** [comment]
> And maybe @cjihrig could you update the libuv/zos team to include the additional members?

Done. Invites sent.
