### ISSUE TITLE
Request for access to private data for Codecov

### ISSUE THREAD

**Issue by targos** [nodejs/admin#583]
https://github.com/orgs/nodejs/policies/applications/119817

I don't know when the request was created. GitHub doesn't display any date.

/cc @bcoe this seems to come from you. What's the need?

**Comment by bcoe** [comment]
@targos I don't believe there's any need for codecov.io to have access to anything but public data.

**Comment by targos** [comment]
Okay, so I denied the request. We can revisit if there are any issues.
