### ISSUE TITLE
Create new github-bot personal token for nodejs/node-v8 automation

### ISSUE THREAD

**Issue by targos** [nodejs/admin#587]
A token is needed with the `public_repo` and `workflow` scopes.
This is for a daily workflow that will update the `node-v8`'s canary branch with latest Node.js commit and V8 lkgr. `workflow` is needed for cases where the Node.js update contains changes to `.github/workflows`.

Reference: https://github.com/nodejs/node-v8/pull/171

/cc @nodejs/tsc @nodejs/community-committee

**Comment by Trott** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by targos** [comment]
@nodejs/community-committee PTAL

**Comment by targos** [comment]
Ping

**Comment by mmarchini** [comment]
Added to commcomm agenda as it needs one more approval from them

**Comment by bnb** [comment]
Hi hello yes, +1

**Comment by joesepi** [comment]
Hi. +1 from me too.

**Comment by targos** [comment]
Thank you!

@mmarchini I think you're one of the few people who both have access to the github bot and repository settings? Would you be able to create the token and add it to https://github.com/nodejs/node-v8/settings/secrets/actions/new ?

**Comment by targos** [comment]
I don't know who else to ask 😕

**Comment by bnb** [comment]
@targos AFAIK this is approved. I'm also waiting on a token for a different issue, this seems to be highlighting a bottleneck. Perhaps @mhdawson could help advise us?

**Comment by mhdawson** [comment]
@bnb I've not been in the loop of creating tokens in the past. I think @joyeecheung was involved in the github bot work. @joyeecheung do you know?

**Comment by joyeecheung** [comment]
I've added a CANARY_UPDATE token with the scopes mentioned in the OP, @targos can you try it out?

**Comment by joyeecheung** [comment]
BTW all I did was creating a personal access token and adding it to the repository, according to the documentation here https://docs.github.com/en/actions/reference/authentication-in-a-workflow

**Comment by targos** [comment]
Thank you @joyeecheung, it's working !
