### ISSUE TITLE
Enable github pages & subdomain for Undici

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#590]
@Ethan-Arrowood has developed a new website for Undici in https://github.com/nodejs/undici/pull/585.

I would like to:

* [x] enable github pages
* [x] setup a domain name for the project

As of domains, here are a few options:
* `undici.nodejs.org`
* `undici.nodejs.dev`
* `undici.dev`

The first two have the benefit of being official.

Are there any objections? What's the process for adding a DNS entry?

**Comment by rvagg** [comment]
For nodejs.org, myself or @mhdawson usually handle these, tho there's some others with infra access that can. I guess just a signal that this is endorsed by (or at least has no objection from) the TSC is enough to make it move ahead, along with technical details of what it needs to point to. For nodejs.dev, that's something else entirely but maybe that'd be a good one to lean in to for this kind of thing? Is it expected that there's going to be more of these "official" style core packages? Maybe loading up nodejs.org isn't a great idea?

**Comment by mhdawson** [comment]
+1

**Comment by mmarchini** [comment]
cc @nodejs/community-committee

**Comment by mcollina** [comment]
I have enabled github pages for the project at https://nodejs.github.io/undici/#/.

**Comment by mcollina** [comment]
@mhdawson could you configure `undici.nodejs.org` to point to `nodejs.github.io`? I'll set up the rest.

**Comment by mhdawson** [comment]
@mcollina done, it shows a 404, same as if I went to nodejs.github.io but I assume there is more setup on your end needed.

**Comment by targos** [comment]
I set the custom domain at https://github.com/nodejs/undici/settings
GitHub says it's not possible to enable HTTPS but it's not clear why.

**Comment by MylesBorins** [comment]
@targos despite the error message https://undici.nodejs.org/ works as expected ¯\_(ツ)_/¯

**Comment by targos** [comment]
So is it not possible to have automatic redirect from `http` to `https` for the `nodejs.org` domain ?

**Comment by bnb** [comment]
+1

**Comment by MylesBorins** [comment]
@targos I'm unsure, would have to find out how dns was setup

**Comment by bnb** [comment]
Should be able to with this setting?

![image](https://user-images.githubusercontent.com/502396/112886116-8033a480-909f-11eb-9bd8-c188569cb58e.png)

**Comment by bnb** [comment]
(deleted a comment of my own that wasn't fully informed)

**Comment by MylesBorins** [comment]
Quickly looking at the dns records on https://dnschecker.org/all-dns-records-of-domain.php it would appear that the DNS record points directly to cloudflare rather than pointing directly at GH-Pages. So we likely either need to enable the redirect on cloudflare (reasonably easy to do) or point DNS directly at GitHub

**Comment by mhdawson** [comment]
Just let me know what you want added to cloudflare, if you can be specific what needs to be added (@MylesBorins sounded like you know what) that would be helpful.

**Comment by mhdawson** [comment]
This is what I'd added earlier:

**Comment by mcollina** [comment]
I think there is something wrong in the DNS configuration.

https://docs.github.com/en/github/working-with-github-pages/troubleshooting-custom-domains-and-github-pages#https-errors

Apparently the DNS server is not configured correctly, it needs to be a CNAME to `nodejs.github.io` and not an `A`  record.

**Comment by mcollina** [comment]
![Screenshot 2021-03-31 at 17 43 04](https://user-images.githubusercontent.com/52195/113172263-8e70f480-9248-11eb-8697-01decef283ad.png)

@mhdawson I think you need to remove `proxied`.

**Comment by MylesBorins** [comment]
@mhdawson that worked http://undici.nodejs.org/ now automatically forwards to https://undici.nodejs.org/
