### ISSUE TITLE
Archive nodejs/workers ?

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#591]
While looking at our repos in respect to https://github.com/nodejs/node/issues/33864

I'm wondering if we still need the https://github.com/nodejs/worker repo since worker support has been integrated into the core repo.  @addaleax what do you think?

**Comment by gireeshpunathil** [comment]
+1 to archiving it

**Comment by targos** [comment]
We would need to close https://github.com/nodejs/worker/issues/6 before archiving. @addaleax are you ok with that?

**Comment by addaleax** [comment]
@targos Sure, done :)

**Comment by mhdawson** [comment]
Ok archived
