### ISSUE TITLE
Create nodejs/social-team-private repo

### ISSUE THREAD

**Issue by joesepi** [nodejs/admin#599]
There will be times when the Foundation (and perhaps others) may need to engage with the @nodejs/social team to plan communications regarding embargoed matters. For example: a new member company or upcoming promotions that would be best to remain private until time of announcement.

A private repo allows us (TSC, CommComm, Social Team) to work through these matters in a private way.

The expectation is that all issues and docs will move to the public repo after embargo or other privacy constraints are lifted.

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
+1

**Comment by WaleedAshraf** [comment]
+1

**Comment by bnb** [comment]
@nodejs/tsc I believe we need one more approval from y'all :)

**Comment by targos** [comment]
+1

**Comment by joesepi** [comment]
repo created: https://github.com/nodejs/social-team-private

Thanks yall.
