### ISSUE TITLE
archive worker and security-advisories

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#600]
Related to moving primary branch to main I've there are a few repos we should archive. I realized I should probably raise an issue here before archiving a repo.  

I have already archived https://github.com/nodejs/worker (Sorry about that, can revert if there are objections, at least I asked @addaleax first :))

The next one is security-advisories, see discussion in - https://github.com/nodejs/security-advisories/issues/4

**Comment by bnb** [comment]
closing, since this has been completed.
