### ISSUE TITLE
Loaders team

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/admin#606]
Hi!

I’ve been working with @MylesBorins to set up a new team to tackle the ES module loaders. I’ve created a repo and a GitHub team, and was starting to set other things up when Myles and @Trott suggested I open an issue here to ask for help. In particular, I’d like to be able to use an official Node account for meetings, and be able to record and upload them.

I’ll create templates in https://github.com/nodejs/create-node-meeting-artifacts/tree/main/templates for meetings for the new team once I figure out a time that doesn’t conflict. Please let me know what else I should do.

Thanks!

**Comment by mhdawson** [comment]
@GeoffreyBooth has been an active member of the Modules team, unless anybody voices concerns by Monday I'll add him to the list of youtube maintainers and ask Brian to give him access to the zoom account.

**Comment by mhdawson** [comment]
Invited @GeoffreyBooth as a manager for the youtube channel and have asked Brian to give him the zoom credentials.

**Comment by GeoffreyBooth** [comment]
Everything appears to be set up, thanks for all your help! I’ll reach out to @mhdawson if I have any issues (unless there’s another point person you recommend). Thanks.
