### ISSUE TITLE
New GitHub feature "Issue Forms" Available for use in Public nodejs repositories

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#609]
We have had a new feature enabled on our repos called "Issue Forms" which will allow us to use forms in issue templates to create a much more interactive experience for folks opening issues in our organiation.

For more details check out [the documentation](https://gh-community.github.io/issue-template-feedback/welcome/ )

If folks run into any issue please feel free to ping me in the OpenJS slack.

Two notes:

* This is for public repos only
* The feature is still in an alpha so things could break / change... but the team is confident about the quality right now

**Comment by bnb** [comment]
If folks would like to see what it's like as a user, you can take a look on electron/electron - we've been using it for a bit and it is excellent 👀

https://github.com/electron/electron/issues/new/choose

**Comment by bnb** [comment]
closing this since it's public and used by us already 👍🏻
