### ISSUE TITLE
Use `ncu-team sync` to maintain list of members in WGs/teams' README

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#61]
Hi all, node-core-utils @ v1.10.0 just released with a new tool `ncu-team` that automatically updates the list of members in a document with members of a Github team. See [the documentation](https://github.com/nodejs/node-core-utils/blob/master/docs/ncu-team.md) for details.

I have already opened https://github.com/nodejs/diagnostics/pull/147 to use this since the original idea came from @mhdawson in https://github.com/nodejs/diagnostics/issues/127#issuecomment-349404400 . I propose we start using it for other teams and WGs so we can better keep these membership stuff in sync.

BTW: the bot idea in https://github.com/nodejs/diagnostics/issues/127#issuecomment-349404400 is going to be harder to implement because that requires an organizational webhook, which we currently [do not allow](https://github.com/nodejs/github-bot#nodejs-github-bot).

**Comment by joyeecheung** [comment]
Some WG/teams have emails of the members listed in their README, while some don't.  A lot of people don't put their emails in the Github profiles, which is why `ncu-team` does not list that by default. It can be tweaked to add the email from the user's github profile with an option, but I am wondering are those emails necessary in the README in the first place, or are people just following previous conventions?

IMO we don't really need to list the emails in the README other than in the node core (where there are actual code gets committed in the history). People update their emails from time to time, and having the email addresses scattered around in different READMEs means they will need to raise a lot of PRs to update those. If someone wants to know how to contact a member they can just go to their github profile page, which I believe people will usually take time to update.

**Comment by Trott** [comment]
@joyeecheung Should this stay open? If so, can we get a task list of what needs to happen?

**Comment by joyeecheung** [comment]
@Trott I think this can stay open for a little longer. Task list:

- [ ] Get a list of repos of teams and WGs (do we have a list for that? There is https://github.com/nodejs/TSC/blob/master/WORKING_GROUPS.md#current-working-groups but I can see there are some teams not included there)
- [ ] Update those repos with ncu-team if the teams/WGs are OK with that

**Comment by Trott** [comment]
@joyeecheung I'm closing stuff that's been inactive for over a year, but if you want to keep this open, just re-open. No justification needed!
