### ISSUE TITLE
Sentiment Analysis Bot

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#613]
Hi, friends.

I was asked today if we had ever considered using [sentiment-bot](https://probot.github.io/apps/sentiment-bot/). I know Tierney brought it up as an example in [a comment](https://github.com/nodejs/admin/pull/133#issuecomment-390791457) once. But I feel like we've had a more substantive discussion at some point, but I can't find it. Maybe I imagined it.

Anyway:

* Have we considered a sentiment-analysis bot for helping to moderate comments?
* What is/were concerns etc.?

Thanks!

@nodejs/moderation @nodejs/community-committee  @janeon 

For future readers: Feel free to close this issue if it seems like it has run its course. No need to hold it open.

**Comment by ljharb** [comment]
My concerns, if it alerted publicly, would be that automated things like this tend to have pretty glaringly bad false positives (when they have any). If it alerted privately, it might be a useful warning system.

**Comment by jasnell** [comment]
Have to agree with @ljharb ... I'd be +1 only if it alerts privately.

**Comment by nschonni** [comment]
Not actually sentiment analysis, but a light one for closing empty issues https://github.com/github/docs/blob/main/.github/workflows/check-for-spammy-issues.yml
