### ISSUE TITLE
Add calendar entry for HTTPS imports discussion

### ISSUE THREAD

**Issue by bmeck** [nodejs/admin#614]
I'm trying to get an entry added on 2021 June 10th 1PM-2PM [ UTC ] to the events calendar for the HTTPS imports discussion:

https://github.com/nodejs/node/discussions/36430#discussioncomment-753311

I do not have permissions to broadcast/record on the normal zoom so might need onboarding to do so.

**Comment by Trott** [comment]
I'm not sure who usually adds events to the calendar and would be comfortable doing this, but I'm going to guess that the folks who run the CommComm and TSC meetings do, so... @bnb @mhdawson Would either of you be comfortable doing this for Bradley?

**Comment by bnb** [comment]
Happy to do this. There is a list of calendar maintainers in the README of this repo, for future reference.

**Comment by bnb** [comment]
AFAIK I only have access to the CommComm Zoom. I would assume @mhdawson has access to TSC Zooms and can help onboard 😅

We will also need the Foundation to add your Google Account to the YouTube account for permissions to stream.

**Comment by Trott** [comment]
> There is a list of calendar maintainers in the README of this repo, for future reference.

I should probably be removed from that list and my permissions removed. As I wrote to Bradley privately: I have access to the calendar, but I don't ever add things to it and am not confident I would Do It The Right Way.

Alternatively, you can just tell me there's no wrong way to do it, and just add things, it's fine. :-D

**Comment by bnb** [comment]
> Alternatively, you can just tell me there's no wrong way to do it, and just add things, it's fine. :-D

There is no wrong way to add things. Everyone does it ad hoc, and if issues arise (they do!) we just solve them.

**Comment by mhdawson** [comment]
@nodejs/tsc, @nodejs/community-committee adding tagging you since this issue includes a request to add Bradley to zoom and youtube for streaming. If there are no objections by next week I'll assume we can move forward with onboarding @bmeck.

@bmeck can you remind me on Tuesday if you don't get an invite as a youtube maintainer on Tuesday ?

**Comment by bmeck** [comment]
@mhdawson sounds good

**Comment by bmeck** [comment]
@mhdawson was out last week due to things, seems nothing has been done here yet.

**Comment by MylesBorins** [comment]
I've made a calendar event, let me know if you need anything else (like a zoom call) setup or added to it

**Comment by mhdawson** [comment]
@bmeck you should now have a youtube invite as a manager which you'd need to stream.

Also have send email to Brian asking that he share the zoom credentials with you.
