### ISSUE TITLE
deprecating the external node-inspect module

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#616]
I can't imagine anyone will object, but I've requested that @jkrems or someone else with publication access to the module deprecate `node-inspect`. See https://github.com/nodejs/node/discussions/36481#discussioncomment-789619 for discussion and context.

@nodejs/tsc @nodejs/community-committee @nodejs/diagnostics 

Future reader: Please close this (if you have sufficient access) if no one has commented for more than 3 days or something like that.

**Comment by mhdawson** [comment]
It's been 5 days, closing as requested.
