### ISSUE TITLE
`NPM_TOKEN` for `node-core-utils` to auto publish to npm

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#618]
Request to create a `NPM_TOKEN` on `node-core-utils` containing an npm automation token for the [nodejs-foundation](https://www.npmjs.com/~nodejs-foundation) npm user so that we can [automate releases](https://github.com/nodejs/node-core-utils/pull/511/files) for node-core-utils.

Requires 2 approvals from @nodejs/tsc and 2 approvals from @nodejs/community-committee.

**Comment by richardlau** [comment]
This would be a change in policy:
https://github.com/nodejs/admin/blob/main/npm-management.md
> The purpose of the `nodejs-foundation` user is not to enable Build Workgroup members to publish npm modules, that should be left to the module collaborators.

**Comment by mmarchini** [comment]
Either that or create a new user for each module (saving the credentials on 1password/lastpass), which is a pain but would prevent the "token can publish any module" security concern.

**Comment by Trott** [comment]
I'm 👍 on this, and would also happily 👍 something that clarified the policy.

**Comment by mhdawson** [comment]
It was the ""you shouldn't login into this user to publish the module manually" part that was intended.

I think for auto publishing this makes sense, and I don't see why we'd create another user. I'm +1 to this as well.

**Comment by joyeecheung** [comment]
> saving the credentials on 1password/lastpass

Don't we do that sort of thing with the secrets repo using dotgpg?

**Comment by bnb** [comment]
+1

**Comment by targos** [comment]
@mhdawson 

1. Go to https://www.npmjs.com/settings/nodejs-foundation/tokens/new
2. Enter the nodejs-foundation account's password
3. Name: `NPM_TOKEN secret to publish node-core-utils` ?
   Type: "Automation"
   Click "Generate Token"
4. Copy the generated token (it starts with "npm_")
5. Go to https://github.com/nodejs/node-core-utils/settings/secrets/actions/new
6. Name: NPM_TOKEN
   Value: the token you copied at 4.
   Click "Add secret"

**Comment by mhdawson** [comment]
@targos ok, done but not sure that will be enough since 2FA is enabled.

**Comment by targos** [comment]
It should be fine. Automation tokens bypass 2FA.

**Comment by targos** [comment]
> @targos ok, done but not sure that will be enough since 2FA is enabled.

Looks like you were right: https://github.com/nodejs/node-core-utils/runs/5885136215?check_suite_focus=true

I don't know what's blocking it, though. I have setup automation tokens without issues before (on an account that has 2FA enabled too).

**Comment by targos** [comment]
I checked on https://www.npmjs.com/package/node-core-utils/access and the package doesn't enforce 2FA so I really don't know what's wrong.

**Comment by targos** [comment]
`nodejs-foundation` also has access:
![image](https://user-images.githubusercontent.com/2352663/163345602-c724532d-6302-44b2-bd06-b35a956b895f.png)

**Comment by targos** [comment]
@mhdawson are you sure that you didn't create a publish token instead of an automation token?

**Comment by mhdawson** [comment]
@targos I thought I followed your instructions above exactly. What would be the difference between the two (ie what did I miss in the instructions above that would result in a publish instead of automation token). Once I understand that I can try again.

**Comment by aduh95** [comment]
See https://github.blog/changelog/2020-10-02-npm-automation-tokens/

An **automation token** will bypass the 2FA when publishing, while the **publish token** will not:
![screenshot from npm website](https://i0.wp.com/user-images.githubusercontent.com/1130014/94804251-6cee9780-03e2-11eb-9380-f18a7b410b9b.png?ssl=1)

**Comment by mhdawson** [comment]
@aduh95 k thanks, updated and I should have it correct this time.

**Comment by targos** [comment]
It worked this time: https://github.com/nodejs/node-core-utils/runs/6081510688?check_suite_focus=true
Thanks!
