### ISSUE TITLE
Create ‘actions’ team

### ISSUE THREAD

**Issue by mmarchini** [nodejs/admin#619]
Requesting creation of the `@nodejs/actions` team to be used as code owner for all actions and action scripts (`tools/actions` on `nodejs/node`).

**Comment by mmarchini** [comment]
We don't seem to have documented requirements to create a new team in our [Teams section of the GitHub Org Management Policy](https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md#teams), so I'll just go with no objections for 72h to create the team. (code ownership of actions will be decided in a PR on `nodejs/node`, as usual).

cc @nodejs/community-committee @nodejs/tsc

**Comment by targos** [comment]
+1

**Comment by bnb** [comment]
+1. I think the reason there's no documentation for just creating teams is that they're *usually* associated with other groups, like committees.

Also, I'd be happy to participate in this 😅

**Comment by mhdawson** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by mmarchini** [comment]
Done
