### ISSUE TITLE
Request for oauth credential for AWX instance

### ISSUE THREAD

**Issue by AshCripps** [nodejs/admin#620]
As part of https://github.com/nodejs/build/issues/2550 im setting up a AWX install to allow for us to have this new team run specific playbooks etc to help fix common CI issues without having to wait for a build member. This would also allow the build team to stay more on top of our ansible scripts with more regular running.

The plan for the AWX instance is for it to sit at ansible.nodejs.org (The DNS entry should still exist)

link to AWX: https://github.com/ansible/awx (Its the open source upstream of Ansible Tower)

cc @nodejs/build

**Comment by targos** [comment]
What kind of credentials are needed?

**Comment by AshCripps** [comment]
an Oath app similar to the grafana one I assume: https://github.com/nodejs/build/issues/2370

**Comment by targos** [comment]
OK, SGTM

**Comment by mhdawson** [comment]
+1

**Comment by AshCripps** [comment]
as its been over 2 weeks can I assume this has been approved?

**Comment by mhdawson** [comment]
Created the new oauth application and gave credentials to @AshCripps, closing.
