### ISSUE TITLE
Access to Node.js Youtube and Zoom account for @KevinEady 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#622]
I'd like to get @KevinEady access so that he can help chair the node-api team meetings. He's a long time Node-api team members and has volunteered to chair when necessary (Thanks!).

Unless there are objections by Friday July 2nd, I'll go ahead and give him access to the youtube account and ask Brian to give him Zoom access.

@nodejs/tsc, @nodejs/community-committee let me know if you have any concerns.

**Comment by mhdawson** [comment]
@brianwarner can you give @KevinEady the password for the Node.js zoom account so that he can stream?

**Comment by mhdawson** [comment]
Invited Kevin as manager for Node.js youtube account so that he can stream.  @KevinEady and invite should be in your inbox.

**Comment by brianwarner** [comment]
Sure, we use LastPass to share the credentials. @KevinEady can you please set up an account if you don't have one already, install the browser extension, and send me an email at operations@openjsf.org with the email address you used?

**Comment by KevinEady** [comment]
Hi all,

@brianwarner, I have sent an email and @mhdawson, I have accepted the invitation.

**Comment by brianwarner** [comment]
Good deal, thanks Kevin. Invite is on its way.

**Comment by KevinEady** [comment]
Hi @brianwarner ,

I have received and accepted the LastPass share. If there is nothing else, I think we can close this issue...?

Thanks!

**Comment by mhdawson** [comment]
Closing since it seems to be set up for @KevinEady
