### ISSUE TITLE
Temporarily make brianwarner an owner for the nodejs org

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#627]
Doesn't feel right doing this without getting at least a few 👍 reactions from TSC and CommComm folks, so posting here:

Brian Warner needs to set up a secret for some calendar integration stuff. So he needs to be Admin in the org at least briefly. As most (all?) of you will know, Brian is employed by the OpenJS Foundation and Linux Foundation as Program Director.

If we could get some pile-on 👍 's on this from @nodejs/tsc and @nodejs/community-committee members, that would be great. I don't want to keep Brian waiting but I also don't want to give TSC and CommComm zero notification that this is happening.

Obviously, if you are opposed, please leave a comment (and maybe throw in a 👎 so it's not missed).

**Comment by Trott** [comment]
Oh, and if someone else is working with Brian on this and feels like there is sufficient evidence of consensus, by all means, go ahead and temporarily elevate Brian's privileges and then close this issue. Thanks.

**Comment by mcollina** [comment]
sgtm

**Comment by bnb** [comment]
sgtm though I'd prefer that in the future a chair of TSC or CommComm work with the Foundation to do this rather than needing to go down the path of granting someone else additional access.

**Comment by Trott** [comment]
> @Trott has this been completed? If not I'll catch up with Brian to see what needs to be one.

I'm not sure. If you could ask @brianwarner if he still needs the elevated access or if things are complete, that would be great. (Or perhaps he'll reply in here. Either way!)

**Comment by mhdawson** [comment]
@brianwarner when you have time please DM me through slack if you still need access/help.

**Comment by Trott** [comment]
I went ahead and removed Brian from the org again.

@brianwarner If you still need access, get in touch! (DM Michael, email me, or whatever.)
