### ISSUE TITLE
removing all non-Trail-of-Bits folks from security-external

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#631]
I'd like to propose removing all the non-Trail-of-Bits folks from @nodejs/security-external. They are all awesome folks, but none of them are routinely involved in security stuff with Node.js, and we can always add them back in for individual items where we need their involvement.

@nodejs/tsc @nodejs/community-committee

**Comment by bnb** [comment]
+1.

**Comment by mhdawson** [comment]
+1

**Comment by Trott** [comment]
Done. Other things to do:

* Remove people who are on 0 teams from nodejs-private. (They'll get an email notification about that so we probably want to give them a personal email heads up first.)
* Clean up "outside collaborators" and "pending invitations" in both nodejs and nodejs-private.
