### ISSUE TITLE
Adding Docker Hub folks to nodejs/docker

### ISSUE THREAD

**Issue by nschonni** [nodejs/admin#633]
Left this one sitting around for awhile https://github.com/nodejs/docker-node/issues/1474
Since @tianon and @yosifkit maintain the upstream official images and contribute to the discussion on issues an PRs, it makes sense to add them to the team.
Since they're not currently part of the nodejs org, I can't directly invite them, so I'm opening the issue here.

/cc @nodejs/docker

**Comment by Trott** [comment]
Might be good to confirm with them that they have 2FA enabled on their GitHub accounts. The nodejs org is configured so that people can't be added unless they have 2FA enabled.

**Comment by tianon** [comment]
Yep, we both do.
