### ISSUE TITLE
archiving https://github.com/nodejs/node-convergence-archive

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#64]
I'd like to use GitHub's archive feature to archive https://github.com/nodejs/node-convergence-archive.

I'd also like to remove outside collaborators for that repo since there won't be any need for outside collaborators on a read-only repo.

Archiving can be undone so I don't think there's much need to tread with care here. 

If no one on @nodjes/tsc or @nodejs/community-committee objects in the next 72 hours, I'll do it after that. Or someone else can do it if I forget about this entirely. :-D 

Archiving is not explicitly addressed in our GitHub policy so I'm winging it here, but the 72-hours-with-no-objections rules makes sense to me. Happy to PR that in if others agree.

**Comment by joyeecheung** [comment]
SGTM

**Comment by oe** [comment]
fine by me!

**Comment by bnb** [comment]
No issue from me. We probably _should_ have an archiving policy, though.

**Comment by mhdawson** [comment]
SGTM

**Comment by Trott** [comment]
> No issue from me. We probably should have an archiving policy, though.

Two other things while we're talking about the policy:

* The policy should probably live in this repository rather than the TSC repository.
* The policy should be clear on who "owns" it. Currently, it seems to be the TSC. I'm fine with that, but I can see how CommComm might not be OK with the idea that the TSC can unilaterally change the policy without CommComm's input/approval. So maybe the policy needs something in it explaining the requirements for changes to the policy.

**Comment by jasnell** [comment]
SGTM

**Comment by Trott** [comment]
All done. Thanks, everyone!
