### ISSUE TITLE
Update commit queue token permission

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#640]
I've been trying to update the CQ to make it able to "purple-merge" PRs with the CQ. Before that, the CQ was using two tokens:
- @nodejs-github-bot's token to push the commits (@nodejs-github-bot is part of `@nodejs/collaborators`)
- `GITHUB_TOKEN` provided by @github-actions to comment/close on PRs

`GITHUB_TOKEN` is not allowed to merge PRs because it's not part of `@nodejs/collaborators`, so @targos tried to use @nodejs-github-bot's token to run the CQ. Unfortunately this didn't work:

```
GraphQL error: Your token has not been granted the required scopes to execute this query. The 'login' field requires one of the following scopes: ['read:org'], but your token has only been granted the: ['read:user', 'repo', 'user:email', 'workflow'] scopes. Please modify your token's scopes at: https://github.com/settings/tokens.
```
https://github.com/nodejs/node/runs/4131235476?check_suite_focus=true

_Originally posted by @aduh95 in https://github.com/nodejs/node/issues/40742#issuecomment-962623239_

I'm asking for permission to update the permissions to make the Commit Queue work correctly:

- `read:org`
- `notifications`

_For info, the current permissions for this token are `['read:user', 'repo', 'user:email', 'workflow']`._

**Comment by aduh95** [comment]
https://github.com/nodejs/admin/blob/87bc4060f3a034736f0edfd01b543d357ac0636a/GITHUB_ORG_MANAGEMENT_POLICY.md#L129-L136

Link to the CQ: https://github.com/nodejs/node/runs/4131235476?check_suite_focus=true

The app being already in use, asking for a fast-tracking this request. Please :+1: this comment to approve.

**Comment by targos** [comment]
Why do we need `notifications`?
Who can make the change (we should mention them)?

**Comment by aduh95** [comment]
> Why do we need `notifications`?

I'm not sure we need it, I've added it because of this sentence in GH REST API docs:

> Merge a pull request
> This endpoint triggers notifications.
_Source: https://docs.github.com/en/rest/reference/pulls#merge-a-pull-request_

It may or may not be necessary, but given the delay of 72 hours for the fast-tracked change to be approved, I thought adding it to the list would not hurt. We should try to only add `read:org` to that token and see if that's sufficient for the CQ, and only add `notification` if it is indeed required.

> Who can make the change (we should mention them)?

Maybe @mmarchini can help with that?

**Comment by targos** [comment]
Ping @nodejs/tsc

**Comment by Trott** [comment]
> Ping @nodejs/tsc

I 👍'ed the fast-track request. Is there anything else TSC should be doing with this?

**Comment by targos** [comment]
I think two 👍🏻 are enough. Now the difficult part will be to find someone who can do the change.

**Comment by aduh95** [comment]
I think anyone that has access to the @nodejs-github-bot GitHub account should be able to do that – the README mentions a 1password account, probably the credentials are there (I don't have access to it AFAIK).

https://github.com/nodejs/admin/blob/87bc4060f3a034736f0edfd01b543d357ac0636a/README.md#L48-L50

**Comment by Trott** [comment]
> I think anyone that has access to the @nodejs-github-bot GitHub account should be able to do that

@nodejs/github-bot

**Comment by phillipj** [comment]
For future ref, credentials to the github-bot account is in the secrets
repo.

I'll try to adjust the token as described above, before the weekend.

**Comment by phillipj** [comment]
<img width="771" alt="Screenshot 2021-11-12 at 22 39 47" src="https://user-images.githubusercontent.com/1231635/141537807-9432d6db-4df0-45f5-96f2-27858b25e048.png">

@aduh95 try again now?

**Comment by aduh95** [comment]
Just tried, and it works: https://github.com/nodejs/node/runs/4194822955?check_suite_focus=true 🎉  thanks a lot!
