### ISSUE TITLE
move bnb/devenv to nodejs/devcontainer

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#641]
per https://github.com/nodejs/node/issues/39672, it seems the next steps would be to move the [bnb/devenv](https://github.com/bnb/devenv) repository into the Node.js org and to PR the `.devcontainer` dir to nodejs/node. I'd recommend moving it to nodejs/devcontainer.

One thing to note, we'd need to grab a Docker Hub token to publish it to the Node.js Docker Hub account to publish the image. I presume we'll want to publish it to `nodejs/devcontainer` to match the repo. We _will_ need to choose some kind of name, which will need to be reflected in code [here](https://github.com/bnb/devenv/blob/main/.github/workflows/docker-build-and-publish.yml#L26).

Worth noting that this *will* consume some portion of our Actions minutes. In its first run, it took about an hour and a half to build and publish on the default 2 core runner. I've presently set it up to run nightly, though the cron can be changed through normal means in GitHub. I've talked a bit with the Actions team and it seems that we'd potentially be able to get dedicated runners for this workload - I'll follow up with them once we've moved the repo into the org ❤️ 

Happy to do this but want to get the appropriate approvals, of course :)

**Comment by bnb** [comment]
cc @nodejs/tsc

also @nodejs/docker potentially worth looking at this. I believe @Trott suggested that y'all might be a good set of stewards if you're okay with that.

**Comment by Trott** [comment]
@bnb Feel free to put a `tsc-agenda` label on this if there's no attention/conversation going on.

**Comment by mhdawson** [comment]
+1 from me

**Comment by jasnell** [comment]
SGTM

**Comment by mhdawson** [comment]
Based on discussion in the TSC meeting today and no objections in the issue believe we can move forward. @bnb if you make me an owner of the repo I can move it over.

**Comment by mhdawson** [comment]
@bnb I think we can close this right?

**Comment by bnb** [comment]
Yep!
