### ISSUE TITLE
Install Slack GitHub app for nodejs/node

### ISSUE THREAD

**Issue by MattIPv4** [nodejs/admin#643]
**Is your feature request related to a problem? Please describe.**

👋 Apologies if this isn't the best place (I thought about asking in Slack, but decided here might be better).

I would like to be able to use the Slack GitHub app to subscribe to releases from nodejs/node.

**Describe the solution you'd like**

Would it be possible for someone to install https://slack.github.com/ for nodejs/node, so that folks using the GitHub app in Slack can subscribe to releases etc. there?

**Describe alternatives you've considered**

- Creating a custom webhook workflow, which requires overhead to monitor for releases there, and then fire a webhook into Slack.
- Using the default RSS Slack integration with the GitHub releases RSS feed. This works, but doesn't provide the same level of integration/formatting as using the GitHub app.

**Comment by MattIPv4** [comment]
The app requests the following permissions:

- Read access to checks, code, commit statuses, metadata, and repository projects
- Read and write access to deployments, issues, and pull request

(Write access is used by the app to allow anyone to open an issue as themselves, to close issues/PRs that they have rights to close)

Ref: https://github.com/integrations/slack#about

**Comment by bnb** [comment]
As a heads up, this isn't actually a "new" app. It's already installed, and the Moderation team takes advantage of it. I've found it particularly useful as a tool to be instantly notified when a new issue is created in nodejs/moderation and there have been a few occasions where it's significantly sped up my ability to respond to incidents.

I fully support this being used in the OpenJS Foundation Slack and would greatly benefit from that myself, but one thing I'm not sure about is if it can be connected to multiple Slack teams.

**Comment by bnb** [comment]
@MattIPv4 which Slack org would you want this to be added to?

**Comment by MattIPv4** [comment]
I was looking to install this in my own Slack org, and had assumed that once it was installed as an app in the repo, anyone could subscribe to the repo using it.

However, given you're saying it's already installed (is it just installed in nodejs/moderation?), perhaps I'm wrong about how it functions -- might need to just stick to the RSS feeds instead.

**Comment by bnb** [comment]
> is it just installed in nodejs/moderation

yes you're correct, it is just installed there.

given that, going to close this. Feel free to reopen if me closing is erroneous :)
