### ISSUE TITLE
Create a .github repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#644]
Per the GitHub Org Management Policy, I'm requesting that we create a .github repo so that we can put a SECURITY.md file there that will appear in the GitHub interface for all nodejs org repos that do not already have a SECURITY.md repo.

Ref: https://github.com/nodejs/security-wg/issues/776#issuecomment-987610423

@nodejs/tsc @nodejs/security-triage 

Policy says this is automatically approved after 72 hours if there are no TSC member objections.

Thanks.

**Comment by Trott** [comment]
Also: @bnb @rcowsill

**Comment by nschonni** [comment]
There may be a few other files that make sense in the repo too https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/creating-a-default-community-health-file

**Comment by bnb** [comment]
SGTM. Might want to consider also migrating our CoC to just live there, since most checked in CoC files already point to this repo rather than actually checking in the CoC.

**Comment by Qard** [comment]
To be clear, is this suggesting a shared template or just generating a file that points to the equivalent on nodejs/node? Because a template added automatically at repo creation time could get out-of-sync over time, if I'm understanding right?

**Comment by ljharb** [comment]
Things in a .github repo transparently apply to any repos without shadowing files, so it would never get out of sync.

**Comment by bnb** [comment]
yep, the files aren't templates so much as context for GitHub's UI (for example, in the sidebar of the main repo page and in issues/PRs).

**Comment by mhdawson** [comment]
I'm +1 for adding the template. One issue though that I think we discussed earlier in the pkgjs repo is that if you clone the repo you don't get a copy of those files. At least my understanding is that you only see them in the UI.  We ended deciding we needed to keep a copy of things like the CoC in the repo as well so that you would have a copy in local clonse.

**Comment by bnb** [comment]
Yep, that is a tradeoff. The one caveat I'd present is that our _current_ CoC isn't actually a CoC: it's a link to our CoC. We've not actually got a CoC in any repo except nodejs/admin right now, and I'm not sure if the impact of the one/two links is the same as having a full CoC checked in to the source.

**Comment by ljharb** [comment]
Additionally, I'm not sure how important a use case it is for people to explore the local clone; if you're only working locally, you have no way to convey any conduct in the first place.

**Comment by Trott** [comment]
For things like a code of conduct, I think it makes sense to have a link in the README to the canonical document in the .github repo. And the CODE_OF_CONDUCT.md in the .github repo shows up in the UI. Same for SECURITY.md. We'll want to test this with a small number of repos first, but I feel like that's probably the way to handle it for all repos.

**Comment by bnb** [comment]
given that it's been a... lot longer than 72 hours, I've created the repo @trott.

https://github.com/nodejs/.github
