### ISSUE TITLE
Archiving nodejs/installer

### ISSUE THREAD

**Issue by nschonni** [nodejs/admin#646]
Was reminded that https://github.com/nodejs/installer is still open because I got a few notifications today.
Don't think there has been any activity there for a few years, and the last issues are probably things for nodejs/help to get routed somewhere better

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by targos** [comment]
+1 we can always unarchive if someone wants to resurrect the initiative.

**Comment by joyeecheung** [comment]
SGTM

**Comment by Trott** [comment]
Archived.
