### ISSUE TITLE
Adding jasnell to security-triage

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#647]
James has volunteered to help out with security triage. The process that the current security triage folks have sketched out for onboarding new members (https://github.com/nodejs-private/meta) includes TSC approval, even for folks who are already on the TSC. (The idea is to err on the side of being super-extra cautious and communicative.)

So...a bunch of TSC +1's or 👍's would be helpful. Thanks!

@nodejs/tsc @nodejs/security-triage

**Comment by richardlau** [comment]
+1

**Comment by mcollina** [comment]
👍

**Comment by danielleadams** [comment]
👍🏼

**Comment by joyeecheung** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
@Trott this has been open for quite some time and on the TSC agenda for a number of weeks as well. While more +1s would be nice there are are some and no objections so I'm comfortable that we can declare TSC consensus and close out the issue?

**Comment by Trott** [comment]
Yeah, let's remove it from the TSC agenda. It's on my list of Stuff To Take Care Of, and I'll get to it this week, although don't let me stop you if you want to do it. I documented a checklist for onboarding somewhere.

**Comment by Trott** [comment]
I've added James to the relevant teams etc. We'll figure out where to put him in the schedule and everything, but for now, this can be closed.

Thanks for volunteering, James!  🎉
