### ISSUE TITLE
Archive mentorship repo, remove team, remove links in other places

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#658]
Hi, everyone. Based on the lack of activity in https://github.com/nodejs/mentorship and https://openjs-foundation.slack.com/archives/C0120JLG02H, it seems to be time to sunset the mentorship program and archive that repository and Slack channel.  If we archive the channel and repo, we can always unarchive them if/when things get restarted. I don't think it's good to have people popping into the channel asking about stuff and not getting a reply. Nobody owes it to us to run a mentorship program or to be a mentor in such a program, and I'm very grateful for all that has happened. I just don't want to have people show up and find a dormant program.

@nodejs/tsc @nodejs/mentorship

**Comment by danielleadams** [comment]
+1 if those that are/were involved are also +1

**Comment by Trott** [comment]
Archived the repo, deleted the team (4 members: @davidguttman, @detrohutt, @demola07, and @LonelyTree), requested the Slack channel be archived, removed folks who aren't on any other teams. Thanks, everyone, and happy to spin this all up again if there's activity/energy that warrants it.

Still TBD: Remove links and mentions where they appear in other repos, especially the website.

**Comment by Trott** [comment]
> Still TBD: Remove links and mentions where they appear in other repos, especially the website.

Did a quick search and didn't find anything.
