### ISSUE TITLE
zoom/stream access for @thescientist13 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#665]
@thescientist13 has volunteered to chair/stream package-maintenance teams meetings when needed.

Would like to get him zoom/youtube access so that he can do that. 

@thescientist13 - link to streaming instructions - https://github.com/nodejs/TSC/blob/main/Streaming/Streaming-To-Youtube.md

**Comment by mhdawson** [comment]
@thescientist13 I'll try to check back on the issue by the end of this week, if you don't see me doing that feel free to remind me.

**Comment by thescientist13** [comment]
Thanks @mhdawson .  For that doc, is there any value in adding notes for running the meeting itself?  Like maintaining / creating the word document, turning that into a markdown / file PR?  Or is it that handled differently per WG?

**Comment by mhdawson** [comment]
I think a lot of wg/teams use the common approach. Documenting it as a suggestion/recommendation makes sense to me. In the above I'd say google doc instead of word doc.

**Comment by mhdawson** [comment]
@brianwarner can you set @thescientist13 with access to the zoom credentials?

**Comment by mhdawson** [comment]
Added @thescientist13 to youtube as manager using email listed in github

**Comment by mhdawson** [comment]
PR to add to zoom email list - https://github.com/nodejs/email/pull/184/

**Comment by brianwarner** [comment]
@thescientist13 For the time being, we're using lastpass to manage the credentials. Can you please set up an account and let me know which email you used for it? You can contact me directly at operations@openjsf.org if you prefer.

Also, we'll soon be moving to 1Password, so unfortunately this is only going to be temporary, but it will at least get you access to the account.

**Comment by thescientist13** [comment]
Sorry for the delay in replying!   Emailing you now @brianwarner

**Comment by mhdawson** [comment]
@thescientist13 do you have everything in place now? Just checking before I close this issue.

**Comment by thescientist13** [comment]
I do, thanks @mhdawson / @brianwarner !
