### ISSUE TITLE
Create @nodejs/test_runner team

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#671]
We have already `@nodejs/testing`, maybe `@nodejs/test` would be too close? Anyway, I think it would make sense to create a GitHub team for folks who want to subscribe to changes related to the new `node:test` module.

**Comment by ljharb** [comment]
I’d like to be on it. We should be sure to include all maintainers of the top ~10-20 test frameworks in the ecosystem on all such discussions (and probably should have prior to landing anything)

**Comment by juliangruber** [comment]
I'd like to be on it as well, for https://github.com/juliangruber/node-core-test

**Comment by aduh95** [comment]
This been opened for 7 days with no objections, I went ahead and created @nodejs/test_runner. Closing now.
