### ISSUE TITLE
Give Alix Robinson from Linux Foundation access to youtube account

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#673]
I'd like to get Alix access to the Node.js youtube account so that the data for top videos can be shared in the board meetings versus just what is in the OpenJS youtube as I personally believe that does not properly represent what people are interested in/watching on its own.

**Comment by mhdawson** [comment]
@arobinsonLF FYI.

**Comment by mcollina** [comment]
SGTM

**Comment by gireeshpunathil** [comment]
+1

**Comment by mhdawson** [comment]
@arobinsonLF  you should have an invite adding you as a manager for the Node.js youtube account.

**Comment by mhdawson** [comment]
Done, closing.
