### ISSUE TITLE
Enable nodejs/node Discussions as Org Discussions

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#679]
GitHub launched a feature today that enables you to select a repo's Discussions tab to be set as the org Discussions tab. Given that nodejs/node is the most active/relevant set of Discussions, I'd really like to recommend we set nodejs/node's Discussions tab as the org discussions.

Context here: https://github.blog/2022-04-12-whats-new-in-github-discussions-organization-discussions-polls-and-more/

**Comment by targos** [comment]
SGTM

**Comment by nschonni** [comment]
Don't feel strongly about it, but https://github.com/nodejs/help might be another candidate

**Comment by mhdawson** [comment]
SGTM

**Comment by bnb** [comment]
@nschonni my idea with this is that org discussions could likely replace nodejs/help :)

**Comment by ljharb** [comment]
We could presumably make nodejs/help’s discussions *be* the org’s discussions, and then there’s a nice transition.

**Comment by nschonni** [comment]
@bnb that could work, but might need to confirm the permissions required. Currently the website folks and a few non-core contrib folks can transfer issues into nodejs/help when the are accidentally created there. That could always get sorted later though

**Comment by bnb** [comment]
> We could presumably make nodejs/help’s discussions be the org’s discussions, and then there’s a nice transition.

The challenge I see with this is that people _will_ default to discussions on nodejs/node, and in general that seems to be where project members have also been most active. I think nodejs/node makes a lot more sense than nodejs/help, since help IMO should only be an _aspect_ of discussions, not the entirety.

**Comment by bnb** [comment]
> @bnb that could work, but might need to confirm the permissions required. Currently the website folks and a few non-core contrib folks can transfer issues into nodejs/help when the are accidentally created there. That could always get sorted later though

hmm good point, I might be able to make an action that could do this but yeah perms might be an issue for that.

**Comment by Trott** [comment]
@nodejs/tsc I'd like to enable org-wide discussions (and we can shut them off again if they cause problems, but at least we'll know what the problems are then and can work to adjust things). Any concerns with turning it on some time this week?

**Comment by Trott** [comment]
I've added the tsc-agenda label because I'd like to get this enabled this week. If we can make the decision asynchronously, then great, but if there's a meeting this week, it would be great for there to be 30 seconds for anyone that has objections or concerns to voice them (although it's preferable if they put them here first/instead).

**Comment by mcollina** [comment]
sgtm

**Comment by ronag** [comment]
sgtm

**Comment by Trott** [comment]
Org discussions enabled with the nodejs/node repo selected as as the source repository for discussions.
