### ISSUE TITLE
Add @Qard to those who can stream to youtube

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#681]
@Qard will chair some Diagnostics WG meetings.

We'll need to add him as a youtube manager and get him access to the Zoom credentials.

Unless I hear objects in the next few days I'll go ahead with that.

@nodejs/tsc FYI

**Comment by mhdawson** [comment]
I don't see any objections think it's unlikely we'll get any.  

@brianwarner could you give @Qard access to the Zoom secret?

@Qard you should have received an invitation as a manager for the Node.js youtube account.

**Comment by brianwarner** [comment]
@qard can you send me an email at operations@openjsf.org and let me know which Google account you'll use for this?

**Comment by brianwarner** [comment]
Just following up, this is done.

**Comment by mhdawson** [comment]
@brianwarner many thanks.  I also got the email telling me that @Qard was a manager of Node.js so I think this is done, closing.
