### ISSUE TITLE
Youtube and Zoom access for @RafaelGSS

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#684]
@RafaelGSS is going to chair security wg meetings. To do that he'll need acess to the Zoom credentials and be a youtube manager.

Unless there are objections I'll make him a youtube manager and ask Brian to share the Zoom credentials.

@nodejs/tsc

**Comment by mhdawson** [comment]
I plan to start getting him access by Thursday unless there are concerns raised.

**Comment by mhdawson** [comment]
Added @RafaelGSS as a manager of youtube account.

@brianwarner can you give @RafaelGSS access to the zoom account credentials.

**Comment by RafaelGSS** [comment]
All good!

**Comment by mhdawson** [comment]
@RafaelGSS thanks for confirming, closing.
