### ISSUE TITLE
Storing the Zoom credentials

### ISSUE THREAD

**Issue by brianwarner** [nodejs/admin#685]
LF just switched from LastPass to 1password, and while we've gained many things in the process, I'm told that credential sharing outside of the LF org is limited to 30 days at a time. Apparently this is currently the max supported by 1password.

The Node.js Zoom account is shared out to many people in the project, so it's not exactly a state secret. Is there a central place for the project to keep the credentials so they can be directly shared when you add a new meeting chair?

**Comment by JakobJingleheimer** [comment]
Do we (or whatever "LF" is) have a 1Password org? If so, people can be added to the org and then there is no 30-day limit.

**Comment by Trott** [comment]
> or whatever "LF" is

Linux Foundation

**Comment by mhdawson** [comment]
@rginn do you know if the suggestion of adding people to the LF org work?

**Comment by mhdawson** [comment]
Getting a 1Password org for the Node.js project would likely make sense.  Is that something that it would make sense for the Foundation to get/setup/have backup access for or would the expectation be that we do that on our own?

**Comment by mhdawson** [comment]
The password is now shared in 1Password and I've done that for new people added.  I'm going to close this.
