### ISSUE TITLE
Youtube and Zoom access for @JakobJingleheimer (me)

### ISSUE THREAD

**Issue by JakobJingleheimer** [nodejs/admin#687]
For when @geoffreybooth and @bmeck can't attend the Loaders team meeting (such as today—we postponed, so no rush).

**Comment by Trott** [comment]
@nodejs/tsc Not sure who usually gets pinged on these kinds of requests.

**Comment by mhdawson** [comment]
@Trott I think any existing youtube manager can add people as additional managers. We then have asked Brian Warner to share the zoom credentials.

I generally leave it for a few days in case there are any concerns/objections and then add as a youtube manager, and ask Brian to share.  @Trott I think you could do the same, if not I'm sure I could tweak the youtube permissions so you could.

**Comment by Trott** [comment]
> @Trott I think any existing youtube manager can add people as additional managers. We then have asked Brian Warner to share the zoom credentials.
> 
> I generally leave it for a few days in case there are any concerns/objections and then add as a youtube manager, and ask Brian to share. @Trott I think you could do the same, if not I'm sure I could tweak the youtube permissions so you could.

Given that @brianwarner's last day at the foundation is Friday, maybe we should expedite this (or find out who to send these kinds of requests to instead going forward).

**Comment by mhdawson** [comment]
As I was typing I was not sure how public that was. I agree if we can expedite it would be good. @brianwarner can you do the share now ?  I also asked Brian what we would do in the future but we've not closed on that yet.

**Comment by Trott** [comment]
> As I was typing I was not sure how public that was.

Oh, shoot, yeah, I thought that was widely known. I'm sorry. I'll edit my comment just in case....

**Comment by mhdawson** [comment]
I don't see any objections/concerns so adding @JakobJingleheimer to the youtube managers.

**Comment by mhdawson** [comment]
Or not. @JakobJingleheimer could you email me the right email to use to add you, don't see one in your github profile.

**Comment by mhdawson** [comment]
@JakobJingleheimer can you also PR yourself into the zoom-nodejs section in  https://github.com/nodejs/email/blob/main/iojs.org/aliases.json ? Once you do that I'll get you the zoom password.

**Comment by JakobJingleheimer** [comment]
done, thanks! nodejs/email#190 (I can't add you as a reviewer O.o)

**Comment by mhdawson** [comment]
@JakobJingleheimer pefect, thanks. Zoom info sent through OpenJS slack.
