### ISSUE TITLE
New label `membership changes` across the org?

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#69]
I propose we use a label across the organization to track membership changes: e.g. Node.js core collaborator nominations, TSC nominations, membership changes in other working groups/teams, so it's easier to find those issues and review them at the end of a year.

**Comment by joyeecheung** [comment]
cc @nodejs/tsc @nodejs/community-committee

**Comment by oe** [comment]
Is there an established process for reviewing them at the end of the year?

**Comment by joyeecheung** [comment]
@oe I don't think so, but I think @Trott does some review from time to time.

**Comment by Trott** [comment]
> @oe I don't think so, but I think @Trott (or @jasnell ?) does some review from time to time.

No established process, but I look through teams nearly every day to try to identify obsolete teams and sometimes obsolete members. Usually I have some goal in mind (like making sure access to the moderation repository is reasonably locked down or trying to make it so the members team does not need to be manually curated anymore). I'm not just kind of going through things looking for something to do. :-D

**Comment by mcollina** [comment]
I'm 👍 in a 'membership changes' label

**Comment by jasnell** [comment]
Sgtm

**Comment by bnb** [comment]
Is this exclusively membership changes in terms of members of a committee, WG, initiative, or team, or does it also include membership _in_ a committee (like that of an initiative like i18n being a "member" initiative of the CommComm)?

Additionally, with new repos spinning up, is there a way to automate adding labels? I know there've been discussions in the past of having `good-first-issue` as a global label, but looking at some newer repos (like [modules](https://github.com/nodejs/modules/labels)) it's not included.

If there's _not_ a way to automate this, we should codify the org-wide repo guidelines/requirements as a doc in this repo and link to it from both the CommComm and TSC.

**Comment by joyeecheung** [comment]
@bnb There is https://github.com/repo-utils/org-labels haven't tried it out yet though.

**Comment by bnb** [comment]
@joyeecheung may be worth pinging @Fishrock123 to see if it's still usable 😅

**Comment by dshaw** [comment]
I think this would be useful. I imagine we may want to get more granular in the future, but don't think we want to get ahead of ourselves.

**Comment by mhdawson** [comment]
SGTM

**Comment by obensource** [comment]
Sounds good! 👍

**Comment by keywordnew** [comment]
Reading the consensus so far, folks seem in favor of labels and automation. 

@Fishrock123 Would it be advisable to use https://www.npmjs.com/package/org-labels to manage labels org-wide?

**Comment by bnb** [comment]
going to close this since it's been ~4 years and several folks involved aren't involved anymore. I'm +1 to this change but it seems like we've not implemented it. I'd be happy to see it revived/implemented.
