### ISSUE TITLE
Revisiting membership expectations

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#693]
Some things I would like the TSC to consider modifying in the membership expectations.

## Mixed signals

First, there is a confusing (or at least confusing-to-me) mix of signals. For example:

> Members of our leadership groups must also conduct themselves in a professional and respectful manner. Some general guidelines include:

The juxtaposition of "must...conduct themselves" with "general guidelines include" leaves things very open to interpretation. (If that is inevitable then let's acknowledge it.)  There is a "must" requirement, but then a "general guidelines" list. 

## Unclear responsibilities

People are told to report "leadership acting outside of the expectations" to the moderation team. That makes sense on one level, in that reporting a violation by a TSC member to the TSC has obvious problems. But (going out on a limb a bit by speaking on behalf of @nodejs/moderation team--members of that team, please comment with contrary opinions if you disagree!) moderation team doesn't consider member expectations as part of their purview. Moderation team considers itself responsible for the Code of Conduct.

## Unclear sanctions

Even if moderation team is responsible for enforcing member expectations, it's not clear what the tools they have are. It does not seem that the (typically serious) sanctions available for Code of Conduct violations would always be useful or applicable here.

**Comment by mhdawson** [comment]
> Unclear responsibilities

I'm in agreement that we should not point reports to the @nodejs/moderation team. 

> Unclear sanctions

I think these guidelines are valuable in terms of setting the expectations for those on the TSC, but I'm not sure we need a reporting/sanctions process to go along with them. 

As with many things in the context of the history in which they were added, the content was wordsmithed/agreed but much of that context no longer applies/makes sense so an update would be good.

**Comment by mcollina** [comment]
I agree we should update those and simplify things.

**Comment by bnb** [comment]
> I think these guidelines are valuable in terms of setting the expectations for those on the TSC, but I'm not sure we need a reporting/sanctions process to go along with them.

What's the point of having them, then?

**Comment by Trott** [comment]
Perhaps someone can report issues to the TSC but told that they can also report it to any individual TSC member so that they don't have to report TSC member violations to the entire TSC.

**Comment by Trott** [comment]
In TSC meeting today, it was pointed out that whoever gets the reports should also have clear processes in place to handle them.

**Comment by Trott** [comment]
> In TSC meeting today, it was pointed out that whoever gets the reports should also have clear processes in place to handle them.

And it should include an escalation process, perhaps involving escalation to the OpenJS Foundation somehow.

**Comment by MylesBorins** [comment]
The important thing here is to not lose that it is important that leaders are held accountable for things above and beyond the baseline code of conduct.

I don't think this needs to be explicitly defined process, a code of conduct issue should go through the normal process... those in leadership should be held to a higher bar.

**Comment by mhdawson** [comment]
I do think there is value in providing expectations even if we don't include a "here is how we punish you if you don't follow them".  I'm not necessarily opposed to that but I think we get the most value by establishing that there is a higher expectation.  

The doc already says `This is especially important in external communications, for example in social media. Should the member be unwilling or unable to do so, then they should resign their leadership position.` so it should be clear that the outcome of not following them could be being asked to resign from the leadership position.

I do think saying you can report behaviour that you don't think is appropriate to individual TSC members instead of the moderation committee makes sense.

**Comment by mhdawson** [comment]
> Members of our leadership groups must also conduct themselves in a professional and respectful manner. Some general guidelines include:

I don't actually see this as a conflict. The first line says more generally that those in leadership must conduct themselves in a professional and respectful manner.  The following lines provide some concrete examples of what in some cases be considered either profession/respectful or not. I don't see that providing some examples should limit/the first line. We might update the language to make it a bit clearer that what is listed is not exhaustive and also depends on context.

In case the suggestion of just removing them comes up, I don't think that's a good idea as the goal is to help people understand the expectations and I the list was useful in doing that in the past.

**Comment by Trott** [comment]
> I don't actually see this as a conflict.

I described it as "mixed signals". While that does indeed imply "conflict" or "contradiction" and you are correct that those things do not strictly contradict each other, that fact doesn't resolve the issue I was trying to raise.  *The document is written as something to be enforced* on the one hand, and *avoids being definitive about what the behaviors are that are to be sanctioned* on the other hand. Those are the "mixed signals" to which I was referring and that's what makes it challenging to enforce. 

The phrase "must also conduct themselves in a professional and respectful manner" is redundant in that it is already in the code of conduct. Moreover, it's presence in this document implies that people who are not in leadership do not need to conduct themselves in a professional and respectful manner. For that reason, I think removing that sentence is appropriate.

**Comment by Trott** [comment]
> For that reason, I think removing that sentence is appropriate.

Maybe better than that would be acknowledging that the sentence applies to everyone. I'll open a PR to do that now.
