### ISSUE TITLE
Decharter the Addon API WG? Remove the nodejs/addon-api team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#70]
The addon-api team (https://github.com/orgs/nodejs/teams/addon-api/members) would seem to be superseded by the n-api team (https://github.com/orgs/nodejs/teams/n-api/members). Should it be removed? Or should it remain for issues with the legacy API?

Whether or not the team should remain, is it active as a working group? As far as I know, it is not. If it is not active, the TSC should probably de-charter it. 

@nodejs/addon-api @nodejs/tsc @nodejs/community-committee

**Comment by addaleax** [comment]
> Whether or not the team should remain, is it active as a working group? As far as I know, it is not. If it is not active, the TSC should probably de-charter it.

Yes, I think it should be de-chartered.

It might be useful to keep it around as a team for mentions – which has basically no cost, right? – but realistically most of the notable API changes in recent times have come from the V8 side anyway.

**Comment by Trott** [comment]
OK, I'll leave the team intact and leave it to someone else if they wish to de-charter that WG at this time. Closing!
