### ISSUE TITLE
Add Claudio Wunder as Member for Node.js Dev (Website Redesign)

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#700]
Hey there 👋 hope y'all are doing fine :)

I've been contributing recently and getting familiar with the whole Node.js Website Redesign initiative and doing strong contributions towards it. After finally getting some big features merged and getting confident with the codebase and getting familiar with the context behind the website (such as some of the motivations, the design, the currently missing features, et cetera), I'd really like to be an active member and work towards getting the Website Redesign initiative in a closed path to being released.

The Node.js website deserves some love, and it is completely understandable that with everything that happened between 2019-now (pandemics, et cetera) there were not enough people to be able to maintain it.

Node.js is a project that from a technical standpoint is a tool that I use daily. And I definitely want to give back to this project in ways I believe I can add and do some impact.

I wish to continue to contribute to the Node.js Project and actively work towards shipping features and making this long-deserved website to get published.

Sadly, there are things out of my reach right now, such as, not knowing who are the right people to ask about Design, and Copy-writing, and who are the right people to ask about general feedback.

Through this Issue: https://github.com/nodejs/nodejs.dev/pull/2505 I'd like to formally request to become a member of the Node.js project and work towards the Website Redesign project and who knows more :)

FYII: I'd really like to know if there are any weekly or ongoing meetings to discuss the website.

I'm more than happy to chat over Matrix: `@ovflowd:gnome.org`.

Cheers,
Claudio W

/cc @benhalverson @bnb @Trott @nschonni

**Comment by Trott** [comment]
Invitation sent.
