### ISSUE TITLE
New repo called  nodejs-dependency-vuln-assessments

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#704]
Requsting a new repo called `nodejs-dependency-vuln-assessments` based on some discussion with @mcollina and @RafaelGSS. FYI @facutuesca

This repo wil be used for

1. Running an action to check for vulnerabilities that are already public in Node.js dependencies using - https://github.com/nodejs/node/commit/07411da64f23b427b517bf7ccf85f26c986acd98
2. Manage assessments of the vulnerabilities aleady publicly reported. We would open an issue with assessments of vulns (either reported by the action or otherwise) as a way to share info more broadly. For example if there is a vuln in a dep, but it does not apply to Node.js we could open an issue which states that along with the assessment that provides supporting info. We could then promote by adding an announce on the website and a note to nodejs-sec or just by pointing to the repo as the place to get answers to questions about vulnerabilities people see being reported (not sure which would be best yet).

All incomming reports (ie not already public and with a public CVE) would still be handled through H1.  This repo woud be only about being ready for "what about vuln X in a Node.js depenency that has been reported publicly" and having a place for the answers so that we can share them, or even not have to do anything because people can find the answer themselves in an existing issue.

**Comment by richardlau** [comment]
+1.

Re.

> 1. Running an action to check for vulnerabilities that are already public in Node.js dependencies using - [nodejs/node@07411da](https://github.com/nodejs/node/commit/07411da64f23b427b517bf7ccf85f26c986acd98)

If we're running the action in this new repository I would suggest we move the script into the new repository and decouple it from the Node.js source tree. That would avoid us having to backport the script to earlier release lines if we want to run the checker on those.

**Comment by mhdawson** [comment]
@richardlau you can take a look at the original PR. I asked if it made sense to included it in the Node.js repo and was convinced it made sense as dependencies etc. can be different for different Node.js versions etc.

**Comment by mhdawson** [comment]
ok no objections to create repo, moving forward.

**Comment by mhdawson** [comment]
New repo here - https://github.com/nodejs/nodejs-dependency-vuln-assessments
