### ISSUE TITLE
Create @nodejs/llhttp team

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#705]
Currently, the permissions on [nodejs/llhttp](https://github.com/nodejs/llhttp) repo are set as such:

- `@indutny` has write access.
- `@nodejs/tsc` has read access.

So only one member has write access, that doesn't seem right – of course, the TSC being admin on the org also have full access, but it would be worth updating anyway, but imo it would be better not to have to use our admin privileges unless strictly necessary.
I suggest we create a @nodejs/llhttp team and give it "Maintain" permission on the repo, add @indutny to that team (assuming they're interested) and remove the other permissions on the repo.

_Originally posted by @aduh95 in https://github.com/nodejs/llhttp/issues/167#issuecomment-1194146994_

**Comment by mcollina** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by mcollina** [comment]
cc @indutny

**Comment by ShogunPanda** [comment]
I'm interested to join this team to take care of llhttp releases.

**Comment by aduh95** [comment]
I see a few approval and no objections, so I went ahead with the proposal. @nodejs/llhttp is now the sole maintainer of [nodejs/llhttp](https://github.com/nodejs/llhttp).
