### ISSUE TITLE
Create @nodejs/single-executable team

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/admin#708]
I'd like to create a team that would focus on planning, implementing and maintaining the Single Executable Application (SEA) feature of Node.js. Interested candidates so far:
* @RaisinTen
* @dsanders11
* @jesec
* @jviotti
* @mhdawson
* @robertgzr
* @addaleax
* @targos
* @richardlau 
* @guest271314
* @joyeecheung 
* @tniessen
* @bnb
* @ovflowd
* @Qard 
* @arcanis
* @kevinswiber
* @ruyadorno
* @gireeshpunathil 
* @sheplu

---

Pinging others who attended the SEA mini-summit (https://github.com/nodejs/next-10/issues/99) / expressed interest in attending but unfortunately weren't able to make it to the meeting:
* @BethGriggs
* @BridgeAR
* @ErickWendel
* @SimonSchick
* @arcanis
* @bnb
* @gireeshpunathil
* @groovecs
* @igorklopov
* @jesec
* @joesepi
* @joyeecheung
* @mhdawson
* @mxschmitt
* @orta
* @richardlau
* @sheplu
* @styfle
* @targos

Also pinging the participants of the PR that's implementing the SEA feature: https://github.com/nodejs/node/pull/42334:
* @Hypfer
* @RaisinTen
* @Trott
* @addaleax
* @bnoordhuis
* @devsnek
* @guest271314
* @jesec
* @mcollina
* @mhdawson
* @mscdex
* @richardlau
* @styfle

Please comment "Interested" on this issue if you want to be added to this team (don't want those comments to get mixed up with voting comments from the TSC).

---

This also entails the creation of a repo named `single-executable` under the Node.js GitHub organization.

@nodejs/tsc yea or nay?

**Comment by targos** [comment]
Interested

**Comment by addaleax** [comment]
Interested

**Comment by richardlau** [comment]
Interested, and +1 to team

**Comment by ErickWendel** [comment]
+1 too!

**Comment by jviotti** [comment]
Very interested :)

**Comment by guest271314** [comment]
Willing to help however I can. Mainly testing.

> von Braun believed in testing. I cannot
emphasize that term enough – test, test,
test. Test to the point it breaks.

-Ed Buckbee, NASA Public Affairs Officer, Chasing the Moon

**Comment by joyeecheung** [comment]
interested

**Comment by mhdawson** [comment]
+1 to creationg the team and an associated repo for issues etc. @RaisinTen you don't mention a repo but I think we'll probably need that as well.

**Comment by tniessen** [comment]
Interested.

(Seeing the issue title with no context, I didn't associate `sea` with the acronym at first, but I don't have a better idea for the name of the team.)

**Comment by Trott** [comment]
Can we name it something else? `@nodejs/single-executable` or something like that? I'd rather have it be long and clear than short and cryptic.

**Comment by bnb** [comment]
Also interested in joining :)

**Comment by ovflowd** [comment]
Ooh, that looks interesting. As a newcomer, would it be too problematic for me to be interested in joining too?

**Comment by jviotti** [comment]
@ovflowd We would be happy to on-board you with the required context!

**Comment by ovflowd** [comment]
Thanks, @jviotti would love to get on-boarded :)

**Comment by Qard** [comment]
I assume single-executable meaning a Node.js build with custom scripts embedded? If so, I'm interested too, though I may be a relatively passive observer due to time constraints.

**Comment by RaisinTen** [comment]
> you don't mention a repo but I think we'll probably need that as well.

@mhdawson done!

> `@nodejs/single-executable` or something like that? 

@Trott done!

**Comment by arcanis** [comment]
Interested as well 👍

**Comment by kevinswiber** [comment]
Interested!

**Comment by ruyadorno** [comment]
Interested

**Comment by gireeshpunathil** [comment]
interested.

**Comment by sheplu** [comment]
interested.

**Comment by mhdawson** [comment]
@RaisinTen based on https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md#repositories, this is now approved (ie no objections after 72hours) so you can go ahead and create the repo/teams. If you need/want any help just let me know.

**Comment by RaisinTen** [comment]
I went ahead and created the team (@nodejs/single-executable) and the repo (https://github.com/nodejs/single-executable). @jviotti and I will be drafting a spec with all our findings till now, so that we can get y'all up to speed for the discussion in the first single-executable team meeting. Thanks for volunteering everyone! :-)

**Comment by RaisinTen** [comment]
Btw, there is also a [#single-executable-application](https://openjs-foundation.slack.com/archives/C03S7Q7RV9R) channel in the OpenJS slack, so feel free to join that too.
