### ISSUE TITLE
Request Zoom Access

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#710]
Hey folks 👋 I'm requesting Zoom access as we need it for the Nodejs.dev weekly meetings. Right now, both I and @benhalverson don't have access to it.

**Comment by ovflowd** [comment]
cc @nodejs/tsc

**Comment by Trott** [comment]
Does TSC handle Zoom access? Or is that a Foundation thing? @mhdawson

**Comment by Trott** [comment]
Let's hold off on this. @joesepi and I are meeting next week to talk about how to bring the website redesign to a conclusion. After that, we'll want to meet with everyone and sort things out. Maybe we can use the Website Redesign meeting slot on the 24th (11am Pacific, 2pm Eastern, 6pm UTC) to discuss further, although I have a standing conflict on Wednesdays at 11am and will likely to be absent.

**Comment by ovflowd** [comment]
@Trott, if you're unable to attend at the regular Redesign meeting time, we could try to change the meeting time :)

**Comment by ovflowd** [comment]
@Trott would it be OK if I could (again) request access to the Zoom Creds? I would like to "manage" the Website meetings if possible.

**Comment by Trott** [comment]
> @Trott would it be OK if I could (again) request access to the Zoom Creds? I would like to "manage" the Website meetings if possible.

I think that's fine. +1 from me

**Comment by mhdawson** [comment]
+1 from me

**Comment by mhdawson** [comment]
Moving forward.

I've invited as a manager to the youtube account, invite should be on its way

@ovflowd can you
* create a 1password account and let me know the user id so I can share the zoom credentials?
* PR yourself into the zoom-nodejs list in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json.
