### ISSUE TITLE
Add Nodejs.dev to Crowdin

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#711]
Hey folks 👋 we're in the process of getting i18n ready for `https://nodejs.dev` and for that we would like to integrate with Crowdin. 

Could we get a new project within Crowdin and give me and @benhalverson maintainer access there? Thanks!

**Comment by ovflowd** [comment]
cc @JohnTitor @Trott

**Comment by Trott** [comment]
We still don't have administrative access to Crowdin yet as far as I know. We might need to get help from Crowdin itself but I'm still holding out on one of the existing admins giving me access.....

**Comment by ovflowd** [comment]
Oh, I didn't know that, I thought you already got access 😅

**Comment by Trott** [comment]
> Oh, I didn't know that, I thought you already got access 😅

Yeah, I thought I'd have access by now, but...not yet....
