### ISSUE TITLE
Clean up membership in @nodejs/website

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#712]
@nodejs/website has 142 members. Of those, I'd say fewer than 10 are active in website maintenance at this point and fewer than 20 have been active in the last year or so.

People I'd keep:

Anyone who is in this group who is also in the collaborators group
Maledong
XhmikosR
Nick Schonning
Aymen Naghmouchi
Willin Wang
Joe Sepi

People I'd add who are not in there yet:
David Kadaria
Claudio W

And remove everyone else. People can always be re-added if someone who should stay gets accidentally removed.

**Comment by Trott** [comment]
@davidkadaria @ovflowd

**Comment by Trott** [comment]
@nodejs/website

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by ovflowd** [comment]
By the way, @Trott could the same cleanup apply on @nodejs/nodejs-dev? There are in theory 33 people in the team but barely 3-4 are actually active 😅

I think it only makes sense to keep people that are active, and if people want to contest (be added back) they can just ask and no harm done (I suppose 🤨)

**Comment by Trott** [comment]
> By the way, @Trott could the same cleanup apply on @nodejs/nodejs-dev?

Yes, but I would rather someone who is active in that team do it rather than me. I'm active in the website team, so I feel reasonably comfortable making an assessment about who is and isn't very active. My engagement in nodejs-dev is comparatively sporadic.

**Comment by benhalverson** [comment]
I’m active and can do it.

**Comment by Trott** [comment]
OK, all done. (Please open a separate issue for node-dev if we're going to do that cleanup!)

If anyone thinks I removed them when I should not have, leave a comment here or send me an email. (My email address is in my GitHub profile.) It's entirely possible I misclicked somewhere. The results look good to me, though. There are now 28 members which is still too many possibly, but not nearly as jaw-dropping as 142 people.
