### ISSUE TITLE
Closure of stale non-relevant issues for nodejs.org repository

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#715]
Hey folks 👋 (@nodejs/website), I wanted to speak up before I take any action, but I'm interested in closing all stale issues (Issues without any updates on the last 6 months). Only issues regarding possible features, feature requests, and open discussions would be closed. Bug reports and essential issues deemed to be a priority for the current website, which might also reflect on the new website, should still likely be kept open.

My motivation behind this is as we starting to prepare nodejs.dev on getting ready, shipping new features on nodejs.org and taking effort on shipping those features might not be the best approach.

**Comment by ljharb** [comment]
Please don't do that; "staleness" has no bearing on whether an issue is actually resolved or not.

You certainly can use staleness as a filter to manually triage issues, and it may be that most of the old ones are closeable with a human-crafted specific explanation! but it feels very hostile as a user when an issue i care about is closed merely because it's been neglected.

**Comment by ovflowd** [comment]
> You certainly can use staleness as a filter to manually triage issues, and it may be that most of the old ones are closeable with a human-crafted specific explanation! but it feels very hostile as a user when an issue i care about is closed merely because it's been neglected.

Oh! That's not my intention here at all 🙈. I don't want to create a sense that issues are being neglected. And I believe giving attention to every single issue creates a bond with the community. 

Hence I believe that closing only issues that feel like they were resolved or moving them to the new website repository might be a better fit.

I don't see any problems in having old issues labelled as stale. That would probably help with triaging. But my biggest concern is about keeping abandoned issues open. As I, as an author of an issue, would hate to have my issues closed without due resolution for no apparent reason, I, as a collaborator, would also suffer from maintaining issues that are not even relevant to the author of them... This is just my personal take on it. I'm more than open for suggestions 🙇

**Comment by nschonni** [comment]
Note that general non-website issues are usually transferred over the the nodesj/help repo using that GitHub feature
![image](https://user-images.githubusercontent.com/1297909/184704863-01f21a19-5dbf-46ea-a724-e8acb881851e.png)
