### ISSUE TITLE
Access to Zoom creds and youtube to stream meetings - @ruyadorno

### ISSUE THREAD

**Issue by ruyadorno** [nodejs/admin#716]
I have [volunteered to run the regular meetings for the Node.js Release WG](https://github.com/nodejs/Release/blob/main/doc/meetings/2022-07-28.md#nodejsrelease) and I would also like to help out the [Tooling Team](https://github.com/nodejs/tooling) to which I'm a part of and has also been [suffering from the lack of contributors with stream access to start the calls](https://app.slack.com/client/T0K2RM7F0/C01GNCK8EUD/thread/D03240KL9UP-1660747919.321119).

**Comment by Trott** [comment]
@nodejs/tsc @mhdawson

**Comment by mhdawson** [comment]
+1

**Comment by gireeshpunathil** [comment]
+1

**Comment by mhdawson** [comment]
Ok believe this is been open long enough without objections and it has some +1's. I'll give @ruyadorno access.

**Comment by mhdawson** [comment]
@ruyadorno invite as manager to youtube account should be on its way

**Comment by mhdawson** [comment]
@ruyadorno can you PR yourself into `zoom-nodejs` in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json. You'll need be in that list for cases where you need a code from zoom to log in.

**Comment by ruyadorno** [comment]
@mhdawson done: https://github.com/nodejs/email/pull/195

**Comment by mhdawson** [comment]
@ruyadorno should be all set now, closing.
