### ISSUE TITLE
Access to Zoom creds and YouTube to stream @nodejs/single-executable team meetings

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/admin#717]
I'd like to stream meetings for the @nodejs/single-executable team.

Refs: https://github.com/nodejs/single-executable/discussions/19

cc @nodejs/tsc @mhdawson

**Comment by mhdawson** [comment]
+1 from me

**Comment by mhdawson** [comment]
I don't see any objections, so will move forward.
@RaisinTen can you PR yourself into `zoom-nodejs` in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json. You'll need be in that list for cases where you need a code from zoom to log in.

**Comment by mhdawson** [comment]
@RaisinTen there sound be an invite on its way to add you as a youtube manager.  Will co-ordinate with you otherwise to get you the password for the zoom account.

**Comment by RaisinTen** [comment]
@mhdawson sure, I've created the the Zoom alias PR here - https://github.com/nodejs/email/pull/196

**Comment by mhdawson** [comment]
PR for zoom alias landed, @RaisinTen should be all set up now, closing.
