### ISSUE TITLE
Request access to Firebase CLI App

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#721]
Hey there 👋, I requested access to the Firebase CLI App for creating a GitHub Action for deploying The Nodejs.dev Repository to Google Firebase Hosting.

I need this access to authorize the Firebase CLI App to communicate to the GitHub repository.

This will allow us to move the build process from G Cloud to GitHub Actions.

cc @Trott

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by Trott** [comment]
/ping @MylesBorins I think you're the one that set up the Google Cloud thing in the first place so seems like something you might have opinions on.

**Comment by ovflowd** [comment]
@Trott, @MylesBorins was the one that told me to do so 👀

**Comment by ovflowd** [comment]
Context: https://openjs-foundation.slack.com/archives/CVAMEJ4UV/p1662747787440039

**Comment by Trott** [comment]
Here's the tool for which access is being requested: https://github.com/apps/firebase-cli

It can be scoped to a single repository rather than the entire org if we'd like to do it that way.

**Comment by Trott** [comment]
It installs with these permissions:

```
Read access to metadata
Read and write access to secrets
```

I imagine scoping it to nodejs.dev would be uncontroversial. Not sure about how folks would feel about getting it installed org-wide. Seems like we can start with just nodejs.dev. We can always add more repos later if needed.

**Comment by targos** [comment]
+1 to install just on nodejs.dev

**Comment by ovflowd** [comment]
Yup only on nodejs.dev is fine 😃

**Comment by ovflowd** [comment]
@targos is there anything blocking us or may we proceed with this? 😄

**Comment by Trott** [comment]
> @targos is there anything blocking us or may we proceed with this? 😄

I was giving it 72 hours because that's what most things in this repo require, but we're at 77 hours now, so I'll go ahead and get this set up.

**Comment by Trott** [comment]
All set up on the nodejs.dev repo. Let me know if there are any problems.

**Comment by ovflowd** [comment]
![image](https://user-images.githubusercontent.com/12037269/189982337-f9481227-b3d1-41a3-8fa3-f26d2f7922e4.png)

@Trott, sadly it is not working 😅

**Comment by ovflowd** [comment]
```
Waiting for authentication...

✔  Success! Logged into GitHub as ovflowd

⠹ For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) nodejs/nodejs.dev

⚠  The provided authorization cannot be used with this repository. If this repository is in an organization, did you remember to grant access?

i  Action required: Visit this URL to ensure access has been granted to the appropriate organization(s) for the Firebase CLI GitHub OAuth App:
https://github.com/settings/connections/applications/89cf50f02ac6aaed3484

? For which GitHub repository would you like to set up a GitHub workflow? (format: user/repository) nodejs/nodejs.dev
```

**Comment by Trott** [comment]
¯\\_(ツ)_/¯

![image](https://user-images.githubusercontent.com/718899/190015408-2c36931f-2294-4f6f-a346-825411ad4b70.png)

Maybe it simply doesn't work if you don't give it access to everything?

**Comment by ovflowd** [comment]
> Maybe it simply doesn't work if you don't give it access to everything?

I have no idea, sadly. @Trott if you don't mind would you mind enabling for the whole org, just so I run this command (https://firebase.google.com/docs/hosting/github-integration) and then lock it back to the repo?

It could also be that my account has no access (not sure)

**Comment by Trott** [comment]
> would you mind enabling for the whole org, just so I run this command (https://firebase.google.com/docs/hosting/github-integration) and then lock it back to the repo?

I wouldn't want to do that without TSC consent. I'm sorry. I know that's probably not what you want to hear.

@nodejs/tsc

**Comment by ovflowd** [comment]
No worries at all, Trott. Better make the decision with the TSC consent rather than not :)

**Comment by GeoffreyBooth** [comment]
From my reading of the error message, it looks like enabling it for the org doesn’t necessarily also enable it for all the repos within that org. If that’s the case, can someone try enabling it for the org and confirming that it only works for nodejs.dev and not the other repos?

**Comment by Trott** [comment]
> From my reading of the error message, it looks like enabling it for the org doesn’t necessarily also enable it for all the repos within that org. If that’s the case, can someone try enabling it for the org and confirming that it only works for nodejs.dev and not the other repos?

That's the way it's set up already and it's not working. (Or am I missing something?)

**Comment by Trott** [comment]
> > From my reading of the error message, it looks like enabling it for the org doesn’t necessarily also enable it for all the repos within that org. If that’s the case, can someone try enabling it for the org and confirming that it only works for nodejs.dev and not the other repos?
> 
> That's the way it's set up already and it's not working. (Or am I missing something?)

Hmmm, that was weird. I checked and it said it was denied, so I changed it to approved. Can you try again now?

**Comment by Trott** [comment]
(And I also double checked that it's only for the nodejs.dev repo.)

<img width="834" alt="image" src="https://user-images.githubusercontent.com/718899/191404239-139d0252-f55b-42d5-a6e2-bcd4fc21ce13.png">

**Comment by Trott** [comment]
And for completeness:

<img width="841" alt="image" src="https://user-images.githubusercontent.com/718899/191404301-7d557052-2530-4071-a41d-65614da90039.png">

Other org owners can see that at https://github.com/organizations/nodejs/settings/oauth_application_policy.

**Comment by GeoffreyBooth** [comment]
So is this issue resolved? Can we remove it from the TSC agenda?

**Comment by ovflowd** [comment]
Lemme check if it works now :)

**Comment by ovflowd** [comment]
It seems like I have permission now. But the command is giving a different Error now (I don't think it's GitHub related).

I think we can close this issue for now :)

Ty, @Trott!
