### ISSUE TITLE
Settings for Nodejs.dev Repository

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#722]
Hey there 👋 we need a few setting changes on the repository, but none of the current maintainers has access to the tab. The changes are:

- Allow only "Squash" merge for PRs (https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/configuring-commit-squashing-for-pull-requests)
- GitHub Pages permissions for GitHub Actions (https://github.com/nodejs/nodejs.dev/pull/2724)

cc @MylesBorins @benhalverson @nodejs/tsc

**Comment by targos** [comment]
Done:
![image](https://user-images.githubusercontent.com/2352663/189586748-0b83353e-97fa-4c80-842b-0923f8da5cd4.png)
![image](https://user-images.githubusercontent.com/2352663/189586877-455fbf73-5842-4b24-855e-f61f658ae03a.png)

**Comment by nschonni** [comment]
Retriggered https://github.com/nodejs/nodejs.dev/runs/8299605238?check_suite_focus=true and the pages seem to build now
