### ISSUE TITLE
Nominating Trott for social team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#726]
In accordance with the [Social team document](https://github.com/nodejs/admin/blob/eae9bc146f3cbdbb01617339765ada0561c31c52/social-team.md), I'm self-nominating for the social team.

"Nominations require +1s from existing Social Team members and no objections after seven days." @nodejs/social 

"Membership in the Social Team requires zero objections from [TSC](https://github.com/nodejs/tsc) members and Foundation Staff." @nodejs/tsc

**Comment by richardlau** [comment]
No objection.

**Comment by mhdawson** [comment]
+1

**Comment by bnb** [comment]
+1

**Comment by joesepi** [comment]
+1

**Comment by BridgeAR** [comment]
+1

**Comment by joyeecheung** [comment]
+1

**Comment by Trott** [comment]
Based on the social-team.md doc in the admin repo, this nomination has passed. I've taken the liberty of adding myself to the social team in GitHub but I'm not sure what else needs to be done. @nodejs/social

**Comment by bnb** [comment]
FWIW onboarding is done here AFAIK and this can be closed.

**Comment by bnb** [comment]
ah wait I can only close because of moderation, my bad - reopening.

**Comment by aduh95** [comment]
Fixed by https://github.com/nodejs/admin/pull/730
