### ISSUE TITLE
Request Admin access for nodejs/nodejs.dev

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#727]
I'm requesting admin access for the nodejs.dev repository so I can efficiently manage the Firebase integrations, GitHub Actions, et cetera.

cc @nodejs/tsc @nodejs/nodejs-dev

**Comment by ovflowd** [comment]
cc @bnb @mhdawson @Trott @benhalverson @mcollina

**Comment by RaisinTen** [comment]
SGTM but does this need the TSC to make a decision? I thought that changing roles in a repo is completely up to the team that's managing it.

**Comment by ovflowd** [comment]
@RaisinTen no one from the current team has admin access to the repo :S

**Comment by RaisinTen** [comment]
I think @joesepi and @MylesBorins has admin access :)

**Comment by ovflowd** [comment]
> I think @joesepi and @MylesBorins has admin access :)

Gotcha, I kinda also needed access (the point of this issue)

**Comment by bnb** [comment]
+1 @ovflowd has been doing a tremendous amount of work in this repo.

**Comment by Trott** [comment]
@ovflowd I've bumped you up from "Write" access to "Maintain" access. Give that a try and if it's not enough, I'll move it to "Admin".

**Comment by ovflowd** [comment]
Hey @Trott, I've just tested, but it still didn't work. Looks like for what I need (Secrets) only Admin will do 😓

**Comment by Trott** [comment]
You're now admin for that repository. I'm going to optimistically close this.
