### ISSUE TITLE
GraphQL API explorer

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#728]
There's a request from @WaleedAshraf for GraphQL API Explorer access to the org. I don't have any more information than that but I'm opening this issue for Waleed or someone else to provide that information so a decision can be made. Thanks!

**Comment by Trott** [comment]
(I clicked Deny but there's nothing stopping me or someone else with Admin privileges from clicking Grant Access to reverse it if we decide to do this. The link/page is https://github.com/orgs/nodejs/policies/applications/402786.)

**Comment by WaleedAshraf** [comment]
We were testing some automation stuff in the morning at Collab Summit. Later I realized that this access is not needed for the GraphQL queries we needed. You did right denying it. You can close this issue.
Thanks,
