### ISSUE TITLE
remove obsolete teams

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#729]
I would propose removing the following teams:

* @nodejs/ecosystem-security 
* @nodejs/wishlist 
* @nodejs/modules-legacy

Any concerns from either members of the those teams or else @nodejs/tsc?

**Comment by BridgeAR** [comment]
+1 on removing the teams

**Comment by mhdawson** [comment]
+1 on removing

**Comment by Trott** [comment]
Done.
