### ISSUE TITLE
archive https://github.com/nodejs/social-team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#733]
It doesn't seem to serve any purpose.

@joesepi Can you confirm?

**Comment by joesepi** [comment]
I can confirm @Trott that that repo is not currently serving any purpose other than being a place to drop issues for the Social Team's efforts which may be moot.

**Comment by ljharb** [comment]
Presumably that could be handled by github team discussions

**Comment by Trott** [comment]
Archived.
