### ISSUE TITLE
Prune nodejs/citgm team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#737]
I'd like to prune the nodejs/citgm team.

I think we can/should keep:

MylesBorins
targos
richardlau
BridgeAR

I think the following people are inactive of late in nodejs as a whole and can be removed from the CITGM team:

bzoz
gdams
al-k21

To give all seven of those people a ping in case they have any comments: @nodejs/citgm 

And for TSC awareness and review/comment: @nodejs/tsc

**Comment by Trott** [comment]
Should we eliminate the citgm team entirely and make CITGM the purview of the release team? @nodejs/releasers

**Comment by jasnell** [comment]
> Should we eliminate the citgm team entirely and make CITGM the purview of the release team? @nodejs/releasers

SGTM

**Comment by richardlau** [comment]
> Should we eliminate the citgm team entirely and make CITGM the purview of the release team? @nodejs/releasers

I guess that's the current reality, but I've always hoped to get more involvement in citgm from outside the release team.

**Comment by ruyadorno** [comment]
> Should we eliminate the citgm team entirely and make CITGM the purview of the release team? @nodejs/releasers

We discussed it today in the Release WG and I agree with the assessment from @richardlau here that it would be great to have an active CITGM community outside of the Release Team.

@darcyclarke was also in the same meeting and mentioned that the @nodejs/npm team might be contributing more to it moving forward so it might be a good idea to keep the citgm team and give it a second chance 😊

**Comment by ruyadorno** [comment]
One issue with CITGM and its contributions that I personally wanted to mention is the fact that is hard to attract contributors to such a low-visibility (but still essential to the project) type of work.

I don't want to derail the conversation over here (this might be a part of a larger conversation, since other groups such as the Build WG might also be in a similar position) but I believe it's still a relevant issue to highlight here.

**Comment by nlf** [comment]
we are planning to potentially use it for acceptance testing of new releases of npm. i don't have much detail beyond that yet, but i do think it's going to play a critical role in how we submit new npm releases upstream

**Comment by ljharb** [comment]
I'd be happy to join the CIGTM team if it would help; I have a couple packages tested by it already.

**Comment by darcyclarke** [comment]
As @ruyadorno / @nlf mentioned the @nodejs/npm team is considering using CITGM prior to cutting our releases which should help ensure things are already looking green before we go & open a PR to the project. With that in mind, I think it would make sense for our team to help maintain CITGM longer-term.

**Comment by Trott** [comment]
Membership pruned. Thanks everyone.
