### ISSUE TITLE
move postject under the nodejs org

### ISSUE THREAD

**Issue by RaisinTen** [nodejs/admin#739]
> The owner and the name of the repository, and a link to it.

Owner: https://github.com/postmanlabs
Name of repository: postject
Repository link: https://github.com/postmanlabs/postject

> What the repository is for, why it should be transferred into the organization.

The repository has the necessary code to inject arbitrary data into a binary post-compilation and also the code required for retrieving the embedded data at runtime. This is needed to make it possible for Node.js to support the creation of [single executable applications](https://github.com/nodejs/single-executable). This repository makes more sense under the nodejs org instead of postmanlabs because then Node.js would have full control over the resource injector and the reader code, both of which are essential for supporting single executable applications.

It was discussed in the collab summit that we'd move postject under the nodejs org.
See @mhdawson's comment in https://github.com/nodejs/node/pull/45066#issuecomment-1284100605.

cc @nodejs/tsc @nodejs/single-executable

**Comment by ovflowd** [comment]
👍

**Comment by jviotti** [comment]
I'm all for it

**Comment by bnb** [comment]
+2

**Comment by jasnell** [comment]
Can you link to the current project repo?

**Comment by richardlau** [comment]
> Can you link to the current project repo?

https://github.com/nodejs/admin/blob/main/transfer-repo-into-the-org.md
> The issue should include:
>
> * The owner and the name of the repository, and a link to it.
> * What the repository is for, why it should be transferred into the organization.
> * Mentions of `@nodejs/community-committee` and `@nodejs/tsc` so the Community Committee and the Technical Steering Committee members can be notified about the request and weigh in.

**Comment by jviotti** [comment]
This is the repo under discussion: https://github.com/postmanlabs/postject. The pre-requisites for transferring it make sense. @dsanders11 @RaisinTen Can you go through it, make the necessary changes in the repo and let me know once its ready for transfer? I'll handle the company logistics from Postman's side afterwards

**Comment by jviotti** [comment]
This is the repo under discussion: https://github.com/postmanlabs/postject. The pre-requisites for transferring it make sense. @dsanders11 @RaisinTen Can you go through it, make the necessary changes in the repo and let me know once its ready for transfer? I'll handle the company logistics afterwards

**Comment by RaisinTen** [comment]
@richardlau thanks for the link, I've updated the repo and the description with the required info.

@nodejs/tsc PTAL.

**Comment by targos** [comment]
Isn't it a bit early to move it under the org when we don't yet have consensus on using it ?

**Comment by RaisinTen** [comment]
I thought that we didn't have consensus on using postject by making it a part of the Node.js binary but we did have consensus on using it separately at least - https://github.com/nodejs/node/pull/45066#issuecomment-1284100605. I'd be happy to address any concerns regarding that.

**Comment by RaisinTen** [comment]
72 hours have passed after I posted https://github.com/nodejs/admin/issues/739#issuecomment-1290170436, so I'm closing this issue now. Will transfer the repo soon!

**Comment by jviotti** [comment]
I'll get the right Postman approvals, etc and will transfer the repo as soon as possible.

**Comment by jviotti** [comment]
We have the final thumbs up. I'm transferring the project now.

**Comment by jviotti** [comment]
And done! https://github.com/nodejs/postject :tada:

**Comment by RaisinTen** [comment]
I have also given the @nodejs/single-executable team `Write` access to the repo. Feel free to raise any concerns regarding that as issues in the repo. Thanks a lot everyone! 🎉

**Comment by aduh95** [comment]
> I have also given the @nodejs/single-executable team `Write` access to the repo.

Shouldn't they get `Maintainer` role instead? That's what I've been doing when transferring repo, I'm never sure which is more appropriate though.

**Comment by RaisinTen** [comment]
Ah, I didn't know that. Done, now the team has the `Maintain` role. :+1:

**Comment by RaisinTen** [comment]
Btw, I have also invited the Node.js foundation npm account to be an owner of the npm package according to https://github.com/nodejs/admin/blob/201fd09510a82b1cc15835dd899fe011ee1fe014/transfer-repo-into-the-org.md?plain=1#L51-L53:
```sh
$ npm owner add nodejs-foundation postject
This operation requires a one-time password.
Enter OTP: ******
npm notice INFO: User nodejs-foundation invited to package postject successfully.
+ nodejs-foundation (postject)
```
