### ISSUE TITLE
Creating @nodejs/performance repository

### ISSUE THREAD

**Issue by anonrig** [nodejs/admin#747]
Hi all,

Upon receiving some great feedback from https://github.com/nodejs/node/issues/45302, I recommend creating a `nodejs/performance` repository that oversees the @nodejs/performance team focusing on performance-related stuff in Node.

I'd like to be the champion of this team in addition to the help of several TSC members.

Best,
Yagiz Nizipli

**Comment by anonrig** [comment]
I feel like I should have cc'd the @nodejs/tsc team

**Comment by richardlau** [comment]
+1 from me. Are you looking to revive the old benchmarking WG (i.e. https://github.com/nodejs/benchmarking) (not necessarily as a full blown WG) or is this going to be a fresh start?

**Comment by anonrig** [comment]
I'm thinking about creating a non-formal team and a place to talk performance at first. Therefore, I believe a fresh start is much better than reviving a WG. We can convert this team to an official working group depending on progress and attendance.

**Comment by mhdawson** [comment]
+1 from me. Would be great to have an active team working together on issues in this area.

**Comment by aduh95** [comment]
What would the repo contain? I don't really understand why a repo is needed.

**Comment by anonrig** [comment]
I assume it'll be a place:

- to prepare and announce meetings
- communicate/ask performance-related stuff
- include docs about what optimizations we are looking for, and where to look for it
- keep track of progress

**Comment by Trott** [comment]
https://github.com/nodejs/performance
