### ISSUE TITLE
Python team review/call for members!

### ISSUE THREAD

**Issue by BethGriggs** [nodejs/admin#748]
I believe the number of active folks in the Python team is small. This issue is to review current membership and also call for others who may be invested in responding to, or reviewing Python issues.

I suggest removing the following three members who are collaborator emeriti and appear to not be active in the nodejs GitHub organisation anymore: refack, thefourtheye, aqrln. (Please correct me if I am mistaken.)

Also courtesey ping to @nodejs/python

**Comment by cclauss** [comment]
I agree that I have not seen those three active for some time.

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by BethGriggs** [comment]
Updated the team as proposed.
