### ISSUE TITLE
Zoom/Youtube access for @sheplu 

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#750]
@sheplu has volunteered to help run Next-10 meeting when necessary.

Unless there are objections I'll give him access by the end of the week.

**Comment by mhdawson** [comment]
Since there have not been any objections I'll proceeding with sharing with @sheplu.

@sheplu, can you PR yourself into the zoom-nodejs list in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json.

I'll also need a 1password account I can use to share the Zoom password with you

**Comment by sheplu** [comment]
PR done

You can use `jean.burellier@gmail.com` for the 1password account

**Comment by mhdawson** [comment]
you should have invite to vault with zoom creds.

**Comment by sheplu** [comment]
the invite was in my spam, didn't saw it until this week end. Could you resent one ? (sorry :( )

**Comment by mhdawson** [comment]
@sheplu resent

**Comment by sheplu** [comment]
all good ! thanks a lot. Any doc or setup information I should be aware of ?

**Comment by mhdawson** [comment]
This is what we currently have - https://github.com/nodejs/TSC/blob/main/Streaming/Streaming-To-Youtube.md

**Comment by mhdawson** [comment]
@sheplu,  I think you should have access to everything you need now.  There are some instructions on streaming in https://github.com/nodejs/node/pull/45582 and I'm also happy to have a short meeting to help you get started if needed. Let me know if you need anything else.
