### ISSUE TITLE
Zoom access

### ISSUE THREAD

**Issue by anonrig** [nodejs/admin#751]
Hi,

In order to plan the first meeting for @nodejs/performance, I ask for permission to access Zoom.

**Comment by mhdawson** [comment]
We'll need to get @anonrig access to both zoom and youtube. Unless there are objections I'll do that early next week.

**Comment by anonrig** [comment]
Meeting is probably going to be on monday, due to the availability of all people. Is it possible to get access earlier @mhdawson? Or I can push the meeting for next week.

**Comment by Trott** [comment]
> Meeting is probably going to be on monday, due to the availability of all people. Is it possible to get access earlier @mhdawson? Or I can push the meeting for next week.

Maybe someone who is attending the meeting already has Zoom access and can make it happen.

**Comment by RafaelGSS** [comment]
I can join. I need the time first.

**Comment by anonrig** [comment]
> I can join. I need the time first.

According to Doodle best time to have a meeting is November 14 1 PM EDT (New York).

**Comment by mhdawson** [comment]
Ok since there has been no objections I'll move forward with giving anonrig access.

@anonrig can you PR yourself into the `zoom-nodejs` list in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json.

**Comment by mhdawson** [comment]
@anonrig I'll also need a 1 password account I can use to share the zoom password with you

**Comment by anonrig** [comment]
> @anonrig can you PR yourself into the `zoom-nodejs` list in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json.

I opened a pull request. (https://github.com/nodejs/email/pull/203)

> @anonrig I'll also need a 1 password account I can use to share the zoom password with you

You can use yagiz@nizipli.com. I have a valid 1password subscription.

**Comment by mhdawson** [comment]
@anonrig you should get an invite to the vault in 1password

**Comment by mhdawson** [comment]
@anonrig I think you should have access to everything you need now.  There are some instructions on streaming in https://github.com/nodejs/node/pull/45582 and I'm also happy to have a short meeting to help you get started if needed. Let me know if you need anything else.
