### ISSUE TITLE
archive hardware repo and remove hardware team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#752]
I'd love to see that team rise from the ashes like a phoenix, but for now, it seems like [the repo](https://github.com/nodejs/hardware) has been inactive for a few years, and I don't think the GitHub team gets much use/activity either. I think it makes sense to archive the repository (which is easy to revert and low risk) and remove the team (which can always be added again, but is less trivial than unarchiving a repo).

/ping @nodejs/hardware in case there's interest in getting stuff going at this time

@nodejs/tsc

**Comment by ovflowd** [comment]
I had no idea we had a Hardware WG...

**Comment by AkashaCoin** [comment]
RIP :(
