### ISSUE TITLE
Create @nodejs/realm team

### ISSUE THREAD

**Issue by legendecas** [nodejs/admin#754]
I'd like to propose creating a @nodejs/realm GitHub team to be able to mention people who are interested and able to review the works on the Node.js Realm support and the ShadowRealm strategic initiative (https://github.com/nodejs/node/issues/42528).

Interested candidates so far: 
@cjihrig 
@joyeecheung 
@ljharb 
@mcollina 

@nodejs/tsc yea or nay?

**Comment by ljharb** [comment]
I'd be interested as well.

**Comment by cjihrig** [comment]
I have created @nodejs/realm and invited the interested parties.
