### ISSUE TITLE
Meta: Request Maintainer Access on Website Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#758]
Hey folks 👋 as I've been talking with the TSC, I'm going to switch the gears from making nodejs.dev happen with the current infra, to make nodejs.org have all the design and current feature set by doing incremental changes.

There's a proposal [issue here](https://github.com/nodejs/nodejs.org/issues/4958) for the large chunk of work necessary on the nodejs.org, and I would require maintaining (probably Admin) access to be able to setup proper GitHub Actions, Secret Keys, and temporary staging deployments over our Google Infra for the temporary work so that we do no disrupt the current nodejs.org infrastructure.

cc @nodejs/tsc @mhdawson

**Comment by ovflowd** [comment]
I believe this has been open for a few day, does anybody object this?

**Comment by Trott** [comment]
It sounds like you want/need elevated privilege on the nodejs.org repo but not necessarily on the website team. Do I have that right? Given no objections from TSC, I'm happy to bump up your privilege on that repo until you can do the things you need to do.

**Comment by ovflowd** [comment]
Yup, that's exactly it 🙃

**Comment by Trott** [comment]
> Yup, that's exactly it 🙃

I've moved you up from "Write" to "Maintain". I'm guessing that won't be enough, but can you try?

**Comment by ovflowd** [comment]
I just checked, and I have the feeling it _might_ not be enough for when I want to configure the secrets and things for the GitHub Actions.

But let's see if that'd be needed, so let's stay with "maintain" for now, and if I need the "admin" permission, I'll reopen this issue. I don't want to stay with more power than needed 👀
