### ISSUE TITLE
Remove community-events team and repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#76]
The `community-events` team and repo both seem to be inactive and superseded by the `community-committee` team and repo. The team has one member, @PatrickHeneise.

Any objection to deleting the team and archving the repo?

@nodejs/tsc @nodejs/community-committee 

Team: https://github.com/orgs/nodejs/teams/community-events
Repo: https://github.com/nodejs/community-events

**Comment by Trott** [comment]
I'll act on this after 72 hours if there are no objections from TSC or CommComm members.

**Comment by oe** [comment]
This has been discussed in the most recent CommComm meeting with the consensus (as far as I know) that it's not needed, so +1 from me.

**Comment by gibfahn** [comment]
SGTM

**Comment by PatrickHeneise** [comment]
Sorry about that. Couldn't find the time to make this useful. Please remove.

**Comment by joyeecheung** [comment]
SGTM

**Comment by bnb** [comment]
+1. @oe's statement on recent discussion in the CommComm is accurate AFAIK.

**Comment by mhdawson** [comment]
SGTM

**Comment by bnb** [comment]
Please let the CommComm know before/when this lands so we can appropriately update our Strategic Initiatives file 🙏

**Comment by hackygolucky** [comment]
+1

**Comment by mcollina** [comment]
+1


Il giorno gio 1 mar 2018 alle ore 17:16 Tracy <notifications@github.com> ha
scritto:

**Comment by Trott** [comment]
Team removed and repo archived.
