### ISSUE TITLE
Crowdin and nodejs.org permission elevated for ovlowd

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#761]
I made @ovflowd a manager of the nodejs-website project in Crowdin and Admin on the nodejs.org repo. He promptly got the Crowdin integration working again. I'm going to bump him back down on the nodejs.org repo to Maintain, but am +1 on increasing him to Admin on that repo if he needs it for anything going forward.

**Comment by Trott** [comment]
@nodejs/tsc FYI

**Comment by mhdawson** [comment]
@Trott are the crowdin credentials in 1password?  Just thinking it would be good to do that  if they are not already.

**Comment by Trott** [comment]
> @Trott are the crowdin credentials in 1password? Just thinking it would be good to do that if they are not already.

I don't believe there are any shared credentials for 1password.
