### ISSUE TITLE
Moving all translation to Crowdin and retiring all i18n groups

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#763]
Once the website repos and teams have been unified (which @ovflowd is working on), it would probably be beneficial to move all translation efforts to Crowdin and retire the very large number of almost-entirely-inactive translation GitHub teams. 

@nodejs/tsc @nodejs/i18n

**Comment by ovflowd** [comment]
One of the reasons (I believe) we have the Website translators within the org was to easily know who is a translator for which language and to easily tag them.

With Crowdin we can easily manage that, not to mention, when new translations are required, the respective translators are automatically tagged.

This would allow us to only keep maintainers of the i18n WG to stay within the org.

(Note we should possibly also audit the current list of translators on Crowdin...)

**Comment by nschonni** [comment]
The actual i18n group is also used for things other than translations, like https://github.com/nodejs/full-icu-npm

**Comment by ovflowd** [comment]
Yeah the idea is to just keep the i18n maintainers/non-translation stuff.

**Comment by ovflowd** [comment]
I've also seen that the "translators" team probably would need to be sunset. I also believe we need to audit the current members of Crowdin. This kind of change would likely need an announcement for our current translators.

@Trott, how are we on track to making this change happen?

**Comment by ovflowd** [comment]
Also, this Issue is a continuation of: https://github.com/nodejs/admin/issues/650

**Comment by Trott** [comment]
> @Trott, how are we on track to making this change happen?

I'm not sure. What are the steps that need to happen?

**Comment by ovflowd** [comment]
I would say:

- Announce to all Translators about the move to Crowdin (probably via Org-wide Discussions)
- Then remove the members and teams
- Accept the invites on Crowdin? (I will also remove current translators that are not active on Crowdin (they can be readded at any moment/time if they request)

**Comment by Trott** [comment]
> I would say:
> 
>     * Announce to all Translators about the move to Crowdin (probably via Org-wide Discussions)
> 
>     * Then remove the members and teams
> 
>     * Accept the invites on Crowdin? (I will also remove current translators that are not active on Crowdin (they can be readded at any moment/time if they request)

The first two would be likely handled by someone on the TSC (like me). The third one is something you would do once the first two are done?

**Comment by ovflowd** [comment]
Sounds like a plan :)

**Comment by ovflowd** [comment]
@Trott can we add `tsc-agenda` for this one? and #650?

**Comment by Trott** [comment]
> @Trott can we add `tsc-agenda` for this one? and #650?

What do you hope to get out of the TSC? Awareness? Approval? A certain action?

**Comment by Trott** [comment]
> > @Trott can we add `tsc-agenda` for this one? and #650?
> 
> What do you hope to get out of the TSC? Awareness? Approval? A certain action?

I guess maybe the thing to get from the TSC is agreement and commitment from one or more TSC members to do these items:

> * Announce to all Translators about the move to Crowdin (probably via Org-wide Discussions)
> 
> * Then remove the members and teams

**Comment by ovflowd** [comment]
Yup! Forgot to answer you, but that pretty much was it :)

**Comment by mhdawson** [comment]
I'm +1 to moving forward with the steps proposed.

**Comment by Trott** [comment]
Announcement posted: https://github.com/orgs/nodejs/discussions/47147

**Comment by Trott** [comment]
This is now done.
