### ISSUE TITLE
Remove roadmap team and archive repo

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#77]
The `roadmap` team and repo are both inactive. The Roadmap WG was decommissioned some time ago. The team has one member, @fhemberger.

Any objection to deleting the team and archving the repo?

@nodejs/tsc @nodejs/community-committee

Team: https://github.com/orgs/nodejs/teams/roadmap
Repo: https://github.com/nodejs/roadmap

I'll wait at least 72 hours for objections from TSC and/or CommComm before acting on this.

**Comment by gibfahn** [comment]
SGTM

**Comment by targos** [comment]
Sgtm

**Comment by mcollina** [comment]
sgtm
Il giorno mer 28 feb 2018 alle 06:46 Michaël Zasso <notifications@github.com>
ha scritto:

**Comment by joyeecheung** [comment]
SGTM

**Comment by oe** [comment]
SGTM

**Comment by mhdawson** [comment]
SGTM

**Comment by Trott** [comment]
Team deleted, repo archived.
