### ISSUE TITLE
Self-nomination: Nominate @ovflowd as the maintainer of the Website Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#773]
I would (selfishly) like to nominate myself as the maintainer of the Website Team. It's more like a formality and unnecessary, but it would allow me to officially act as a website team maintainer.

During the last few months (almost one year already :O), I've been (stupidly hard) pushing towards completing the goals of the Website Redesign Initiative and pushing towards the Node.js Website to get the love it deserves.

Thank you if you believe I deserve to be the maintainer of the Team. Thanks!

<sup>I don't know if maintainer roles in teams are even a thing here, so feel free to ignore my request 😅</sup>

cc @nodejs/tsc

**Comment by Trott** [comment]
Done.
