### ISSUE TITLE
Nominating @mikeesto for the Website Team

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#774]
I want to nominate Michael Esteban (@mikeesto) as part of the Website Team. Over the last few years, they have contributed to the Nodejs.org and Nodejs.dev repository with good-quality reviews, issues, and pull requests, from hotfixes to very-needed features and bug fixes.

I feel like they should have been added to the team a long time ago, but they probably didn't know about the process or that they would be able to contribute as part of the Team

Here is a summary of their contributions:

Pull requests opened: [github.com/search?q=author%3Amikeesto+org%3Anodejs&type=pullrequests](https://github.com/search?q=author%3Amikeesto+org%3Anodejs&type=pullrequests)
Issues opened: [github.com/search?q=author%3Amikeesto+org%3Anodejs&type=issues](https://github.com/search?q=author%3Amikeesto+org%3Anodejs&type=issues)
Comments on pull requests and issues throughout the Node.js organization: [github.com/search?q=commenter%3Amikeesto+org%3Anodejs&type=pullrequests](https://github.com/search?q=commenter%3Amikeesto+org%3Anodejs&type=pullrequests)

/cc @nodejs/tsc

**Comment by marco-ippolito** [comment]
Wrong tag I'm afraid 😅

**Comment by ovflowd** [comment]
Oh man, I forgot to update the tag xD

**Comment by mikeesto** [comment]
Thanks for the nomination @ovflowd. I'm grateful for your support. I've enjoyed being involved over the past few years, particularly in nodejs.dev. I use Next.js for my day-to-day work, and I'm looking forward to hopefully continuing to contribute, in a perhaps more formal capacity, to the migration to nodejs.org.

**Comment by ovflowd** [comment]
Hey @mhdawson, how do we proceed with this? Since I'm not the maintainer of the team, I cannot add members to the Website Team.

(Also @Trott https://github.com/nodejs/admin/issues/773 I guess this one got enough +1 from the TSC?)

**Comment by Trott** [comment]
> Hey @mhdawson, how do we proceed with this? Since I'm not the maintainer of the team, I cannot add members to the Website Team.
> 
> (Also @Trott #773 I guess this one got enough +1 from the TSC?)

Hi, @ovflowd. You're a maintainer now. You can add people at your discretion. In general, it's a good idea to keep the TSC at least apprised of people being added. That can be done in a public issue like this or a private email the TSC email address or a DM on the OpenJS Slack to me or any other TSC member.  In general, we don't micro-manage team memberships but Website is special IMO and we should have a good idea of everyone who has the power to publish things to our website.

**Comment by ovflowd** [comment]
Closed as @mikeesto got an invitation.
