### ISSUE TITLE
Youtube and Zoom access for @UlisesGascon

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#776]
@UlisesGascon is going to chair the next Security WG meeting (I'll be traveling next session and as we discussed would be great for someone else from the team to have the right to lead sessions). To do that he'll need access to the Zoom credentials and be a youtube manager.

Unless there are objections I'll make him a youtube manager and share the Zoom credentials through 1password.

cc @nodejs/tsc

**Comment by mhdawson** [comment]
Just a quick correction we now share credentials through 1password since Brian left the foundation.

But +1 to getting @UlisesGascon  access

**Comment by mhdawson** [comment]
Invited to 1password to share zoom password.

**Comment by mhdawson** [comment]
Invited as manager to youtube account

**Comment by mhdawson** [comment]
Can you PR yourself into zoom-nodejs section in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json. You'll need that when zoom decides you are from a different location.

**Comment by UlisesGascon** [comment]
I created the PR in https://github.com/nodejs/email/pull/210. I accepted both invitations as well.

**Comment by RafaelGSS** [comment]
Thank you @mhdawson

**Comment by mhdawson** [comment]
I think this can be closed now.  @UlisesGascon we can meet 5 mins in advance of the next Security WG meeting and I can help you start the zoom and stream.

**Comment by UlisesGascon** [comment]
That will be fantastic! Thanks a lot @mhdawson
