### ISSUE TITLE
Resign from @i18n

### ISSUE THREAD

**Issue by RichardLitt** [nodejs/admin#777]
Hi there! I would like to resign from all of the Node committees I am currently a part of. I don't feel like I am adequately participating, and if I participate in the future, I would like to have the same process as anyone else to rejoin. 

Can someone please remove me from the relevant notifications? I would not mind being a member in the org without a team, but understand if there is no alumni group to add me too.

**Comment by aduh95** [comment]
Thanks for your service, hope to see you around 👋 I've removed you from the organization.

**Comment by RichardLitt** [comment]
Thank you. :)
