### ISSUE TITLE
Transfer aduh95/node-pr-doc-preview into the org

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#780]
Transfer [aduh95/node-pr-doc-preview](https://github.com/aduh95/node-pr-doc-preview) into the nodejs org so https://github.com/nodejs/node/pull/47196 can move forward. Only the bot needs write permission on it, the repo itself should require 0 maintenance.

**Comment by mhdawson** [comment]
+1

**Comment by aduh95** [comment]
More than 48 hours have passed without any objections, and there are a few +1s from TSC voting members. I went ahead with the transfer and have set the permissions for the repository.
