### ISSUE TITLE
sunset/remove https://github.com/orgs/nodejs/teams/crowdin-managers team and subteams

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#781]
The only Crowdin Managers now are me, @Trott, @danielleadams and @joesepi. These teams sound inactive and can be removed. (At least it has no use for the actual current managers of Crowdin).

cc @nodejs/tsc

**Comment by Trott** [comment]
It looks to me like the team has been removed so I'm going to close this. Let me know if I'm mistaken.
