### ISSUE TITLE
decharter/cleanup the i18n WG

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#784]
The meta i18n team has been silent for a long time. Not much effort is being made there (as the central i18n repository has been dead, and no meetings have been done for a long time). It feels like the i18n WG can be unchartered and cleaned up.

Besides the actual important subteams, such as `i18n-api` (which are i18n features of the core of Node.js, such as ICU and TextEncoder), the remaining sub-teams, such as `i18n-module-admins` and `crowdin-managers` pretty much (probably) can be removed as they (I'm assuming) present no value anymore.

For the actual i18n tasks for other parts of Node.js, I only see the Website, those we already have third-party tooling (Crowdin) with its managers.

cc @nodejs/tsc

**Comment by srl295** [comment]
- makes some sense, can always come back if someone has a new charter.   If my count is right, this is the second i18n WG that’s being archived.
