### ISSUE TITLE
Archive https://github.com/nodejs/tweet

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#786]
I think it's time to archive the repository. Tweets are now handled through Slack and Google Forms. The automation in that repository is not needed. (And we can always unarchive if that turns out to be incorrect.)

@nodejs/social @nodejs/tsc

**Comment by tniessen** [comment]
If any of the recently updated information/instructions in the README become outdated, would we have to unarchive the repository to update them? If we don't intend to do so if it becomes necessary, maybe that's a sign we shouldn't have any instructions in that repository.

**Comment by Trott** [comment]
> If any of the recently updated information/instructions in the README become outdated, would we have to unarchive the repository to update them?

Yes. I think unarchiving to update would be fine, but we can also choose to remove the instructions now instead. I'd prefer to leave them there, though.
