### ISSUE TITLE
Do we need a PyPI org?

### ISSUE THREAD

**Issue by ryzokuken** [nodejs/admin#790]
I believe we have a number of Python packages owned by the Node.js org that need to be regularly published. At the moment I have total control over the gyp-next package that I updated manually (https://github.com/nodejs/gyp-next/issues/29#issuecomment-1514565036) but in order to automate this process and for general maintenance I believe we should probably create a Node.js org that I could initiate the handover of this package to.

**Comment by aduh95** [comment]
What would be the steps to take to do that?

**Comment by legendecas** [comment]
Ref: https://github.com/nodejs/admin/issues/863#issuecomment-2138376815
