### ISSUE TITLE
Including @marco-ippolito to actions team

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#791]
After the work on https://github.com/nodejs/security-wg/issues/828 @marco-ippolito asked to be part of the actions team, so he gets notified about any changes in the update action.

I'm planning to do it in the next 2 days if no objections.

cc: @nodejs/security-wg

**Comment by mhdawson** [comment]
+1 from me. He's helped automate the build of a number of the deps and it would be good if he got notifications about any failed runs.

**Comment by Trott** [comment]
I don't think you need to wait on it. They're an active collaborator and I don't think the @nodejs/actions team gets any special privileges or anything--not even write access to a repository or anything at all. I think you can do this now and close the issue.

**Comment by RafaelGSS** [comment]
Done
