### ISSUE TITLE
Allow integration: from Github to Slack

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/admin#799]
**Related**
- https://github.com/nodejs/build/issues/3088
- https://github.com/nodejs/build/issues/3362
- cc: @nodejs/build 

**Context**

In the build team we want to get notifications in the `#nodejs-build-infra-alerts` slack channel when a new issue is created in the repo [nodejs/jenkins-alerts](https://github.com/nodejs/jenkins-alerts)

**What is needed?**

I think one of the most simple solutions for this is to use the Github Integration for Slack. The Github app was already available in our Slack.

In order to do that I need an approval from the Github Organization admin(s) to allow this integration to work. This integration will only pull notifications from one specific repo and not all the Node.js Org repositories

**Additional information**

![image](https://github.com/nodejs/admin/assets/5110813/13add78e-d1a0-4128-a777-50b0ac67258f)

![image](https://github.com/nodejs/admin/assets/5110813/9771390e-3d03-4f1b-8921-4bd317be37c5)

**Comment by MoLow** [comment]
+1 Sounds good to me

**Comment by ovflowd** [comment]
+1 that'd be great!

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by Trott** [comment]
I added the tsc-agenda label, but only so that it shows up on the agenda if it gets stalled. If this gets resolved and closed before the next TSC meeting, then great.

**Comment by mhdawson** [comment]
+1 from in terms of the level of integration requested.

**Comment by mhdawson** [comment]
Discussed in TSC today, no concerns, Richard will click the button.

**Comment by Trott** [comment]
I clicked the button.

**Comment by UlisesGascon** [comment]
Thanks @Trott! 

The integration is working
<img width="898" alt="Captura de pantalla 2023-06-02 a las 11 46 21" src="https://github.com/nodejs/admin/assets/5110813/d6baae8e-4975-4ba5-94b7-7e1d197419dc">
