### ISSUE TITLE
Request to attend Collaborator Summit Berlin 2018

### ISSUE THREAD

**Issue by inidaname** [nodejs/admin#80]
I wish to attend The [Collaborator Summit Berlin 2018](https://github.com/nodejs/summit/issues/60), I am a member of the @nodejs/modules team. I want to use the opportunity to give a talk on the benefit of participation of Africans collaborators to NodeJs Development and how the NodeJs Foundation can effectively support that.
Coming from Nigeria I will be glad if there will be any available support the NodeJs Foundation can provide for me to achieve this.

Thank You

**Comment by MylesBorins** [comment]
@inidaname you can follow the instructions in https://github.com/nodejs/admin/blob/master/MEMBER_TRAVEL_FUND.md#request to make the request

Thanks for opening the issue!

**Comment by mhdawson** [comment]
@inidaname the other thing to make sure is that you are an individual member of the Foundation, probably covered in the doc that @MylesBorins referenced.

**Comment by inidaname** [comment]
@mhdawson yes I have registered with the Foundation as an individual member and received the confirmation email from _Linux Foundation_

Thank You

**Comment by Trott** [comment]
@inidaname I don't see a pull request for your travel funding request. Have you decided not to attend? Or do you need any assistance putting together the pull request? (Or is there one already and I'm missing it?)

**Comment by inidaname** [comment]
@Trott My PR #81 was merged sometime ago. Thank You, if plans change I will comment here.
Will be okay if I can close this issue.
Feel free to re-open.

Thank You

**Comment by Trott** [comment]
@inidaname Awesome! See you in Berlin!

**Comment by inidaname** [comment]
I wish to reopen this.
I could not attend the Berlin Collab Summit due to issues with Visa application, I appreciate the approvak of my travelling request granted to me by the foundation to attend the Summit. I wish to request for a similar support for the Vancouver Summit.
I am still an active member of the Foundation @nodejs/modules this will be a great opportunity for me to meet and share with the members of @nodejs/modules. I have opened a PR #167 .

Thank You

**Comment by Tiriel** [comment]
Hey!

Since you have opened the other PR and the event for the present issue has already passed, I think this one is not needed and can be closed. No need to have two issues/PR opened.

But we'll definitely look into your PR!
