### ISSUE TITLE
Setup Terraform Cloud account

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/admin#801]
Based on the discussion in https://github.com/nodejs/build/issues/3270#issuecomment-1562947464. cc: @nodejs/build

I will need help to setup the [Terraform Cloud Account](https://portal.cloud.hashicorp.com/sign-in) for Node.js Org. This account will be used to create a Team in Terraform Cloud and provide access to individual accounts. Can you create the account using the `*@iojs.org` email? 

**Additional steps**
- [ ] Add my personal account to the team as well as `Workspace Administrator level`. [This guide can help](https://developer.hashicorp.com/terraform/tutorials/cloud/cloud-permissions) or I can do it if you share the credentials for Terraform Cloud
- [ ] I will generate a token for the GitHub actions that will sync the terraform state

**Comment by mhdawson** [comment]
+1 with readonly access to start.

**Comment by targos** [comment]
I created an account with the build email. Could be a good opportunity to start sharing build login credentials with 1Password

**Comment by targos** [comment]
With the free tier, I can only add people as team owners. We would need at lest the [Standard plan](https://www.hashicorp.com/products/terraform/pricing) to create additional teams. They say the first 500 resources per month are free, but I don't know what counts as a resource and if it will be enough for us.

**Comment by targos** [comment]
@UlisesGascon What's your account's email address?

**Comment by UlisesGascon** [comment]
It is working! Thanks a lot @targos 👍
