### ISSUE TITLE
Archive nodejs/help in favour of a Help Section on Discussions

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#802]
**More Context on Slack:** https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1684794644392399

---

So, with the Discussions feature becoming increasingly popular, many "Help" questions are being opened there.

With the current moderation features and the "nature" of a Help question being a Discussion, it feels time to archive the nodejs/help repository (that uses Issues for Help) in favour of the Discussions.

It's easier to monitor Discussions, and easier to mark an answer as "the best answer", Discussions have a threaded model, which also is more tailored for discussions.

Not to mention one less repository to maintain.

cc @nodejs/tsc

**Comment by benjamingr** [comment]
I'm going to piggyback on this and follow up and ask: where do we point users with general (non Node.js core, feature request or bugs) related questions?

We've had two recent instances where I closed something that _seemed_ to be offtopic (and updated @nodejs/moderation) and I was not sure where to tell users to go:
 - https://github.com/orgs/nodejs/discussions/48290
 -  https://github.com/orgs/nodejs/discussions/48289

Would be good to get guidance from the TSC about what's on topic for orgs/nodejs/discussions and where to point users that need general help unrelated to core or Node.js development itself.

**Comment by benjamingr** [comment]
I would like the TSC to discuss this if possible. Guidance can be "let X pick" or "send them to the OpenJS slack" or "we don't endorse anywhere to not play favorites and we don't allow it here, sorry!" which is also fine.

I feel more strongly about having a clear, transparent and documented policy than the policy itself.

**Comment by ovflowd** [comment]
> I'm going to piggyback on this and follow up and ask: where do we point users with general (non Node.js core, feature request or bugs) related questions?

We want to recommend users ask for help on shared platforms such as StackOverflow, but since we can't prohibit people from asking for help over here (and we shouldn't), it'd still be better to do it over discussions.

The two cases you linked would not fit for the "Help" section, as it would need to be Help directly related to Node.js and on of the provided APIs, e.g. "fs".

**Comment by ovflowd** [comment]
> I would like the TSC to discuss this if possible. Guidance can be "let X pick" or "send them to the OpenJS slack" or "we don't endorse anywhere to not play favorites and we don't allow it here, sorry!" which is also fine.

IMHO I actually wish we didn't redirect users to OpenJS Slack for Node.js help as there so little of engagement and activity there.

**Comment by gireeshpunathil** [comment]
I am -1 to this proposal.

 - nature of engagement in help repo is not of a discussion kind, instead an iterative and collaborative problem determination kind.
 -  it resembles core issues in most aspects, except the later manages perceived bugs. we have seen issues reported in help repo being identified as bugs too. We have seen issues getting transferred between these 2 repos often.
 - it helps as a central place for asking general help with Node.js. Having such as place improves user experience with Node.js IMO.
 - we haven't seen issues with multiple answers for the OP to select the best etc. The clear pattern we have seen is interesting, insightful and diverse field usage stories, and usage problems.
 
it is worthwhile to see if we can discuss and identify actions to reduce the backlog (through activities such as bounty programs), but maintaining a repo for general help is great for a healthy project IMO.

**Comment by RafaelGSS** [comment]
I'm also -1. Github Discussions have a horrible UX per nature.

**Comment by ovflowd** [comment]
@RafaelGSS how discussions have an horrible UX? The UX is way better and better accommodating than Issues. That's the whole point why they made the Discussions feature.

**Comment by ovflowd** [comment]
I also wanted to mention that right now people are opening "Help" issues on Discussions (even if not a lot) and pretty much we can only convert them into an issue for the help repository. But it honestly feels like the opposite is better suited.

Conversion of Issues into Discussions works better than the opposite, sadly converting Discussions to Issues causes... well, lost of context.

**Comment by gireeshpunathil** [comment]
> isn't this the very nature of a discussion?

may be, at a generic level every collaboration is a discussion, but problem determination is a specialised instance of discussion that involves (usually) one party carrying out debug operations on their system  and the other providing instructions and interpreting the output.

> The Help section is not meant for bug reporting, just general help with Node.js

It is generally hard to assert issues as bugs or non-bugs upfront, that revelation comes after few iterations.

> How is a Discussion Category not a dedicated space?

my understanding is `gitHub.com/orgs/nodejs/discussions` is common for all ~200 repos in the `nodes` org. Isn't it the case?

> We? Who "is" we?

those who have been helping users in the help repo.

**Comment by ovflowd** [comment]
Also, discussions directly on the nodejs/node repository can easily be transferred as issues for nodejs/node if they happen to be bug reports...

**Comment by ovflowd** [comment]
Also noted that I'm suggesting this based on my almost 5 years of moderating communities (Reddit, Discourse, Matrix) 😅

But I am definitely biased here, and I'm not saying I'm sorry right, also because I have no idea what works best for Node.js 🙃

**Comment by nschonni** [comment]
There was some previous discussion in https://github.com/nodejs/admin/issues/771

**Comment by Trott** [comment]
Related: We should update https://github.com/nodejs/node/blob/main/.github/SUPPORT.md. How active is libera.chat? And OpenJS #ask-anything channel is missing. And so on.

**Comment by ljharb** [comment]
It remains pretty active.

**Comment by Trott** [comment]
> It remains pretty active.

@ljharb Are you referring to libera.chat or to the help repo (or something else)?

**Comment by ljharb** [comment]
libera.chat, since that was the question you asked :-)

**Comment by preveen-stack** [comment]
While I agree that @ovflowd arguments are valid, I feel we should keep  the nodejs/help issues as Level 1 support to new nodejs users for a foreseeable future, if it is not very inconvenient. 

Seeing many issues I see a lot of room improvement in nodejs error messages that would enable new users to graduate through initial hurdles.

**Comment by ovflowd** [comment]
Level 1 support? I don't think we're in a capacity to give dedicated Level 1 support to users. (In terms of human resources and time)

**Comment by mhdawson** [comment]
My take is that I'd trust the opinion of those who have been active in answering the questions and triaging the issues in the nodeks/help repo. I think @gireeshpunathil has been one of those people over time so I support his view on this issue.

**Comment by benjamingr** [comment]
I mostly just wanted the TSC to guide us here, I'm content with the resolution of keeping it. We should consider inviting volunteers to help people there or perhaps increase its visibility.

**Comment by ovflowd** [comment]
I wrote some stuff on Slack after @Trott's comment (https://openjs-foundation.slack.com/archives/C019Y2T6STH/p1687275661864849?thread_ts=1684794644.392399&cid=C019Y2T6STH) just for context/visibility.
