### ISSUE TITLE
Transfer stduhpf/caritat into the nodejs org

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#805]
I suggest to transfer https://github.com/stduhpf/caritat into the nodejs GitHub organisation, and to create the `@nodejs/caritat` team to maintain it.

The goal of Caritat is to propose a robust voting solution that's integrated with the tools Node.js devs use. The TSC is ready to use it as its de facto voting solution, other teams are of course welcome to use it as well.

@stduhpf can you please :+1: to confirm you're OK with that plan? If you are, please transfer the repo to my GitHub account so I can transfer it to the org.

Refs: https://github.com/nodejs/TSC/issues/1165

/cc @nodejs/tsc

**Comment by aduh95** [comment]
No objections from TSC members and the issue has been open for more than 72 hours, so the transfer is accepted. I'm going to proceed with the plan.

@mhdawson IIRC you have access to the bot account, could you take care of the NPM token creation please?

1. Go to https://www.npmjs.com/settings/nodejs-foundation/tokens/new
2. Enter the nodejs-foundation account's password
3. Name: `NPM_TOKEN secret to publish Caritat` ?
   Type: "Automation"
   Click "Generate Token"
4. Copy the generated token (it starts with "npm_")
5. Go to https://github.com/nodejs/caritat/settings/secrets/actions/new
6. Name: NPM_TOKEN
   Value: the token you copied at 4.
   Click "Add secret"

**Comment by mhdawson** [comment]
@aduh95 can you add some of the missing boilderplate files ? I think we need a contributing.md with the DCO, one for Code of conduct and the licence should likely update to say "and collaborators" as we have for other reapos.

I'll try to get to looking at the token in the early part of this week.

**Comment by aduh95** [comment]
Hum I followed the recommendation in https://github.com/nodejs/admin/blob/130c4e8971f9a922e144aac95c4c179a84c91c1c/transfer-repo-into-the-org.md?plain=1#L11-L22

+1 for the license file, I'll send a PR.

**Comment by aduh95** [comment]
@mhdawson friendly ping, I would love to be able to finish the transfer of the npm package.

**Comment by mhdawson** [comment]
@aduh95 token added.

**Comment by aduh95** [comment]
Thanks, I've confirmed it works. The transfer is complete now,
