### ISSUE TITLE
Archive inactive repos

### ISSUE THREAD

**Issue by benjamingr** [nodejs/admin#813]
Hey,

We have a bunch of inactive repos such as https://github.com/nodejs/promises-debugging or https://github.com/nodejs/social-media-delegates or https://github.com/nodejs/post-mortem

I propose we archive any repo without activity for a year when that repository represents a team/effort rather than code to make it clear these are not ongoing efforts.

Repos that exist in order to have stuff moved there like https://github.com/nodejs/premature-disclosures would also be excluded.

cc @nodejs/tsc , let's see how people feel about it and raise it in the agenda if it doesn't generate enough 👍  or there are objections.

**Comment by Trott** [comment]
I've archived https://github.com/nodejs/social-media-delegates.

**Comment by benjamingr** [comment]
I've gone ahead and archvied https://github.com/nodejs/promises-debugging and https://github.com/nodejs/post-mortem/ as well as nodejs/code-and-learn - if anyone disagrees this is reversible.

I'll go ahead and close this issue.
