### ISSUE TITLE
Archive https://github.com/nodejs/social-media-delegates

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#815]
We should archive https://github.com/nodejs/social-media-delegates.

**Comment by mcollina** [comment]
sgtm

**Comment by benjamingr** [comment]
I opened an issue about this last week https://github.com/nodejs/admin/issues/813 :)

**Comment by Trott** [comment]
Looks like we removing archiving the social-media-delegates team when we archived the repo. I'll open a new ticket about that.
