### ISSUE TITLE
Add @guybedford to @nodejs/security-external and @nodejs-private/security-external

### ISSUE THREAD

**Issue by GeoffreyBooth** [nodejs/admin#817]
Hi, I’d like to add @guybedford to @nodejs/security-external and @nodejs-private/security-external. Guy is one of the primary authors of the ESM implementation and I’d like to involve him in discussions about security fixes.

**Comment by RafaelGSS** [comment]
+1

**Comment by GeoffreyBooth** [comment]
Done
