### ISSUE TITLE
Archive nodejs/modules

### ISSUE THREAD

**Issue by benjamingr** [nodejs/admin#822]
We've recently had an issue in the modules repo where there was a CoC violation and after discussion with @GeoffreyBooth it seems like the discussion isn't happening there (it moved to nodejs/loaders) and it can be archved.

This issue is in order to archive the nodejs/modules repository.

**Comment by GeoffreyBooth** [comment]
There are pending feature requests and a few still-active discussions over there. Can we migrate them into nodejs/node? Potentially all open issues, but probably not all; I can do a pass first to close all the ones that should’ve been closed.

**Comment by benjamingr** [comment]
@GeoffreyBooth we can archive them and redirect people to nodejs/loaders or nodejs/node instead?

Anything you want to automatically transfer to nodejs/node by all means go ahead

**Comment by GeoffreyBooth** [comment]
Related: https://github.com/nodejs/modules/issues/567 😄

**Comment by GeoffreyBooth** [comment]
> Anything you want to automatically transfer to nodejs/node by all means go ahead

I’ve transferred all the issues that seemed worth keeping alive. I think https://github.com/nodejs/modules is ready to be archived.
