### ISSUE TITLE
Youtube and zoom access for @marco-ippolito

### ISSUE THREAD

**Issue by UlisesGascon** [nodejs/admin#827]
@marco-ippolito has volunteered to help host the security team group calls.

**Comment by UlisesGascon** [comment]
cc: @nodejs/security

**Comment by mhdawson** [comment]
+1 from me. I'm out this week at OpenJS world and my guess is that this will be ready so we can give @marco-ippolito access before I'm back. Unless somebody beats me to it I'll try to remember to help set it up soon after I'm back.

**Comment by RafaelGSS** [comment]
+1

**Comment by mhdawson** [comment]
Ok, considering approved.

@marco-ippolito can you PR yourself into the zoom-nodejs list in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json

**Comment by mhdawson** [comment]
invited to zoom
Invited to youtube as manager

both using email from Node.js collaborator listing.

**Comment by marco-ippolito** [comment]
Thank you 😄 
I accepted the youtube invitation.
I also accepted the 1password invitation although I don't have access to any vault.
I havent received anything on zoom

**Comment by mhdawson** [comment]
I double checked you seem to be on the zoom-creds vault like other people. Can you take a look again. It will be shared vault versus a personal one.

**Comment by marco-ippolito** [comment]
@mhdawson confirm I have access 😄

**Comment by UlisesGascon** [comment]
I believe that the issue can be closed, please re-open if needed :)
