### ISSUE TITLE
FYI - adding @AdamBraden to windows teams

### ISSUE THREAD

**Issue by mhdawson** [nodejs/admin#838]
On an email thread I'd asked if there was anybody else we should add to the Windows teams to help pull people into Windows related issues. Answer wast that Adam will be getting more involved so I'm adding him to the following teams:

platform-windows
platform-windows-arm
platform-windows-arm-testing

**Comment by mhdawson** [comment]
@AdamBraden FYI.

I will close this issue after a few days unless there are concerns raised.

**Comment by AdamBraden** [comment]
Thanks. I seem to be up and running.
