### ISSUE TITLE
Create platform teams for `loong64` and `riscv64`

### ISSUE THREAD

**Issue by targos** [nodejs/admin#839]
I'd like to create two new teams related to new experimental platforms. They'd be like other platform teams: no specific permissions granted. Purpose is to have generic way to ping relevant people.

Refs:
- LoongArch
  - https://github.com/nodejs/build/issues/3511
  - https://github.com/nodejs/node/pull/50086
- RISC-V
  - https://github.com/nodejs/build/issues/2876
  - https://github.com/nodejs/node/pull/42251

**Comment by sxa** [comment]
+1 to both, and please include me in the RISC-V one when you create it.

**Comment by shipujin** [comment]
That's great!~

**Comment by targos** [comment]
Created @nodejs/platform-loong64 and @nodejs/platform-riscv64. If you would like to be added to the team, please respond to https://github.com/nodejs/build/issues/3511#issuecomment-1774047939 or https://github.com/nodejs/build/issues/2876#issuecomment-1774048007
