### ISSUE TITLE
Status of GitHub LTS team

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#84]
Is the @nodejs/LTS team now supplanted by and/or absorbed by the @nodejs/Release team, similar to the way @nodejs/CTC is now supplanted by and/or absorbed by @nodejs/TSC?

Trying to figure out if LTS should be made a subteam of members or not.

**Comment by MylesBorins** [comment]
LTS could potentially be a sub team of Release.

Please leave those teams for now and we can open an issue to discuss team setup in the release repo

**Comment by Trott** [comment]
@MylesBorins OK, thanks. I'll make LTS a subteam of members for now. If it gets moved to be a subteam of Release, then it will be a sub-subteam of members, which is also fine.

**Comment by Trott** [comment]
(I'm guessing here, but you probably don't want LTS to be a subteam of Release. If you do that, then any @-mentioning of Release about release-related things will also @-mention LTS. And any access you give Release will also be granted to LTS. Permissions and access flow down to subteams.)

**Comment by MylesBorins** [comment]
Release is the working group, different from releasers which is the team...
But ironing this out is part of the reason I think we need to discuss as a
wg

**Comment by Trott** [comment]
@MylesBorins Hmmm.... The description for @nodejs/release is "Access to cut Node.js releases". Either the description wrong or @nodejs/release is not the Release WG but instead the releasers.

**Comment by gibfahn** [comment]
So we discussed this _a lot_ previously, and decided to have:

- `nodejs/Release`, with subteams:
  - `nodejs/LTS`
  - `nodejs/releasers` (what is now nodejs/release)
  - `nodejs/citgm`

It's all documented in [the readme](https://github.com/nodejs/Release#node-abstraction-layer), and was discussed exhaustively in https://github.com/nodejs/Release/pull/223.

Unfortunately no-one actually did the renaming.

I think the crucial thing is the updating of CI to change access permissions for `nodejs/release` to `nodejs/releasers`. Other than that there shouldn't be anything that needs particular care.

**Comment by mhdawson** [comment]
@gibfahn are you going to handle the updates?

**Comment by gibfahn** [comment]
I guess I can do that, sure.
