### ISSUE TITLE
Create GitHub Account for Shared Vercel Account

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#843]
We are creating a shared Vercel Account for Node.js Infra (Website) on the realm of Node.js Build (build@iojs.org)

The shared account is just a placeholder account, as Vercel doesn't allow Password Logins. The account credentials will be stored on the Shared Bucket on Node.js's 1Password Account.

The account requires no permissions, nor be invited to the Node.js Org, and it's only functionality for now is to be used to login on Vercel without requiring us everytime to look the `build@iojs.org` email.

cc @nodejs/tsc @nodejs/build-infra

**Comment by mhdawson** [comment]
@ovflowd I assume you don't need to receive email at that build+vercel address ?

Related, were are all of the vercel credentials/and related stuff needed to access/manage stored. Are they all in the 1Password account?

**Comment by ovflowd** [comment]
> @ovflowd I assume you don't need to receive email at that build+vercel address ?

Hmm I thought that it would route that to build@iojs.org? At least when I add a + on my Google Mail accounts it routes to the same email?

> Related, were are all of the vercel credentials/and related stuff needed to access/manage stored. Are they all in the 1Password account?

Not sure if I got it right, but the Vercel account is owned by OpenJS right now; The idea was to have a shared account for the Node.js project that has access there so Build WG and maybe Web folks can access there when needed.

Sadly Vercel Auth system is not password-based but OAuth based, so either you login with a confirmation code email or with an integration, such as GitHub, hence the idea of making a GitHub Account just for logging-in to Vercel

**Comment by ovflowd** [comment]
We could also maybe, simply create another email alias for Vercel, like vercel@iojs.org but since that GitHub account would be used only to login on Vercel, I thought that using an existing alias would suffice. We dont even need to add that GitHub account to the Node.js org, for example.

**Comment by tniessen** [comment]
> At least when I add a + on my Google Mail accounts it routes to the same email?

From what I remember, this is one of the many quirks that are specific to Google's implementation, and not demanded by any standard. (I might be wrong, I was looking this up years ago and email is a mess…)

**Comment by ljharb** [comment]
Yes, `foo+whatever@gmail.com` and `f.o.o@gmail.com` and `f.oo@gmail.com` and `fOo@gmail.com` etc all go to the same `foo@gmail.com` account on any Google email system.

**Comment by ovflowd** [comment]
Oh stupid me! I had no idea this was a gmail thingy only.

So should we make another alias for a Vercel GitHub Account... org? Open to suggestions!

**Comment by ovflowd** [comment]
I'm down for making a new alias or using the existing build@iojs.org alias, but it depends on what the build team (cc @nodejs/build) thinks about using `build@iojs.org` or creating a new one

**Comment by ovflowd** [comment]
I've made a PR here, https://github.com/nodejs/email/pull/233 I feel that a dedicated alias makes more sense

**Comment by mhdawson** [comment]
@ovflowd landed that PR and deployed, the email alias should now be working

**Comment by ovflowd** [comment]
I've created the GitHub Account and stored on Node.js's 1Password. I've also linked the Vercel account with that GitHub Account.

To Login to Node.js's Infrastructure on Vercel, please go to https://vercel.com, and click to sign-in with GitHub. If you have the 1Password Extension it will prompt automatically to use the GitHub Account to Login to Vercel

cc @richardlau @Trott (and @bmuenzenmeyer if you want to get access to Vercel, please request access to our 1Password account)
