### ISSUE TITLE
Transfer aduh95/collaborators-public-votes to the org

### ISSUE THREAD

**Issue by aduh95** [nodejs/admin#844]
We would need some public place for hosting public votes – including the upcoming mascot election – so I'm requesting to have this repo transfered for this use.

URL to the repo: https://github.com/aduh95/collaborators-public-votes

**Comment by mhdawson** [comment]
+1

**Comment by marco-ippolito** [comment]
+1

**Comment by aduh95** [comment]
No objections after 72 hours, the transfer has happened, closing this as completed.
