### ISSUE TITLE
Giving access to @marco-ippolito to security releases

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#846]
Recently, Marco was nominated to work in the automation of security releases (SOW described here https://github.com/nodejs/security-wg/issues/860). That said, Marco needs access to the following resources in order to contribute to this initiative:

* nodejs-private
* nodejs.org-private
* HackerOne
* nodejs-security-triage (slack)

Meanwhile, he'll be supporting @nodejs/releasers and eventually becoming one after the onboarding process. I'm planning to do it by Monday (8/1/24) if no objections.

cc: @nodejs/tsc

**Comment by mhdawson** [comment]
+1 from me
