### ISSUE TITLE
Transfer RafaelGSS/nodejs-cve-checker to nodejs

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#847]
As suggested by @mhdawson I'd like to transfer https://github.com/RafaelGSS/nodejs-cve-checker to nodejs org.

The idea of this repo is to be proactive in cases such as https://github.com/nodejs/security-wg/issues/1058.

**Comment by mhdawson** [comment]
+1 from me :)

**Comment by benjamingr** [comment]
SGTM

**Comment by mhdawson** [comment]
@RafaelGSS can you add the required boilerplate files like the Licence file?

**Comment by RafaelGSS** [comment]
Done @mhdawson

**Comment by mhdawson** [comment]
@RafaelGSS I think based on our governance and no objections for 2 weeks along wtih a few +1s this can be moved over.

**Comment by RafaelGSS** [comment]
Transferred to Node.js org https://github.com/nodejs/nodejs-cve-checker. Feel free to adjust the permissions according to our governance model.
