### ISSUE TITLE
Modules team meeting is on wrong date on calendar

### ISSUE THREAD

**Issue by MylesBorins** [nodejs/admin#85]
Should be bi-weekly on wednesdays, it is currently on Friday.  The meeting scheduled for this friday on the calendar should be moved to next wednesday

time does not change

**Comment by bnb** [comment]
@MylesBorins Should be updated.

**Comment by MylesBorins** [comment]
The single meeting has been fixed but the recurring meeting has not. Can you please delete the current recurring event and make a new one?

**Comment by bnb** [comment]
@MylesBorins Should be fixed. Can you check again?

**Comment by MylesBorins** [comment]
Lgtm
