### ISSUE TITLE
Give Triagers access to the Node.js feature requests project

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/admin#861]
(CC @nodejs/issue-triage)

As a (relatively new) member of the Issue Triage team, I think it'd be reasonably helpful if we had the permissions to move issues around in the [**Node.js feature requests**](https://github.com/orgs/nodejs/projects/4) project. This way, we can mark issues as triaged/stale/fixed rather than waiting for the bot to mark them stale or an admin to change their status.

**Comment by RedYetiDev** [comment]
If we have access, I'd gladly reorganize it (<https://github.com/nodejs/node/issues/52485>). I really like it's concept, but it just needs a bit of oversight.

**Comment by gireeshpunathil** [comment]
+1

**Comment by RedYetiDev** [comment]
Great! I'll close this issue once we get access (or a different conclusion is reached)

Thanks for your help!

**Comment by RedYetiDev** [comment]
I'm glad we are a fan of this idea, I'm exciting to help out :-)

**Comment by RedYetiDev** [comment]
@targos, 

Do you think it'll also be a good idea to create a Node.js bug reports project? I'm happy to manage it if needed

**Comment by targos** [comment]
What would you do with it?

**Comment by RedYetiDev** [comment]
I meant just for tracking issues so that they are known

**Comment by RedYetiDev** [comment]
It's been about a month without objections from the TSC, are we okay to give triagers access to the Node.js Feature Requests project? We can always discuss a new project seperately.

**Comment by ovflowd** [comment]
I'm just concerned with what plan you have. Could you elaborate more what you want do to with the feature requests board?

**Comment by targos** [comment]
I'm pretty sure nobody uses that board at the moment. I created it and attempted to maintain it a few years ago, but AFAIK it never gained interest from other collaborators.
So I don't mind if someone else tries to revive the initiative. There's no risk.

**Comment by ovflowd** [comment]
> I'm pretty sure nobody uses that board at the moment. I created it and attempted to maintain it a few years ago, but AFAIK it never gained interest from other collaborators. So I don't mind if someone else tries to revive the initiative. There's no risk.

I see! Thx for clarifying. If there's no risk, then it's all good. Still, a concrete plan would always be preferable. I also wonder if we want to showcase the board somewhere?

**Comment by targos** [comment]
> Still, a concrete plan would always be preferable.

Agreed.

**Comment by RedYetiDev** [comment]
Sorry, I intend to move the misplaced issues into the correct columns, as many are in the wrong places. (For example, closed issues are in waiting triage).

**Comment by tniessen** [comment]
@targos What was the goal of having the board in the first place?

**Comment by targos** [comment]
I don't remember exactly. The main goal was to use custom fields like the existing "status" classify issues and more easily filter them.

**Comment by RedYetiDev** [comment]
My plan for this project is, if I am given access, remove the hundreds of items that are in the wrong place, making it easier for future users to find new tasks to work on, and triagers to find new issues to triage

**Comment by RedYetiDev** [comment]
Hey, still no objections, just curious whether this is still on the table.

**Comment by tniessen** [comment]
I don't think anyone is actually using that project, so as long as all effects are strictly contained to that project and don't affect labels on issues or so, nobody will have an issue with that. If anyone else ever actually starts using that project, we might have to come up with some rules around it, but it doesn't seem like there's interest in using the project so far.
