### ISSUE TITLE
Remove triagers the ability to run CI

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#862]
The bar for triagers is _lower_ than the ones for collaborators, and I recommend preventing them to run CI.

**Comment by targos** [comment]
@aduh95 opened https://github.com/nodejs/node-core-utils/pull/798.
With it, triagers will still be able to run CI, but only when the HEAD of the PR branch has been approved (IIUC).

**Comment by ovflowd** [comment]
I assume this can be closed? Since it is solved? Wdyt, Matteo?

**Comment by mcollina** [comment]
I don't think https://github.com/nodejs/node-core-utils/pull/798 was a good solution to the problem... because it also blocked the collaborators to run CI.

**Comment by aduh95** [comment]
Do you still want to push for this @mcollina?

**Comment by mcollina** [comment]
No.closing
