### ISSUE TITLE
Create a Node.js org account on pypi registry

### ISSUE THREAD

**Issue by legendecas** [nodejs/admin#863]
At the moment, @ryzokuken is the maintainer of the `gyp-next` package on pypi: https://pypi.org/project/gyp-next/.

I discussed with @ryzokuken to setup a Node.js org account and host `gyp-next` under that org account so that we can better maintain the ownership of the package.

I would like to request to setup a Node.js organization for this purpose.

Ref: https://github.com/nodejs/gyp-next/pull/234#issuecomment-2077105006

**Comment by benjamingr** [comment]
SGTM

**Comment by MoLow** [comment]
+1. there is also this package that can benefit from such an account: https://github.com/nodejs/tap2junit/issues/56

**Comment by targos** [comment]
Should this be owned by the build WG or the TSC?

**Comment by legendecas** [comment]
Is https://www.npmjs.com/~nodejs-foundation owned by the build WG or the TSC?

**Comment by targos** [comment]
Build WG

**Comment by targos** [comment]
@nodejs/build wdyt?

**Comment by richardlau** [comment]
I think the question is, who needs access to it? 

The original reasons that the Build WG owns the npm account was as an emergency access in the event that people become inactive/leave the project (so we could manage who could publish modules). Initially we did not actively use the account. Over time that changed and I think we now publish modules under that account. Possibly the TSC at the time didn't have a solution for storing secrets (there's a 1Password account now, I believe), i.e. the account's log in details.

**Comment by mhdawson** [comment]
+1 from me. I think using 1password might make the most sense unless this is somehow related to build/infra

**Comment by targos** [comment]
+1 on 1password + moving the npm credentials there too

**Comment by legendecas** [comment]
I have submitted request to create a orgnanization named `nodejs` on pypi.org. Still waiting for response.

**Comment by legendecas** [comment]
Account created and saved in 1password.

**Comment by targos** [comment]
I rotated the npm credentials and saved them in 1Password too.

**Comment by richardlau** [comment]
> I rotated the npm credentials and saved them in 1Password too.

@targos could you update `build/test/test_logins.md` in the secrets repo, which previously recorded the account name, password and 2fa recovery codes? I don't mind if we move that to 1Password, but we currently document https://github.com/nodejs/admin/blob/a2d01cfd3c93b40d528cb95c84c4f98b7d8bd668/npm-management.md?plain=1#L37-L38

**Comment by targos** [comment]
Ok but can I move them to infra level? IMO this doesn't belong to test

**Comment by richardlau** [comment]
> Ok but can I move them to infra level? IMO this doesn't belong to test

SGTM

**Comment by mhdawson** [comment]
+1 to moving to infra or storing all the info in 1 password. We need the recovery info.

**Comment by targos** [comment]
Secrets repo updated.
