### ISSUE TITLE
Create api-tooling repository

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#866]
As described on https://github.com/nodejs/node/issues/52343 we want to create a new repository to keep the actual tooling of the API docs, and keep it separated from core, so that its development is unrelated to the core itself (which IMO makes sense)

**The goal for the tooling repository is to:**

- Provide the source of a tooling system (similar to the existing one, but revamped) for building the API docs
  - The build system behind the tooling will be discussed within the new repository, but so far, the stack I'm foreseeing is:
    - Vite as the Build System for the API Tooling (Which also supports built-in DevServer and HMR, etc)
      - Works on top of ESBuild
    - A JSX Library, such as React (preferably React), which is going to be used for crafting the templates, layouts, and components of the API Docs
      - We aim to follow the same approach as the Node.js Website by converting the existing HTML/JavaScript/CSS code into React and then iterating on its design.
    - MDXv3 for parsing the Markdown sources and generating JSX
    - And other components as on the Node.js Website, such as Tailwind, Radix UI, Shiki, etc)
- Provide a native way of generating the docs with output formats (by creating a rich "bundling system"), where the output formats can be JSON, MDX and HTML
- Construct a solid Developer Experience and documentation for the Node.js API Docs Tooling
- Create a foundation for the future of the API Docs, so we're able to redesign it, further add features (such as search), and other relative improvements.

cc @nodejs/tsc (and the @nodejs/web-infra and @nodejs/web-standards, since I want to consult regarding the tech stack above, and since the Web Infra would be the primary "code owners" besides Core Collaborators)

**Comment by targos** [comment]
I suggest a more precise name: `api-docs-tooling`.

**Comment by mhdawson** [comment]
+1 from me and I also like the name suggested by @targos

**Comment by benjamingr** [comment]
+1 from me (+ the naming suggestion)

**Comment by ovflowd** [comment]
+1 for the suggested name, thanks @targos!

**Comment by mcollina** [comment]
+1

**Comment by ovflowd** [comment]
Hey y'all 👋 can the repository be created? 👀

**Comment by benjamingr** [comment]
I've created the repository and gave @nodejs/web-infra write access https://github.com/nodejs/api-docs-tooling/ 

Please add the regular documents (LICENSE, README, CODE_OF_CONDUCT and CONTRIBUTING).

Also I am explicitly giving you permission as a TSC member to use your org ownership powers (granted as moderator) to perform non-moderation org-admin actions in that repo so you can add/edit access at https://github.com/nodejs/api-docs-tooling/settings/access , edit description etc.

**Comment by aduh95** [comment]
> Also I am explicitly giving you permission as a TSC member to use your org ownership powers (granted as moderator) to perform non-moderation org-admin actions in that repo so you can add/edit access at https://github.com/nodejs/api-docs-tooling/settings/access , edit description etc.

We usually grant "Maintain" role to the team that "owns" the repo, so it doesn't require org admin privileges to operate.

**Comment by ovflowd** [comment]
Appreciate it, @benjamingr! (and thx for the memo, Antoine!) I'll start preping the repository probably today and start working on the tooling tmrw :)
