### ISSUE TITLE
Is there a uniform locale for Node.js?

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/admin#867]
There are several instances of different spellings, like `behavior` vs. `behaviour`, throughout the documentation and source code. Does Node.js have a preferred locale for spelling?

**Comment by richardlau** [comment]
For documentation for core, US English: https://github.com/nodejs/node/tree/main/doc#documentation-style-guide

**Comment by RedYetiDev** [comment]
Thanks, sorry for my not-looking into it enough
