### ISSUE TITLE
Give Triagers Wiki Edit Access for nodejs/help

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/admin#868]
I suggest that the triage team have access to modify the `nodejs/help` wiki, as right now it contains few characters (One page is: `Y`), and it'd be helpful to clean it up.

**Comment by aduh95** [comment]
For reference: https://github.com/nodejs/help/wiki

**Comment by mcollina** [comment]
Wiki in GitHub is just plain unusable. -1.

If you want to add some information, send PRs to the actual repository;).

**Comment by targos** [comment]
I think the wiki should be disabled.

**Comment by ovflowd** [comment]
The TSC can simply completely disable it :)

**Comment by benjamingr** [comment]
As there were no objections and several requests - I disabled the wiki in the help repo. Thanks 🙏
