### ISSUE TITLE
Archive https://github.com/nodejs/js-native-api-test

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#870]
I think we can archive this one. It doesn't have the tests it's supposed to have and it hasn't been touched in 3 years. We can always unarchive it if someone wants to start working on it again.

https://github.com/nodejs/js-native-api-test

**Comment by Trott** [comment]
@nodejs/node-api

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by devsnek** [comment]
Interestingly I've been working on n-api in deno this week. I didn't realize this repo exists but lemme double check real quick if we'd be interested in setting this up as our test situation right now is not fantastic.

**Comment by legendecas** [comment]
@devsnek this repo was setup to make node-api implementers easier to test with node-api. Please let us know if you find it useful and we can setup an automation like https://github.com/nodejs/node-api-headers to release the tests in a more friendly way.

**Comment by devsnek** [comment]
@legendecas yeah that would be really useful. I wonder if we could also include makefiles from `node-gyp configure` in the repo so people testing don't need to set that all up.

**Comment by Trott** [comment]
Archived. (We can unarchive it if needed/requested, so just leave a comment if you'd use this, @devsnek.)

**Comment by legendecas** [comment]
@Trott thanks for the action. I agree it is good to archive the repo and we can un-archive once it is needed again.
