### ISSUE TITLE
Creating a new nodejs/nbytes repo

### ISSUE THREAD

**Issue by jasnell** [nodejs/admin#885]
The https://github.com/nodejs/node/pull/53507 pr in nodejs/node starts the process of extracting certain byte and string related utility methods out of nodejs/src in order to make it easier for other projects to integrate node.js compatibility. Eventually the idea is to separate those out into a separate repo that is bundled into nodejs/node as a dependency.  To this end, I would like to create a nodejs/nbytes repo to host it.

**Comment by mcollina** [comment]
+1

**Comment by anonrig** [comment]
+1

**Comment by mhdawson** [comment]
+1

**Comment by mhdawson** [comment]
Just wanted to add that I really like the idea of working towards a shared implementation
