### ISSUE TITLE
Give Triagers More Control Over Issues

### ISSUE THREAD

**Issue by RedYetiDev** [nodejs/admin#887]
There are times when, as a triage team member, we need to perform certain actions but lack the necessary access. Specifically:
  
- **Transferring issues**: At times, issues need to be moved to another repo better suited to handle them. (Mainly `nodejs/node` to `nodejs/help`). Without the ability to transfer issues, we can’t efficiently move issues to the best place.

CC @nodejs/issue-triage

**Comment by targos** [comment]
Transferring issues requires write access on both the source and target repositories.

**Comment by RedYetiDev** [comment]
Nevermind then...
