### ISSUE TITLE
Transfer amaro to the org

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/admin#896]
As mentioned in today's TSC meeting, I've created a package to be able to decouple the typescript library from Node.
This package allows the project not lock a specific typescript version and let users upgrade independently,  more info on why [here](https://github.com/nodejs/loaders/issues/217).
The project is currently just a wrapper around swc.

The repo is => https://github.com/marco-ippolito/amaro

Ping @nodejs/tsc @nodejs/loaders

**Comment by mhdawson** [comment]
+1 from me

**Comment by ShogunPanda** [comment]
+1

**Comment by marco-ippolito** [comment]
Transfered https://github.com/nodejs/amaro

**Comment by aduh95** [comment]
Note the action taken before the request was approved:

https://github.com/nodejs/admin/blob/6e2221443e38c4ef2f04d3990d6509c2ec7915ff/GITHUB_ORG_MANAGEMENT_POLICY.md#L61-L64

**Comment by marco-ippolito** [comment]
My bad I totally missed the 72h 💀
