### ISSUE TITLE
Remove coverage-admins team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#899]
I don't think @nodejs/coverage-admins is a thing anymore now that we've basically migrated to codecov. I imagine @joaocgreis would know, of course, or @richardlau or someone else on Build. Anyway, if it's not a meaningful team, perhaps we should remove it.

@nodejs/tsc

**Comment by richardlau** [comment]
+1. 

FWIW the jobs still exist in Jenkins but have been disabled for a long time. They probably won't work as the infrastructure to store/process results isn't there anymore. I think enough time has passed that we can delete those as well.

**Comment by richardlau** [comment]
> FWIW the jobs that this team have admin access to still exist in Jenkins but have been disabled for a long time. They probably won't work as the infrastructure to store/process results isn't there anymore. I think enough time has passed that we can delete those as well.

Jenkins coverage jobs are now gone.

**Comment by mhdawson** [comment]
+1 from me

**Comment by benjamingr** [comment]
+1

**Comment by Trott** [comment]
(This is another one where if someone from @nodejs/tsc could do the honors, that would be appreciated! Thanks!)

**Comment by Trott** [comment]
Can someone on @nodejs/tsc please take care of this? It's not urgent or anything but also, it has been open for almost two weeks now.

**Comment by targos** [comment]
I deleted the team
