### ISSUE TITLE
Remove dtrace-mdb team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#900]
I imagine @nodejs/dtrace-mdb is no longer a meaningful team and we should remove it. It would be great if @misterdjules could confirm this or explain that it is still a helpful team to have around.

**Comment by RafaelGSS** [comment]
+1

**Comment by Trott** [comment]
@nodejs/tsc

**Comment by mhdawson** [comment]
+1 from me

**Comment by joyeecheung** [comment]
+1

**Comment by mcollina** [comment]
+1

**Comment by Trott** [comment]
Can someone from @nodejs/tsc take care of this? I have the ability to do it but only because I'm on Moderation Team and I'm only supposed to use the Owner role privileges for moderation purposes. This isn't that, so....someone else has to do it.

**Comment by benjamingr** [comment]
Done, thanks.

**Comment by benjamingr** [comment]
I've also gone ahead and removed members with 0 teams from the org per our policy.
