### ISSUE TITLE
Create nodejs/typescript repo

### ISSUE THREAD

**Issue by marco-ippolito** [nodejs/admin#903]
As discussed in https://github.com/nodejs/TSC/issues/1600 TSC meeting, I'd like to create a new repo for the collaboration with the typescript team and add it as a new strategic initiative
Ping @nodejs/tsc

**Comment by GeoffreyBooth** [comment]
I mentioned in the meeting that I’d prefer we create a new team, `@nodejs/typescript`, but keep using https://github.com/nodejs/loaders as the repo. There’s already a lot of history about TypeScript in the loaders repo.

**Comment by marco-ippolito** [comment]
It would be a separate space with different meetings, so it would make sense to have its own repo.

**Comment by mhdawson** [comment]
+1 from me

**Comment by marco-ippolito** [comment]
There is already a @nodejs/typescript but afaik it's more oriented towards the type definitions for node than the typescript implementation. To avoid confusion, would it be ok to use https://github.com/orgs/nodejs/teams/typescript for everything related to typescript loader, and create a new team @nodejs/types for type definitions? ping @nodejs/tsc

**Comment by mcollina** [comment]
+1 for me.

@robpalme has expressed interested in joining as well.

**Comment by marco-ippolito** [comment]
Team @nodejs/typescript any objection on renaming to @nodejs/types?

**Comment by marco-ippolito** [comment]
I have created @nodejs/types and added all the previous members of @nodejs/typescript

**Comment by marco-ippolito** [comment]
repo created https://github.com/nodejs/typescript

**Comment by marco-ippolito** [comment]
team kickstart here https://github.com/nodejs/typescript/issues/1
