### ISSUE TITLE
Conversion to Enterprise account

### ISSUE THREAD

**Issue by mcollina** [nodejs/admin#905]
<img width="931" alt="Screenshot 2024-07-26 at 09 06 07" src="https://github.com/user-attachments/assets/ac74efec-eb11-4d99-8370-e108fea96447">

Currently we are on the Enterprise Cloud system, and we are going to be migrated to "Enterprise Account" on September 3rd. I recommend we do it earlier, between now and then, and deal with all the possible hiccups on our terms.

Alternatively, we let the deadline expire and deal with anything in September. I feel this might be a bit disruptive for the collaborators because of the upcoming cutoff for v23, so I'd recommend we do this asap.

**Comment by mcollina** [comment]
I have been told that said migration is not as straightforward as we think, so an independent org it's better. (we have quite a lot of custom stuff here).

**Comment by targos** [comment]
Then let's do it!

**Comment by mcollina** [comment]
@nodejs/tsc are there any objections?

**Comment by anonrig** [comment]
+1 let's do it

**Comment by ovflowd** [comment]
> I have been told that said migration is not as straightforward as we think, so an independent org it's better. (we have quite a lot of custom stuff here).

I don't think that was the outcome of the CPC meeting. If I recall, what Ben from the Foundation meant is that billing settings could be tricky, but to be honest, nothing that GitHub staff couldn't help us out.

IMO, if we already need to move to the GitHub Enterprise system, I don't see why it shouldn't be under the OpenJS Foundation "Enterprise." Does it make any difference? 🤔

**Comment by mcollina** [comment]
> I don't think that was the outcome of the CPC meeting. If I recall, what Ben from the Foundation meant is that billing settings could be tricky, but to be honest, nothing that GitHub staff couldn't help us out.

Given we have a wild amount of custom discount & quotas from GitHub, a problematic scenario is that the project is "broken" for some time before we try to fix this. I'm absolutely certain that GitHub staff can fix this, but why breaking things?  

> IMO, if we already need to move to the GitHub Enterprise system, I don't see why it shouldn't be under the OpenJS Foundation "Enterprise." Does it make any difference?

See above.

**Comment by mcollina** [comment]
> We have a scheduled call with GitHub staff to clear out questions. Isn't it worth to first clarify things rather than move by fear?

I would prefer _not_ to change anything at all. They are the ones forcing a change.

---

we should also apply this to nodejs-private.

**Comment by ovflowd** [comment]
Well they, as, GitHub. So if they are forcing a change, shouldn't we ask counselling to them regardless? To check if anything would break at all, regardless of OpenJS Enterprise?

**Comment by targos** [comment]
> we should also apply this to nodejs-private.

I would like to try and put `nodejs-private` under the same enterprise account. It could have the nice side-effect to remove the current limitation we have on runner minutes.

**Comment by mcollina** [comment]
> shouldn't we ask counselling to them regardless? To check if anything would break at all, regardless of OpenJS Enterprise?

I have no time for another meeting, unfortunately.

> It could have the nice side-effect to remove the current limitation we have on runner minutes.

We have the maximum amount of free credits we could get in nodejs-private already. The chances of _losing_ that and having to re-negotiate it are high enough (free credits are indeed related to billing).

---

It seems apparent that we do not have consensus on this move, and I do not have the time to "push it through" and have meetings about it. Therefore, I will not take care of this.

(Hopefully somebody else will, or we do have the forced migration in September).

**Comment by ovflowd** [comment]
I'm no TSC, but I'd be more than happy to help on the OpenJS side of things as a CPC member.

**Comment by ovflowd** [comment]
> I also prefer to keep the organization separate, maybe once there is more experience by other projects having moved we might consider again. I see keeping it separate and transitioning to our own enterprise account as the least risk which is why I would prefer that.

Fair enough.

**Comment by ruyadorno** [comment]
+1 to move forward with the migration and keep the orgs separate

**Comment by mhdawson** [comment]
@targos I wonder if we could flips the two orgs (nodejs and nodejs-private) separtely to their own Enterprise orgs to reduce risk.

We could then try adding a new private org under the Enterprise Node.js org. We could then experiment to see if that new org has unlimited minutes and if so move the repos from the nodejs-private org over to the Node.js enterprise org.

That might be more work, but let us transition as/when we have time to test out/transition.

**Comment by mcollina** [comment]
Done for the nodejs one. Does anybody know how to merge the private one with the main one?

**Comment by richardlau** [comment]
> Done for the nodejs one. Does anybody know how to merge the private one with the main one?

Possibly via "Invite organization" on https://github.com/enterprises/nodejs/organizations?

**Comment by mcollina** [comment]
<img width="1135" alt="Screenshot 2024-08-14 at 17 16 56" src="https://github.com/user-attachments/assets/436e3eb1-da5f-414f-99fa-1627c1c35fb6">


unfortunately that does not seem to be possible.

**Comment by targos** [comment]
@mcollina We have unlimited seats. I just added one, can you try again?

**Comment by mcollina** [comment]
Done. However before inviting I would like to remove all non-tsc members as enterprise owners, as this access is not needed by moderation.

Alternatively, we could keep limit it
 to the TSC chair, vice-chair, and openjs representative.

**Comment by ovflowd** [comment]
> Alternatively, we could keep limit it to the TSC chair, vice-chair, and openjs representative.
> 
> We should do this before adding the nodejs-private org.

This makes sense IMO

**Comment by richardlau** [comment]
Our GitHub actions are now backlogged. I'm getting lots of notifications for canceled Auto Start CI runs which started appearing time-wise shortly after the conversion 😞.

**Comment by ovflowd** [comment]
That's bad, any updates on that?

**Comment by mcollina** [comment]
I've removed from Enterprise owners:

- @atlowChemi 
- @bmuenzenmeyer
- @JohnTitor
- @othiym23
- @UlisesGascon
- @Trott 
- ovflowd

Enterprise owners are now all TSC members + @bensternthal.

**Comment by bensternthal** [comment]
@mcollina @ovflowd thanks for the heads up. 

Note one thing I noticed when I did this upgrade on other projects is that some of our CI broke (looks like there is a similar issue here). At least for me, this was caused by some stricter rules in GH enterprise (and apologies if you know this already)

<img width="757" alt="Screenshot 2024-08-15 at 8 03 20 AM" src="https://github.com/user-attachments/assets/2348c820-f4b9-4fd4-9aac-60bd3564ce67">

I solved this by adding more granular [permissions](https://docs.github.com/en/actions/writing-workflows/choosing-what-your-workflow-does/controlling-permissions-for-github_token) into the workflow .yml file [example](https://github.com/chipsalliance/chips-alliance-website/blob/04fa55648fc23a9f5f0de5e13d42295e9b8417b4/.github/workflows/preview_deploy.yml#L12)

Hope this helps!

**Comment by richardlau** [comment]
> That's bad, any updates on that?

Looks a lot better today.

https://github.com/enterprises/nodejs/settings/actions/hosted-runners yesterday was reporting a concurrency limit of 18 which has slowly been creeping upwards (in a private Slack thread it was noted later showing 23 and then 29) -- currently the concurrency limit is 131. We're hoping this will self-resolve.

**Comment by mcollina** [comment]
I've ticked to allow gh actions to create and approve PRs.

**Comment by mcollina** [comment]
Closing as completed, feel free to reopen in case more problems arises.
