### ISSUE TITLE
Becoming maintainer of llhttp and its related repositories

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/admin#906]
I would like to take care of llhttp, llparse, llparse-test-fixture and become a maintainer of these repositories. Unfortunately currently there is no real development activity. I know that @ShogunPanda wants to provide a rewrite in rust, but till then, we should not neglect llhttp and co.. 

I am already part of the undici team, and there are potential issues, we probably have to fix in llhttp. 

The first step is to
- modernize the dependencies
-  make the tests work again
- add ci workflow 

The first step is not controversial, as it does not change the product itself. So I would like to merge them via PRs into the repo. 

The second step is to propose some changes regarding performance. I already tested some changes locally with a modified llhttp.c file, which I want to propose as PRs, which is foreseeable controversial. But I wouldnt merge them without enough approval. 

Thank you :)

**Comment by anonrig** [comment]
I'm +1 (cc @nodejs/tsc)

**Comment by mcollina** [comment]
I’m +1

**Comment by benjamingr** [comment]
The repo is maintained by @nodejs/llhttp - which has two members @ShogunPanda and @indutny , I think the ask would just be to ask @ShogunPanda to add you to that team which would grant you maintainer status for that repo.

I honestly don't think this requires TSC approval/involvement (and thanks for the effort and working on this :))

**Comment by anonrig** [comment]
I'm also interested in maintaining to help @ShogunPanda

**Comment by benjamingr** [comment]
@anonrig since you're voting TSC and willing to do this - I think you can just add yourself and Aras and Paolo wouldn't mind but no harm waiting a bit for Paolo to respond.

**Comment by benjamingr** [comment]
Adding tsc-agenda in case Paolo doesn't have time to respond until Wed so this doesn't stall.

**Comment by Trott** [comment]
> The repo is maintained by @nodejs/llhttp - which has two members @ShogunPanda and @indutny , I think the ask would just be to ask @ShogunPanda to add you to that team which would grant you maintainer status for that repo.
> 
> I honestly don't think this requires TSC approval/involvement (and thanks for the effort and working on this :))

One omission is https://github.com/nodejs/llparse-test-fixture which only @indutny has write access too (along with org owners). Should we remove @indutny and add the team @nodejs/llhttp instead? (He's on the team so it won't affect his access.)

**Comment by Trott** [comment]
Similar story for https://github.com/nodejs/llparse. It has access granted to just @indutny and @nodejs/tsc. The latter is pointless (as they're all org owners anyway). Should @indutny and @nodejs/tsc be removed and @nodejs/llhttp be added?

**Comment by Uzlopak** [comment]
If we do this, can we also create a copy of https://github.com/indutny/llparse-frontend in the nodejs-org and release it under a new name on npm?

**Comment by indutny** [comment]
I'm happy to move it to nodejs org and transfer npm ownership.

**Comment by indutny** [comment]
In fact, I just initiated move on github. Sorry this wasn't done long time ago.

**Comment by Uzlopak** [comment]
Nice, thank you :)

**Comment by aduh95** [comment]
Note the action taken before the request was approved:

https://github.com/nodejs/admin/blob/6e2221443e38c4ef2f04d3990d6509c2ec7915ff/GITHUB_ORG_MANAGEMENT_POLICY.md#L61-L64

**Comment by indutny** [comment]
Honestly, I thought there would an approval on the organization end. Sorry for not really knowing how the github transfer works nowadays.

**Comment by Uzlopak** [comment]
@indutny I think he refers to the fact that there is a general grace period. So giving me permissions is the original request and as such can be fulfilled earliest after 72 h.

Can you please also transfer llparse-build? Than the toolchain should be afaik complete in nodejs org, right?

**Comment by Trott** [comment]
> Honestly, I thought there would an approval on the organization end. Sorry for not really knowing how the github transfer works nowadays.

Without tooling to enforce the rules that aren't widely-known or even necessarily easy to find, these kinds of things are going to happen. 🤷  We're all doing the best we can.

**Comment by ShogunPanda** [comment]
Hello folks!
I'm totally happy with it, due to lack of time any help on llhttp is absolutely welcome.

@Uzlopak welcome on board!

PS: Yes, Milo is still under the work. I have few things to take care of but I can't really find the time. I'll try to deliver ASAP.

**Comment by benjamingr** [comment]
>  the tsc-agenda label added by @benjamingr was maybe too early.

Yes - that was just in case no one picks it up so it doesn't get missed, removed now that it got engagement.

**Comment by mhdawson** [comment]
+1 from me.

**Comment by Uzlopak** [comment]
72 h are over :)

**Comment by Uzlopak** [comment]
@mhdawson 
@mcollina 
@ShogunPanda 
@anonrig 

Can we proceed please :)?

**Comment by Uzlopak** [comment]
Anything blocking :)?

**Comment by ShogunPanda** [comment]
I'm off today. Tomorrow I'll be please to add you.

**Comment by aduh95** [comment]
I've added @nodejs/llhttp as Maintainer of https://github.com/nodejs/llparse-frontend. There are a few points to address to make this repo "ready for transfer", notably it lacks a `LICENSE` file (but is licensed as MIT according to its `package.json`, so that should be easily addressed); but that's not exactly related to this issue since the repo has already been transfered, and it's not listed as a mandatory step in https://github.com/nodejs/admin/blob/6e2221443e38c4ef2f04d3990d6509c2ec7915ff/transfer-repo-into-the-org.md?plain=1#L3-L26

@Uzlopak has been added to @nodejs/llhttp
