### ISSUE TITLE
add `llparse` to team `llhttp`, request @indutny to transfer llparse-builder

### ISSUE THREAD

**Issue by Uzlopak** [nodejs/admin#910]
Follow up from #906 

Unfortunately the llparse repo was not assigned to the llhttp team. 

@indutny could you plese also transfer llparse-builder?

Are there any other repo related to llhttp?

Thank you very much.

**Comment by indutny** [comment]
Done. Moved.

**Comment by Uzlopak** [comment]
First of all, thank you indutny

@aduh95 
or any other:
Can you please assign llparse-builder and llparse to the llhttp team?

**Comment by mcollina** [comment]
Done.
