### ISSUE TITLE
Remove Medium email account

### ISSUE THREAD

**Issue by WaleedAshraf** [nodejs/admin#912]
Hi All,

Since [nodejs-collection](https://github.com/nodejs/nodejs-collection) time we have medium@nodejs.org email address.
We didn't remove this email during the [cleanup phase](https://github.com/nodejs/nodejs-collection/issues/44).

This email keeps getting spam emails and I think there are still a number of people on this email forwarding list.

I suggest that we remove it.

**Comment by Trott** [comment]
Is this something @bensternthal would have to do for us? I don't see this email address in https://github.com/nodejs/email/blob/main/iojs.org/aliases.json so I'm guessing it was set up on the foundation side of things.

**Comment by bensternthal** [comment]
This was setup as part of your nodejs.org Gsuite as a google group. I have permissions to edit and/or delete the group.

Can you confirm you 100% want this removed and that it is no longer used?

**Comment by WaleedAshraf** [comment]
@bensternthal if it's not tied to the [Node.js user](https://nodejs.medium.com/) than it can be removed right away.
[Node.js user](https://nodejs.medium.com/) is the only user who has access to the [Archived Node.js Publication](https://medium.com/the-node-js-collection).

In case the email is being used for the user account, I suggest we move the user to a new email.

**Comment by bensternthal** [comment]
It's just a group, it is not a user account. I have deleted this group.
