### ISSUE TITLE
Create a new repository for documenting CJS/ESM package shipping patterns

### ISSUE THREAD

**Issue by joyeecheung** [nodejs/admin#917]
When working on https://github.com/nodejs/node/pull/54648 I noticed that the package API documentation has been documenting [some opinionated patterns](https://github.com/nodejs/node/blob/298dea0c635e776cf00fc9014e6e4ce2f760e039/doc/api/packages.md?plain=1#L887) that [some consider dangerous](https://github.com/nodejs/node/issues/52174). I think instead of continue piling more opinionated patterns or bikeshed about them in the API docs, we should just move these into their own repository (similar to https://github.com/nodejs/node-addon-examples), with example folders containing the multi-file structures that they are describing, and maybe some links to the discussions about their pros and cons. This repository can be named `package-examples`, etc., and we can extend it to describe other patterns such as how TypeScript packages can configure themselves before being shipped to npm.

cc @nodejs/package-maintenance @nodejs/loaders @nodejs/tsc

**Comment by JakobJingleheimer** [comment]
I think Learn is the ideal place for recommendations :)

**Comment by mcollina** [comment]
yes

**Comment by mhdawson** [comment]
+1 from me

**Comment by joyeecheung** [comment]
Created https://github.com/nodejs/package-examples and chose the MIT license (since the addons example repo also used that). Will work on files to add there.
