### ISSUE TITLE
Node.js should have an OpenCollective

### ISSUE THREAD

**Issue by ovflowd** [nodejs/admin#919]
Numerous projects on the JavaScript (and non-JavaScript ecosystem) and even under the Foundation (namely Jest, ESLint, and WebPack) have OpenCollective funding that allows the project to prioritize resources and reward long-standing collaborators for working on specific feature requests, security incidents, and bug fixes and dedicate spiking/research time to proposals and new features.

I bet that this was already suggested before, but recently, with my work on defining a governance model for Webpack (https://github.com/webpack/webpack-governance), it became clear to me that we should have an OpenCollective.

More importantly, we should have a model to allocate and disburse and a government amendment to support such endeavors.

With an OpenCollective, we can gather funds from individual contributors and enterprises, allowing us to spend more CI resources efficiently and pay for core collaborator's time (and any eligible Working group work).

From the bottom of my heart, please implement an OpenCollective and funding/disbursing model. We need this.

**Comment by ovflowd** [comment]
cc @nodejs/tsc

**Comment by aduh95** [comment]
Duplicate of https://github.com/nodejs/TSC/issues/1553?

**Comment by ovflowd** [comment]
Duplicate of https://github.com/nodejs/TSC/issues/1553
