### ISSUE TITLE
Request for Comments: Archiving Several Repos

### ISSUE THREAD

**Issue by bnb** [nodejs/admin#93]
In the process of going through every single repository in the org for https://github.com/nodejs/admin/issues/88, I discovered a suite of repositories that were stated to be inactive, that were artifacts of the io.js work and aren't going to be developed further, and that have (seemingly) had zero meaningful activity for an extended period.

I'd like to propose that we archive all of these repositories.

@nodejs/tsc and @nodejs/community-committee if you have objections to any of these repositories being archived, could you please state which repositories and why? That would be immensely helpful in keeping track for the future.

Also, I'd like to note that this proposal **does not** cover any of the i18n repos that existed for the purpose of translating the Node.js site and docs. There are quite a few inactive ones, but I'd like to leave that up to @nodejs/i18n to decide how to proceed with those.

## Unchartered/Visibly Inactive
https://github.com/nodejs/Intl
https://github.com/nodejs/testing
https://github.com/nodejs/docs
https://github.com/nodejs/Future-CI
https://github.com/nodejs/http
https://github.com/nodejs/nodejs.org-archive

## Artifacts of io.js
https://github.com/nodejs/logos
https://github.com/nodejs/NG
https://github.com/nodejs/doc-tool

## Zero activity
https://github.com/nodejs/v8
https://github.com/nodejs/live.nodejs.org
https://github.com/nodejs/dev-policy
https://github.com/nodejs/inclusivity-slack-inviter
https://github.com/nodejs/build-container-sync
https://github.com/nodejs/contribution-slides
https://github.com/nodejs/foundation-slides
https://github.com/nodejs/build-containers
https://github.com/nodejs/nodejs.org-new

**Comment by Trott** [comment]
No objections from me although I'm actually not sure about all of these. But archiving is low-risk. It's easy to unarchive.

I did just clear out the issues and PRs in the testing repo to prepare it for archiving. If other people want to do the same for some of these others that are definitely archive candidates, please do!

**Comment by targos** [comment]
No objections from me.

**Comment by gibfahn** [comment]
SGTM

**Comment by mhdawson** [comment]
LGTM except for testing.  It has some scripts that are still used for coverage in older versions (not sure if the changes to use the copies in the build repo have been fully backported)

**Comment by Trott** [comment]
> LGTM except for testing. It has some scripts that are still used for coverage in older versions (not sure if the changes to use the copies in the build repo have been fully backported)

@mhdawson I could be wrong, but wouldn't the availability of these scripts be unaffected by archiving, which essentially just puts the repo into read-only mode?

**Comment by srl295** [comment]
Wait on intl which is covered by sep issues

**Comment by mcollina** [comment]
SGTM

**Comment by mhdawson** [comment]
@Trott I don't know enough about archiving, but if the repo can still be cloned then we'd be ok.

**Comment by Trott** [comment]
About to archive all but intl and testing as those are the only ones about which any concerns were lodged.

**Comment by Trott** [comment]
(Might want to take down live.nodejs.org or else unarchive that repo. Not sure if that would be @nodejs/build or if a request needs to go into the Foundation for removing the site.)

**Comment by Trott** [comment]
All done.

**Comment by srl295** [comment]
nodejs/Intl archived as promised
