### ISSUE TITLE
New repo and team: `userland-migrations`

### ISSUE THREAD

**Issue by JakobJingleheimer** [nodejs/admin#931]
Pursuent to the positive reception of my proposal ([slides](https://docs.google.com/presentation/d/1ygpEfNKeBKfK7lGxZDvNao-kE6KWd6MHPacVjLgQeic/view)) at Collab Summit Dublin 2024, I would like to establish a new team `@nodejs/userland-migrations` and a new repository `nodejs/userland-migrations` (owned by the aforementioned new team).

Initial members of this team would be:
* me (owner/champion)
* @AugustinMauroy
* @darcyclarke
* @tchetwin
* @alexweej
* @lukekarrys
* @ljharb
* @bmuenzenmeyer 
* @alexbit-codemod

**Comment by ljharb** [comment]
I'd be interested in joining as well.

**Comment by JakobJingleheimer** [comment]
> I'd be interested in joining as well.

@ljharb Added!

**Comment by mhdawson** [comment]
+1 from me to the new team and repo

**Comment by JakobJingleheimer** [comment]
It's been a week, and no objections have been raised. So I believe this has passed.

@mhdawson a few of the members are not currently part of the nodejs org, so I can't add them to the `@nodejs/userland-migrations` github team. What should happen—should they be added to the org, or should I only add them to the repo ad-hoc? For the latter, they won't get notified when the team gets tagged.

* @alexbit-codemod
* @alexweej
* @tchetwin

**Comment by mhdawson** [comment]
I think this section the documents how we manage our GitHub org answers that question:

https://github.com/nodejs/admin/blob/main/GITHUB_ORG_MANAGEMENT_POLICY.md#members

It says:
```markdown
## Members
GitHub users are added as members to our GitHub Organization when they are added to any Working Group or team. Organization Owners should add new members to the organization when requested by a Working Group or team.
```

**Comment by mhdawson** [comment]
I tried to add 

@alexbit-codemod
@alexweej
@tchetwin

but it just tells me they "X isn/t a GitHub member"

@targos I think I remember you mentioning something about adding new members. Is there some step I need to do before adding them?

**Comment by mhdawson** [comment]
Also I think @mcollina might have been involved in the discussion of extra steps to add a new member

**Comment by mhdawson** [comment]
@JakobJingleheimer I tried again today and for some reason I was able to add them on the same page I could not before.

Invites sent for all three, I think you should be able to add to the team now.

**Comment by JakobJingleheimer** [comment]
Actually, @mhdawson could we please also add @mohebifar (from codemod) to the node org so I can add him to the group. Sorry he was missed before.

**Comment by mhdawson** [comment]
@JakobJingleheimer ok invited.
