### ISSUE TITLE
Transfer is-my-node-vulnerable to Node.js org

### ISSUE THREAD

**Issue by RafaelGSS** [nodejs/admin#937]
I wrote this package to serve as a tool for end-users to identify if they are running an outdated version of Node.js.

Since we are sharing this tool using the Node.js communication channels (X, Node.js org (https://github.com/nodejs/nodejs.org/pull/7328), ambassadors program), I think it would sound more professional if that package lived in the Node.js organisation.

cc: @nodejs/tsc @rginn

**Comment by mcollina** [comment]
sgtm

**Comment by RafaelGSS** [comment]
Proceeding with that

**Comment by RafaelGSS** [comment]
Done. 

I gave access to @nodejs/tsc and @nodejs/security-wg
