### ISSUE TITLE
update documentation team membership

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#94]
The @nodejs/documentation group has 29 members. That suggests a robust and active group, but alas, only a fraction of those folks are active. I suspect (but don't know) that having a large number of people on there discourages others from asking to join.

I'd like to pare down some of the less active folks. No shame in being inactive. We all have lives and there's an ebb and flow in our involvement in all things.

Happy to have any of these people listed below say "Whoa, I'm still interested and still doing work here, what are you talking about? Please leave me!" I've certainly not done a scientific analysis here. (Basically, if this is your only team in the org and I'm unaware of any recent activity, you're listed.)

And there's nothing stopping someone from being removed now and then added 3 months later when they become active again.

All that said, does anyone (including the named GitHub accounts below!) object to me removing the following from @nodejs/documentation?:

* @ryansobol
* @danjenkins
* @kahwee 
* @drewfish
* @tomgco 
* @techjeffharris 
* @Zeus 
* @DavidTPate

I'll wait 72 hours before doing anything, and I won't remove anyone who says they don't want to be removed. (And even if you are removed, it's awfully easy to get added back!)

**Comment by Trott** [comment]
@nodejs/tsc @nodejs/community-committee

**Comment by benjamingr** [comment]
@Trott for the past year the documentation team hasn't been active anyway and has been dechartered was a WG anyway.

I think that if you want to revive the effort (which is excellent) it would be fair to remove _everyone_ from the team and ping them asking if they wanted to remain in the team since that would effectively be starting a new team. No strong feelings about it though.

**Comment by a0viedo** [comment]
Since the WG was dechartered I understood that the GitHub team was no longer being used.

**Comment by Trott** [comment]
@a0viedo There's precedence for keeping teams around after a WG is de-chartered. For the Testing WG, we thought it was useful to have a team of people that care about tests, even if the WG is defunct. I always thought about the documentation team the same way: Even though it's not a WG, it's still useful to have a group of Collaborators and others who are the designated "we care a lot about documentation" people.

**Comment by codeekage** [comment]
@benjamingr I completely agree with you. If a team has been inactive for a while, the best way is taking everyone out and getting the ones who seem to be more interested in the team.

@Trott I also understand your passion for the documentation team but taking down the teammates don't necessarily mean taking out the team. The team still exist just with a new set of members that really cares about documentation the same way you care about it too.

I think this will give you the advantage of working with a better and a more effective team.

**Comment by Trott** [comment]
If anyone who's been removed wants to be re-added, comment here or open an issue or send me an email. Thanks!
