### ISSUE TITLE
Remove the Collaboration team?

### ISSUE THREAD

**Issue by Trott** [nodejs/admin#95]
I don't think @nodejs/collaboration is an active team. I suspect its function has been superseded by @nodejs/community-committee. Any objections to removing the team?  @nodejs/tsc

**Comment by Trott** [comment]
(Not gonna lie: That team name is particularly irksome because I accidentally pick it and then have to delete and start typing again when I'm trying to @-mention the Collaborators team instead.)

**Comment by bnb** [comment]
As a member of that team, I have no objection. I have no clue why the team exists, nor why I'm a maintainer.

Judging by the membership, I'd wager it was an effort from the io.js days.

**Comment by Trott** [comment]
>  I have no clue why the team exists, nor why I'm a maintainer.

I could be wrong, but I think because you are an org owner, you are listed as a Maintainer of any team on which you are a member.

**Comment by bnb** [comment]
@Trott yep, that does seem to be the case 😅

**Comment by mhdawson** [comment]
+1 from me.
