### ISSUE TITLE
Requesting calendar admin privileges

### ISSUE THREAD

**Issue by dshaw** [nodejs/admin#96]
I am championing @nodejs/user-feedback and helping bootstrap https://github.com/nodejs/mentorship under the CommComm charter. It would be great to be able to help manage the calendar. Thanks.

**Comment by williamkapke** [comment]
> If you would like to help maintain your team's calendar events, open a PR adding your name to the list above. Once approved, one of the calendar maintainers will add you to the calendar settings.

https://github.com/nodejs/admin#nodejs-foundation-calendar

;)

**Comment by amiller-gh** [comment]
@dshaw Can we close this issue? ;)

**Comment by Trott** [comment]
Re-open if I'm closing in error, of course.
